### ISSUE TITLE
Exception: Must specify file for SVGMobject

### ISSUE THREAD

**Issue by KjellCools** [3b1b/manim#1008]
Hello, 

I just installed manim on macOS Catalina version 10.15.4. I followed all steps as described on
http://bhowell4.com/manic-install-tutorial-for-mac/

Arriving at Step 11: Final Test

I run following command:    python3 manim.py example_scenes.py WriteStuff -pl

and got into problem:

Traceback (most recent call last):
  File "/Users/kjellcools/manim37/manim/manimlib/extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "/Users/kjellcools/manim37/manim/manimlib/scene/scene.py", line 53, in __init__
    self.construct()
  File "example_scenes.py", line 102, in construct
    tex_to_color_map={"text": YELLOW}
  File "/Users/kjellcools/manim37/manim/manimlib/mobject/svg/tex_mobject.py", line 148, in __init__
    self, self.arg_separator.join(tex_strings), **kwargs
  File "/Users/kjellcools/manim37/manim/manimlib/mobject/svg/tex_mobject.py", line 46, in __init__
    SVGMobject.__init__(self, file_name=file_name, **kwargs)
  File "/Users/kjellcools/manim37/manim/manimlib/mobject/svg/svg_mobject.py", line 45, in __init__
    self.ensure_valid_file()
  File "/Users/kjellcools/manim37/manim/manimlib/mobject/svg/svg_mobject.py", line 51, in ensure_valid_file
    raise Exception("Must specify file for SVGMobject")
Exception: Must specify file for SVGMobject

I have no idea what I have to do.   For completeness I show you the file "tex_file_writing.py", since I had to change the last two functions in the original file according to the installation steps specified in 

http://bhowell4.com/manic-install-tutorial-for-mac/

<img width="642" alt="Schermafbeelding 2020-04-26 om 13 48 33" src="https://user-images.githubusercontent.com/64358725/80306624-b8ae6c80-87c4-11ea-907f-6cd6fea63448.png">

**Comment by KjellCools** [comment]
Issue is solved. The TEX_DIR variable was empty.

**Comment by t1nak** [comment]
Just a little note in case someone else has this problem. I had the same issue and found out that my dvi_to_svg conversion was failing because of a ghostscript issue. You can test ``dvisvgm`` manually and see whether you get any errors. This lead me to discover that I had a second ghostscript  (in addition to MacTex's ghostscript) installed in one of the mac port directories which caused all the problems. So my solution was to uninstall all mac ports.
