### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by tanuj-chamil** [3b1b/manim#1011]
When I tried to run the example, This error happens. How can I resolve it?

```
C:\Program Files\manim>python -m manim example_scenes.py SquareToCircle -pl
Traceback (most recent call last):
  File "C:\Users\tanuj\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\tanuj\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\manim\manim.py", line 2, in <module>
    import manimlib
  File "C:\Program Files\manim\manimlib\__init__.py", line 4, in <module>
    import manimlib.extract_scene
  File "C:\Program Files\manim\manimlib\extract_scene.py", line 9, in <module>
    from manimlib.scene.scene import Scene
  File "C:\Program Files\manim\manimlib\scene\scene.py", line 9, in <module>
    from manimlib.animation.animation import Animation
  File "C:\Program Files\manim\manimlib\animation\animation.py", line 5, in <module>
    from manimlib.mobject.mobject import Mobject
  File "C:\Program Files\manim\manimlib\mobject\mobject.py", line 15, in <module>
    from manimlib.utils.color import color_gradient
  File "C:\Program Files\manim\manimlib\utils\color.py", line 8, in <module>
    from manimlib.utils.bezier import interpolate
  File "C:\Program Files\manim\manimlib\utils\bezier.py", line 1, in <module>
    from scipy import linalg
  File "C:\Users\tanuj\AppData\Roaming\Python\Python37\site-packages\scipy\__init__.py", line 70, in <module>
    from ._lib.deprecation import _deprecated
ModuleNotFoundError: No module named 'scipy._lib'
```

**Comment by TheTrueBrot** [comment]
Did you succesfully install all the dependencies? This happens sometimes if you get a broken scipy install. If you tried to install manim by cloning this repository you could try to fix it, by running `python3 -m pip install -r requirements.txt`. If you didn't install manim that way, I would also try to reinstall scipy with pip.

**Comment by therealchaudhri** [comment]
What version of Python and Manim are you running?

**Comment by tanuj-chamil** [comment]
I reinstalled scipy and the clone of the manim repository on 25 of April 2020. Still same issue with scipy

**Comment by Tony031218** [comment]
Try to uninstall scipy, and install a lower version scipy instead.

**Comment by TyomikJan** [comment]
I had the same issue.

**Comment by AndreaIdini** [comment]
As far as I understand, that's because manim will run all the content of your script from the library's file location that might no be the same location where you hold other libraries (even if usually is).

You can either reinstall your library in the appropriate module, if its library, or if its a personalized module you can specify the module absolute path with this workaround:

```
import importlib.util
spec = importlib.util.spec_from_file_location("module.name", "/your/path/file.py")
file = importlib.util.module_from_spec(spec)
spec.loader.exec_module(file)
```

Enjoy.
