### ISSUE TITLE
Exception: Xelatex error converting to xdv.

### ISSUE THREAD

**Issue by ahmedafifkhan** [3b1b/manim#1055]
For the past few hours I have been to stackoverflow, reddit and github issues, tried those but couldnot solve the problem. A kind help would be appreciated.

Also I think for future reference, if someone can shed the reasons that can lead to this issue, would be very much helpful.

```
PS C:\Users\...\manim> python -m manim example_scenes.py WriteStuff -pl
Media will be written to ./media\. You can change this behavior with the --media_dir flag.

Traceback (most recent call last):
  File "C:\Users\...\manim\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\Users\...\manim\manimlib\scene\scene.py", line 53, in __init__
    self.construct()
  File "example_scenes.py", line 100, in construct
    example_text = TextMobject(
  File "C:\Users\...\manim\manimlib\mobject\svg\tex_mobject.py", line 147, in __init__
    SingleStringTexMobject.__init__(
  File "C:\Users\...\manim\manimlib\mobject\svg\tex_mobject.py", line 42, in __init__
    file_name = tex_to_svg_file(
  File "C:\Users\...\manim\manimlib\utils\tex_file_writing.py", line 19, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
  File "C:\Users\...\manim\manimlib\utils\tex_file_writing.py", line 64, in tex_to_dvi
    raise Exception(
Exception: Xelatex error converting to xdv. See log output above or the log file: ./media\Tex\cfae0c2243103963.log
```

**Comment by Tony031218** [comment]
If you can read Chinese, [this pdf file](https://github.com/manim-kindergarten/manim_sandbox/blob/master/documents/manim%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98v2.2.pdf) will help you.

**Comment by TheFibonacciEffect** [comment]
Is KikTex properly installed?

**Comment by ahmedafifkhan** [comment]
> Is MikTex properly installed?

It is.
It's properly installed.
I was so frustrated that I reinstalled `manim` after trying so long to understand the issue.

I think if anyone trying to use `manim` for languages other than English will run into same issue. I was trying to `Write` in Bangla. I found some issue #735 where the solution posted by #680 by @xy-23 helped me write Bangla. I also downloaded `latexbangla` package for MiKTex. I rendered several texts.
I had to make `TEX_USE_CTEX` from `False` to `True`.

Then I was trying to use `TextMobject` to get along with the tutorial. When I ran into this issue. I tried almost everything possible for a newbie. But could not understand what was going on. It was several hours.

Then with no hope, I cloned the git repository and have overwritten all the files. It's back to work now. But I can't write `Bangla` now.

Even while writing this, I did #735 and tried to run `example_scenes.py` it showed this `Exception: Xelatex error converting to xdv.` I undid #735 then its working just fine.

**Comment by ElonDormancy** [comment]
> If you can read Chinese, [this pdf file](https://github.com/manim-kindergarten/manim_sandbox/blob/master/documents/manim%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98v2.2.pdf) will help you.
I read the pdf but I still have the same problem

**Comment by sallenkey-wei** [comment]
The latest Miktex seems to have a problem, so I chose to install the old offline package (http://mirror.lzu.edu.cn/CTAN/systems/win32/protext/protext.zip), after decompression, Under the directory [MiKTeX / setup], find the 64-bit installation package to install, do not update after installation, directly run writeStuff in example_scenes.py of manim, if prompted "Xelatex error converting to xdv", open tex File under [manim/media/Tex] , select xelatex to compile, if prompted ''! Package ctex Error: Support package `expl3 'too old.", Search for “l3kernel” package in MikTex Console, uninstall and reinstall.    [My current time is May 25, 2020]

**Comment by HumbleHumbert** [comment]
I have met this error when I make `TEX_USE_CTEX = True #False`
I tried many ways, finaly located it on `MiKTeX`, I then uninstall it and download `TexLive 2020 .IOS`, which own rather enough pakages, and it finally work.
So from what I see, it's the MiKTeX couldn't detect which pakage to install, or installed the wrong pakages, or didn't set the pakage properly.
Hope this would help!
