### ISSUE TITLE
Example_scenes.py run problem question

### ISSUE THREAD

**Issue by lakeside-park** [3b1b/manim#1065]
I was able to get the install success thanks to help.  I ran the example_scenes.py file and have the results below.  I am now also going  through https://talkingphysics.wordpress.com/2019/01/08/getting-started-animating-with-manim-and-python-3-7/ and have similar errors when running the first run python -m manim pymanim_tutorial_P37.py Shapes -pl.  So I am trying to crawl before walking and would like to get through example_scenes and first tutorial .py run with success so any help is appreciated.

C:\Users\Admin\Desktop\manim-master>python ./manim.py example_scenes.py SquareTo
Circle -pl
Media will be written to ./media\. You can change this behavior with the --media
_dir flag.
[concat @ 0000000000375a40] Impossible to open 'CC:/Users/Admin/Desktop/manim-ma
ster/media/videos/example_scenes/480p15/partial_movie_files/SquareToCircle/00000
.mp4'
C:\Users\Admin\Desktop\manim-master\media\videos\example_scenes\480p15\partial_m
ovie_files\SquareToCircle\partial_movie_file_list.txt: Protocol not found
Did you mean file:C:\Users\Admin\Desktop\manim-master\media\videos\example_scene
s\480p15\partial_movie_files\SquareToCircle\partial_movie_file_list.txt?

File ready at C:\Users\Admin\Desktop\manim-master\media\videos\example_scenes\48
0p15\SquareToCircle.mp4

Played 3 animations

Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\manim-master\manimlib\extract_scene.py", line 156
, in main
    open_file_if_needed(scene.file_writer, **config)
  File "C:\Users\Admin\Desktop\manim-master\manimlib\extract_scene.py", line 35,
 in open_file_if_needed
    os.startfile(file_path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\
Users\\Admin\\Desktop\\manim-master\\media\\videos\\example_scenes\\480p15\\Squa
reToCircle.mp4'

**Comment by lakeside-park** [comment]
thanks....line 289 change made it work
