### ISSUE TITLE
Problem launching example scenes

### ISSUE THREAD

**Issue by ziplas** [3b1b/manim#1088]
I ran the classis "python -m manim example_scenes.py" after the whole downloading and installing process and ended up with this message : 
`Traceback (most recent call last):
  File "C:\Users\[User]\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\[User]\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Manim\Actual Manim\manim_3_feb\manim.py", line 3, in <module>
    import manimlib.extract_scene
  File "C:\Manim\Actual Manim\manim_3_feb\manimlib\extract_scene.py", line 9, in <module>
    from manimlib.scene.scene import Scene
  File "C:\Manim\Actual Manim\manim_3_feb\manimlib\scene\scene.py", line 11, in <module>
    from manimlib.camera.camera import Camera
  File "C:\Manim\Actual Manim\manim_3_feb\manimlib\camera\camera.py", line 8, in <module>
    from scipy.spatial.distance import pdist
  File "C:\Users\[User]\AppData\Local\Programs\Python\Python37-32\lib\site-packages\scipy\spatial\__init__.py", line 94, in <module>
    from .kdtree import *
  File "C:\Users\[User]\AppData\Local\Programs\Python\Python37-32\lib\site-packages\scipy\spatial\kdtree.py", line 8, in <module>
    import scipy.sparse
  File "C:\Users\[User]\AppData\Local\Programs\Python\Python37-32\lib\site-packages\scipy\sparse\__init__.py", line 229, in <module>
    from .csr import *
  File "C:\Users\[User]\AppData\Local\Programs\Python\Python37-32\lib\site-packages\scipy\sparse\csr.py", line 15, in <module>
    from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, get_csr_submatrix, csr_sample_values
ImportError: DLL load failed: %1 is not a valid Win32 application.`
I have not seen that error anywhere else. Has anyone an idea ?

**Comment by asafmaman101** [comment]
Try checking out  #964
