### ISSUE TITLE
File runs with low resolution but has errors with high resolution

### ISSUE THREAD

**Issue by lakeside-park** [3b1b/manim#1098]
Developed a .py file using -pl option at end of command file.  Happy with results now want to create high resolution version of the file and getting an error.  Here is .cmd screen results below.  Is there something simple I am doing wrong?

LOW RESOLUTION RUN:
C:\Users\Admin\Desktop\manim-master\Mia_Video>python -m manim mit_name_scene_final.py -pl
Media will be written to ./media\. You can change this behavior with the --media_dir flag.

File ready at C:\Users\Admin\Desktop\manim-master\Mia_Video\media\videos\mit_name_scene_final\480p15\MIT_Name_Scene.mp4

Played 34 animations

HIGH RESOLUTION RUN:
C:\Users\Admin\Desktop\manim-master\Mia_Video>python -m manim mit_name_scene_final.py
Media will be written to ./media\. You can change this behavior with the --media_dir flag.

Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\manim-master\Mia_Video\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\Users\Admin\Desktop\manim-master\Mia_Video\manimlib\scene\scene.py", line 53, in __init__
    self.construct()
  File "mit_name_scene_final.py", line 14, in construct
    self.play(Write(MIT_name))
  File "C:\Users\Admin\Desktop\manim-master\Mia_Video\manimlib\scene\scene.py", line 406, in wrapper
    func(self, *args, **kwargs)
  File "C:\Users\Admin\Desktop\manim-master\Mia_Video\manimlib\scene\scene.py", line 463, in play
    self.progress_through_animations(animations)
  File "C:\Users\Admin\Desktop\manim-master\Mia_Video\manimlib\scene\scene.py", line 439, in progress_through_animations
    self.add_frames(self.get_frame())
  File "C:\Users\Admin\Desktop\manim-master\Mia_Video\manimlib\scene\scene.py", line 543, in add_frames
    self.file_writer.write_frame(frame)
  File "C:\Users\Admin\Desktop\manim-master\Mia_Video\manimlib\scene\scene_file_writer.py", line 178, in write_frame
    self.writing_process.stdin.write(frame.tostring())
OSError: [Errno 22] Invalid argument

**Comment by Level-314** [comment]
[Errno 22] with stdin.write is almost always a problem with either slashes or special characters in a file path.

I would say try creating a basic "hello world" video with one Write animation and see if that works in both "low" (-l) and standard resolution.

If that does work, please post at least a portion of your code here and I will try it on my end. If it doesn't work, you know there's weird back slash or special character sneaking into your file and path names.

**Comment by lakeside-park** [comment]
Here is a simple file I used to learn about warping -

from manimlib.imports import *

class WarpSquare(Scene):
    def construct(self):
        square = Square()
        self.play(ApplyPointwiseFunction(
            lambda point: complex_to_R3(np.exp(R3_to_complex(point))),
            square
        ))
        self.wait(3)

here are the result from the 2 runs

C:\Users\Admin\Desktop\manim-master\Mia_Video>python -m manim warp_sq.py -pl
Media will be written to ./media\. You can change this behavior with the --media_dir flag.

File ready at C:\Users\Admin\Desktop\manim-master\Mia_Video\media\videos\warp_sq\480p15\WarpSquare.mp4

Played 2 animations

C:\Users\Admin\Desktop\manim-master\Mia_Video>python -m manim warp_sq.py -p
Media will be written to ./media\. You can change this behavior with the --media_dir flag.



Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\manim-master\Mia_Video\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\Users\Admin\Desktop\manim-master\Mia_Video\manimlib\scene\scene.py", line 53, in __init__
    self.construct()
  File "warp_sq.py", line 8, in construct
    square
  File "C:\Users\Admin\Desktop\manim-master\Mia_Video\manimlib\scene\scene.py", line 406, in wrapper
    func(self, *args, **kwargs)
  File "C:\Users\Admin\Desktop\manim-master\Mia_Video\manimlib\scene\scene.py", line 463, in play
    self.progress_through_animations(animations)
  File "C:\Users\Admin\Desktop\manim-master\Mia_Video\manimlib\scene\scene.py", line 439, in progress_through_animations
    self.add_frames(self.get_frame())
  File "C:\Users\Admin\Desktop\manim-master\Mia_Video\manimlib\scene\scene.py", line 543, in add_frames
    self.file_writer.write_frame(frame)
  File "C:\Users\Admin\Desktop\manim-master\Mia_Video\manimlib\scene\scene_file_writer.py", line 178, in write_frame
    self.writing_process.stdin.write(frame.tostring())
OSError: [Errno 22] Invalid argument

**Comment by lakeside-park** [comment]
I ran the same thing in the main manim-master directory to see if that made a difference - it did not.  it got to about 24% processing then failed


C:\Users\Admin\Desktop\manim-master>python -m manim warp_sq.py -pl
Media will be written to ./media\. You can change this behavior with the --media_dir flag.

File ready at C:\Users\Admin\Desktop\manim-master\media\videos\warp_sq\480p15\WarpSquare.mp4

Played 2 animations

C:\Users\Admin\Desktop\manim-master>python -m manim warp_sq.py -p
Media will be written to ./media\. You can change this behavior with the --media_dir flag.



Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\manim-master\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\Users\Admin\Desktop\manim-master\manimlib\scene\scene.py", line 53, in __init__
    self.construct()
  File "warp_sq.py", line 8, in construct
    square
  File "C:\Users\Admin\Desktop\manim-master\manimlib\scene\scene.py", line 406, in wrapper
    func(self, *args, **kwargs)
  File "C:\Users\Admin\Desktop\manim-master\manimlib\scene\scene.py", line 463, in play
    self.progress_through_animations(animations)
  File "C:\Users\Admin\Desktop\manim-master\manimlib\scene\scene.py", line 439, in progress_through_animations
    self.add_frames(self.get_frame())
  File "C:\Users\Admin\Desktop\manim-master\manimlib\scene\scene.py", line 543, in add_frames
    self.file_writer.write_frame(frame)
  File "C:\Users\Admin\Desktop\manim-master\manimlib\scene\scene_file_writer.py", line 178, in write_frame
    self.writing_process.stdin.write(frame.tostring())
OSError: [Errno 22] Invalid argument

**Comment by lakeside-park** [comment]
if you want an even more basic program, please tell me and I will find a hello world .py to use

**Comment by Level-314** [comment]
No need for a more basic program; the one you provided is perfect. It rules out anything "odd" with the scene that could be causing your trouble.

Four questions to try to help debug:
1- Have you tried medium resolution (-pm)?

2- Have you tried without previewing (no options for high quality without preview and -m for medium without preview)?

3- Have you tried saving the frames to see where it fails (-g)?

4- Have you checked in the media folder to see what the output is. For example, for your -pl low quality test you should see files in a folder like
...[manim home directory]\media\videos\warp_sq\480p15\partial_movie_files

- - - - - - - - - - - - - - - - - - -

https://www.youtube.com/channel/UCgfJSRv4F86RDx8mDR-rK4Q/

https://level314.com

**Comment by lakeside-park** [comment]
Thanks for your help.  Back at this today.  After I posted last time I had a problem where nothing worked...even low resolution.  No idea what happened.  I tried to re-install ffmpeg because I saw that name in one error message and fixed the PATH to make sure it pointed to ffmpeg/bin.  Rebooted the computer.  Ran with -pl option fine.  Failed again with -p.  Ran many different versions - cmd output in attached file.  Tried several combinations and ordering - very strange results.   Hope you can make sense of what I was trying to do with all the tests

Today I followed some of your suggestions above - attached is docx  cmd output for
1) running file mit_logo_scene_final at low resolution - runs to completion
2) running file mit_logo_scene_final at high resolution - runs to completion
3) running file mit_logo_scene_final at high resolution - runs to completion
4) running file mit_name_scene_final at high resolution - error generated
5) running file mit_logo_scene_final at high resolution - runs to completion
6) running file mit_name_scene_final at low resolution -  runs to completion
7) running file mit_name_scene_final at medium resolution -  runs to completion
8) running file mit_name_scene_final at high resolution -  runs to completion
9) running file mit_name_scene_final at high resolution -  error generated
10) running file mit_name_scene_final at low resolution -  runs to completion - with latex warning
11) running file mit_name_scene_final at medium resolution -  runs to completion
12) running file mit_name_scene_final at high resolution -  error generated
13) running file mit_name_scene_final at high resolution with -g option -  error generated - I do not believe any partial frames were generated before error

[cmd window text.docx](https://github.com/3b1b/manim/files/4673695/cmd.window.text.docx)

**Comment by lakeside-park** [comment]
So I realized that you might have wanted me to stick to warp_sq.py  - here are the result from that

the high resolution run that failed generated about 95% of  the video

C:\Users\Admin\Desktop\manim-master\Mia_Video>python -m warp_sq.py -pl
C:\Users\Admin\AppData\Local\Programs\Python\Python37\python.exe: Error while finding module specification for 'warp_sq.py' (Modul
oundError: __path__ attribute not found on 'warp_sq' while trying to find 'warp_sq.py')

C:\Users\Admin\Desktop\manim-master\Mia_Video>python -m manim warp_sq.py -pl
Media will be written to ./media\. You can change this behavior with the --media_dir flag.

File ready at C:\Users\Admin\Desktop\manim-master\Mia_Video\media\videos\warp_sq\480p15\WarpSquare.mp4

Played 2 animations

C:\Users\Admin\Desktop\manim-master\Mia_Video>python -m manim warp_sq.py -pm
Media will be written to ./media\. You can change this behavior with the --media_dir flag.

File ready at C:\Users\Admin\Desktop\manim-master\Mia_Video\media\videos\warp_sq\720p30\WarpSquare.mp4

Played 2 animations

C:\Users\Admin\Desktop\manim-master\Mia_Video>python -m manim warp_sq.py -p
Media will be written to ./media\. You can change this behavior with the --media_dir flag.



Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\manim-master\Mia_Video\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\Users\Admin\Desktop\manim-master\Mia_Video\manimlib\scene\scene.py", line 53, in __init__
    self.construct()
  File "warp_sq.py", line 8, in construct
    square
  File "C:\Users\Admin\Desktop\manim-master\Mia_Video\manimlib\scene\scene.py", line 406, in wrapper
    func(self, *args, **kwargs)
  File "C:\Users\Admin\Desktop\manim-master\Mia_Video\manimlib\scene\scene.py", line 463, in play
    self.progress_through_animations(animations)
  File "C:\Users\Admin\Desktop\manim-master\Mia_Video\manimlib\scene\scene.py", line 439, in progress_through_animations
    self.add_frames(self.get_frame())
  File "C:\Users\Admin\Desktop\manim-master\Mia_Video\manimlib\scene\scene.py", line 543, in add_frames
    self.file_writer.write_frame(frame)
  File "C:\Users\Admin\Desktop\manim-master\Mia_Video\manimlib\scene\scene_file_writer.py", line 178, in write_frame
    self.writing_process.stdin.write(frame.tostring())
OSError: [Errno 22] Invalid argument




C:\Users\Admin\Desktop\manim-master\Mia_Video>python -m manim warp_sq.py -pg
Media will be written to ./media\. You can change this behavior with the --media_dir flag.
Animation 0: ApplyPointwiseFunctionSquare:  74%|#####################################9             | 134/180 [00:13<00:04,  9.90it


Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\manim-master\Mia_Video\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\Users\Admin\Desktop\manim-master\Mia_Video\manimlib\scene\scene.py", line 53, in __init__
    self.construct()
  File "warp_sq.py", line 8, in construct
    square
  File "C:\Users\Admin\Desktop\manim-master\Mia_Video\manimlib\scene\scene.py", line 406, in wrapper
    func(self, *args, **kwargs)
  File "C:\Users\Admin\Desktop\manim-master\Mia_Video\manimlib\scene\scene.py", line 463, in play
    self.progress_through_animations(animations)
  File "C:\Users\Admin\Desktop\manim-master\Mia_Video\manimlib\scene\scene.py", line 439, in progress_through_animations
    self.add_frames(self.get_frame())
  File "C:\Users\Admin\Desktop\manim-master\Mia_Video\manimlib\scene\scene.py", line 543, in add_frames
    self.file_writer.write_frame(frame)
  File "C:\Users\Admin\Desktop\manim-master\Mia_Video\manimlib\scene\scene_file_writer.py", line 178, in write_frame
    self.writing_process.stdin.write(frame.tostring())
OSError: [Errno 22] Invalid argument




C:\Users\Admin\Desktop\manim-master\Mia_Video>

**Comment by Level-314** [comment]
Based on the intermittent nature of the error, it seems that you can rule out a PATH name issue. Based on the information you've provided so far, my educated guess is one of two things:

1- Something wrong with your version of ffmpeg or
2- You're running into some issue with virtual memory

(1) because the line where you keep failing is basically trying to pipe the data for the next frame to ffmpeg for processing.

(2) because the seemingly "random" nature of when the bug pops makes me think there may be some system resource issue at play. The error only pops once some yet unknown threshold his reached.

When the full size video completes successfully, what is the resolution of the video? The version of manim I have installed defaults to 1440p. Maybe, if you only need 1080p you can try setting that as your resolution using the -r option.

(In case you weren't aware you can get a full list of options with: python -m manim -h)

I wish I could provide more assistance but I'm out of ideas to try from a distance.

**Comment by shakeneed** [comment]
maybe you forget to set “temporary_storage”  in default_config.yml
