### ISSUE TITLE
Open movie error

### ISSUE THREAD

**Issue by PackSciences** [3b1b/manim#1119]
Hi,

I had a previous error which I closed in which I had the incorrect version of Python.
I currently have Python 3.8.3 for Windows.
I have all the requirements in the requirements.txt (all satisfied when I redo the same command).

However when I do the command to test if it works:  `py -m pip install -r ./requirements.txt`.

I get one warning and one error.

The warning, first is:

> C:\Users\X\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
>   warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
> Media will be written to ./media\. You can change this behavior with the --media_dir flag.
> 

However I do have ffmpeg installed through pip.

Then I get the error:

> Traceback (most recent call last):
>   File "C:\Users\X\manim-master\manim-master\manimlib\extract_scene.py", line 155, in main
>     scene = SceneClass(**scene_kwargs)
>   File "C:\Users\X\manim-master\manim-master\manimlib\scene\scene.py", line 75, in __init__
>     self.construct()
>   File "example_scenes.py", line 83, in construct
>     self.play(ShowCreation(square))
>   File "C:\Users\X\manim-master\manim-master\manimlib\scene\scene.py", line 847, in wrapper
>     self.file_writer.begin_animation(allow_write)
>   File "C:\Users\X\manim-master\manim-master\manimlib\scene\scene_file_writer.py", line 310, in begin_animation
>     self.open_movie_pipe()
>   File "C:\Users\X\manim-master\manim-master\manimlib\scene\scene_file_writer.py", line 425, in open_movie_pipe
>     self.writing_process = subprocess.Popen(command, stdin=subprocess.PIPE)
>   File "C:\Users\X\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "C:\Users\X\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

which stops the program.

This error seems to be an output problem. I think Python has access to that folder so it is probably not a rights problem.

Could you please help me?

**Comment by PackSciences** [comment]
I found https://github.com/jiaaro/pydub/issues/348 by luck by looking for the warning keywords.
I installed manually ffmpeg to path (which seems it wasn't the case with pip install).
And it worked perfectly.
