### ISSUE TITLE
Shows BrokenPipeError while writing frames

### ISSUE THREAD

**Issue by NiCaiWoCaiBu** [3b1b/manim#1128]
When I finished downloading everything, I tried to render the example scene on my mac, but it showed an error. Below is the terminal message:
```bash
(base) situjianfeideMacBook-Air:manim situjianfei$ manim example_scenes.py SquareToCircle

Media will be written to ./media/. You can change this behavior with the --media_dir flag.                                                                                                     
Traceback (most recent call last):
  File "/Users/situjianfei/Anaconda/anaconda3/lib/python3.7/site-packages/manimlib/extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "/Users/situjianfei/Anaconda/anaconda3/lib/python3.7/site-packages/manimlib/scene/scene.py", line 53, in __init__
    self.construct()
  File "example_scenes.py", line 83, in construct
    self.play(ShowCreation(square))
  File "/Users/situjianfei/Anaconda/anaconda3/lib/python3.7/site-packages/manimlib/scene/scene.py", line 406, in wrapper
    func(self, *args, **kwargs)
  File "/Users/situjianfei/Anaconda/anaconda3/lib/python3.7/site-packages/manimlib/scene/scene.py", line 463, in play
    self.progress_through_animations(animations)
  File "/Users/situjianfei/Anaconda/anaconda3/lib/python3.7/site-packages/manimlib/scene/scene.py", line 439, in progress_through_animations
    self.add_frames(self.get_frame())
  File "/Users/situjianfei/Anaconda/anaconda3/lib/python3.7/site-packages/manimlib/scene/scene.py", line 543, in add_frames
    self.file_writer.write_frame(frame)
  File "/Users/situjianfei/Anaconda/anaconda3/lib/python3.7/site-packages/manimlib/scene/scene_file_writer.py", line 185, in write_frame
    self.writing_process.stdin.write(frame.tostring())
BrokenPipeError: [Errno 32] Broken pipe

(base) situjianfeideMacBook-Air:manim situjianfei$ 
```

**Comment by 314har-code** [comment]
Yes, I have the exact same problem. Mine prints:
`Traceback (most recent call last):
  File "/Users/henry/Desktop/ManimInstall/manim-master/manimlib/extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "/Users/henry/Desktop/ManimInstall/manim-master/manimlib/scene/scene.py", line 75, in __init__
    self.construct()
  File "example_scenes.py", line 111, in construct
    self.play(Write(example_text))
  File "/Users/henry/Desktop/ManimInstall/manim-master/manimlib/scene/scene.py", line 848, in wrapper
    func(self, *args, **kwargs)
  File "/Users/henry/Desktop/ManimInstall/manim-master/manimlib/scene/scene.py", line 944, in play
    self.progress_through_animations(animations)
  File "/Users/henry/Desktop/ManimInstall/manim-master/manimlib/scene/scene.py", line 901, in progress_through_animations
    self.add_frames(self.get_frame())
  File "/Users/henry/Desktop/ManimInstall/manim-master/manimlib/scene/scene.py", line 1135, in add_frames
    self.file_writer.write_frame(frame)
  File "/Users/henry/Desktop/ManimInstall/manim-master/manimlib/scene/scene_file_writer.py", line 336, in write_frame
    self.writing_process.stdin.write(frame.tostring())
BrokenPipeError: [Errno 32] Broken pipe`

**Comment by huguesdevimeux** [comment]
Did you correctly install `FFMPEG` ?
To check run `ffmpeg --version`.

**Comment by NiCaiWoCaiBu** [comment]
@huguesdevimeux You found the error, but I can't solve it. It says `Segmentation fault: 11`. No matter how I reinstall it, the error still appears. Maybe I'll try manim on another PC :(

**Comment by brainer3220** [comment]
Same error Apple Silicon M1.

Did you solve it?
