### ISSUE TITLE
Latex Matrix creation error

### ISSUE THREAD

**Issue by JimChr-R4GN4R** [3b1b/manim#1141]
I am trying to render this:
```
text1 = TextMobject(r"\begin{bmatrix} a & b \\ d & e \\ g & h \end{bmatrix}")

self.play(Write(text1))
```

But I get this error:
```
Traceback (most recent call last):
  File "D:\Manim\manim\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "D:\Manim\manim\manimlib\scene\scene.py", line 75, in __init__
    self.construct()
  File "tutorial\test.py", line 42, in construct
    text1 = TextMobject(r"""\begin{bmatrix} a & b \\ d & e \\ g & h \end{bmatrix}""")
  File "D:\Manim\manim\manimlib\mobject\svg\tex_mobject.py", line 147, in __init__
    SingleStringTexMobject.__init__(
  File "D:\Manim\manim\manimlib\mobject\svg\tex_mobject.py", line 42, in __init__
    file_name = tex_to_svg_file(
  File "D:\Manim\manim\manimlib\utils\tex_file_writing.py", line 21, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
  File "D:\Manim\manim\manimlib\utils\tex_file_writing.py", line 69, in tex_to_dvi
    raise Exception(
Exception: Latex error converting to dvi. See log output above or the log file: media/Tex/8b45b90e41755109.log
```

Also I used this to generate the Latex matrix: https://www.codecogs.com/latex/eqneditor.php

Can anyone help me? ^^

**Comment by JimChr-R4GN4R** [comment]
Also I used this to generate the Latex matrix: https://www.codecogs.com/latex/eqneditor.php

**Comment by Tony031218** [comment]
`TexMobject`

**Comment by JimChr-R4GN4R** [comment]
I could not see it XD
thank you <3
