### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by SabryAwad** [3b1b/manim#1143]
when I run the command
python -m manim example_scenes.py SquareToCircle -pl

this message is appeared 
Traceback (most recent call last):
  File "C:\Users\Sabry\AppData\Local\Programs\Python\Python37\lib\runpy.py", lin
e 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Sabry\AppData\Local\Programs\Python\Python37\lib\runpy.py", lin
e 85, in _run_code
    exec(code, run_globals)
  File "C:\Manim\manim_3_feb\manim.py", line 9, in <module>
    config = manimlib.config.get_configuration(args)
  File "C:\Manim\manim_3_feb\manimlib\config.py", line 158, in get_configuration

    module = get_module(args.file)
  File "C:\Manim\manim_3_feb\manimlib\config.py", line 153, in get_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "example_scenes.py", line 3, in <module>
    from big_ol_pile_of_manim_imports import *
  File "C:\Manim\manim_3_feb\big_ol_pile_of_manim_imports.py", line 81, in <modu
le>
    from manimlib.scene.scene_from_video import *
  File "C:\Manim\manim_3_feb\manimlib\scene\scene_from_video.py", line 2, in <mo
dule>
    import cv2
  File "C:\Users\Sabry\AppData\Local\Programs\Python\Python37\lib\site-packages\
cv2\__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: DLL load failed: The specified module could not be found.

**Comment by Tony031218** [comment]
https://github.com/skvark/opencv-python/issues/36
