### ISSUE TITLE
can't open file 'extract_scene.py'

### ISSUE THREAD

**Issue by scottyjung** [3b1b/manim#1146]
python3 extract_scene.py example_scenes.py SquareToCircle -pl

This code would not launch and returns

/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'extract_scene.py': [Errno 2] No such file or directory

![image](https://user-images.githubusercontent.com/67251139/85245147-a594e180-b481-11ea-9084-f70144b5fc20.png)

This is my file directory. Please help me.

**Comment by scottyjung** [comment]
python3 manim.py example_scenes.py SquareToCircle -pl

I've tried to code but it returned this.

/Users/hanbinjung/Programming/animation/manim37/venv/lib/python3.7/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Media will be written to ./media/. You can change this behavior with the --media_dir flag.



Traceback (most recent call last):
  File "/Users/hanbinjung/Programming/animation/manim37/manimlib/extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "/Users/hanbinjung/Programming/animation/manim37/manimlib/scene/scene.py", line 75, in __init__
    self.construct()
  File "example_scenes.py", line 83, in construct
    self.play(ShowCreation(square))
  File "/Users/hanbinjung/Programming/animation/manim37/manimlib/scene/scene.py", line 847, in wrapper
    self.file_writer.begin_animation(allow_write)
  File "/Users/hanbinjung/Programming/animation/manim37/manimlib/scene/scene_file_writer.py", line 310, in begin_animation
    self.open_movie_pipe()
  File "/Users/hanbinjung/Programming/animation/manim37/manimlib/scene/scene_file_writer.py", line 425, in open_movie_pipe
    self.writing_process = subprocess.Popen(command, stdin=subprocess.PIPE)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg': 'ffmpeg'


I've installed ffmpeg but I don't know why it is not working...

Please help.

**Comment by Tony031218** [comment]
Don't use pip to install ffmpeg. ffmpeg is an independent software not a python package.

Try `ffmpeg --version` first after installing ffmpeg to your computer.
