### ISSUE TITLE
Tab error

### ISSUE THREAD

**Issue by Bharadwaj17** [3b1b/manim#1149]
I could not fix this error. Please help me to fix this. This is the code I have written

![Capture](https://user-images.githubusercontent.com/67364925/85556278-51862a80-b644-11ea-9c77-44d659893cfe.JPG)

C:\manim\manim_21_june>python manim.py Cyclic.py

Traceback (most recent call last):
  File "manim.py", line 5, in <module>
    manimlib.main()
  File "C:\manim\manim_21_june\manimlib\__init__.py", line 9, in main
    config = manimlib.config.get_configuration(args)
  File "C:\manim\manim_21_june\manimlib\config.py", line 155, in get_configuration
    module = get_module(args.file)
  File "C:\manim\manim_21_june\manimlib\config.py", line 150, in get_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "Cyclic.py", line 306
    circle = Circle()
                    ^
TabError: inconsistent use of tabs and spaces in indentation

![log](https://user-images.githubusercontent.com/67364925/85556545-91e5a880-b644-11ea-8bd8-e512aeddbb8f.JPG)

**Comment by Tony031218** [comment]
Don't mix tabs and spaces. Try to remove all indentation and use only spaces for indentation or only tabs for indentation.
Btw, this is not a question about manim, but a question about python. You can find the answer on Google.

**Comment by Bharadwaj17** [comment]
I apologize for posting this here. Thanks for your response.
