### ISSUE TITLE
ModuleNotFoundError: No module named 'cairo._cairo'

### ISSUE THREAD

**Issue by Juliebas** [3b1b/manim#1158]
I was trying to install Manim using this video:

https://youtu.be/z_WJaHYH66M?

but, after all steps, ocorred me this error on Python 3.7 trying to execute "python3.7 -m manim example_scenes.py SquareToCircle -pl":

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/julin/Manim/manim-master/manim.py", line 2, in <module>
    import manimlib
  File "/home/julin/Manim/manim-master/manimlib/__init__.py", line 4, in <module>
    import manimlib.extract_scene
  File "/home/julin/Manim/manim-master/manimlib/extract_scene.py", line 9, in <module>
    from manimlib.scene.scene import Scene
  File "/home/julin/Manim/manim-master/manimlib/scene/scene.py", line 11, in <module>
    from manimlib.camera.camera import Camera
  File "/home/julin/Manim/manim-master/manimlib/camera/camera.py", line 9, in <module>
    import cairo
  File "/usr/lib/python3/dist-packages/cairo/__init__.py", line 1, in <module>
    from ._cairo import *  # noqa: F401,F403
ModuleNotFoundError: No module named 'cairo._cairo'

I already tried to install cairo in so many ways, but nothing changes, what can I do?

**Comment by naveen521kk** [comment]
Which os do you run @Juliebas ?

**Comment by Juliebas** [comment]
> Which os do you run @Juliebas ?
> If you are on linux Ubuntu based distro running the below command would fix AFAIK.
> 
> ```shell
> sudo apt install libcairo2-dev pkg-config python3-dev
> ```

I run Ubuntu and made what you said, seems like download something but nothing changes, still give me the same results

**Comment by naveen521kk** [comment]
First check https://pycairo.readthedocs.io/en/latest/getting_started.html, if there is a solution for the above. 
If not you should open this as an issue in [pycairo](https://github.com/pygobject/pycairo/issues). Because it's a issue there and not of manim. Please close the issue ;)

**Comment by Juliebas** [comment]
Yes, the issue is on cairo, I will ask on their forum, thx!
