### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'loader'

### ISSUE THREAD

**Issue by jotrades** [3b1b/manim#1172]
I have been getting this error after I created an anaconda environment 
```python
Traceback (most recent call last):
  File "/home/jotrades/Anaconda/anaconda3/envs/manim/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jotrades/Anaconda/anaconda3/envs/manim/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jotrades/Documents/manim/manim/manim.py", line 5, in <module>
    manimlib.main()
  File "/home/jotrades/Documents/manim/manim/manimlib/__init__.py", line 9, in main
    config = manimlib.config.get_configuration(args)
  File "/home/jotrades/Documents/manim/manim/manimlib/config.py", line 155, in get_configuration
    module = get_module(args.file)
  File "/home/jotrades/Documents/manim/manim/manimlib/config.py", line 149, in get_module
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 568, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'
```
the command I ran is :
```bash
python3 -m manim example_scenes OpeningManimExample -pl
```
OS: Linux(Ubuntu 18.04)
Python:3.6

**Comment by kilacoda** [comment]
You need to pass in the filename with the extension. So `example_scenes` will be `example_scenes.py`

**Comment by jotrades** [comment]
oops, my bad, got it working, thanks
