### ISSUE TITLE
Broken pipe error but not because FFMPEG, in stead `permission denied`

### ISSUE THREAD

**Issue by stevenschn** [3b1b/manim#1182]
I have been working with MANIM quite some time now and it all worked well. I haven't worked on it for about two weeks and all of the sudden (with no serious changes on either manim or computer) I run into an error when I try to compile a video.

I get the following:
```

PS C:\Users\steve\OneDrive\Documenten\Nerds\Manim\manim> py -m manim .\example_scenes.py SquareToCircle -pl
Media will be written to ./media\. You can change this behavior with the --media_dir flag.
Animation 0: ShowCreationSquare:   7%|########7
1/15 [00:00<00:02,  5.89it/s]C:\Users\steve\OneDrive\Documenten\Nerds\Manim\manim\media\videos\example_scenes\480p15\partial_movie_files\SquareToCircle\00000_temp.mp4: Permission denied

Traceback (most recent call last):
  File "C:\Users\steve\OneDrive\Documenten\Nerds\Manim\manim\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\Users\steve\OneDrive\Documenten\Nerds\Manim\manim\manimlib\scene\scene.py", line 53, in __init__
    self.construct()
  File ".\example_scenes.py", line 83, in construct
    self.play(ShowCreation(square))
  File "C:\Users\steve\OneDrive\Documenten\Nerds\Manim\manim\manimlib\scene\scene.py", line 406, in wrapper
    func(self, *args, **kwargs)
  File "C:\Users\steve\OneDrive\Documenten\Nerds\Manim\manim\manimlib\scene\scene.py", line 463, in play
    self.progress_through_animations(animations)
  File "C:\Users\steve\OneDrive\Documenten\Nerds\Manim\manim\manimlib\scene\scene.py", line 439, in progress_through_animations
    self.add_frames(self.get_frame())
  File "C:\Users\steve\OneDrive\Documenten\Nerds\Manim\manim\manimlib\scene\scene.py", line 543, in add_frames
    self.file_writer.write_frame(frame)
  File "C:\Users\steve\OneDrive\Documenten\Nerds\Manim\manim\manimlib\scene\scene_file_writer.py", line 186, in write_frame
    self.writing_process.stdin.write(frame.tostring())
BrokenPipeError: [Errno 32] Broken pipe
```
Now I have found other issues regarding the Broken Pipe issue, but as far as I can tell, this was always because of the FFMPEG codec. But in the above we find:

`1/15 [00:00<00:02,  5.89it/s]C:\Users\steve\OneDrive\Documenten\Nerds\Manim\manim\media\videos\example_scenes\480p15\partial_movie_files\SquareToCircle\00000_temp.mp4: Permission denied`

As if this map is unreachable. I already tried to change the MEDIA DIR, but same error occurs. Also, when I render an image, so use `-ps`, no error occurs at all.

Any thoughts?

**Comment by naveen521kk** [comment]
That because of your AV probably. Disable it.

**Comment by WilloughbySeago** [comment]
I'm trying to run manim for the first time and I'm having the same problem, the reply hasn't helped as I don't know what 'AV' is, any help would be much appreciated.

**Comment by naveen521kk** [comment]
'AV' -> AntiVirus. Sorry, for not telling this before.

**Comment by stevenschn** [comment]
Honestly I am not quite sure how I fixed it. I tried a lot a lot of different ways. Eventually it worked out. I did follow the procedure as described by Theorem from Beethoven, and only deviated from it when I got errors. Sorry that this is not a very accurate solution for your problem. But keep having faith, I reckon it is possible to get it running on any machine!

**Comment by WilloughbySeago** [comment]
It was the antivirus, thanks for the encouragement, its fixed now

**Comment by Raph1603** [comment]
I am having exactly the same issue but I am not sure I have any AV. I am on macOS Catalina. Any ideas?

**Comment by kl43b** [comment]
> I am having exactly the same issue but I am not sure I have any AV. I am on macOS Catalina. Any ideas?

Might be ransomware protection (on your OS I think the default protection is XProtect). You could try a project folder outside of your "home" folder. While this isn't a permanent solution, if this works then at least manim's install is probably okay.

In my experience, ransomware blocking has been less informative, but it's getting better. A few weeks ago ffmpeg just died on me with no explanation; today I got an alert and was prompted to allow ffmpeg access to my protected folders (and now it works like it should).
