### ISSUE TITLE
 Problems in compiling Chinese tex

### ISSUE THREAD

**Issue by H-cloud-code** [3b1b/manim#1188]
When I run Python manim.py wz.py -PL, it reported an error:

Traceback (most recent call last):

File "..\manim\manimlib\extract_ scene.py ", line 155, in main

scene = SceneClass(**scene_ kwargs)

File "..\manim\manimlib\scene\ scene.py ", line 53, in __ init__

self.construct ()

My system is Windows 7 manim, which is on July 28, 2020.

wz.py The source code is:

from manimlib.imports import *

class textE(Scene):

def construct(self):

T1 = textmobject ('Hello everyone ')

T2 = texmobject ("Hello, hi")

t2.shift(DOWN)

self.add (t1,t2)

self.wait ()

What should I do?

**Comment by Tony031218** [comment]
Please copy the error message in its entirety, and search for related issues in this repo, such as: #1027 #1055 #290 #570
