### ISSUE TITLE
Latex itemize list support

### ISSUE THREAD

**Issue by gitlqs** [3b1b/manim#1193]
I'm trying to manipulate each item in a latex list (e.g. change colour, set movement animation) in Manim but it won't let me do so. I can break a latex formula into parts but why can't I do the same to latex list?

This is my code:
```
class TitleAndListOfContent(Scene):
    def construct(self):
        list_of_content = TextMobject(
            '\\begin {itemize}',
            '\\item a',
            '\\item b',
            '\\item c',
            '\\end {itemize}',
        )
        self.play(Write(list_of_content))
        self.wait()
```
and the traceback:
```
Traceback (most recent call last):
  File ".../manim/manimlib/extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File ".../manim/manimlib/scene/scene.py", line 75, in __init__
    self.construct()
  File "my_scene.py", line 33, in construct
    '\\end {itemize}',
  File ".../manim/manimlib/mobject/svg/tex_mobject.py", line 148, in __init__
    self, self.arg_separator.join(tex_strings), **kwargs
  File ".../manim/manimlib/mobject/svg/tex_mobject.py", line 44, in __init__
    self.template_tex_file_body
  File ".../manim/manimlib/utils/tex_file_writing.py", line 21, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
  File ".../manim/manimlib/utils/tex_file_writing.py", line 72, in tex_to_dvi
    "See log output above or the log file: %s" % log_file)
Exception: Xelatex error converting to xdv. See log output above or the log file: media/Tex/a64dc4dc7f5621bd.log
```

For a reference, the visual effect I'm trying to achieve is something like this: https://youtu.be/BOMNd-bRQ4A?t=31

Thank you

**Comment by Tony031218** [comment]
Don't split them:
```python
list_of_content = TextMobject("""
    \\begin {itemize}
    \\item a
    \\item b
    \\item c
    \\end {itemize}
""")
```
And you can try `BulletedList` (also in `moject/svg/tex_mobject.py`

**Comment by gitlqs** [comment]
`BulletedList` is exact what I what! Thank you!
