### ISSUE TITLE
ThreeDScene crashes

### ISSUE THREAD

**Issue by bhbr** [3b1b/manim#121]
This playground:

```
from helpers import *
from mobject import Mobject
from mobject.vectorized_mobject import *
from animation.animation import Animation
from animation.transform import *
from animation.simple_animations import *
from topics.geometry import *
from scene import Scene
from camera import Camera
from topics.three_dimensions import *


class SampleScene(ThreeDScene):

    def construct(self):

        mob = Circle()
        self.add(mob)
```

yields:

```
Bens-MacBook-Pro:manim Ben$ python extract_scene.py ben_playground.py SampleScene -s
Played a total of 0 animations



Traceback (most recent call last):
  File "extract_scene.py", line 242, in main
    handle_scene(SceneClass(**scene_kwargs), **config)
  File "extract_scene.py", line 125, in handle_scene
    scene.save_image(mode = config["saved_image_mode"])
  File "/Users/Ben/Developer/manim/scene/scene.py", line 520, in save_image
    self.update_frame()
  File "/Users/Ben/Developer/manim/scene/scene.py", line 150, in update_frame
    self.capture_mobjects_in_camera(mobjects, **kwargs)
  File "/Users/Ben/Developer/manim/scene/scene.py", line 131, in capture_mobjects_in_camera
    self.camera.capture_mobjects(mobjects, **kwargs)
  File "/Users/Ben/Developer/manim/camera/camera.py", line 202, in capture_mobjects
    self.display_multiple_vectorized_mobjects(vmobjects)
  File "/Users/Ben/Developer/manim/topics/three_dimensions.py", line 98, in display_multiple_vectorized_mobjects
    self, sorted(vmobjects, cmp = z_cmp)
  File "/Users/Ben/Developer/manim/camera/camera.py", line 226, in display_multiple_vectorized_mobjects
    self.display_multiple_non_background_colored_vmobjects(batch)
  File "/Users/Ben/Developer/manim/camera/camera.py", line 232, in display_multiple_non_background_colored_vmobjects
    self.display_vectorized(vmobject, canvas)
  File "/Users/Ben/Developer/manim/camera/camera.py", line 241, in display_vectorized
    pen, fill = self.get_pen_and_fill(vmobject)
  File "/Users/Ben/Developer/manim/camera/camera.py", line 251, in get_pen_and_fill
    stroke_rgb = self.get_stroke_rgb(vmobject)
  File "/Users/Ben/Developer/manim/topics/three_dimensions.py", line 50, in get_stroke_rgb
    return self.modified_rgb(vmobject, vmobject.get_stroke_rgb())
  File "/Users/Ben/Developer/manim/topics/three_dimensions.py", line 47, in modified_rgb
    return color
NameError: global name 'color' is not defined



Bens-MacBook-Pro:manim Ben$
```

**Comment by 3b1b** [comment]
This should be fixed now.
