### ISSUE TITLE
Hi, How can I configure the tex_template to write Arabic In Manim?

### ISSUE THREAD

**Issue by KhadimNamah** [3b1b/manim#1241]
I want to display the text `"عشق"` in Manim.

This issue is pretty similar to #840 

I have tried to do what was suggested for this issue (#840 that is) but I was unable to make it work.

1. Firstly, I changed TEX_USE_CTEX in manimlib/constants.py to True.

2. Then I changed the file ctex_template.tex as follows:

The original ctex_template.tex file was:
```tex
    \documentclass[preview]{standalone}

    \usepackage[english]{babel}
    \usepackage{amsmath}
    \usepackage{amssymb}
    \usepackage{dsfont}
    \usepackage{setspace}
    \usepackage{tipa}
    \usepackage{relsize}
    \usepackage{textcomp}
    \usepackage{mathrsfs}
    \usepackage{calligra}
    \usepackage{wasysym}
    \usepackage{ragged2e}
    \usepackage{physics}
    \usepackage{xcolor}
    \usepackage{microtype}
    %\DisableLigatures{encoding = *, family = * }
    \usepackage[UTF8]{ctex}
    \linespread{1}

    \begin{document}

    YourTextHere

    \end{document}
```

I have change it to:
```tex
    \documentclass[preview]{standalone}

    %\usepackage[english]{babel}
    \usepackage{amsmath}
    \usepackage{amssymb}
    \usepackage{dsfont}
    \usepackage{setspace}
    \usepackage{tipa}
    \usepackage{relsize}
    \usepackage{textcomp}
    \usepackage{mathrsfs}
    \usepackage{calligra}
    \usepackage{wasysym}
    \usepackage{ragged2e}
    \usepackage{physics}
    \usepackage{xcolor}
    \usepackage{microtype}
    %\DisableLigatures{encoding = *, family = * }
    \usepackage[UTF8]{ctex}
    %\linespread{1}

    \usepackage{polyglossia}
    \setmainlanguage{arabic}
    \setotherlanguage{english}
    \newfontfamily\englishfont[Scale=MatchLowercase]{Linux Biolinum O}
    \newfontfamily\arabicfont{Droid Arabic Naskh}

    \begin{document}

    YourTextHere

    \end{document}
```
3. After this I tried rendering the following scene:

```python
class Test(Scene):
    def construct(self):
        text = TextMobject("عشق", font="Droid Arabic Naskh")
        self.add(text)
```

I got the following error:

    Traceback (most recent call last):
    File "/Users/sameedmac/PycharmProjects/ManimPyCharmTrial/manim/manimlib/extract_scene.py", line 155, in main
      scene = SceneClass(**scene_kwargs)
    File "/Users/sameedmac/PycharmProjects/ManimPyCharmTrial/manim/manimlib/scene/scene.py", line 75, in __init__
      self.construct()
    File "/Users/sameedmac/Desktop/ManimTemplatePyCharm/main.py", line 15, in construct
      text = TextMobject("عشق", font="Droid Arabic Naskh")
    File "/Users/sameedmac/PycharmProjects/ManimPyCharmTrial/manim/manimlib/mobject/svg/tex_mobject.py", line 147, in     __init__
    SingleStringTexMobject.__init__(
    File "/Users/sameedmac/PycharmProjects/ManimPyCharmTrial/manim/manimlib/mobject/svg/tex_mobject.py", line 42, in __init__
    file_name = tex_to_svg_file(
    File "/Users/sameedmac/PycharmProjects/ManimPyCharmTrial/manim/manimlib/utils/tex_file_writing.py", line 21, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
    File "/Users/sameedmac/PycharmProjects/ManimPyCharmTrial/manim/manimlib/utils/tex_file_writing.py", line 69, in tex_to_dvi
    raise Exception(
    Exception: Latex error converting to dvi. See log output above or the log file: media/Tex/1fdc1280131ec656.log

    Process finished with exit code 0

I am not sure what I am supposed to do now. Any help with this issue would be great.
Thank you:)

**Comment by Tony031218** [comment]
Try to use `Text`, like #1015

**Comment by KhadimNamah** [comment]
> Try to use `Text`, like #1015

Hi, thanks for the response.

I have tried this now. Here is what I have done:

I tried to render the following scene:

```python
class Test(Scene):
    text = Text("عشق", font="Droid Arabic Naskh")
    self.add((text))
```

I get the output as follows:


<img width="852" alt="Test Arabic" src="https://user-images.githubusercontent.com/60799596/94783139-28540380-03c4-11eb-8dd5-60c743bfd4e2.png">

This should not happen. It should instead look like:

<img width="375" alt="Arabic" src="https://user-images.githubusercontent.com/60799596/94783657-e8415080-03c4-11eb-9044-1821e4be69b3.png">

So, what it is doing is that it is:
1. Not joining the letters properly
2. Printing the letters from left to right instead of right to left.


I am guessing I will have to use the original approach of making changes in ctex_template.tex so that I can use proper XeLatex to print arabic text properly.


Is there a way to fix the original issue that I have laid out?

Are there any other ways to do this?

And this: https://github.com/3b1b/manim/issues/1015#issuecomment-621834526_ be used here somehow??

Any help with this issue would be great. Thanks a lot in advance:)

**Comment by Nyarlth** [comment]
try to use "texmobjext("\\text{عشق}")"

**Comment by KhadimNamah** [comment]
> try to use "texmobjext(r"\text{عشق}")"

Hi! Thanks for the response.

I tried doing that and for some reason it is giving the same error...

Is it working for you?

**Comment by Nyarlth** [comment]
> > try to use "texmobjext(r"\text{عشق}")"
> 
> Hi! Thanks for the response.
> 
> I tried doing that and for some reason it is giving me an error...
> 
> Is it working for you?
i tried it.But,it give me a error"list out of range",i add same number in it ,it work but just have numbers.

**Comment by Nyarlth** [comment]
> > > try to use "texmobjext(r"\text{عشق}")"
> > 
> > 
> > Hi! Thanks for the response.
> > I tried doing that and for some reason it is giving me an error...
> > Is it working for you?
> > i tried it.But,it give me a error"list out of range",i add same number in it ,it work but just have numbers.


![屏幕截图 2020-10-27 182617](https://user-images.githubusercontent.com/48179007/97289275-f0849280-1881-11eb-9606-69aeb54b956e.png)

**Comment by aliPMPAINT** [comment]
I think you might be better off trying https://github.com/ManimCommunity/manim , I've heard that they've added support for Arabic.

**Comment by yousif-hag-ahmed** [comment]
Alsalam Alikoum
After trying some Ideas ,I found this to work , I hope this solves the issue . Salam Alikoum in Arabic with some text in English 

change your manim>tex_template.tex to 

\documentclass[preview]{standalone}



\usepackage[utf8]{inputenc}
\usepackage[main = arabic,english]{babel}
\usepackage{arabtex}
\usepackage[LAE,LFE]{fontenc}


\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{dsfont}
\usepackage{setspace}
\usepackage{tipa}
\usepackage{relsize}
\usepackage{textcomp}
\usepackage{mathrsfs}
\usepackage{calligra}
\usepackage{wasysym}
\usepackage{ragged2e}
\usepackage{physics}
\usepackage{xcolor}
\usepackage{microtype}
%\DisableLigatures{encoding = *, family = * }
\usepackage[UTF8]{ctex}
\linespread{1}

\begin{document}

YourTextHere

\end{document}




note that this will change the default language to Arabic so to render English text you need to use text()
For arabic ,You use TextMobject 

Example :

https://user-images.githubusercontent.com/69925471/103449184-a6010700-4c72-11eb-856f-8aa382a0bf75.mp4

class Arabic(Scene):
    def add_text(self):
        text_1 = TextMobject("السلام عليكم " )
        self.play(Write(text_1))
        self.wait(2)
        self.play(Uncreate(text_1))
        self.wait(1)
        example_text = Text(
            "This is some text",
            tex_to_color_map={"text": YELLOW}
        )
        example_tex = TexMobject(
            "\\sum_{k=1}^\\infty {1 \\over k^2} = {\\pi^2 \\over 6}",
        )
        group = VGroup(example_text, example_tex)
        group.arrange(DOWN)
        group.set_width(FRAME_WIDTH - 2 * LARGE_BUFF)
        self.play(Write(example_text))
        self.play(Write(example_tex))
        self.wait()
    def construct(self):
        self.add_text()


best

**Comment by yousif-hag-ahmed** [comment]
https://github.com/3b1b/manim/issues/1173#issuecomment-796085675

**Comment by ahmedmick** [comment]
just use ```Text``` with ```font``` set to ```arabic``` ex:
```c++
arab_text = Text("كل مرة", font="arabic", font_size=100)
````
