### ISSUE TITLE
Issue running WriteStuff

### ISSUE THREAD

**Issue by Samorales03** [3b1b/manim#1242]
I was able to run SquareToCircle, but when running WriteStuff I get the following error 

> Traceback (most recent call last):
  File "C:\manim\manim_\manimlib\extract_scene.py", line 153, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\manim\manim_\manimlib\scene\scene.py", line 54, in __init__
    self.construct()
  File "example_scenes.py", line 100, in construct
    tex_to_color_map={"text": YELLOW}
  File "C:\manim\manim_\manimlib\mobject\svg\tex_mobject.py", line 144, in __init__
    self, self.arg_separator.join(tex_strings), **kwargs
  File "C:\manim\manim_\manimlib\mobject\svg\tex_mobject.py", line 45, in __init__
    self.template_tex_file_body
  File "C:\manim\manim_\manimlib\utils\tex_file_writing.py", line 19, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
  File "C:\manim\manim_\manimlib\utils\tex_file_writing.py", line 67, in tex_to_dvi
    "See log output above or the log file: %s" % log_file)
Exception: Latex error converting to dvi. See log output above or the log file: C:\manim\manim_\manimlib\files\Tex\3b64c623784a415b.log

I tried running the error file and after a while (around 3 minutes) it showed the document without any error
Any help?

**Comment by Tony031218** [comment]
https://github.com/3b1b/manim/labels/LaTeX
