### ISSUE TITLE
Broken Pipe Error

### ISSUE THREAD

**Issue by vrajgohil1** [3b1b/manim#1256]
root@goorm:/workspace/Manim/manim(master)# python3 ./manim.py example_scenes.py SquareToCircle -pl
Media will be written to /workspace/Manim/manim/media/. You can change this behavior with the --media_dir flag.

Traceback (most recent call last):
  File "/workspace/Manim/manim/manimlib/extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "/workspace/Manim/manim/manimlib/scene/scene.py", line 75, in __init__
    self.construct()
  File "example_scenes.py", line 83, in construct
    self.play(ShowCreation(square))
  File "/workspace/Manim/manim/manimlib/scene/scene.py", line 848, in wrapper
    func(self, *args, **kwargs)
  File "/workspace/Manim/manim/manimlib/scene/scene.py", line 944, in play
    self.progress_through_animations(animations)
  File "/workspace/Manim/manim/manimlib/scene/scene.py", line 901, in progress_through_animations
    self.add_frames(self.get_frame())
  File "/workspace/Manim/manim/manimlib/scene/scene.py", line 1135, in add_frames
    self.file_writer.write_frame(frame)
  File "/workspace/Manim/manim/manimlib/scene/scene_file_writer.py", line 336, in write_frame
    self.writing_process.stdin.write(frame.tobytes())
BrokenPipeError: [Errno 32] Broken pipe

**Comment by Tony031218** [comment]
See [these issues](https://github.com/3b1b/manim/issues?q=is%3Aissue+broken+pipe) first.

**Comment by paprika-wasabi** [comment]
having same issue using macOS
