### ISSUE TITLE
Problem installing on Windows

### ISSUE THREAD

**Issue by plof27** [3b1b/manim#1271]
I am running Windows 10 64-bit. I already successfully installed `pycairo` (version `1.20.0`). I was able to get manim working when cloning directly from the repository, but when I try to install the `manim` package using `pip3`, I get the following error:

```
pangocairocffi file-.pangocairocffi-VERSION requires cairocffi>=1.0.2, but you'll have cairocffi file-.cairocffi-VERSION which is incompatible.
pangocairocffi file-.pangocairocffi-VERSION requires pangocffi>=0.4.0, but you'll have pangocffi file-.pangocffi-VERSION which is incompatible.
manim 0.1.0 requires cairocffi<2.0.0,>=1.1.0, but you'll have cairocffi file-.cairocffi-VERSION which is incompatible.
manim 0.1.0 requires pangocairocffi<0.4.0,>=0.3.0, but you'll have pangocairocffi file-.pangocairocffi-VERSION which is incompatible.
manim 0.1.0 requires pangocffi<0.7.0,>=0.6.0, but you'll have pangocffi file-.pangocffi-VERSION which is incompatible.
```
(full output: [manim_install.log](https://github.com/3b1b/manim/files/5533176/manim_install.log))

I can only assume this is related, although I honestly don't know how. When I try to run the examples, I get the [No module named ‘[…]._generated.ffi’](https://docs.manim.community/en/latest/installation/troubleshooting.html) error. After following those fixes, I got the following error from manim.
```
PS D:\Documents\manim-install> python3 -m manim example_scenes.py SquareToCircle -pl
[11/12/20 14:35:11] WARNING  Option -l is deprecated please use the --quality/-q flag.              config_utils.py:670
Traceback (most recent call last):
  File "D:\Programs\Python3.6\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "D:\Programs\Python3.6\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "D:\Programs\Python3.6\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "D:\Programs\Python3.6\lib\site-packages\manim\__init__.py", line 61, in <module>
    from .scene.js_scene import *
  File "D:\Programs\Python3.6\lib\site-packages\manim\scene\js_scene.py", line 5, in <module>
    from ..grpc.gen import renderserver_pb2
  File "D:\Programs\Python3.6\lib\site-packages\manim\grpc\gen\renderserver_pb2.py", line 20, in <module>
    serialized_pb=b'\n\x12renderserver.proto\x12\x0crenderserver"\x0e\n\x0c\x45mptyRequest"\x0f\n\rEmptyResponse"\x1f\n\x0fNewSceneRequest\x12\x0c\n\x04name\x18\x01 \x01(\t"\x12\n\x10NewSceneResponse"+\n\tAnimation\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x64uration\x18\x02 \x01(\x02"\x18\n\x16\x41nimationStatusRequest"\x19\n\x17\x41nimationStatusResponse"m\n\x12ManimStatusRequest\x12\x12\n\nscene_name\x18\x01 \x01(\t\x12\x16\n\x0escene_finished\x18\x02 \x01(\x08\x12+\n\nanimations\x18\x03 \x03(\x0b\x32\x17.renderserver.Animation"\x15\n\x13ManimStatusResponse"\x14\n\x12UpdateSceneRequest"\x15\n\x13UpdateSceneResponse2\x94\x03\n\x0cRenderServer\x12J\n\x0f\x41nimationStatus\x12\x1a.renderserver.EmptyRequest\x1a\x1b.renderserver.EmptyResponse\x12R\n\x0bManimStatus\x12 .renderserver.ManimStatusRequest\x1a!.renderserver.ManimStatusResponse\x12R\n\x0bUpdateScene\x12 .renderserver.UpdateSceneRequest\x1a!.renderserver.UpdateSceneResponse\x12\x46\n\x08NewScene\x12\x1d.renderserver.NewSceneRequest\x1a\x1b.renderserver.EmptyResponse\x12H\n\rSceneFinished\x12\x1a.renderserver.EmptyRequest\x1a\x1b.renderserver.EmptyResponseb\x06proto3',
TypeError: __init__() got an unexpected keyword argument 'serialized_options'
```

Any help is appreciated.

**Comment by Tony031218** [comment]
If you are using [ManimCommunity/manim](https://github.com/ManimCommunity/manim), please open a issue there not here.

**Comment by plof27** [comment]
This answer was not related to my question, as I wasn't using ManimCommunity/manim. (I didn't even know of its existence until now.) However, installing the community fork did give me a functioning manim install, so it all worked out in the end. Thanks!
