### ISSUE TITLE
problem installing on windows 10

### ISSUE THREAD

**Issue by IRFANBINASHRAF** [3b1b/manim#1272]
Request for help
While executing the  command on win 10 it shows the following error

C:\Program Files\manim\manim_11_nov>python -m manim example_scenes.py SquareToCircle -pl
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
Traceback (most recent call last):
  File "C:\Users\CAD Lab 9\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\CAD Lab 9\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\manim\manim_11_nov\manim.py", line 2, in <module>
    import manimlib
  File "C:\Program Files\manim\manim_11_nov\manimlib\__init__.py", line 2, in <module>
    import manimlib.config
  File "C:\Program Files\manim\manim_11_nov\manimlib\config.py", line 8, in <module>
    import manimlib.constants
  File "C:\Program Files\manim\manim_11_nov\manimlib\constants.py", line 1, in <module>
    import numpy as np
  File "C:\Users\CAD Lab 9\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\__init__.py", line 305, in <module>
    _win_os_check()
  File "C:\Users\CAD Lab 9\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('C:\\Users\\CAD Lab 9\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86

**Comment by Tony031218** [comment]
Try to reinstall numpy
```sh
pip uninstall numpy
pip install numpy
```

**Comment by IRFANBINASHRAF** [comment]
reinstalling didn't solve the problem

**Comment by t-wolfeadam** [comment]
> RuntimeError: The current Numpy installation ('C:\Users\CAD Lab 9\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\**init**.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86

If you read through the suggested link, you'll find that this issue is ultimately a bug with Windows machines and that a fix is expected end of January. For now, there are two suggestions:

* Use the 32-bit version of Python, as the problem is specific to the 64-bit implementation.
* Try using NumPy version 1.19.3 (other libraries may need to be downgraded to a compatible version)

**Comment by IRFANBINASHRAF** [comment]
@t-wolfeadam Thanks, it worked, but got stuck in another one
 
C:\Program Files\manim\manim_11_nov>python -m manim example_scenes.py WriteStuff -pl
Media will be written to C:\Program Files\manim\manim_11_nov\media\. You can change this behavior with the --media_dir flag.
'latex' is not recognized as an internal or external command,
operable program or batch file.


Traceback (most recent call last):
  File "C:\Program Files\manim\manim_11_nov\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\Program Files\manim\manim_11_nov\manimlib\scene\scene.py", line 75, in __init__
    self.construct()
  File "example_scenes.py", line 100, in construct
    example_text = TextMobject(
  File "C:\Program Files\manim\manim_11_nov\manimlib\mobject\svg\tex_mobject.py", line 147, in __init__
    SingleStringTexMobject.__init__(
  File "C:\Program Files\manim\manim_11_nov\manimlib\mobject\svg\tex_mobject.py", line 42, in __init__
    file_name = tex_to_svg_file(
  File "C:\Program Files\manim\manim_11_nov\manimlib\utils\tex_file_writing.py", line 21, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
  File "C:\Program Files\manim\manim_11_nov\manimlib\utils\tex_file_writing.py", line 69, in tex_to_dvi
    raise Exception(
Exception: Latex error converting to dvi. See log output above or the log file: C:/Program Files/manim/manim_11_nov/media/Tex/c0bd21d57323a926.log



The log file reads
\documentclass[preview]{standalone}

\usepackage[english]{babel}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{dsfont}
\usepackage{setspace}
\usepackage{tipa}
\usepackage{relsize}
\usepackage{textcomp}
\usepackage{mathrsfs}
\usepackage{calligra}
\usepackage{wasysym}
\usepackage{ragged2e}
\usepackage{physics}
\usepackage{xcolor}
\usepackage{microtype}
\DisableLigatures{encoding = *, family = * }
%\usepackage[UTF8]{ctex}
\linespread{1}

\begin{document}

\centering This is some text

\end{document}

**Comment by t-wolfeadam** [comment]
> 'latex' is not recognized as an internal or external command,

Problem's right there ;) You dont have LaTeX installed

**Comment by IRFANBINASHRAF** [comment]
Miktex installation was the first step in manim, even i tried 32 bit ,furthermore i installed all missing pakages given in the error from tex_template.tex and added path in Env. variables. Still nott working 😟

**Comment by IRFANBINASHRAF** [comment]
Request for help
C:\Program Files\manim\manim_11_nov>Python -m manim example_scenes.py WriteStuff -pl

Media will be written to C:\Program Files\manim\manim_11_nov\media\. You can change this behavior with the --media_dir flag.
C:\Program Files\manim\manim_11_nov\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-84 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Program Files\manim\manim_11_nov\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-104 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Program Files\manim\manim_11_nov\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-105 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Program Files\manim\manim_11_nov\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-115 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Program Files\manim\manim_11_nov\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-111 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Program Files\manim\manim_11_nov\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-109 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Program Files\manim\manim_11_nov\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-101 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Program Files\manim\manim_11_nov\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-116 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Program Files\manim\manim_11_nov\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-120 not recognized
  warnings.warn("%s not recognized" % ref)



Traceback (most recent call last):
  File "C:\Program Files\manim\manim_11_nov\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\Program Files\manim\manim_11_nov\manimlib\scene\scene.py", line 75, in __init__
    self.construct()
  File "example_scenes.py", line 100, in construct
    example_text = TextMobject(
  File "C:\Program Files\manim\manim_11_nov\manimlib\mobject\svg\tex_mobject.py", line 150, in __init__
    self.break_up_by_substrings()
  File "C:\Program Files\manim\manim_11_nov\manimlib\mobject\svg\tex_mobject.py", line 190, in break_up_by_substrings
    sub_tex_mob.move_to(self.submobjects[last_submob_index], RIGHT)
IndexError: list index out of range

**Comment by NeoPlato** [comment]
We had a good discussion on this over at #1276 . You should take a look there.
