### ISSUE TITLE
Svg Error & Indexing Error when Editing text animations

### ISSUE THREAD

**Issue by AEX-DOS** [3b1b/manim#1278]
```C:\Users\TYVM\manim\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-84 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\TYVM\manim\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-104 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\TYVM\manim\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-105 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\TYVM\manim\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-115 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\TYVM\manim\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-97 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\TYVM\manim\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-114 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\TYVM\manim\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-101 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\TYVM\manim\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-103 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\TYVM\manim\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-117 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\TYVM\manim\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-108 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\TYVM\manim\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-116 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\TYVM\manim\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-120 not recognized
  warnings.warn("%s not recognized" % ref)



Traceback (most recent call last):
  File "C:\Users\TYVM\manim\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\Users\TYVM\manim\manimlib\scene\scene.py", line 75, in __init__
    self.construct()
  File "tutorial/1_text_format.py", line 5, in construct
    text = TextMobject("This is a regular text")
  File "C:\Users\TYVM\manim\manimlib\mobject\svg\tex_mobject.py", line 150, in __init__
    self.break_up_by_substrings()
  File "C:\Users\TYVM\manim\manimlib\mobject\svg\tex_mobject.py", line 190, in break_up_by_substrings
    sub_tex_mob.move_to(self.submobjects[last_submob_index], RIGHT)
IndexError: list index out of range```

These are the errors I got. Any help would be appreciated thx

**Comment by NeoPlato** [comment]
See #1276 . We may have found a solution
