### ISSUE TITLE
Why can't I install 'manimlib'?

### ISSUE THREAD

**Issue by Cogito24** [3b1b/manim#1280]
Window 10, manim version:(Tony031218 Merge pull request #1268 from niedong/ci-fix)

I installed Python 3.9.0 and Pycairo-1.20.0-cp39-cp39-win_amd64.whl.

This is how the current file is installed.
1. C:\ffmpeg
2. C:\sox-14-4-2
3. D:\manim
4. D:\Program Files\MiKTeX
5. C:\Users\Admini\AppData\Local\Programs\Python\Python39

When I installed requirements.txt in cmd, 'The wheel package is not available' appeared and the rest of the files were installed. It pops up like this when you try to install it again.
/////////////////////
D:\manim>python -m pip install -r requirements.txt
Requirement already satisfied: argparse in c:\users\admini\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 1)) (1.4.0)
Requirement already satisfied: colour in c:\users\admini\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 2)) (0.1.5)
Requirement already satisfied: numpy in c:\users\admini\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 3)) (1.19.4)
Requirement already satisfied: Pillow in c:\users\admini\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 4)) (8.0.1)
Requirement already satisfied: progressbar in c:\users\admini\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 5)) (2.5)
Requirement already satisfied: scipy in c:\users\admini\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 6)) (1.5.4)
Requirement already satisfied: tqdm in c:\users\admini\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 7)) (4.53.0)
Requirement already satisfied: opencv-python in c:\users\admini\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 8)) (4.4.0.46)
Requirement already satisfied: pycairo in c:\users\admini\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 9)) (1.20.0)
Requirement already satisfied: pydub in c:\users\admini\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 10)) (0.24.1)
Requirement already satisfied: pygments in c:\users\admini\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 11)) (2.7.2)
Requirement already satisfied: pyreadline in c:\users\admini\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 12)) (2.1)
////////////////////////

I also updated my 'pip' because I kept getting warnings.
////////////////////////
C:\Users\Admini>pip3 install --upgrade pip
Collecting pip
  Using cached pip-20.2.4-py2.py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.2.3
    Uninstalling pip-20.2.3:
      Successfully uninstalled pip-20.2.3
///////////////////////////

But there was an error when I tried to install 'manimlib'.
///////////////////////////
D:\manim>python -m pip install manimlib
Collecting manimlib
  Using cached manimlib-0.1.11.tar.gz (4.8 MB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Admini\AppData\Local\Programs\Python\Python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Admini\\AppData\\Local\\Temp\\pip-install-0zvo25zb\\manimlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\Admini\\AppData\\Local\\Temp\\pip-install-0zvo25zb\\manimlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Admini\AppData\Local\Temp\pip-pip-egg-info-a0b1uyus'
         cwd: C:\Users\Admini\AppData\Local\Temp\pip-install-0zvo25zb\manimlib\
    Complete output (23 lines):
    WARNING: The wheel package is not available.
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "c:\users\admini\appdata\local\temp\pip-install-0zvo25zb\manimlib\.eggs\pbr-5.5.1-py3.9.egg\pbr\core.py", line 96, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "c:\users\admini\appdata\local\temp\pip-install-0zvo25zb\manimlib\.eggs\pbr-5.5.1-py3.9.egg\pbr\util.py", line 271, in cfg_to_args
        pbr.hooks.setup_hook(config)
      File "c:\users\admini\appdata\local\temp\pip-install-0zvo25zb\manimlib\.eggs\pbr-5.5.1-py3.9.egg\pbr\hooks\__init__.py", line 25, in setup_hook
        metadata_config.run()
      File "c:\users\admini\appdata\local\temp\pip-install-0zvo25zb\manimlib\.eggs\pbr-5.5.1-py3.9.egg\pbr\hooks\base.py", line 27, in run
        self.hook()
      File "c:\users\admini\appdata\local\temp\pip-install-0zvo25zb\manimlib\.eggs\pbr-5.5.1-py3.9.egg\pbr\hooks\metadata.py", line 25, in hook
        self.config['version'] = packaging.get_version(
      File "c:\users\admini\appdata\local\temp\pip-install-0zvo25zb\manimlib\.eggs\pbr-5.5.1-py3.9.egg\pbr\packaging.py", line 862, in get_version
        version = _get_version_from_pkg_metadata(package_name)
      File "c:\users\admini\appdata\local\temp\pip-install-0zvo25zb\manimlib\.eggs\pbr-5.5.1-py3.9.egg\pbr\packaging.py", line 830, in _get_version_from_pkg_metadata
        pkg_metadata = email.message_from_file(pkg_metadata_file)
      File "C:\Users\Admini\AppData\Local\Programs\Python\Python39\lib\email\__init__.py", line 54, in message_from_file
        return Parser(*args, **kws).parse(fp)
      File "C:\Users\Admini\AppData\Local\Programs\Python\Python39\lib\email\parser.py", line 53, in parse
        data = fp.read(8192)
    UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 2512: illegal multibyte sequence
    error in setup command: Error parsing C:\Users\Admini\AppData\Local\Temp\pip-install-0zvo25zb\manimlib\setup.cfg: UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 2512: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output
////////////////////////////////////////

What should I do?

**Comment by saamkim** [comment]
Same error here
![eee](https://user-images.githubusercontent.com/59216483/101788611-a6125900-3b43-11eb-9fed-f94d134835d0.png)

**Comment by yuhan2680** [comment]
> Window 10, manim version:(Tony031218 Merge pull request #1268 from niedong/ci-fix)
> 
> I installed Python 3.9.0 and Pycairo-1.20.0-cp39-cp39-win_amd64.whl.
> 
> This is how the current file is installed.
> 
> 1. C:\ffmpeg
> 2. C:\sox-14-4-2
> 3. D:\manim
> 4. D:\Program Files\MiKTeX
> 5. C:\Users\Admini\AppData\Local\Programs\Python\Python39
> 
> When I installed requirements.txt in cmd, 'The wheel package is not available' appeared and the rest of the files were installed. It pops up like this when you try to install it again. ///////////////////// D:\manim>python -m pip install -r requirements.txt Requirement already satisfied: argparse in c:\users\admini\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 1)) (1.4.0) Requirement already satisfied: colour in c:\users\admini\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 2)) (0.1.5) Requirement already satisfied: numpy in c:\users\admini\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 3)) (1.19.4) Requirement already satisfied: Pillow in c:\users\admini\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 4)) (8.0.1) Requirement already satisfied: progressbar in c:\users\admini\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 5)) (2.5) Requirement already satisfied: scipy in c:\users\admini\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 6)) (1.5.4) Requirement already satisfied: tqdm in c:\users\admini\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 7)) (4.53.0) Requirement already satisfied: opencv-python in c:\users\admini\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 8)) (4.4.0.46) Requirement already satisfied: pycairo in c:\users\admini\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 9)) (1.20.0) Requirement already satisfied: pydub in c:\users\admini\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 10)) (0.24.1) Requirement already satisfied: pygments in c:\users\admini\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 11)) (2.7.2) Requirement already satisfied: pyreadline in c:\users\admini\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 12)) (2.1) ////////////////////////
> 
> I also updated my 'pip' because I kept getting warnings. //////////////////////// C:\Users\Admini>pip3 install --upgrade pip Collecting pip Using cached pip-20.2.4-py2.py3-none-any.whl (1.5 MB) Installing collected packages: pip Attempting uninstall: pip Found existing installation: pip 20.2.3 Uninstalling pip-20.2.3: Successfully uninstalled pip-20.2.3 ///////////////////////////
> 
> But there was an error when I tried to install 'manimlib'. /////////////////////////// D:\manim>python -m pip install manimlib Collecting manimlib Using cached manimlib-0.1.11.tar.gz (4.8 MB) ERROR: Command errored out with exit status 1: command: 'C:\Users\Admini\AppData\Local\Programs\Python\Python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\Admini\AppData\Local\Temp\pip-install-0zvo25zb\manimlib\setup.py'"'"'; **file**='"'"'C:\Users\Admini\AppData\Local\Temp\pip-install-0zvo25zb\manimlib\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Admini\AppData\Local\Temp\pip-pip-egg-info-a0b1uyus' cwd: C:\Users\Admini\AppData\Local\Temp\pip-install-0zvo25zb\manimlib Complete output (23 lines): WARNING: The wheel package is not available. ERROR:root:Error parsing Traceback (most recent call last): File "c:\users\admini\appdata\local\temp\pip-install-0zvo25zb\manimlib.eggs\pbr-5.5.1-py3.9.egg\pbr\core.py", line 96, in pbr attrs = util.cfg_to_args(path, dist.script_args) File "c:\users\admini\appdata\local\temp\pip-install-0zvo25zb\manimlib.eggs\pbr-5.5.1-py3.9.egg\pbr\util.py", line 271, in cfg_to_args pbr.hooks.setup_hook(config) File "c:\users\admini\appdata\local\temp\pip-install-0zvo25zb\manimlib.eggs\pbr-5.5.1-py3.9.egg\pbr\hooks__init__.py", line 25, in setup_hook metadata_config.run() File "c:\users\admini\appdata\local\temp\pip-install-0zvo25zb\manimlib.eggs\pbr-5.5.1-py3.9.egg\pbr\hooks\base.py", line 27, in run self.hook() File "c:\users\admini\appdata\local\temp\pip-install-0zvo25zb\manimlib.eggs\pbr-5.5.1-py3.9.egg\pbr\hooks\metadata.py", line 25, in hook self.config['version'] = packaging.get_version( File "c:\users\admini\appdata\local\temp\pip-install-0zvo25zb\manimlib.eggs\pbr-5.5.1-py3.9.egg\pbr\packaging.py", line 862, in get_version version = _get_version_from_pkg_metadata(package_name) File "c:\users\admini\appdata\local\temp\pip-install-0zvo25zb\manimlib.eggs\pbr-5.5.1-py3.9.egg\pbr\packaging.py", line 830, in _get_version_from_pkg_metadata pkg_metadata = email.message_from_file(pkg_metadata_file) File "C:\Users\Admini\AppData\Local\Programs\Python\Python39\lib\email__init__.py", line 54, in message_from_file return Parser(*args, **kws).parse(fp) File "C:\Users\Admini\AppData\Local\Programs\Python\Python39\lib\email\parser.py", line 53, in parse data = fp.read(8192) UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 2512: illegal multibyte sequence error in setup command: Error parsing C:\Users\Admini\AppData\Local\Temp\pip-install-0zvo25zb\manimlib\setup.cfg: UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 2512: illegal multibyte sequence ---------------------------------------- ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output ////////////////////////////////////////
> 
> What should I do?

Please check your manim edition is between 3.7 and 3.9 .And you has installed LaTex and FFmpeg.

And here is some website for you:
https://docs.manim.community/en/stable/installation.html
https://docs.manim.org.cn/getting_started/installation.html
http://3b1b.github.io/manim/getting_started/installation.html
