### ISSUE TITLE
Multiple problems in example_scene.py --> OpeningManimExample, WriteStuff  not working. I am receiving IndexError: 'List out of Range Error'. Any quick Fix?

### ISSUE THREAD

**Issue by P0intMaN** [3b1b/manim#1286]
**Encountered this error while playing the example_scene. The mentioned examples (i.e. OpeningManimExample and WriteStuff)
is throwing *__IndexError__* The following is the errored output:**

But before that, I am using a windows system and downloaded  manim 2days ago.

The error message:

``` 
C:\manim\manim-master\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g1-88 not recognized
  warnings.warn("%s not recognized" % ref)

Traceback (most recent call last):
  File "C:\manim\manim-master\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\manim\manim-master\manimlib\scene\scene.py", line 75, in __init__
    self.construct()
  File "example_scenes.py", line 20, in construct
    title = TextMobject("This is some \\LaTeX")
  File "C:\manim\manim-master\manimlib\mobject\svg\tex_mobject.py", line 150, in __init__
    self.break_up_by_substrings()
  File "C:\manim\manim-master\manimlib\mobject\svg\tex_mobject.py", line 190, in break_up_by_substrings
    sub_tex_mob.move_to(self.submobjects[last_submob_index], RIGHT)
IndexError: list index out of range 

```

###Hoping to get a fix soon 👍

**Comment by NeoPlato** [comment]
#1276

**Comment by NeoPlato** [comment]
Did it work mate?
For research purposes

**Comment by P0intMaN** [comment]
No buddy.. I think there is some problem with TextMobject. Because whenever I use it to write anything, say, heading or title of a video, the same error pops up.

**Comment by NeoPlato** [comment]
Can you tell what svg file gets produced
If so post its contents here

**Comment by P0intMaN** [comment]
Here is the error.. Cant figure out which svg file is being produced

C:\manim\manim-master\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-120 not recognized
  warnings.warn("%s not recognized" % ref)

Traceback (most recent call last):
  File "C:\manim\manim-master\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\manim\manim-master\manimlib\scene\scene.py", line 75, in __init__
    self.construct()
  File "Logo_YT\logo.py", line 41, in construct
    Headings=TextMobject("This is some text")
  File "C:\manim\manim-master\manimlib\mobject\svg\tex_mobject.py", line 150, in __init__
    self.break_up_by_substrings()
  File "C:\manim\manim-master\manimlib\mobject\svg\tex_mobject.py", line 190, in break_up_by_substrings
    sub_tex_mob.move_to(self.submobjects[last_submob_index], RIGHT)
IndexError: list index out of range

**Comment by P0intMaN** [comment]
Hey, and thanks for helping me out bud 👍

**Comment by NeoPlato** [comment]
Try and print `title.file_name`. That should be the name of the svg file

**Comment by P0intMaN** [comment]
Should i directly write 'print(title.file_name)' in CMD? I am sorry i didnt you. Could you please elaborate?

Also, 
After reading the threads regarding this issue, I am now downloading the rest of 3000 packages from MikTex that were previously not installed. Hoping that this would rectify the issue.

**Comment by NeoPlato** [comment]
> Should i directly write 'print(title.file_name)' in CMD? I am sorry i didnt you. Could you please elaborate?

```python
class OpeningManimExample(Scene):
    def construct(self):
        title = TextMobject("This is some \\LaTeX")
        print(title.file_name)           #<- Here
        basel = TexMobject(
            "\\sum_{n=1}^\\infty "
            "\\frac{1}{n^2} = \\frac{\\pi^2}{6}"
        )
        VGroup(title, basel).arrange(DOWN)
        self.play(
            Write(title),
            FadeInFrom(basel, UP),
        )
        self.wait()

        transform_title = TextMobject("That was a transform")
        transform_title.to_corner(UP + LEFT)
        self.play(
            Transform(title, transform_title),
            LaggedStart(*map(FadeOutAndShiftDown, basel)),
        )
        self.wait()

        grid = NumberPlane()
        grid_title = TextMobject("This is a grid")
        grid_title.scale(1.5)
        grid_title.move_to(transform_title)

        self.add(grid, grid_title)  # Make sure title is on top of grid
        self.play(
            FadeOut(title),
            FadeInFromDown(grid_title),
            ShowCreation(grid, run_time=3, lag_ratio=0.1),
        )
        self.wait()

        grid_transform_title = TextMobject(
            "That was a non-linear function \\\\"
            "applied to the grid"
        )
        grid_transform_title.move_to(grid_title, UL)
        grid.prepare_for_nonlinear_transform()
        self.play(
            grid.apply_function,
            lambda p: p + np.array([
                np.sin(p[1]),
                np.sin(p[0]),
                0,
            ]),
            run_time=3,
        )
        self.wait()
        self.play(
            Transform(grid_title, grid_transform_title)
        )
        self.wait()
```

**Comment by P0intMaN** [comment]
> > Should i directly write 'print(title.file_name)' in CMD? I am sorry i didnt you. Could you please elaborate?
> 
> ```python
> class OpeningManimExample(Scene):
>     def construct(self):
>         title = TextMobject("This is some \\LaTeX")
>         print(title.file_name)           #<- Here
>         basel = TexMobject(
>             "\\sum_{n=1}^\\infty "
>             "\\frac{1}{n^2} = \\frac{\\pi^2}{6}"
>         )
>         VGroup(title, basel).arrange(DOWN)
>         self.play(
>             Write(title),
>             FadeInFrom(basel, UP),
>         )
>         self.wait()
> 
>         transform_title = TextMobject("That was a transform")
>         transform_title.to_corner(UP + LEFT)
>         self.play(
>             Transform(title, transform_title),
>             LaggedStart(*map(FadeOutAndShiftDown, basel)),
>         )
>         self.wait()
> 
>         grid = NumberPlane()
>         grid_title = TextMobject("This is a grid")
>         grid_title.scale(1.5)
>         grid_title.move_to(transform_title)
> 
>         self.add(grid, grid_title)  # Make sure title is on top of grid
>         self.play(
>             FadeOut(title),
>             FadeInFromDown(grid_title),
>             ShowCreation(grid, run_time=3, lag_ratio=0.1),
>         )
>         self.wait()
> 
>         grid_transform_title = TextMobject(
>             "That was a non-linear function \\\\"
>             "applied to the grid"
>         )
>         grid_transform_title.move_to(grid_title, UL)
>         grid.prepare_for_nonlinear_transform()
>         self.play(
>             grid.apply_function,
>             lambda p: p + np.array([
>                 np.sin(p[1]),
>                 np.sin(p[0]),
>                 0,
>             ]),
>             run_time=3,
>         )
>         self.wait()
>         self.play(
>             Transform(grid_title, grid_transform_title)
>         )
>         self.wait()
> ```

I wrote print(title.file_name) as you have suggested, but didnt print any svg file name

**Comment by P0intMaN** [comment]
Here is the output:
```
C:\manim\manim-master>python -m manim example_scenes.py
Media will be written to C:\manim\manim-master\media\. You can change this behavior with the --media_dir flag.
1: OpeningManimExample
2: SquareToCircle
3: UpdatersExample
4: WarpSquare
5: WriteStuff

Choose number corresponding to desired scene/arguments.
(Use comma separated list for multiple entries)
Choice(s): 1
C:\manim\manim-master\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g1-84 not recognized
  warnings.warn("%s not recognized" % ref)

Traceback (most recent call last):
  File "C:\manim\manim-master\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\manim\manim-master\manimlib\scene\scene.py", line 75, in __init__
    self.construct()
  File "example_scenes.py", line 20, in construct
    title = TextMobject("This is some \\LaTeX")
  File "C:\manim\manim-master\manimlib\mobject\svg\tex_mobject.py", line 150, in __init__
    self.break_up_by_substrings()
  File "C:\manim\manim-master\manimlib\mobject\svg\tex_mobject.py", line 190, in break_up_by_substrings
    sub_tex_mob.move_to(self.submobjects[last_submob_index], RIGHT)
IndexError: list index out of range
```

**Comment by NeoPlato** [comment]
Oh right, the thing isn't allowed to exist yet. My bad.

Just look for this piece of code and print it here:

```python
class TexMobject(SingleStringTexMobject):
    CONFIG = {
        "arg_separator": " ",
        "substrings_to_isolate": [],
        "tex_to_color_map": {},
    }

    def __init__(self, *tex_strings, **kwargs):
        digest_config(self, kwargs)
        print(self.file_name)
```

**Comment by P0intMaN** [comment]
This 

> Oh right, the thing isn't allowed to exist yet. My bad.
> 
> Just look for this piece of code and print it here:

> ```python
> class TexMobject(SingleStringTexMobject):
>     CONFIG = {
>         "arg_separator": " ",
>         "substrings_to_isolate": [],
>         "tex_to_color_map": {},
>     }
> 
>     def __init__(self, *tex_strings, **kwargs):
>         digest_config(self, kwargs)
>         print(self.file_name)
> ```

Its not there in my code.. What!? How could this possibly be? I mean, from where did you find this code? Is it there In your  example_scenes.py file?

**Comment by NeoPlato** [comment]
It's in `manimlib\mobject\svg\tex_mobject.py`

Here we edit library code for breakfast

**Comment by P0intMaN** [comment]
ok 😂👍 I found that code. Now what?

**Comment by P0intMaN** [comment]
Here is the entire code: (for reference)

```
class TexMobject(SingleStringTexMobject):
    CONFIG = {
        "arg_separator": " ",
        "substrings_to_isolate": [],
        "tex_to_color_map": {},
    }

    def __init__(self, *tex_strings, **kwargs):
        digest_config(self, kwargs)
        tex_strings = self.break_up_tex_strings(tex_strings)
        self.tex_strings = tex_strings
        SingleStringTexMobject.__init__(
            self, self.arg_separator.join(tex_strings), **kwargs
        )
        self.break_up_by_substrings()
        self.set_color_by_tex_to_color_map(self.tex_to_color_map)

        if self.organize_left_to_right:
            self.organize_submobjects_left_to_right()

    def break_up_tex_strings(self, tex_strings):
        substrings_to_isolate = op.add(
            self.substrings_to_isolate,
            list(self.tex_to_color_map.keys())
        )
        split_list = split_string_list_to_isolate_substrings(
            tex_strings, *substrings_to_isolate
        )
        if self.arg_separator == ' ':
            split_list = [str(x).strip() for x in split_list]
        #split_list = list(map(str.strip, split_list))
        split_list = [s for s in split_list if s != '']
        return split_list

    def break_up_by_substrings(self):
        """
        Reorganize existing submojects one layer
        deeper based on the structure of tex_strings (as a list
        of tex_strings)
        """
        new_submobjects = []
        curr_index = 0
        config = dict(self.CONFIG)
        config["alignment"] = ""
        for tex_string in self.tex_strings:
            sub_tex_mob = SingleStringTexMobject(tex_string, **config)
            num_submobs = len(sub_tex_mob.submobjects)
            new_index = curr_index + num_submobs
            if num_submobs == 0:
                # For cases like empty tex_strings, we want the corresponing
                # part of the whole TexMobject to be a VectorizedPoint
                # positioned in the right part of the TexMobject
                sub_tex_mob.submobjects = [VectorizedPoint()]
                last_submob_index = min(curr_index, len(self.submobjects) - 1)
                sub_tex_mob.move_to(self.submobjects[last_submob_index], RIGHT)
            else:
                sub_tex_mob.submobjects = self.submobjects[curr_index:new_index]
            new_submobjects.append(sub_tex_mob)
            curr_index = new_index
        self.submobjects = new_submobjects
        return self

    def get_parts_by_tex(self, tex, substring=True, case_sensitive=True):
        def test(tex1, tex2):
            if not case_sensitive:
                tex1 = tex1.lower()
                tex2 = tex2.lower()
            if substring:
                return tex1 in tex2
            else:
                return tex1 == tex2

        return VGroup(*[m for m in self.submobjects if test(tex, m.get_tex_string())])

    def get_part_by_tex(self, tex, **kwargs):
        all_parts = self.get_parts_by_tex(tex, **kwargs)
        return all_parts[0] if all_parts else None

    def set_color_by_tex(self, tex, color, **kwargs):
        parts_to_color = self.get_parts_by_tex(tex, **kwargs)
        for part in parts_to_color:
            part.set_color(color)
        return self

    def set_color_by_tex_to_color_map(self, texs_to_color_map, **kwargs):
        for texs, color in list(texs_to_color_map.items()):
            try:
                # If the given key behaves like tex_strings
                texs + ''
                self.set_color_by_tex(texs, color, **kwargs)
            except TypeError:
                # If the given key is a tuple
                for tex in texs:
                    self.set_color_by_tex(tex, color, **kwargs)
        return self

    def index_of_part(self, part):
        split_self = self.split()
        if part not in split_self:
            raise Exception("Trying to get index of part not in TexMobject")
        return split_self.index(part)

    def index_of_part_by_tex(self, tex, **kwargs):
        part = self.get_part_by_tex(tex, **kwargs)
        return self.index_of_part(part)

    def sort_alphabetically(self):
        self.submobjects.sort(
            key=lambda m: m.get_tex_string()
        )
```

**Comment by NeoPlato** [comment]
After `digest_config`

On the next line, add the print statement

`print(self.file_name)`

**Comment by P0intMaN** [comment]
done.

**Comment by NeoPlato** [comment]
Yeah. Now what's the name of the svg file?

Once you have that search for it in `media\Tex` and send its contents here

**Comment by P0intMaN** [comment]
Got this instead..
```
FileNotFoundError: [Errno 2] No such file or directory: 'mobject\\svg\\tex_mobject.py'

```

In fact, i do have these files

The command i typed was:
```
C:\manim\manim-master>python -m manim mobject\svg\tex_mobject.py TexMobject -pl
```
I am sorry if i am troubling you with my silly mistakes (if any) 😅

**Comment by P0intMaN** [comment]
Upon typing ths:
```
python -m manim manimlib\mobject\svg\tex_mobject.py TexMobject -p
```
I got this:
```
Media will be written to C:\manim\manim-master\media\. You can change this behavior with the --media_dir flag.

   There are no scenes inside that module
```

**Comment by P0intMaN** [comment]
I am sorry if I am troubling you with my silly mistakes 😅

**Comment by NeoPlato** [comment]
> Upon typing this:
> 
> ```
> python -m manim manimlib\mobject\svg\tex_mobject.py TexMobject -p
> ```
> 
> I got this:
> 
> ```
> Media will be written to C:\manim\manim-master\media\. You can change this behavior with the --media_dir flag.
> 
>    There are no scenes inside that module
> ```

Hold all the way up!
How new are you to programming

**Comment by P0intMaN** [comment]
I am relatively new to python but am good with c++.

**Comment by P0intMaN** [comment]
> You know what, forget it.
> Remove the print statement, clear the folder and try running the original scene again


Ok Trying..

**Comment by NeoPlato** [comment]
> I am relatively new to python but am good with c++.

You have quite a bit to learn. Just know, Mobjects and Scenes are different objects, and one can't do the work of the other
What you did is treat TextMobject like a Scene object, which doesn't have the member functions used by Manim itself

**Comment by P0intMaN** [comment]
> > I am relatively new to python but am good with c++.
> 
> You have quite a bit to learn. Just know, Mobjects and Scenes are different objects, and one can't do the work of the other
> What you did is treat TextMobject like a Scene object, which doesn't have the member functions used by Manim itself

OK, thanks.. Now i understood. 

I removed the print statement from TexMobject

**Comment by P0intMaN** [comment]
Now, what shall i run?

**Comment by P0intMaN** [comment]
These Scenes and other concepts of manim are bit confusing for beginners and noobs like me..😢

**Comment by NeoPlato** [comment]
> These Scenes and other concepts of manim are bit confusing for beginners and noobs like me..😢

No no relax mate
Manim is a subset of Python. All you need to do is master the latter. I was at your place once but with zero experience so I get the feeling.

If you understand how at least classes work you'll have this library in the bag

**Comment by P0intMaN** [comment]
yeah, i have learnt classes objects and things like that when i was learning OOPS in c++.

**Comment by NeoPlato** [comment]
> yeah, i have learnt classes objects and things like that when i was learning OOPS in c++.

Did you cover polymorphism? Python lives on that principle.

**Comment by NeoPlato** [comment]
> Now, what shall i run?

The same one from before. But with a cleared Tex folder so you can identify the svg file

**Comment by P0intMaN** [comment]
Ya polymorphism is when an attribute or function of a particular member of a class can be accessed by many other members of other classes right? I learnt it when i was dealin with Inheritances.

**Comment by P0intMaN** [comment]
Yeah, i have studied about polymorphism when i was dealin with inheritance. Polymorphism is when function of class can be accessed by many other classes and can be used in any form the class intend it to. Right?

**Comment by NeoPlato** [comment]
See? You're halfway there

**Comment by P0intMaN** [comment]
OK.. so, i just commented out the texmobject class and am now running example_scenes.py alright?

**Comment by P0intMaN** [comment]
ooooh... so you meant 

> > Now, what shall i run?
> 
> The same one from before. But with a cleared Tex folder so you can identify the svg file

OOOhhhh... so, you meant that i should create an empty .tex folder and should try to run the TexMobject there right?

**Comment by P0intMaN** [comment]
> OK.. so, i just commented out the texmobject class and am now running example_scenes.py alright?

I am an idiot!

**Comment by P0intMaN** [comment]
but this wont work i guess. 
How can one run TexMobject class in .tex?

I am an ultra idiot! damn!

**Comment by NeoPlato** [comment]
> but this wont work i guess.
> How can one run TexMobject class in .tex?
> 
> I am an ultra idiot! damn!

Relax bruv
Just do what you did in the beginning

**Comment by P0intMaN** [comment]
> Just do what you did in the beginning

I ran the example_scenes.py in the beginning. 

Going to run it again... But what difference will it make now?

**Comment by NeoPlato** [comment]
We need that svg file my friend.
So you may see what the program isn't doing

**Comment by P0intMaN** [comment]
```
C:\manim\manim-master\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g1-88 not recognized
  warnings.warn("%s not recognized" % ref)
```
same errors.  What's this UserWarning:g1-g8

**Comment by P0intMaN** [comment]
There is some problem in svg_mobject.py

**Comment by NeoPlato** [comment]
That's what I want to explain!

Do you have the svg file?

**Comment by P0intMaN** [comment]
Got it buddy!!!
i added print(self.file_name) and i got this:
```
C:/manim/manim-master/media/Tex/664e80e8d8d98482.svg
```

**Comment by NeoPlato** [comment]
Open it with Notepad and paste its contents here

**Comment by P0intMaN** [comment]
Here you go:
```
<?xml version='1.0' encoding='UTF-8'?>
<!-- This file was generated by dvisvgm 2.8.2 -->
<svg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='83.275349pt' height='9.005688pt' viewBox='130.227832 -6.861476 83.275349 9.005688'>
<defs/>
<g id='page1'>
<use x='130.227832' y='0' xlink:href='#g1-84'/>
<use x='137.421316' y='0' xlink:href='#g1-104'/>
<use x='142.954764' y='0' xlink:href='#g1-105'/>
<use x='145.721489' y='0' xlink:href='#g1-115'/>
<use x='152.970307' y='0' xlink:href='#g1-105'/>
<use x='155.737031' y='0' xlink:href='#g1-115'/>
<use x='162.985849' y='0' xlink:href='#g1-115'/>
<use x='166.914598' y='0' xlink:href='#g1-111'/>
<use x='171.894702' y='0' xlink:href='#g1-109'/>
<use x='180.194875' y='0' xlink:href='#g1-101'/>
<use x='187.941703' y='0' xlink:href='#g1-76'/>
<use x='190.581158' y='-2.058443' xlink:href='#g0-65'/>
<use x='194.966477' y='0' xlink:href='#g1-84'/>
<use x='200.499576' y='2.144211' xlink:href='#g1-69'/>
<use x='206.033025' y='0' xlink:href='#g1-88'/>
</g>
</svg>
```

**Comment by NeoPlato** [comment]
Let me show you what mine looks like

```
<?xml version='1.0' encoding='UTF-8'?>
<!-- This file was generated by dvisvgm 2.8.2 -->
<svg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='53.148776pt' height='6.861476pt' viewBox='145.281154 -6.861476 53.148776 6.861476'>
<defs>
<path id='g0-72' d='M.328767-6.814446V-6.505604C.458281-6.505604 .587796-6.515567 .707347-6.515567C1.066002-6.515567 1.354919-6.465753 1.354919-6.067248V-.747198C1.354919-.368618 1.026152-.308842 .687422-.308842C.557908-.308842 .438356-.318804 .328767-.318804V-.009963H3.267746V-.318804H2.929016C2.510585-.318804 2.241594-.33873 2.241594-.757161V-3.39726H5.220423V-.757161C5.220423-.358655 4.881694-.318804 4.523039-.318804H4.194271V-.009963H7.13325V-.318804C7.013699-.318804 6.884184-.308842 6.764633-.308842C6.41594-.308842 6.107098-.358655 6.107098-.747198V-6.067248C6.107098-6.455791 6.425903-6.515567 6.764633-6.515567C6.894147-6.515567 7.023661-6.505604 7.13325-6.505604V-6.814446H4.194271V-6.505604H4.533001C4.951432-6.505604 5.220423-6.485679 5.220423-6.067248V-3.706102H2.241594V-6.067248C2.241594-6.465753 2.580324-6.505604 2.938979-6.505604H3.267746V-6.814446H.328767Z'/>
<path id='g0-87' d='M.179328-6.814446V-6.505604H.388543C1.016189-6.505604 1.05604-6.216687 1.165629-5.838107C1.793275-3.955168 2.391034-2.072229 3.008717-.179328C3.058531-.039851 3.088418 .209215 3.277709 .209215H3.297634C3.476961 .179328 3.506849-.139477 3.5467-.219178C4.044832-1.743462 4.523039-3.277709 5.031133-4.79203C5.061021-4.881694 5.090909-4.961395 5.110834-5.051059H5.120797C5.17061-4.811955 5.280199-4.582814 5.339975-4.353674C5.788294-2.978829 6.22665-1.594022 6.684932-.219178L6.774595 .049813C6.804483 .119552 6.844334 .18929 6.924035 .209215H6.953923C7.13325 .209215 7.163138-.029888 7.212951-.169365C7.840598-2.012453 8.408468-3.875467 9.026152-5.718555C9.145704-6.127024 9.354919-6.505604 10.052304-6.505604V-6.814446H7.960149V-6.505604C8.308842-6.505604 8.797011-6.37609 8.826899-5.987547C8.826899-5.927771 8.806974-5.858032 8.787049-5.798257L8.697385-5.549191C8.52802-4.98132 8.33873-4.423412 8.14944-3.855542L7.551681-2.012453C7.462017-1.733499 7.362391-1.464508 7.28269-1.185554C7.143213-1.524284 7.043587-1.902864 6.933998-2.251557C6.535492-3.447073 6.166874-4.652553 5.758406-5.84807C5.728518-5.957659 5.65878-6.087173 5.65878-6.206725C5.65878-6.505604 6.216687-6.505604 6.495641-6.505604V-6.814446H3.865504V-6.505604H4.134496C4.582814-6.505604 4.672478-6.405978 4.901619-5.718555C4.921544-5.648817 4.971357-5.549191 4.971357-5.459527V-5.439601C4.971357-5.310087 4.871731-5.120797 4.83188-4.98132C4.503113-4.064757 4.214197-3.128269 3.915318-2.181818C3.815691-1.853051 3.686177-1.524284 3.596513-1.185554H3.58655C3.566625-1.305106 3.516812-1.414695 3.476961-1.534247L2.400996-4.851806C2.251557-5.270237 2.141968-5.678705 1.992528-6.087173C1.982565-6.127024 1.972603-6.176837 1.972603-6.216687V-6.246575C2.042341-6.505604 2.520548-6.505604 2.809465-6.505604V-6.814446H.179328Z'/>
<path id='g0-100' d='M3.028643-6.814446V-6.505604H3.188045C3.536737-6.505604 3.805729-6.465753 3.805729-5.88792L3.795766-3.795766C3.556663-4.194271 2.988792-4.403487 2.530511-4.403487C1.305106-4.403487 .328767-3.347447 .328767-2.141968C.328767-1.075965 1.145704 .099626 2.460772 .099626C2.978829 .099626 3.447073-.14944 3.775841-.547945V.099626L5.250311-.009963V-.318804H5.080946C4.772105-.318804 4.473225-.348692 4.473225-.816936V-6.924035L3.028643-6.814446ZM1.165629-1.902864V-2.052304C1.165629-2.789539 1.255293-3.536737 1.942715-3.995019C2.141968-4.11457 2.371108-4.184309 2.600249-4.184309C3.088418-4.184309 3.785803-3.785803 3.785803-3.158157C3.785803-3.028643 3.775841-2.899128 3.775841-2.769614V-1.115816C3.775841-.986301 3.726027-.896638 3.656289-.797011C3.39726-.408468 2.968867-.119552 2.500623-.119552C1.77335-.119552 1.315068-.787049 1.205479-1.474471C1.185554-1.613948 1.185554-1.763387 1.165629-1.902864Z'/>
<path id='g0-101' d='M1.115816-2.311333H3.985056C4.094645-2.311333 4.144458-2.381071 4.144458-2.49066C4.144458-3.5467 3.496887-4.463263 2.381071-4.463263C1.155666-4.463263 .278954-3.377335 .278954-2.191781C.278954-1.275218 .787049-.458281 1.663761-.059776C1.892902 .039851 2.161893 .099626 2.410959 .099626H2.440847C3.20797 .099626 3.845579-.328767 4.11457-1.09589C4.124533-1.125778 4.124533-1.165629 4.124533-1.195517C4.124533-1.265255 4.084682-1.315068 4.014944-1.315068C3.865504-1.315068 3.805729-.986301 3.745953-.876712C3.496887-.438356 3.01868-.14944 2.500623-.14944C2.132005-.14944 1.8132-.358655 1.544209-.627646C1.145704-1.085928 1.115816-1.733499 1.115816-2.311333ZM1.125778-2.520548C1.125778-3.287671 1.534247-4.244085 2.351183-4.244085H2.400996C3.377335-4.154421 3.367372-3.118306 3.466999-2.520548H1.125778Z'/>
<path id='g0-108' d='M.328767-6.814446V-6.505604H.478207C.846824-6.505604 1.105853-6.465753 1.105853-5.987547V-.956413C1.105853-.886675 1.115816-.816936 1.115816-.737235C1.115816-.358655 .846824-.318804 .56787-.318804H.328767V-.009963H2.550436V-.318804H2.30137C2.012453-.318804 1.77335-.358655 1.77335-.747198V-6.924035L.328767-6.814446Z'/>
<path id='g0-111' d='M2.34122-4.463263C1.085928-4.333748 .278954-3.277709 .278954-2.122042C.278954-.996264 1.165629 .099626 2.49066 .099626C3.686177 .099626 4.692403-.876712 4.692403-2.132005C4.692403-3.317559 3.795766-4.473225 2.470735-4.473225C2.430884-4.473225 2.381071-4.463263 2.34122-4.463263ZM1.115816-1.892902V-2.331258C1.115816-3.088418 1.354919-4.244085 2.480697-4.244085C3.287671-4.244085 3.745953-3.566625 3.835616-2.809465C3.855542-2.590286 3.855542-2.381071 3.855542-2.161893C3.855542-1.514321 3.785803-.707347 3.148194-.33873C2.948941-.209215 2.729763-.14944 2.500623-.14944C1.77335-.14944 1.265255-.71731 1.155666-1.494396C1.135741-1.62391 1.135741-1.763387 1.115816-1.892902Z'/>
<path id='g0-114' d='M.268991-4.293898V-3.985056H.418431C.747198-3.985056 1.046077-3.955168 1.046077-3.486924V-.737235C1.046077-.328767 .767123-.318804 .328767-.318804H.268991V-.009963H2.67995V-.318804C2.560399-.318804 2.420922-.308842 2.30137-.308842C1.982565-.308842 1.713574-.358655 1.713574-.727273V-2.052304C1.713574-2.899128 1.912827-4.184309 2.889166-4.184309C2.929016-4.184309 2.958904-4.184309 2.998755-4.174346V-4.164384C2.849315-4.104608 2.769614-3.945205 2.769614-3.785803C2.769614-3.556663 2.919054-3.39726 3.148194-3.35741C3.437111-3.35741 3.626401-3.536737 3.626401-3.785803C3.626401-4.184309 3.247821-4.403487 2.889166-4.403487C2.30137-4.403487 1.77335-3.875467 1.673724-3.337484L1.663761-4.403487L.268991-4.293898Z'/>
</defs>
<g id='page1'>
<use x='145.281154' y='0' xlink:href='#g0-72'/>
<use x='152.75131' y='0' xlink:href='#g0-101'/>
<use x='157.178069' y='0' xlink:href='#g0-108'/>
<use x='159.944793' y='0' xlink:href='#g0-108'/>
<use x='162.711518' y='0' xlink:href='#g0-111'/>
<use x='171.011691' y='0' xlink:href='#g0-87'/>
<use x='181.248571' y='0' xlink:href='#g0-111'/>
<use x='186.228675' y='0' xlink:href='#g0-114'/>
<use x='190.129756' y='0' xlink:href='#g0-108'/>
<use x='192.896481' y='0' xlink:href='#g0-100'/>
</g>
</svg>
```

Focus on the angle bracketed labels like `use` and `g`. What does mine have that yours doesn't

**Comment by P0intMaN** [comment]
You have
```
 <defs> some path ids </defs> 
```
but mine does'nt

**Comment by NeoPlato** [comment]
Exactly! Those are the paths that are used to generate the points. At the bottom they are referred to but not defined, hence the timeless error of undefined variable.

I really don't want to do this for the seventh time so just hop over to #1276 and follow the latest instructions there

**Comment by P0intMaN** [comment]
You have different set of use and g values right?

**Comment by NeoPlato** [comment]
> You have different set of use and g values right?

It's not the values I'm talking about but the elements.

**Comment by P0intMaN** [comment]
> Exactly! Those are the paths that are used to generate the points. At the bottom they are referred to but not defined, hence the timeless error of undefined variable.
> 
> I really don't want to do this for the seventh time so just hop over to #1276 and follow the latest instructions there

Aye Aye sire!

**Comment by P0intMaN** [comment]
Hello, i am sorry to disturb again, i followed your steps to create a tex_test.tex thing and it dumped me a file which is having defs and paths in it. Also, it produced 'THIS IS TEXT' on a black screen.

**Comment by P0intMaN** [comment]
Now, shall i copy this code and paste it in place of my original svg file which was causing problem?

**Comment by P0intMaN** [comment]
Wait never mind.. I think i got it.. Thanks!
