### ISSUE TITLE
import ka_playground.circuits import Resistor, Source, LongResistor

### ISSUE THREAD

**Issue by xsmaster01** [3b1b/manim#1290]
I want run the old file eola file chapter6 and there is the import ka_playground.circuits import Resistor, Source, LongResistor. I can't find the file in my manim-master(folder). can you help me plss p.s sorry my English very bad. and here is the Traceback

Traceback (most recent call last):
  File "C:\Python\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python\manim\manim-master\manim.py", line 5, in <module>
    manimlib.main()
  File "C:\Python\manim\manim-master\manimlib\__init__.py", line 9, in main
    config = manimlib.config.get_configuration(args)
  File "C:\Python\manim\manim-master\manimlib\config.py", line 155, in get_configuration
    module = get_module(args.file)
  File "C:\Python\manim\manim-master\manimlib\config.py", line 150, in get_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "chapter6.py", line 2, in <module>
    from ka_playgrounds.circuits import Resistor, Source, LongResistor
ModuleNotFoundError: No module named 'ka_playgrounds'

**Comment by seanjensengrey** [comment]
I glanced through the git commit history with

```
git log -S ka_playground
```

the first occurrence of `ka_playgrounds` is in the `.gitignore` file here

https://github.com/3b1b/manim/commit/fd86816b66636787b22396305f9869f462ef2481

I don't think it ever got checked in, my recommendation would be to code a work-a-like from how it was used.

**Comment by seanjensengrey** [comment]
It was confirmed in this comment for the next commit that mentions `ka_playgrounds` here 

https://github.com/3b1b/manim/commit/e5747b3f3bef8b5be833d59516c4f3965143cea9#commitcomment-18732856

@crclayton Did you end up re-creating the circuits functionality? 

@xsmaster01 it looks like Resistor, LongResistor is a subclass of line, see https://github.com/3b1b/manim/blob/master/manimlib/mobject/geometry.py#L423

**Comment by crclayton** [comment]
@seanjensengrey Oh man this goes way back. I ended up abandoning that project but I downloaded some SVGs from the internet for different components and importing them to use and animate that way instead of creating them from scratch.

**Comment by xsmaster01** [comment]
thanks man for help me @seanjensengrey  @crcclayton.dll
