### ISSUE TITLE
Cannot Load ManimPango dynlibs on Mojave

### ISSUE THREAD

**Issue by melMass** [3b1b/manim#1307]
Hi, 

### The Issue: 

```log
Symbol not found: _objc_opt_class libgio-2.0.0.dylib (which was built for Mac OS X 10.15)
````

I'm having an issue using macOS Mojave, here are the reproducible steps:

1. Installed all brew dependencies (by the way the command is now `brew install --cask` it still use the old behavior in [manim's docs](https://docs.manim.community/en/latest/installation/mac.html))
2. Installed using pip in a poetry environment
3. Try to run the sample from the readme:

### Relevant config information
- macOS 10.14.6
- Python 3.7.4

```
poetry run manim sample.py
```

### The stacktrace
<details><summary>Click to expand</summary>
<p>

#### Output

```ruby
Traceback (most recent call last):
  File "$root/.venv/lib/python3.7/site-packages/manimpango/__init__.py", line 11, in <module>
    from .cmanimpango import *  # noqa: F403,F401
ImportError: dlopen($root/.venv/lib/python3.7/site-packages/manimpango/cmanimpango.cpython-37m-darwin.so, 2): Symbol not found: _objc_opt_class
  Referenced from: $root/.venv/lib/python3.7/site-packages/manimpango/.dylibs/libgio-2.0.0.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib
 in $root/.venv/lib/python3.7/site-packages/manimpango/.dylibs/libgio-2.0.0.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/imac/.pyenv/versions/3.7.4/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/imac/.pyenv/versions/3.7.4/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/imac/.pyenv/versions/3.7.4/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "$root/.venv/lib/python3.7/site-packages/manim/__init__.py", line 47, in <module>
    from .mobject.svg.text_mobject import *
  File "$root/.venv/lib/python3.7/site-packages/manim/mobject/svg/text_mobject.py", line 56, in <module>
    import manimpango
  File "$root/.venv/lib/python3.7/site-packages/manimpango/__init__.py", line 13, in <module>
    raise ImportError("Couldn't load the necessary Shared Libraries.")
ImportError: Couldn't load the necessary Shared Libraries.

```

</p>
</details>

Thanks

**Comment by cshewmake2** [comment]
Same issue here.

**Comment by Tony031218** [comment]
If this is an issue on community version, please open an issue in [ManimCommunity/manim](https://github.com/ManimCommunity/manim) instead of here. So close this.
