### ISSUE TITLE
Errors happening after trying out example commands

### ISSUE THREAD

**Issue by BearJere** [3b1b/manim#1322]
OS: Mac OS X 11.0 (on Apple Silicon)

Whenever I try to run `python3 ./manim.py example_scenes.py SquareToCircle -pl` or other manim commands, I get
`Traceback (most recent call last):
  File "/Users/bearjere/Desktop/manim/./manim.py", line 2, in <module>
    import manimlib
  File "/Users/bearjere/Desktop/manim/manimlib/__init__.py", line 4, in <module>
    import manimlib.extract_scene
  File "/Users/bearjere/Desktop/manim/manimlib/extract_scene.py", line 9, in <module>
    from manimlib.scene.scene import Scene
  File "/Users/bearjere/Desktop/manim/manimlib/scene/scene.py", line 11, in <module>
    from manimlib.camera.camera import Camera
  File "/Users/bearjere/Desktop/manim/manimlib/camera/camera.py", line 9, in <module>
    import cairo
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cairo/__init__.py", line 1, in <module>
    from ._cairo import *  # noqa: F401,F403
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cairo/_cairo.cpython-39-darwin.so, 2): Symbol not found: _cairo_append_path
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cairo/_cairo.cpython-39-darwin.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cairo/_cairo.cpython-39-darwin.so`

**Comment by BearJere** [comment]
Also when I try to run `python -m manim -h`
I get 
`Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/jerryhwang/Desktop/manim/manim.py", line 2, in <module>
    import manimlib
  File "manimlib/__init__.py", line 2, in <module>
    import manimlib.config
  File "manimlib/config.py", line 144
    print(f"Failed to render scene: {str(e)}")
                                            ^
SyntaxError: invalid syntax`

But when I try to run `python3 -m manim -h`, I get the original error message.

**Comment by tinfungster** [comment]
Try reinstalling cairo.

**Comment by BearJere** [comment]
I tried, it gave me the same error.

**Comment by naveen521kk** [comment]
try running
```sh
brew install cairo
pip install pycairo --force --no-cache
```

**Comment by BearJere** [comment]
Nope, for some reason it still doesn't work.

**Comment by naveen521kk** [comment]
Report an issue in https://github.com/pygobject/pycairo

**Comment by htprgrm** [comment]
I came across the same problem on my M1 macbook air. Here's how I solved the problem: First uninstall the pycairo installed by pip. Then re-install it using anaconda, `conda install pycairo`, conda should install its own cairo binary for you. Then everything works well on my computer.

**Comment by owenschris** [comment]
> I came across the same problem on my M1 macbook air. Here's how I solved the problem: First uninstall the pycairo installed by pip. Then re-install it using anaconda, `conda install pycairo`, conda should install at least two packages: cairo and pycairo, where cairo is its own built binary. Then everything works well on my computer.

This corrected the issue for me on the same platform.
