### ISSUE TITLE
Error after installing manim

### ISSUE THREAD

**Issue by AliNear** [3b1b/manim#1330]
I installed all manim & dependecies, but when I ran `python -m manim example_scenes.py OpeningManimExample`, I got the following error:
`Traceback (most recent call last):
  File "c:\users\jm\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\jm\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\jm\Documents\work\manim_new\manim\manim.py", line 5, in <module>
    manimlib.main()
  File "C:\Users\jm\Documents\work\manim_new\manim\manimlib\__init__.py", line 9, in main
    scenes = manimlib.extract_scene.main(config)
  File "C:\Users\jm\Documents\work\manim_new\manim\manimlib\extract_scene.py", line 113, in main
    scenes = get_scenes_to_render(all_scene_classes, scene_config, config)
  File "C:\Users\jm\Documents\work\manim_new\manim\manimlib\extract_scene.py", line 74, in get_scenes_to_render
    scene = scene_class(**scene_config)
  File "C:\Users\jm\Documents\work\manim_new\manim\manimlib\scene\scene.py", line 44, in __init__
    self.window = Window(self, **self.window_config)
  File "C:\Users\jm\Documents\work\manim_new\manim\manimlib\window.py", line 19, in __init__
    super().__init__(**kwargs)
  File "C:\Users\jm\Envs\manim.new\lib\site-packages\moderngl_window\context\pyglet\window.py", line 51, in __init__
    self._window = PygletWrapper(
  File "C:\Users\jm\Envs\manim.new\lib\site-packages\pyglet\window\win32\__init__.py", line 134, in __init__
    super(Win32Window, self).__init__(*args, **kwargs)
  File "C:\Users\jm\Envs\manim.new\lib\site-packages\pyglet\window\__init__.py", line 603, in __init__
    config = screen.get_best_config(config)
  File "C:\Users\jm\Envs\manim.new\lib\site-packages\pyglet\canvas\base.py", line 194, in get_best_config
    raise window.NoSuchConfigException()
pyglet.window.NoSuchConfigException`.
Any advice? And thank you

**Comment by TonyCrane** [comment]
Try to comment out this line?
https://github.com/3b1b/manim/blob/fe85d4e02f6935c49fb0b88eebbd492dfff2d324/manimlib/window.py#L15

**Comment by christina-0725** [comment]
@TonyCrane  Thanks a lot. I had the same problem. And your method is really useful!

**Comment by zalo** [comment]
For others (on Windows?) who have seen the above error and still have issues, I had to:
1) Install miktek to get rid of the File Not Found error.
2) And change this line:
https://github.com/3b1b/manim/blob/fe85d4e02f6935c49fb0b88eebbd492dfff2d324/manimlib/animation/creation.py#L136
to this:
```python
            self.lag_ratio = min(4.0 / max(0.1, length), 0.2)
```
to get rid of the `ZeroDivisionError: float division by zero` error.
