### ISSUE TITLE
moderngl.error.Error: GLSL Compiler failed

### ISSUE THREAD

**Issue by pedrommaiaa** [3b1b/manim#1340]
pedrommaiaa@pedromaia:~/Desktop/manim$ python3 manim.py example_scenes.py OpeningManimExample

Traceback (most recent call last):                                                                               
  File "manim.py", line 5, in <module>
    manimlib.main()
  File "/home/pedrommaiaa/Desktop/manim/manimlib/__init__.py", line 12, in main
    scene.run()
  File "/home/pedrommaiaa/Desktop/manim/manimlib/scene/scene.py", line 75, in run
    self.construct()
  File "example_scenes.py", line 19, in construct
    self.play(
  File "/home/pedrommaiaa/Desktop/manim/manimlib/scene/scene.py", line 385, in wrapper
    func(self, *args, **kwargs)
  File "/home/pedrommaiaa/Desktop/manim/manimlib/scene/scene.py", line 449, in play
    self.progress_through_animations(animations)
  File "/home/pedrommaiaa/Desktop/manim/manimlib/scene/scene.py", line 426, in progress_through_animations
    self.update_frame(dt)
  File "/home/pedrommaiaa/Desktop/manim/manimlib/scene/scene.py", line 154, in update_frame
    self.camera.capture(*self.mobjects)
  File "/home/pedrommaiaa/Desktop/manim/manimlib/camera/camera.py", line 326, in capture
    for render_group in self.get_render_group_list(mobject):
  File "/home/pedrommaiaa/Desktop/manim/manimlib/camera/camera.py", line 363, in get_render_group
    shader_program, vert_format = self.get_shader_program(shader_wrapper)
  File "/home/pedrommaiaa/Desktop/manim/manimlib/camera/camera.py", line 407, in get_shader_program
    program = self.ctx.program(**shader_wrapper.get_program_code())
  File "/home/pedrommaiaa/.local/lib/python3.8/site-packages/moderngl/context.py", line 1124, in program
    res.mglo, ls1, ls2, ls3, ls4, ls5, res._subroutines, res._geom, res._glo = self.mglo.program(
moderngl.error.Error: GLSL Compiler failed

geometry_shader
===============
0:261(35): error: `return' with wrong type int, in function `angle_between_vectors' returning float
0:323(20): warning: `has_prev' used uninitialized
0:324(20): warning: `has_next' used uninitialized
0:332(5): warning: `has_prev' used uninitialized
0:332(32): warning: `angle_from_prev' used uninitialized
0:333(5): warning: `has_next' used uninitialized
0:333(32): warning: `angle_to_next' used uninitialized

**Comment by TonyCrane** [comment]
Try #1329.
