### ISSUE TITLE
pyglet.window.NoSuchConfigException

### ISSUE THREAD

**Issue by Maruoka842** [3b1b/manim#1342]
### Describe the error
I try installing manima as follows : 
```
# Install python requirements
pip install -r requirements.txt

# Try it out
python manim.py example_scenes.py OpeningManimExample
```
However, following errors occured. 
How can I fix this ?

**Error**:
```
python manim.py example_scenes.py OpeningManimExample
Traceback (most recent call last):
  File "manim.py", line 5, in <module>
    manimlib.main()
  File "/home/maru/manim/manimlib/__init__.py", line 9, in main
    scenes = manimlib.extract_scene.main(config)
  File "/home/maru/manim/manimlib/extract_scene.py", line 113, in main
    scenes = get_scenes_to_render(all_scene_classes, scene_config, config)
  File "/home/maru/manim/manimlib/extract_scene.py", line 74, in get_scenes_to_render
    scene = scene_class(**scene_config)
  File "/home/maru/manim/manimlib/scene/scene.py", line 46, in __init__
    self.window = Window(self, **self.window_config)
  File "/home/maru/manim/manimlib/window.py", line 19, in __init__
    super().__init__(**kwargs)
  File "/home/maru/.local/lib/python3.8/site-packages/moderngl_window/context/pyglet/window.py", line 51, in __init__
    self._window = PygletWrapper(
  File "/home/maru/.local/lib/python3.8/site-packages/pyglet/window/xlib/__init__.py", line 173, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/maru/.local/lib/python3.8/site-packages/pyglet/window/__init__.py", line 603, in __init__
    config = screen.get_best_config(config)
  File "/home/maru/.local/lib/python3.8/site-packages/pyglet/canvas/base.py", line 194, in get_best_config
    raise window.NoSuchConfigException()
pyglet.window.NoSuchConfigException
```
### Environment
Ubuntu on WSL1

**Comment by TonyCrane** [comment]
Please search in the issues page first. See #1330 #1337 #1341.

**Comment by Maruoka842** [comment]
Thank you.
When I change "sample=1" to "sample=0" or delete it, this error is resolved.
However, new error occured.
Do you have any idea ?

```
Traceback (most recent call last):
  File "manim.py", line 5, in <module>
    manimlib.main()
  File "/home/maru/manim/manimlib/__init__.py", line 9, in main
    scenes = manimlib.extract_scene.main(config)
  File "/home/maru/manim/manimlib/extract_scene.py", line 113, in main
    scenes = get_scenes_to_render(all_scene_classes, scene_config, config)
  File "/home/maru/manim/manimlib/extract_scene.py", line 74, in get_scenes_to_render
    scene = scene_class(**scene_config)
  File "/home/maru/manim/manimlib/scene/scene.py", line 46, in __init__
    self.window = Window(self, **self.window_config)
  File "/home/maru/manim/manimlib/window.py", line 20, in __init__
    super().__init__(**kwargs)
  File "/home/maru/.local/lib/python3.8/site-packages/moderngl_window/context/pyglet/window.py", line 51, in __init__
    self._window = PygletWrapper(
  File "/home/maru/.local/lib/python3.8/site-packages/pyglet/window/xlib/__init__.py", line 173, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/maru/.local/lib/python3.8/site-packages/pyglet/window/__init__.py", line 606, in __init__
    context = config.create_context(gl.current_context)
  File "/home/maru/.local/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 204, in create_context
    return XlibContextARB(self, share)
  File "/home/maru/.local/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 314, in __init__
    super(XlibContext13, self).__init__(config, share)
  File "/home/maru/.local/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 218, in __init__
    raise gl.ContextException('Could not create GL context')
pyglet.gl.ContextException: Could not create GL context
```

**Comment by TonyCrane** [comment]
Please open a new issue. But before that, you are supposed to search the internet first.

**Comment by Maruoka842** [comment]
Yes. Thank you.
