### ISSUE TITLE
pyglet.gl.ContextException: Could not create GL context

### ISSUE THREAD

**Issue by Maruoka842** [3b1b/manim#1344]
I try installing manima as follows : 
```
# Install python requirements
pip install -r requirements.txt

# Try it out
python manim.py example_scenes.py OpeningManimExample
```
However, following errors occured. 
How can I fix this ?

```
Traceback (most recent call last):
  File "manim.py", line 5, in <module>
    manimlib.main()
  File "/home/maru/manim/manimlib/__init__.py", line 9, in main
    scenes = manimlib.extract_scene.main(config)
  File "/home/maru/manim/manimlib/extract_scene.py", line 113, in main
    scenes = get_scenes_to_render(all_scene_classes, scene_config, config)
  File "/home/maru/manim/manimlib/extract_scene.py", line 74, in get_scenes_to_render
    scene = scene_class(**scene_config)
  File "/home/maru/manim/manimlib/scene/scene.py", line 46, in __init__
    self.window = Window(self, **self.window_config)
  File "/home/maru/manim/manimlib/window.py", line 20, in __init__
    super().__init__(**kwargs)
  File "/home/maru/.local/lib/python3.8/site-packages/moderngl_window/context/pyglet/window.py", line 51, in __init__
    self._window = PygletWrapper(
  File "/home/maru/.local/lib/python3.8/site-packages/pyglet/window/xlib/__init__.py", line 173, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/maru/.local/lib/python3.8/site-packages/pyglet/window/__init__.py", line 606, in __init__
    context = config.create_context(gl.current_context)
  File "/home/maru/.local/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 204, in create_context
    return XlibContextARB(self, share)
  File "/home/maru/.local/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 314, in __init__
    super(XlibContext13, self).__init__(config, share)
  File "/home/maru/.local/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 218, in __init__
    raise gl.ContextException('Could not create GL context')
pyglet.gl.ContextException: Could not create GL context

```

**Comment by counter-attack-me2me** [comment]
Did you use a `virtual machine` to run the program ?
If so, you can try use the `mobaxterm` to `ssh` into your virtual machine (there are a lot of tutorials on how to install ssh in the virtual machine )
Then you can try run it in the mobaxterm `session` like this. 
> In this case, I just ran the official demo. 

```bash
# Install manimgl
pip install -e .

# Try it out
manimgl example_scenes.py OpeningManimExample
# or
manim-render example_scenes.py OpeningManimExample
```
![](https://cdn.jsdelivr.net/gh/counter-attack-me2me/img_cache/20210830193949.png)
>the error happen because I don't install `latex`. After install it, everything is OK.



![](https://cdn.jsdelivr.net/gh/counter-attack-me2me/img_cache/20210830195438.png)

If you can run the offical demo but the error sticks , then maybe your program has some problems. You should show the **related codes** with **the error logs** shown above. I can try to figure out where the problem(s) are.

I hope my answer helps you in some way.

**Comment by sherlcok314159** [comment]
Hey, if you are using NVIDIA on Ubuntu, maybe something is wrong with your GPU driver or something similar.

**Comment by pedrormjunior** [comment]
Through `conda`, the solution in GNU/Linux was to run `conda install -c conda-forge libstdcxx-ng` after activating the created environment specified in the README.md (https://github.com/3b1b/manim#anaconda-install).

_Originally posted by @OleBialas in https://github.com/mmatl/pyrender/issues/13#issuecomment-1402054024_
