### ISSUE TITLE
'TexText' is not defined

### ISSUE THREAD

**Issue by Maruoka842** [3b1b/manim#1346]
I have installed manim by the following.
```
pip3 install manimlib
```
However, following error occured.
I'm using ubuntu on WSL1.
How to fixt this ?
```
manim example_scenes.py OpeningManimExample
```
```
Media will be written to /home/maru/manim/media/. You can change this behavior with the --media_dir flag.

Traceback (most recent call last):
  File "/home/maru/.local/lib/python3.8/site-packages/manimlib/extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "/home/maru/.local/lib/python3.8/site-packages/manimlib/scene/scene.py", line 75, in __init__
    self.construct()
  File "example_scenes.py", line 13, in construct
    title = TexText("This is some \\LaTeX")
NameError: name 'TexText' is not defined
```

**Comment by TonyCrane** [comment]
The version on pypi is still the old version which is in the `cairo-backend` now, and `TexText` in that version is still called `TextMobject`.
If you want to use the new version in the `master` branch, you can only clone this repo and run it now.
