### ISSUE TITLE
Issue: Error when running any program

### ISSUE THREAD

**Issue by Saransh-cpp** [3b1b/manim#1349]
### Describe the error

Manim has been installed on my device for a long time. Today I decided to create a simulation, after a month maybe and no program would run. Everything comes to a single error statement in my terminal ```ImportError: cannot import name 'Color' from 'colour' (unknown location)``` ( full error below ). Even the previously made and successfully running programs are not running now. Help me please.

### Code and Error
**Code**:

```
from manimlib.imports import *

class TestScene(Scene):
    def construct(self):

        a = TextMobject('Hello')

        self.play(Write(a))
```

**Error**:

```
C:\Users\Saransh\Saransh_softwares\Manim python files\Physics Innovation>manim intro.py -pls
Traceback (most recent call last):
  File "C:\Users\Saransh\Saransh_softwares\Python_3.9\Scripts\manim-script.py", line 33, in <module>
    sys.exit(load_entry_point('manimlib==0.1.11', 'console_scripts', 'manim')())
  File "C:\Users\Saransh\Saransh_softwares\Python_3.9\Scripts\manim-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\Saransh\Saransh_softwares\Python_3.9\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Users\Saransh\Saransh_softwares\Python_3.9\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Saransh\Saransh_softwares\Python_3.9\lib\site-packages\manimlib\__init__.py", line 4, in <module>
    import manimlib.extract_scene
  File "C:\Users\Saransh\Saransh_softwares\Python_3.9\lib\site-packages\manimlib\extract_scene.py", line 9, in <module>
    from manimlib.scene.scene import Scene
  File "C:\Users\Saransh\Saransh_softwares\Python_3.9\lib\site-packages\manimlib\scene\scene.py", line 9, in <module>
    from manimlib.animation.animation import Animation
  File "C:\Users\Saransh\Saransh_softwares\Python_3.9\lib\site-packages\manimlib\animation\animation.py", line 5, in <module>
    from manimlib.mobject.mobject import Mobject
  File "C:\Users\Saransh\Saransh_softwares\Python_3.9\lib\site-packages\manimlib\mobject\mobject.py", line 9, in <module>
    from colour import Color
ImportError: cannot import name 'Color' from 'colour' (unknown location)
```

### Environment
**OS System**: Windows
**manim version**: master 
**python version**: Python 3.9

**Comment by TonyCrane** [comment]
Have you installed python package `colour`? Try `pip install colour` or `python -m pip install colour`.
And, is your manim version master? Firstly, the version in master now can't be installed through pip. Secondly, `TextMobject` has been renamed to `TexText` in the master version.

**Comment by Saransh-cpp** [comment]
Apologies for abandoning this, I have updated `manim` using `pip install manim`, still the same error. Then I tried following the README instructions, cloning the repository, installing dependencies, and then running the example. I get the same error, here it is -
```bash
Traceback (most recent call last):
  File "C:\Users\Saransh\Saransh_softwares\Python_3.9\Scripts\manimgl-script.py", line 33, in <module>
    sys.exit(load_entry_point('manimgl', 'console_scripts', 'manimgl')())
  File "C:\Users\Saransh\Saransh_softwares\Python_3.9\Scripts\manimgl-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "c:\users\saransh\saransh_softwares\python_3.9\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "c:\users\saransh\saransh_softwares\python_3.9\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\users\saransh\saransh_softwares\python_3.9\lib\site-packages\manimlib\__init__.py", line 4, in <module>
    import manimlib.extract_scene
  File "c:\users\saransh\saransh_softwares\python_3.9\lib\site-packages\manimlib\extract_scene.py", line 9, in <module>
    from manimlib.scene.scene import Scene
  File "c:\users\saransh\saransh_softwares\python_3.9\lib\site-packages\manimlib\scene\scene.py", line 9, in <module>
    from manimlib.animation.animation import Animation
  File "c:\users\saransh\saransh_softwares\python_3.9\lib\site-packages\manimlib\animation\animation.py", line 5, in <module>
    from manimlib.mobject.mobject import Mobject
  File "c:\users\saransh\saransh_softwares\python_3.9\lib\site-packages\manimlib\mobject\mobject.py", line 9, in <module>
    from colour import Color
ImportError: cannot import name 'Color' from 'colour' (unknown location)
```

Note: I did `pip install colour` and it shows me that it is already installed.

**Comment by TonyCrane** [comment]
If you use `pip install manim`, then what you installed is the community version.
If you want to install 3b1b/manim, you need to use `pip install manimgl`.

**Comment by Saransh-cpp** [comment]
Yes, I tried that too. I think the problem is with my python version, the latest python3 version `colour` supports is 3.6. I'll try it out.

**Comment by Saransh-cpp** [comment]
Finally it works, for everyone seeing this from the future -

`colour` is only supported till `python 3.6` and I had `python 3.9` installed.

Closing this issue, thanks for helping me out @TonyCrane.

**Comment by hindupurv** [comment]
What is the replacement for colour on python 3.9

**Comment by Saransh-cpp** [comment]
I don't think this issue exists now. I can use manim (the community version) without any issues on Python 3.9.

Anyways, independent of manim, if you are looking for alternatives to `Colour`, I would recommend [colour-science](https://github.com/colour-science/colour)!
