### ISSUE TITLE
Trouble with setup_axes( )

### ISSUE THREAD

**Issue by cosmicapple-svg** [3b1b/manim#1354]
### Describe the error
I'm new using Manim and I tried to animate a basic graph plot. When I run the code is displayed a error in self.setup_axes(). It is related with "tick_marks". What should I do?

### Code and Error
**Code**:
from manimlib.imports import *
import numpy as np 

class Plot2yLabelNumbers(GraphScene):
    CONFIG = {
        "y_min": 0,
        "y_max": 100,
        "y_axis_config": {"tick_frequency": 10},
        "y_labeled_nums": np.arange(0, 100, 10)
    }

    def construct(self):
        self.setup_axes()
        dot = Dot().move_to(self.coords_to_point(PI / 2, 20))
        func_graph = self.get_graph(lambda x: 20 * np.sin(x))
        self.add(dot,func_graph)
**Error**:
Traceback (most recent call last):
  File "manim.py", line 5, in <module>
    manimlib.main()
  File "/home/hugo/manim-master/manimlib/__init__.py", line 12, in main
    scene.run()
  File "/home/hugo/manim-master/manimlib/scene/scene.py", line 75, in run
    self.construct()
  File "/home/hugo/Documentos/grafica.py", line 14, in construct
    self.setup_axes()
  File "/home/hugo/manim-master/manimlib/scene/graph_scene.py", line 89, in setup_axes
    x_axis.get_tick_marks(), UP + RIGHT,
  File "/home/hugo/manim-master/manimlib/mobject/number_line.py", line 102, in get_tick_marks
    return self.tick_marks
AttributeError: 'NumberLine' object has no attribute 'tick_marks'

### Environment
**OS System**: Ubuntu
**manim version**: I reinstalled it today
**python version**: 3.8

**Comment by TonyCrane** [comment]
Change `self.tick_marks` in the 102rd line of `manimlib/mobject/number_line.py` to `self.ticks`.
But there is another bug, I'll open a pull request soon.

**Comment by cosmicapple-svg** [comment]
@TonyCrane thanks but now there is another error:

  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/hugo/manim-master/manim.py", line 5, in <module>
    manimlib.main()
  File "/home/hugo/manim-master/manimlib/__init__.py", line 12, in main
    scene.run()
  File "/home/hugo/manim-master/manimlib/scene/scene.py", line 75, in run
    self.construct()
  File "/home/hugo/Documentos/grafica.py", line 14, in construct
    self.setup_axes()
  File "/home/hugo/manim-master/manimlib/scene/graph_scene.py", line 119, in setup_axes
    y_axis.add_numbers(*self.y_labeled_nums)
TypeError: add_numbers() takes from 1 to 3 positional arguments but 10 were given

**Comment by TonyCrane** [comment]
So I said:
> But there is another bug, I'll open a pull request soon.

In the pr, I also fixed this by removing `*` in `.add_numbers()`
