### ISSUE TITLE
Conflict between extract_scene.py and scene_file_writer.py causes error while displaying GraphScene

### ISSUE THREAD

**Issue by StreakSharn** [3b1b/manim#1363]
## Description of bug / unexpected behavior
When attempting to display a GraphScene class, the program throws error **'SceneFileWriter' object has no attribute 'movie_file_path'**. After examining log output below, I traced the error to stem from a disagreement between extract_scene.py and scene_file_writer.py, where the former has 'write_to_movie' as True, whereas the latter has it as False.

## Expected behavior

/media/videos folder should contain videos of animated graph as file output.

## How to reproduce the issue

<details><summary>BuildingGraph program</summary>

```py
# experiments.py
from manimlib.imports import *


class BuildingGraph(GraphScene):

    def __init__(self,**kwargs):
        GraphScene.__init__(self)

    def construct(self):
        #build graph
        self.setup_axes(animate=False)
        graph = self.get_graph(lambda x:x**2,RED) #x^2 graph
        graph_label = self.get_graph_label(graph,label = 'x^{2}')
        graph2 = self.get_graph(lambda x:x**3,PURPLE) #x^3 graph
        graph2_label = self.get_graph_label(graph2,label = 'x^{3}')

        #display graph
        self.wait(1)
        self.play(ShowCreation(graph), Write(graph_label))
        self.wait(1)
        self.play(Transform(graph,graph2),Transform(graph_label,graph2_label))
        self.wait(1)
```

</details>
<details><summary>Command Line call</summary>

```
C:\Users\shrey\Documents\Programs\Manim>manim experiments.py BuildingGraph -p -i --low_quality --leave_progress_bars
```
</details>

## Files added

</details>

<details><summary>Tex Folder Output</summary>

![image](https://user-images.githubusercontent.com/74095821/107098176-87100a80-6806-11eb-8a60-164cec4a63e6.png)

Texts and video folders both remained empty.
</details>

</details>

## Logs
<details><summary>Terminal output</summary>

```
Media will be written to C:\Users\shrey\Documents\Year_11\Computer_Science\Programs\Manim\media\. You can change this behavior with the --media_dir flag.
Played 5 animations



Traceback (most recent call last):
  File "c:\users\shrey\anaconda3\lib\site-packages\manimlib\extract_scene.py", line 156, in main
    open_file_if_needed(scene.file_writer, **config)
  File "c:\users\shrey\anaconda3\lib\site-packages\manimlib\extract_scene.py", line 31, in open_file_if_needed
    file_paths.append(file_writer.get_movie_file_path())
  File "c:\users\shrey\anaconda3\lib\site-packages\manimlib\scene\scene_file_writer.py", line 219, in get_movie_file_path
    return self.movie_file_path
AttributeError: 'SceneFileWriter' object has no attribute 'movie_file_path'
```
</details>

## System specifications

<details><summary>System Details</summary>

- OS: Microsoft Windows [Version 10.0.18363.1316]
- RAM: 8.00 GB
- Python version: Python 3.8.5
<details><summary>Installed Modules</summary>

```
aiohttp                       3.7.3
alabaster                     0.7.12
argon2-cffi                   20.1.0
array-to-latex                0.82
async-generator               1.10
async-timeout                 3.0.1
attrs                         20.3.0
Babel                         2.9.0
backcall                      0.2.0
bleach                        3.2.2
bottle                        0.12.19
brotlipy                      0.7.0
certifi                       2020.12.5
cffi                          1.14.4
chardet                       3.0.4
clipboard                     0.0.4
colorama                      0.4.4
colorcet                      2.0.2
colour                        0.1.5
commonmark                    0.9.1
conan                         1.32.1
cryptography                  3.3.1
cycler                        0.10.0
Cython                        0.29.21
data                          0.4
decorator                     4.4.2
defusedxml                    0.6.0
deprecation                   2.0.7
dill                          0.3.3
discord.py                    1.6.0
distro                        1.5.0
dlx                           1.0.4
docplex                       2.19.202
docutils                      0.16
dulwich                       0.20.15
entrypoints                   0.3
fastdtw                       0.3.4
fasteners                     0.16
fastjsonschema                2.14.5
funcsigs                      1.0.2
future                        0.18.2
h5py                          3.1.0
IBMQuantumExperience          2.0.4
idna                          2.10
imagesize                     1.2.0
inflection                    0.5.1
ipykernel                     5.4.3
ipython                       7.19.0
ipython-genutils              0.2.0
ipywidgets                    7.6.3
jedi                          0.18.0
Jinja2                        2.11.2
joblib                        1.0.0
jsonschema                    3.2.0
jupyter                       1.0.0
jupyter-client                6.1.11
jupyter-console               6.2.0
jupyter-core                  4.7.0
jupyter-manim                 1.3
jupyterlab-pygments           0.1.2
jupyterlab-widgets            1.0.0
kaleidoscope                  0.0.10
kiwisolver                    1.3.1
latex                         0.7.0
llvmlite                      0.35.0
lxml                          4.6.2
manim                         0.3.0
manimlib                      0.2.0
manimpango                    0.2.0
MarkupSafe                    1.1.1
matplotlib                    3.3.3
menuinst                      1.4.16
mistune                       0.8.4
mkl-fft                       1.2.0
mkl-random                    1.1.1
mkl-service                   2.3.0
more-itertools                8.6.0
mpmath                        1.1.0
multidict                     5.1.0
multitasking                  0.0.9
navigator-updater             0.2.1
nbclient                      0.5.1
nbconvert                     6.0.7
nbformat                      5.1.2
nest-asyncio                  1.4.3
networkx                      2.5
node-semver                   0.6.1
notebook                      6.2.0
ntlm-auth                     1.5.0
numba                         0.52.0
numpy                         1.19.5
olefile                       0.46
opencv-python                 4.5.1.48
packaging                     20.8
pandas                        1.2.1
pandocfilters                 1.4.3
param                         1.10.1
parso                         0.8.1
patch-ng                      1.17.4
pbr                           5.5.1
pickleshare                   0.7.5
Pillow                        8.1.0
pip                           20.3.3
plotly                        4.14.1
pluginbase                    1.0.0
ply                           3.11
progressbar                   2.5
prometheus-client             0.9.0
prompt-toolkit                3.0.13
psutil                        5.8.0
pybind11                      2.6.1
pycairo                       1.20.0
pycparser                     2.20
pyct                          0.4.8
pydub                         0.24.1
pygame                        2.0.1
Pygments                      2.7.4
PyJWT                         1.7.1
pylatexenc                    2.8
pyparsing                     2.4.7
pyperclip                     1.8.1
PyQt5                         5.15.2
PyQt5-sip                     12.8.1
pyreadline                    2.1
pyrsistent                    0.17.3
PySide2                       5.15.2
python-constraint             1.4.0
python-dateutil               2.8.1
python-dotenv                 0.15.0
pytz                          2020.5
pywin32                       227
pywinpty                      0.5.7
PyYAML                        5.3.1
pyzmq                         21.0.1
qiskit                        0.23.2
qiskit-aer                    0.7.2
qiskit-aqua                   0.8.1
qiskit-ibmq-provider          0.11.1
qiskit-ignis                  0.5.1
qiskit-terra                  0.16.1
qiskit-textbook               0.1.0
qtconsole                     5.0.1
QtPy                          1.9.0
Quandl                        3.6.0
reno                          3.2.0
requests                      2.25.1
requests-ntlm                 1.1.0
retrying                      1.3.3
retworkx                      0.7.2
rich                          6.2.0
scikit-build                  0.11.1
scikit-learn                  0.24.1
scipy                         1.6.0
seaborn                       0.11.1
Send2Trash                    1.5.0
setuptools                    52.0.0
shiboken2                     5.15.2
shutilwhich                   1.1.0
sip                           4.19.13
six                           1.15.0
snowballstemmer               2.0.0
Sphinx                        3.4.3
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
sympy                         1.7.1
tempdir                       0.7.1
terminado                     0.9.2
testpath                      0.4.4
threadpoolctl                 2.1.0
tornado                       6.1
tqdm                          4.56.0
traitlets                     5.0.5
typing-extensions             3.7.4.3
urllib3                       1.25.11
wcwidth                       0.2.5
webencodings                  0.5.1
websockets                    8.1
wheel                         0.36.2
widgetsnbextension            3.5.1
wincertstore                  0.2
yarl                          1.6.3
yfinance                      0.1.55
```

</details>
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution: TeX Live 2020
+ Installed LaTeX packages: 
![image](https://user-images.githubusercontent.com/74095821/107101506-79ab4e00-680f-11eb-9613-b7c705dfae6f.png)

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
ffmpeg version 2021-01-31-git-6c92557756-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
```
</details>

## Additional comments

I followed the Traceback messages, and ended up with what I think could be the issue:
In extract_scene.py, the following code from Line 31 is part of the error.
```py
if config["file_writer_config"]["write_to_movie"]:
    file_paths.append(file_writer.get_movie_file_path())
```
Here, a print statement reveals:
```py
print(config["file_writer_config"]["write_to_movie"])
True
```

'file_writer.get_movie_file_path()' calls upon scene_file_writer.py, but there is a conflict here. 
```py
CONFIG = {
        "write_to_movie": False,
        .
        .
        .
}
```
Here, write_to_movie is hardcoded as False, conflicting with the 'True' from before.
Now that write_to_movie is false, it causes this piece of code to not execute, and self.movie_file_path to never be assigned.
```py
if self.write_to_movie:
            if consts.VIDEO_DIR != "":
                movie_dir = guarantee_existence(os.path.join(
                    consts.VIDEO_DIR,
                    module_directory,
                    self.get_resolution_directory(),
                ))
            else:
                movie_dir = guarantee_existence(consts.VIDEO_OUTPUT_DIR)
            self.movie_file_path = os.path.join(
                movie_dir,
                add_extension_if_not_present(
                    scene_name, self.movie_file_extension
                )
            )
```

Which then results in the error when get_movie_file_path is called, and tries to return self.movie_file_path, which was never created.
```py
def get_movie_file_path(self):
    """
    Returns the final path of the written video file.

    Returns
    -------
    str
        The path of the movie file.
    """
    return self.movie_file_path
```

Hard-coding write_to_movie in the CONFIG from scene_file_writer.py causes the program to run as expected, as both programs act upon write_to_movie being True. 
I'm not sure why write_to_movie is forced to False, therefore - shouldn't it change with extract_scene.py?

I also looked into where the 'True' write_to_movie originated from in extract_scene.py, but it appeared to come from:
```py
def main(config):
```
I don't know where this is called, so I couldn't go further.

Is this expected behaviour? Since scene_file_writer.py includes a message about not needing to edit it, I imagine I shouldn't need to do so to create the animation; if it is intended, my apologies, and I'd wonder if it should be changed to be based upon extract_scene.py.

Thanks in advance!

**Comment by 3b1b** [comment]
In the example you gave, by ignoring the kwargs passed into __init__, it will not take in any of the configurations from extract scene.  How does it look if you remove that __init__ method, or otherwise pass in the kwargs to GraphScene.__init__?

It's not that the value write_to_movie is hard-coded to False, it can be determined by passing in the appropriate arguments to Scene on initialization, specifically via the configuration that Scene passes along to SceneFileWriter.  The purpose of extract_scene.py is to determine what configuration should be passed to Scene, but if the keyword arguments in Scene.__init__ are ignored, that configuration will not show up.

--

As a side note, the current plan in this repository is to deprecate GraphScene, and instead let all that functionality live as methods of the CoordinateSystem mobject.

**Comment by StreakSharn** [comment]
Ah, I see - my bad! 
Removing **init** entirely seems to have solved the issue - thanks for the help!
