### ISSUE TITLE
Object has no attribute 'set_camera_orientation'

### ISSUE THREAD

**Issue by Azelide** [3b1b/manim#1370]
First off, I'm not sure whether this error is related more to Manim or Python so don't kill me for that. So I've tried to run this program from a YouTube video ([here it is](https://www.youtube.com/watch?v=oqDQwEvHGfE&ab_channel=Visualization101)), which is supposed to be an animation of the Lorenz Attractor.

**Code**: 

```python
from manimlib.imports import *

class Lorenz_Attractor(ThreeDScene):
    def construct(self):
        axes = ThreeDAxes(x_min=-3.5,x_max=3.5,y_min=-3.5,y_max=3.5,z_min=0,z_max=6,axis_config={"include_tip": True,"include_ticks":True,"stroke_width":1})
        dot = Sphere(radius=0.05,fill_color=BLUE).move_to(0*RIGHT + 0.1*UP + 0.105*OUT)
        
        self.set_camera_orientation(phi=65 * DEGREES,theta=30*DEGREES,gamma = 90*DEGREES)  
        self.begin_ambient_camera_rotation(rate=0.05)            #Start move camera

        dtime = 0.01
        numsteps = 30

        self.add(axes,dot)

        def lorenz(x, y, z, s=10, r=28, b=2.667):
            x_dot = s*(y - x)
            y_dot = r*x - y - x*z
            z_dot = x*y - b*z
            return x_dot, y_dot, z_dot

        def update_trajectory(self, dt):
            new_point = dot.get_center()
            if get_norm(new_point - self.points[-1]) > 0.01:
                self.add_smooth_curve_to(new_point)

        traj = VMobject()
        traj.start_new_path(dot.get_center())
        traj.set_stroke(BLUE, 1.5, opacity=0.8)
        traj.add_updater(update_trajectory)
        self.add(traj)

        def update_position(self,dt):
            x_dot, y_dot, z_dot = lorenz(dot.get_center()[0]*10, dot.get_center()[1]*10, dot.get_center()[2]*10)
            x = x_dot * dt/10
            y = y_dot * dt/10
            z = z_dot * dt/10
            self.shift(x/10*RIGHT + y/10*UP + z/10*OUT)

        dot.add_updater(update_position)
        self.wait(420)
```

When I run this code, I get this:

**Error**:
```
Traceback (most recent call last):
  File "C:\Users\Azelide\manim\manim.py", line 5, in <module>
    manimlib.main()
  File "C:\Users\Azelide\manim\manimlib\__init__.py", line 12, in main
    scene.run()
  File "C:\Users\Azelide\manim\manimlib\scene\scene.py", line 76, in run
    self.construct()
  File "lorenztrick.py", line 8, in construct
    self.set_camera_orientation(phi=65 * DEGREES,theta=30*DEGREES,gamma = 90*DEGREES)
AttributeError: 'Lorenz_Attractor' object has no attribute 'set_camera_orientation'
```
This looks to me quite inexplicable, since ``` set_camera_orientation ``` does exist in the Manim library and I assume the code should work fine otherwise, you can see the video for the demonstration.

Also, this is already a different issue but when I've tried running the 8 scenes from the example_scenes.py, they worked quite ok apart from the first scene (OpeningManimExample) giving me this traceback after I see the transformation of z to z^2:
```
C:\Users\Azelide\manim\manimlib\mobject\svg\svg_mobject.py:132: UserWarning: g1-79 not recognized
  warnings.warn(f"{ref} not recognized")
C:\Users\Azelide\manim\manimlib\mobject\svg\svg_mobject.py:132: UserWarning: g1-114 not recognized
  warnings.warn(f"{ref} not recognized")
C:\Users\Azelide\manim\manimlib\mobject\svg\svg_mobject.py:132: UserWarning: g1-116 not recognized
  warnings.warn(f"{ref} not recognized")
C:\Users\Azelide\manim\manimlib\mobject\svg\svg_mobject.py:132: UserWarning: g1-104 not recognized
  warnings.warn(f"{ref} not recognized")
C:\Users\Azelide\manim\manimlib\mobject\svg\svg_mobject.py:132: UserWarning: g1-105 not recognized
  warnings.warn(f"{ref} not recognized")
C:\Users\Azelide\manim\manimlib\mobject\svg\svg_mobject.py:132: UserWarning: g1-110 not recognized
  warnings.warn(f"{ref} not recognized")
C:\Users\Azelide\manim\manimlib\mobject\svg\svg_mobject.py:132: UserWarning: g1-107 not recognized
  warnings.warn(f"{ref} not recognized")
C:\Users\Azelide\manim\manimlib\mobject\svg\svg_mobject.py:132: UserWarning: g1-103 not recognized
  warnings.warn(f"{ref} not recognized")
C:\Users\Azelide\manim\manimlib\mobject\svg\svg_mobject.py:132: UserWarning: g1-111 not recognized
  warnings.warn(f"{ref} not recognized")
C:\Users\Azelide\manim\manimlib\mobject\svg\svg_mobject.py:132: UserWarning: g1-102 not recognized
  warnings.warn(f"{ref} not recognized")
C:\Users\Azelide\manim\manimlib\mobject\svg\svg_mobject.py:132: UserWarning: g1-101 not recognized
  warnings.warn(f"{ref} not recognized")
C:\Users\Azelide\manim\manimlib\mobject\svg\svg_mobject.py:132: UserWarning: g1-112 not recognized
  warnings.warn(f"{ref} not recognized")
C:\Users\Azelide\manim\manimlib\mobject\svg\svg_mobject.py:132: UserWarning: g1-108 not recognized
  warnings.warn(f"{ref} not recognized")
C:\Users\Azelide\manim\manimlib\mobject\svg\svg_mobject.py:132: UserWarning: g1-97 not recognized
  warnings.warn(f"{ref} not recognized")
C:\Users\Azelide\manim\manimlib\mobject\svg\svg_mobject.py:132: UserWarning: g1-115 not recognized
  warnings.warn(f"{ref} not recognized")
C:\Users\Azelide\manim\manimlib\mobject\svg\svg_mobject.py:132: UserWarning: g1-44 not recognized
  warnings.warn(f"{ref} not recognized")
C:\Users\Azelide\manim\manimlib\mobject\svg\svg_mobject.py:132: UserWarning: g1-109 not recognized
  warnings.warn(f"{ref} not recognized")

```

I'm running on Python 3.9.1, Windows 10 64-bit, in virtualenv. I was getting exactly the same errors both when not running via virtualenv and running via virtualenv. Reinstalled everything a few times, routed everything necessary to PATH in environment variable settings, nothing has improved.

**Comment by TonyCrane** [comment]
`set_camera_orientation` is removed in the new version, you can achieve the same effect by using `self.camera.frame.set_euler_angles`.
And `begin_ambient_camera_rotation` has also been deleted, you can use `self.camera.frame.add_updater(lambda m, dt: m.increment_theta(0.05 * dt))` to achieve the same effect.
If you still want to use this, you can download the old version from the current cairo-backend branch.

As for `UserWarning: ... not recognized`, this may be an issue of LaTeX and dvisvgm, you can search about it in [the issue page](https://github.com/3b1b/manim/issues). Sorry, but I don't know more about it.

**Comment by Azelide** [comment]
Ah okay, thank you @TonyCrane. I'm gonna use these new ones. I'd searched up something about dvi-svg conversion issues already, one of the solutions somebody suggested was to delete the wrong svg files and run a command in cmd prompt. However, I can't really find where are the svg files getting saved... Also, in my case it's g1-xxx not being recognized instead of g0-xxx, which might be making some difference too. Does anybody have further suggestions on this?

**Comment by TonyCrane** [comment]
The svg is saved in the `Tex/` folder under the `temporary_storage` directory you set in `custom_defaults.yml`. If you do not set it, it will be staved in `C:\Users\Azelide\Temp\Tex\` by default.
For more questions about this, maybe you'd better open another issue to seek help from others.
