### ISSUE TITLE
First example command returns error (get_monitors)

### ISSUE THREAD

**Issue by ultravision3d** [3b1b/manim#1389]
### Describe the error
I want to execute :
manimgl example_scenes.py OpeningManimExample

### Code and Error
**Code**:
example_scenes.py

**Error**:
Warning: Using the default configuration file, which you can modify in d:\videos\manim\manimlib\default_config.yml
        If you want to create a local configuration file, you can create a file named custom_config.yml, or run manimgl --config

Traceback (most recent call last):
  File "C:\Users\bob\AppData\Local\Programs\Python\Python37-32\Scripts\manimgl-script.py", line 33, in <module>
    sys.exit(load_entry_point('manimgl', 'console_scripts', 'manimgl')())
  File "d:\videos\manim\manimlib\__main__.py", line 13, in main
    config = manimlib.config.get_configuration(args)
  File "d:\videos\manim\manimlib\config.py", line 237, in get_configuration
    monitor = get_monitors()[custom_config["window_monitor"]]
  File "c:\users\bob\appdata\local\programs\python\python37-32\lib\site-packages\screeninfo\screeninfo.py", line 37, in get_monitors
    raise ScreenInfoError("No enumerators available")
screeninfo.common.ScreenInfoError: No enumerators available

### Environment
**OS System**:  windows 8.1
**manim version**: master 
**python version**: Python 3.7.2

**Comment by ultravision3d** [comment]
Any help ?

**Comment by ultravision3d** [comment]
Any help ?

**Comment by MLee-Sci** [comment]
@ultravision3d The automatic config creator doesn't appear to create the param window_monitor: 0

Adding it under:
window_position: UR
window_monitor: 0

Fixed the issue for me

**Comment by Alex23rodriguez** [comment]
running 
manim-render example_scenes.py OpeningManimExample
instead of 
manimgl example_scenes.py OpeningManimExample
worked for me. Afterwards I had no problem running the original command

**Comment by carlolimb** [comment]
I have the same issue. Tried both fixes mentioned above and the problem persists. Any advise?

**Comment by mohsen-2066** [comment]
🧐

Mohsen Salah

**Comment by LVotto** [comment]
This is due to a bug in screeninfo. [This ](https://github.com/rr-/screeninfo/pull/32) pull request has solved it for me.

**Comment by moep0** [comment]
> This is due to a bug in screeninfo. [This ](https://github.com/rr-/screeninfo/pull/32) pull request has solved it for me.

I tried the pr in screeninfo. Unfortunately, it didn't work for me. Any advice?

**Comment by moep0** [comment]
> > This is due to a bug in screeninfo. [This ](https://github.com/rr-/screeninfo/pull/32) pull request has solved it for me.
> 
> I tried the pr in screeninfo. Unfortunately, it didn't work for me. Any advice?

It can be fixed manually by just replacing all the `monitor` variables in window.py and config.py. You can set them to a constant like `monitor.width=1920`.
