### ISSUE TITLE
pip install -e . doesn't work + 'manimgl' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by abartoha** [3b1b/manim#1390]
I tried it last night and it worked perfectly, but after a restart it doesn't work, says:

`manimgl is not a recocgnized internal or external command`

SO I delete everything, reclone it and do:

### Code and Error
`pip install -e .`

and I get:
```
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///C:/Users/USER/Desktop/animation/manim
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USER\\Desktop\\animation\\manim\\setup.py'"'"'; __file__='"'"'C:\\Users\\USER\\Desktop\\animation\\manim\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\USER\AppData\Local\Temp\pip-pip-egg-info-gbw01nwl'
         cwd: C:\Users\USER\Desktop\animation\manim\
    Complete output (16 lines):
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "c:\users\user\desktop\animation\manim\.eggs\pbr-5.5.1-py3.8.egg\pbr\core.py", line 96, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "c:\users\user\desktop\animation\manim\.eggs\pbr-5.5.1-py3.8.egg\pbr\util.py", line 271, in cfg_to_args
        pbr.hooks.setup_hook(config)
      File "c:\users\user\desktop\animation\manim\.eggs\pbr-5.5.1-py3.8.egg\pbr\hooks\__init__.py", line 25, in setup_hook
        metadata_config.run()
      File "c:\users\user\desktop\animation\manim\.eggs\pbr-5.5.1-py3.8.egg\pbr\hooks\base.py", line 27, in run
        self.hook()
      File "c:\users\user\desktop\animation\manim\.eggs\pbr-5.5.1-py3.8.egg\pbr\hooks\metadata.py", line 25, in hook
        self.config['version'] = packaging.get_version(
      File "c:\users\user\desktop\animation\manim\.eggs\pbr-5.5.1-py3.8.egg\pbr\packaging.py", line 874, in get_version
        raise Exception("Versioning for this project requires either an sdist"
    Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name manimgl was given, but was not able to be found.
    error in setup command: Error parsing C:\Users\USER\Desktop\animation\manim\setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name manimgl was given, but was not able to be found.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.3.3; however, version 21.0.1 is available.
You should consider upgrading via the 'c:\program files\python38\python.exe -m pip install --upgrade pip' command.
```

### Environment
**Win10 64 bit**: 
**1.0.0devs41**: master 
**3.8**:

**Comment by TonyCrane** [comment]
Did you delete the hidden folder `.git/`? If you delete it, the installation cannot proceed normally.
Maybe you can execute `git clone https://github.com/3b1b/manim.git` to download the source code and install again.

**Comment by abartoha** [comment]
I deleted everything and redone hat in the same directory. BUT, nothing new happens.

**Comment by TonyCrane** [comment]
Have you solved this problem?
- You need to **clone** this repository through git, you should **not** download the `.zip` file.
- And you should **not** delete any files and folders after cloning.

If you ensure these, this problem shouldn't arise.

**Comment by naveen521kk** [comment]
> You need to clone this repository through git, you should not download the .zip file.

That's a bad way of packaging.... Normally, it should be possible to install directly from zip file. Essentially
```sh
pip install https://github.com/3b1b/manim/archive/master.zip
```
should work.

**Comment by Envoy-VC** [comment]
i just got the same issue i solved it by reinstalling python (but only for the current user not all users) and then reinstalled manim 
u could try it and tell me if it works for you

**Comment by abartoha** [comment]
@Envoy-VC 
I reinstalled python as root
It's faintly infuriating to ctrl+shift+ret into cmd and cd-ing all the time but reinstalling actually worked
(15 days ago)

Sorry for my late reply because I was studying for Physics Olympiad. Case closed.
