### ISSUE TITLE
No module named 'manimlib.__main__'

### ISSUE THREAD

**Issue by matiaspalumbo** [3b1b/manim#1400]
I followed the steps of the macOS installation cited in the README:

```
git clone https://github.com/3b1b/manim.git
cd manim
pip install -e .
manimgl example_scenes.py OpeningManimExample
```

But when I run the last command, this error appears:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/manimgl", line 6, in <module>
    from manimlib.__main__ import main
ModuleNotFoundError: No module named 'manimlib.__main__'
```

I don't know how to solve it, but I suspect it might have something to do with the previous manim installation I had. I moved the manim folder to another directory when I cloned the new version. Don't know how to fix this.

**Comment by einarf** [comment]
You might be running a different `manimgl` command or something?

Try installing manim in a virtualenv. I think something like this on macOS
```
git clone https://github.com/3b1b/manim.git
cd manim
python3 -m venv .venv
source .venv/bin/activate
pip install -e .
manimgl example_scenes.py OpeningManimExample
```

**Comment by FuckerLinda** [comment]
> You might be running a different `manimgl` command or something?
> 
> Try installing manim in a virtualenv. I think something like this on macOS
> 
> ```
> git clone https://github.com/3b1b/manim.git
> cd manim
> python3 -m venv .venv
> source .venv/bin/activate
> python -m pip install -e .
> manimgl example_scenes.py OpeningManimExample
> ```

REALLY HELPFUL!!!

**Comment by ya-echo** [comment]
> You might be running a different `manimgl` command or something?
> 
> Try installing manim in a virtualenv. I think something like this on macOS
> 
> ```
> git clone https://github.com/3b1b/manim.git
> cd manim
> python3 -m venv .venv
> source .venv/bin/activate
> python -m pip install -e .
> manimgl example_scenes.py OpeningManimExample
> ```

I'm sorry, I try this, but it's still not work.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/manimgl", line 6, in <module>
    from manimlib.__main__ import main
ModuleNotFoundError: No module named 'manimlib.__main__'
Do you know how to solve it? Thanks!

**Comment by TonyCrane** [comment]
Try reinstall it.

**Comment by niedong** [comment]
I was using Python 3.7.2 and encountered the same problem. I downloaded Python 3.9.4 and install manimgl via
`pip install manimgl`
and test with
`manimgl`
Everything is fine.

Change a fresh python may help.

**Comment by ya-echo** [comment]
@niedong 

> I was using Python 3.7.2 and encountered the same problem. I downloaded Python 3.9.4 and install manimgl via
> `pip install manimgl`
> and test with
> `manimgl`
> Everything is fine.
> 
> Change a fresh python may help.

YES! It's work, thank you!

**Comment by ya-echo** [comment]
> Try reinstall it.

I had reinstall many times, but it's still not work.
Then I tried @niedong 's method, it's work.
Anyway, thank you!
