### ISSUE TITLE
 name 'GraphScene' is not defined

### ISSUE THREAD

**Issue by SafalRaj10** [3b1b/manim#1420]
manimgl test.py
Warning: Using the default configuration file, which you can modify in c:\users\91785\desktop\manim\manimlib\default_config.yml
        If you want to create a local configuration file, you can create a file named custom_config.yml, or run manimgl --config

Traceback (most recent call last):
  File "C:\Users\91785\AppData\Local\Programs\Python\Python39\Scripts\manimgl-script.py", line 33, in <module>
    sys.exit(load_entry_point('manimgl', 'console_scripts', 'manimgl')())
  File "c:\users\91785\desktop\manim\manimlib\__main__.py", line 14, in main
    scenes = manimlib.extract_scene.main(config)
  File "c:\users\91785\desktop\manim\manimlib\extract_scene.py", line 115, in main
    scenes = get_scenes_to_render(all_scene_classes, scene_config, config)
  File "c:\users\91785\desktop\manim\manimlib\extract_scene.py", line 91, in get_scenes_to_render
    return [scene_class(**scene_config) for scene_class in result]
  File "c:\users\91785\desktop\manim\manimlib\extract_scene.py", line 91, in <listcomp>
    return [scene_class(**scene_config) for scene_class in result]
  File "test.py", line 4, in __init__
    GraphScene.__init__(
NameError: name 'GraphScene' is not defined

the required graph_scene.py was not in manim\manimlib\scene
Help Me...

**Comment by FlorianWoelki** [comment]
The reason for that is that the `graph_scene.py` is now in [once_useful_constructs](https://github.com/3b1b/manim/blob/master/manimlib/once_useful_constructs/graph_scene.py) directory. I think it is not included in the main library yet. However, you can easily reconstruct your examples with the classes in the `mobject` directory (e.g. CoordinateSystem, NumberPlane).

**Comment by giacomovagni** [comment]
Would you mind explaining how to reconstruct these functions? I tried to include the functions directly 

      def coords_to_point(self, x, y):
            assert(hasattr(self, "x_axis") and hasattr(self, "y_axis"))
            result = self.x_axis.number_to_point(x)[0] * RIGHT
            result += self.y_axis.number_to_point(y)[1] * UP
            return result

        def point_to_coords(self, point):
            return (self.x_axis.point_to_number(point),
                    self.y_axis.point_to_number(point))

But I get the error message `in coords_to_point assert(hasattr(self, "x_axis") and hasattr(self, "y_axis"))`

Thanks

**Comment by pifparfait** [comment]
Hi, I got this error, any help?
I can execute well the OpeningManimExample from example_scenes.py

That module has multiple scenes, which ones would you like to render?
Scene Name or Number: 06
Animation 0: WriteText:   0%|                            | 0/60 [00:00<?, ?it/s]2021-04-14 15:03:23.440 python[87935:2451268] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7f96ba471730>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2021-04-14 15:03:23.440 python[87935:2451268] Warning: Expected min height of view: (<NSButton: 0x7f96bd2b4a10>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2021-04-14 15:03:23.442 python[87935:2451268] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7f96bd2b6ac0>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2021-04-14 15:03:23.444 python[87935:2451268] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7f96bd2c04f0>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
ERROR:root:"                                                                    

 LaTeX Error!  Not a worry, it happens to the best of us.

 Missing $ inserted.

**Comment by TonyCrane** [comment]
> Would you mind explaining how to reconstruct these functions? I tried to include the functions directly
> 
> ```
>   def coords_to_point(self, x, y):
>         assert(hasattr(self, "x_axis") and hasattr(self, "y_axis"))
>         result = self.x_axis.number_to_point(x)[0] * RIGHT
>         result += self.y_axis.number_to_point(y)[1] * UP
>         return result
> 
>     def point_to_coords(self, point):
>         return (self.x_axis.point_to_number(point),
>                 self.y_axis.point_to_number(point))
> ```
> 
> But I get the error message `in coords_to_point assert(hasattr(self, "x_axis") and hasattr(self, "y_axis"))`
> 
> Thanks

For example, you can use `NumberPlane.coords_to_point(x, y)` instead of `GraphScene.coords_to_point(x, y)`
