### ISSUE TITLE
name 'Scene' is not defined

### ISSUE THREAD

**Issue by yyslush** [3b1b/manim#1424]
manim example_scenes.py
Traceback (most recent call last):
  File "/home/yyslush/.local/bin/manim", line 8, in <module>
    sys.exit(main())
  File "/home/yyslush/.local/lib/python3.8/site-packages/manimlib/__init__.py", line 9, in main
    config = manimlib.config.get_configuration(args)
  File "/home/yyslush/.local/lib/python3.8/site-packages/manimlib/config.py", line 155, in get_configuration
    module = get_module(args.file)
  File "/home/yyslush/.local/lib/python3.8/site-packages/manimlib/config.py", line 150, in get_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "example_scenes.py", line 12, in <module>
    class OpeningManimExample(Scene):
NameError: name 'Scene' is not defined

python3.8

**Comment by zqc-hhg** [comment]
me too

**Comment by TonyCrane** [comment]
`manimgl example_scenes.py` not `manim example_scenes.py`
`manim` is of community version.
