### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by wargod1632** [3b1b/manim#1482]
C:\Users\User>manim shape.py TestScene -pql
Manim Community v0.5.0
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\tools\Manim\Scripts\manim.exe\__main__.py", line 7, in <module>
  File "C:\tools\Manim\Lib\site-packages\manim\__main__.py", line 73, in main
    for SceneClass in scene_classes_from_file(input_file):
  File "C:\tools\Manim\Lib\site-packages\manim\utils\module_ops.py", line 117, in scene_classes_from_file
    module = get_module(file_path)
  File "C:\tools\Manim\Lib\site-packages\manim\utils\module_ops.py", line 46, in get_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\User\shape.py", line 1, in <module>
    from manimlib.imports import *
ModuleNotFoundError: No module named 'manimlib'

**Comment by CodingPower472** [comment]
Have you installed manimlib through pip?

**Comment by libinglong** [comment]
It's obvious that the program can not find manimlib.Take a look at document.

**Comment by wargod1632** [comment]
yes
I have installed through pip

**Comment by wargod1632** [comment]
what document libinglong?

**Comment by libinglong** [comment]
> what document libinglong?
> 
> 

You use manim，but import manimlib.Please show your code also.

**Comment by kilacoda** [comment]
Change the line `from manimlib.imports import *` to `from manim import *`. You're using the [community version](https://github.com/ManimCommunity/manim) which has a different import than manimgl (this repository).

**Comment by TonyCrane** [comment]
community version, not here.
