### ISSUE TITLE
what's wrong

### ISSUE THREAD

**Issue by kkl-oop** [3b1b/manim#1503]
when i run python ./manim.py example_scenes.py SquareToCircle -pl
error happens like following:

Animation 0: ShowCreationSquare:   7%| | 1/15 [00:00<00:01,  7.21it/s]  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0.0: Video: rawvideo, rgba, 854x480, 15 tbr, 15 tbn, 15 tbc
Expected number for loglevel but found: error

Traceback (most recent call last):
  File "C:\Users\ljj12\Documents\manim\manim-0.2.0\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\Users\ljj12\Documents\manim\manim-0.2.0\manimlib\scene\scene.py", line 75, in __init__
    self.construct()
  File "example_scenes.py", line 83, in construct
    self.play(ShowCreation(square))
  File "C:\Users\ljj12\Documents\manim\manim-0.2.0\manimlib\scene\scene.py", line 848, in wrapper
    func(self, *args, **kwargs)
  File "C:\Users\ljj12\Documents\manim\manim-0.2.0\manimlib\scene\scene.py", line 944, in play
    self.progress_through_animations(animations)
  File "C:\Users\ljj12\Documents\manim\manim-0.2.0\manimlib\scene\scene.py", line 901, in progress_through_animations
    self.add_frames(self.get_frame())
  File "C:\Users\ljj12\Documents\manim\manim-0.2.0\manimlib\scene\scene.py", line 1135, in add_frames
    self.file_writer.write_frame(frame)
  File "C:\Users\ljj12\Documents\manim\manim-0.2.0\manimlib\scene\scene_file_writer.py", line 336, in write_frame
    self.writing_process.stdin.write(frame.tobytes())
BrokenPipeError: [Errno 32] Broken pipe

**Comment by TonyCrane** [comment]
Search old issues first.
