### ISSUE TITLE
Transform of a VGroup to another VGroup causes assertion error 

### ISSUE THREAD

**Issue by RYNEQ** [3b1b/manim#1505]
### Describe the error
I have two VGroups consisting of other VGroups and Mobjects. When I try to Transform one into the other I get assertion error about not being a Mobject !

### Code and Error
```
def create_shape(array):
    orig_shape = array.shape 
    orig_len = len(orig_shape )
    if len(array.shape) < 2: 
        array.resize(1, array.shape[0])

    n, m = array.shape
    items = []
    for item in array.flatten():
        frame = Rectangle(width=1, height=1, stroke_width=0.9, color=WHITE, fill_color=color_gradient((BLUE,BLUE,WHITE), 100), fill_opacity=0.1)
        text = TextMobject(str(item)).scale(0.8)
        cell = VGroup(frame, text)
        cell.arrange(ORIGIN, center=True, buff=0)
        items.append(cell)

    fullmatrix = VGroup(*items)
    fullmatrix.arrange_in_grid(n, m, buff=0)

    title = VGroup(Text(f"Number of dims: {len(orig_shape)}"), Text("Shape: {}".format("x".join(map(str, orig_shape)))))
    title.arrange(DOWN, center=True, buff=0.2)
    title.scale(0.9)
    title.next_to(fullmatrix, DOWN, buff=0.5)

    axes = []
    if orig_len == 1:        
       axes.append(Text(f"Axis #1").scale(0.6).rotate(0).next_to(fullmatrix, UP)) 
    elif orig_len == 2:
       axes.append(Text(f"Axis #1").scale(0.6).rotate(PI/2).next_to(fullmatrix, LEFT)) 
       axes.append(Text(f"Axis #2").scale(0.6).rotate(0).next_to(fullmatrix, UP)) 

    shape = VGroup(fullmatrix, title, *axes)
    return shape


class Test(Scene):
    def construct(self):
        array1 = np.random.randint(1, 100, (6))
        shape = create_shape(array1)
        array2 = np.random.randint(1, 100, (4,6)) 
        self.play(FadeIn(shape))
        self.wait()
        self.play(Transform(array1, array2))
        self.wait(5)
```

**Error**:
```
Traceback (most recent call last):
  File "/home/ryn/.virtualenvs/manim/lib/python3.6/site-packages/manimlib/extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "/home/ryn/.virtualenvs/manim/lib/python3.6/site-packages/manimlib/scene/scene.py", line 75, in __init__
    self.construct()
  File "numpy_array.py", line 48, in construct
    self.play(Transform(array1, array2))
  File "/home/ryn/.virtualenvs/manim/lib/python3.6/site-packages/manimlib/animation/transform.py", line 27, in __init__
    super().__init__(mobject, **kwargs)
  File "/home/ryn/.virtualenvs/manim/lib/python3.6/site-packages/manimlib/animation/animation.py", line 31, in __init__
    assert(isinstance(mobject, Mobject))
AssertionError


```

### Environment
**OS System**: Linux (Ubuntu)
**manim version**: manimlib (0.2.0), manim (0.6.0)
**python version**: 3.8

**Comment by TonyCrane** [comment]
In your code, `array1` and `array2` which you passed to `Transform` are both `numpy.ndarray` not `Mobject`. So you can't Transform between them.
Maybe you want `Transform(create_shape(array1), create_shape(array2))`.

**Comment by RYNEQ** [comment]
> In your code, `array1` and `array2` which you passed to `Transform` are both `numpy.ndarray` not `Mobject`. So you can't Transform between them.
> Maybe you want `Transform(create_shape(array1), create_shape(array2))`.

Oh thanks! that was a typo! I should transform the `shape`
