### ISSUE TITLE
Tex not working

### ISSUE THREAD

**Issue by TheRealKinglogic** [3b1b/manim#1508]
### Describe the error
I have installed it exactly (I believe) as in the documentation, and it worked when I tried to run SquareToCircle, but it doesn't work when I try to run the OpeningManimExample. 

### Code and Error
**Code**:
under example_scenes.py, OpeningManimExample doesn't work. 

**Error**:
Traced all the way back to 
File "C:\Users\[my name]\PycharmProjects\manimm\manimlib\utils\tex_file_writing.py", line 72, in tex_to_d
vi
    "See log output above or the log file: %s" % log_file)
Exception: Latex error converting to dvi. See log output above or the log file: media/Tex/664e80e8d8d98
482.log

### Environment
**OS System**: Windows 10
**manim version**: master  Latest version, about 2 weeks ago as of this issue.
**python version**:3.7

**Comment by TheRealKinglogic** [comment]
Since this is my first time using github, I apologize in advance if something in this issue seems unprofessional or if this is a very simple error.

**Comment by Y0N1N1** [comment]
---
name: Same problem, latex giving funky errors
about: The error you encountered while using manim, when tried running programs using the "Tex" class
---

### Describe the error
The error is given whenever I run latex related things on manim.

### Code and Error
**Code**:
`from manimlib import *

class st(Scene):
    def construct(self):
        tex = Tex(r'x^{2}').scale(3)
        self.add(tex)`

**Error**:
`sh: latex: command not found
ERROR:root:

 LaTeX Error!  Not a worry, it happens to the best of us.

Traceback (most recent call last):
  File "/Users/gabriel/.pyenv/versions/3.9.4/bin/manimgl", line 8, in <module>
    sys.exit(main())
  File "/Users/gabriel/.pyenv/versions/3.9.4/lib/python3.9/site-packages/manimlib/__main__.py", line 17, in main
    scene.run()
  File "/Users/gabriel/.pyenv/versions/3.9.4/lib/python3.9/site-packages/manimlib/scene/scene.py", line 75, in run
    self.construct()
  File "start.py", line 5, in construct
    tex = Tex(r'x^{2}').scale(3)
  File "/Users/gabriel/.pyenv/versions/3.9.4/lib/python3.9/site-packages/manimlib/mobject/svg/tex_mobject.py", line 167, in __init__
    super().__init__(full_string, **kwargs)
  File "/Users/gabriel/.pyenv/versions/3.9.4/lib/python3.9/site-packages/manimlib/mobject/svg/tex_mobject.py", line 42, in __init__
    filename = tex_to_svg_file(full_tex)
  File "/Users/gabriel/.pyenv/versions/3.9.4/lib/python3.9/site-packages/manimlib/utils/tex_file_writing.py", line 52, in tex_to_svg_file
    tex_to_svg(tex_file_content, svg_file)
  File "/Users/gabriel/.pyenv/versions/3.9.4/lib/python3.9/site-packages/manimlib/utils/tex_file_writing.py", line 60, in tex_to_svg
    svg_file = dvi_to_svg(tex_to_dvi(tex_file))
  File "/Users/gabriel/.pyenv/versions/3.9.4/lib/python3.9/site-packages/manimlib/utils/tex_file_writing.py", line 94, in tex_to_dvi
    with open(log_file, "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/7r/drxcwz0s5h9ggsqw4_5c0b2w0000gp/T/Tex/81b653697ca64401.log'`

### Environment
**OS System**: mac
**manim version**: master, latest
**python version**: 3.9.4

**Comment by umm233** [comment]
Maybe you need to check:
- whether adding LaTex to the environment variable
- whether missing LaTex packages

**Comment by AhmedThahir** [comment]
Same problem for me.

LaTex error comes up when using manimgl, but not when using manimce

# Environment
OS System: Windows
manim version: master, latest
python version: 3.9.4

**Comment by aljabrak** [comment]
> Same problem for me.
> Regular text works in manimgl but
> LaTex error comes up when using manimgl, but not when using manimce
> 
> # Environment
> OS System: Windows
> manim version: master, latest
> python version: 3.9.4


Warning: Using the default configuration file, which you can modify in c:\python39\lib\site-packages\manimlib\default_config.yml
If you want to create a local configuration file, you can create a file named custom_config.yml, or run manimgl --config
ERROR:root:A^{2} + B^{2} = C^{2}$"

 LaTeX Error!  Not a worry, it happens to the best of us.

Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\manimgl.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\manimlib\__main__.py", line 17, in main
    scene.run()
  File "c:\python39\lib\site-packages\manimlib\scene\scene.py", line 75, in run
    self.construct()
  File "text.py", line 5, in construct
    formula = Tex('$A^{2} + B^{2} = C^{2}$')
  File "c:\python39\lib\site-packages\manimlib\mobject\svg\tex_mobject.py", line 163, in __init__
    super().__init__(full_string, **kwargs)
  File "c:\python39\lib\site-packages\manimlib\mobject\svg\tex_mobject.py", line 42, in __init__
    filename = tex_to_svg_file(full_tex)
  File "c:\python39\lib\site-packages\manimlib\utils\tex_file_writing.py", line 52, in tex_to_svg_file
    tex_to_svg(tex_file_content, svg_file)
  File "c:\python39\lib\site-packages\manimlib\utils\tex_file_writing.py", line 60, in tex_to_svg
    svg_file = dvi_to_svg(tex_to_dvi(tex_file))
  File "c:\python39\lib\site-packages\manimlib\utils\tex_file_writing.py", line 94, in tex_to_dvi
    with open(log_file, "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\[user]~1\\AppData\\Local\\Temp\\Tex\\7473536f085b74af.log'


># Environment
> OS System: Windows
> manim version: master, latest
> python version: 3.9.4

**Comment by MrHeavythree** [comment]
You can consider the following steps:
1.Create TempLatex directory in C drive
2.Find manimlib/default_config.yml in the manim (manimgl version) directory and open it with a text editor
3.Modify line 18: before: temporary_storage: "" after: temporary_storage: "C:/TempLatex "
4.Save

**Comment by zhOrange** [comment]
I got the same problem with mikTex. Anyone has ideas?

**Comment by ItsSunnyMonster** [comment]
@zhOrange Try use @MrHeavythree 's method. It worked perfectly for me.
