### ISSUE TITLE
ImportError: module 'manimlib' has no attribute 'main'

### ISSUE THREAD

**Issue by Bruno-Noobador** [3b1b/manim#1528]
### Describe the error
I tried to use the command "Manim" on cmd and I get this error.

### Code and Error
**Manim**:

**Error**:
C:\Users\Samsung>manim
Traceback (most recent call last):
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2451, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'manimlib' has no attribute 'main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python38\Scripts\manim-script.py", line 11, in <module>
    load_entry_point('manimlib==0.2.0', 'console_scripts', 'manim')()
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2453, in resolve
    raise ImportError(str(exc))
ImportError: module 'manimlib' has no attribute 'main'

### Environment
**OS System**: Windows 10
**manim version**: master 
**python version**: Python 3.8

**Comment by Bruno-Noobador** [comment]
Uptade:
If I use the command "pip install manimlib" and "pip install manim" it solves the problem.

**Comment by TonyCrane** [comment]
But you just install another version - community version
