### ISSUE TITLE
Python 3.9 TypeError: argument of type 'int' is not iterable window.py

### ISSUE THREAD

**Issue by ChristopherHanks** [3b1b/manim#1558]
Issue validating the installation of manimgl after following the installation instructions for windows.

manim execution 'manimgl start.py SquareToCircle' results in a python TypeError

 File "c:\manim\manimlib\window.py", line 47, in find_initial_position
    if "," in custom_position:
TypeError: argument of type 'int' is not iterable

C:\manim>manimgl start.py SquareToCircle
Traceback (most recent call last):
  File "C:\Python39\Scripts\manimgl-script.py", line 33, in <module>
    sys.exit(load_entry_point('manimgl', 'console_scripts', 'manimgl')())
  File "c:\manim\manimlib\__main__.py", line 14, in main
    scenes = manimlib.extract_scene.main(config)
  File "c:\manim\manimlib\extract_scene.py", line 115, in main
    scenes = get_scenes_to_render(all_scene_classes, scene_config, config)
  File "c:\manim\manimlib\extract_scene.py", line 76, in get_scenes_to_render
    scene = scene_class(**scene_config)
  File "c:\manim\manimlib\scene\scene.py", line 46, in __init__
    self.window = Window(scene=self, **self.window_config)
  File "c:\manim\manimlib\window.py", line 35, in __init__
    initial_position = self.find_initial_position(size)
  File "c:\manim\manimlib\window.py", line 47, in find_initial_position
    if "," in custom_position:
TypeError: argument of type 'int' is not iterable

Microsoft Windows 10 Pro
Version	10.0.19042 Build 19042
Python 3.9.5

start.py
from manimlib import *

class SquareToCircle(Scene):
    def construct(self):
        circle = Circle()
        circle.set_fill(BLUE, opacity=0.5)
        circle.set_stroke(BLUE_E, width=4)

        self.add(circle)

C:\manim>ffmpeg -version
ffmpeg version 4.4-essentials_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
libavutil      56. 70.100 / 56. 70.100
libavcodec     58.134.100 / 58.134.100
libavformat    58. 76.100 / 58. 76.100
libavdevice    58. 13.100 / 58. 13.100
libavfilter     7.110.100 /  7.110.100
libswscale      5.  9.100 /  5.  9.100
libswresample   3.  9.100 /  3.  9.100
libpostproc    55.  9.100 / 55.  9.100

C:\manim>latex
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (MiKTeX 21.2)
**

**Comment by TonyCrane** [comment]
Did you modify `window_position` in `default_config.yml` or `custom_config.yml` ?
