### ISSUE TITLE
Trying to write Stuff with WriteStuff in example_scenes.py

### ISSUE THREAD

**Issue by jacobhelbig** [3b1b/manim#157]
When I try to run WriteStuff in example_scenes.py, I get the following error:
Traceback (most recent call last):
  File "extract_scene.py", line 15, in <module>
    from scene import Scene
  File "/Users/jacob 1/Desktop/manim-master/scene/__init__.py", line 5, in <module>
    from scene import Scene
  File "/Users/jacob 1/Desktop/manim-master/scene/scene.py", line 21, in <module>
    from animation.continual_animation import ContinualAnimation
  File "/Users/jacob 1/Desktop/manim-master/animation/continual_animation.py", line 3, in <module>
    from simple_animations import MaintainPositionRelativeTo
  File "/Users/jacob 1/Desktop/manim-master/animation/simple_animations.py", line 9, in <module>
    from mobject.tex_mobject import TextMobject
  File "/Users/jacob 1/Desktop/manim-master/mobject/tex_mobject.py", line 368
    exit_code = os.system(" ".join(commands))
    ^
IndentationError: unexpected indent

shell returned 1

I did all the steps recommended in Issues #64 and #36, before I got the Issue of "Latex Error converting to dvi" (#40). Can somebody help me?

**Comment by ishandutta2007** [comment]
is this issues solved ?

**Comment by BETAPANDERETA** [comment]
Take a look if you have a correct identation on 15 line of example_scene.py
