### ISSUE TITLE
Manim seems to be analphabetical.

### ISSUE THREAD

**Issue by jacobhelbig** [3b1b/manim#158]
I followed the steps described by hmuar in [this issue](https://github.com/3b1b/manim/issues/124), but now, no matter which Scene I try to play (The example is SquareToCircle), I get the following error message:

```
Jacobs-MBP:manim-master jacob$ python extract_scene.py example_scenes.py SquareToCircle -p
Traceback (most recent call last):
  File "extract_scene.py", line 15, in <module>
    from scene import Scene
  File "/Users/jacob 1/Desktop/manim-master/scene/__init__.py", line 5, in <module>
    from scene import Scene
  File "/Users/jacob 1/Desktop/manim-master/scene/scene.py", line 21, in <module>
    from animation.continual_animation import ContinualAnimation
  File "/Users/jacob 1/Desktop/manim-master/animation/continual_animation.py", line 3, in <module>
    from simple_animations import MaintainPositionRelativeTo
  File "/Users/jacob 1/Desktop/manim-master/animation/simple_animations.py", line 9, in <module>
    from mobject.tex_mobject import TextMobject
  File "/Users/jacob 1/Desktop/manim-master/mobject/tex_mobject.py", line 343
    exit_code = os.system(" ".join(commands))
    ^
IndentationError: unexpected indent
```

Can somebody help me?

**Comment by eulertour** [comment]
Closing, as this isn't an issue with the current version of manim.
