### ISSUE TITLE
Error when running the Quick start test, and would love some help!

### ISSUE THREAD

**Issue by Jiraffe19** [3b1b/manim#1599]
Hi, I am a math teacher and would like to start making math videos.
But I ran into some problems when running the Quickstart test on the official website:
https://docs.manim.community/en/v0.9.0/tutorials/quickstart.html

This is my code return when I run the file (Using a Macbook air M1 chip):

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/manim", line 5, in <module>
    from manim.__main__ import main
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/manim/__init__.py", line 37, in <module>
    from .animation.composition import *
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/manim/animation/composition.py", line 12, in <module>
    from ..scene.scene import Scene
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/manim/scene/scene.py", line 31, in <module>
    from ..camera.camera import Camera
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/manim/camera/camera.py", line 14, in <module>
    import cairo
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cairo/__init__.py", line 1, in <module>
    from ._cairo import *  # noqa: F401,F403
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cairo/_cairo.cpython-39-darwin.so, 2): Symbol not found: _cairo_append_path
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cairo/_cairo.cpython-39-darwin.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cairo/_cairo.cpython-39-darwin.so

As mentioned, Im using Apple Silicon the M1 chip on my macbook air,
I checked that I've correctly installed Manim (community version, and by the instructions to use Rosetta2 to install brew and other dependencies), can't really figure out what the probelm is!

Hope you can enlighten me!

**Comment by TonyCrane** [comment]
You are using the community version, so please ask this question on their discord channel or open an issue in [ManimCommunity/manim](https://github.com/ManimCommunity/manim) instead of here.
