### ISSUE TITLE
I can't play animations when using WSL #1628

### ISSUE THREAD

**Issue by cmershen** [3b1b/manim#1629]
```
$ python3 -m manim example_scenes.py SquareToCircle -pl
Manim Community v0.4.0
[09/21/21 16:28:25] WARNING  Option -l is deprecated please use the --quality/-q flag.                      utils.py:138
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sry/.local/lib/python3.6/site-packages/manim/__main__.py", line 104, in <module>
    main()
  File "/home/sry/.local/lib/python3.6/site-packages/manim/__main__.py", line 92, in main
    for SceneClass in scene_classes_from_file(input_file):
  File "/home/sry/.local/lib/python3.6/site-packages/manim/utils/module_ops.py", line 117, in scene_classes_from_file
    module = get_module(file_path)
  File "/home/sry/.local/lib/python3.6/site-packages/manim/utils/module_ops.py", line 46, in get_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/f/manim/manim/example_scenes.py", line 1, in <module>
    from manimlib import *
  File "/mnt/f/manim/manim/manimlib/__init__.py", line 19, in <module>
    from manimlib.window import *
  File "/mnt/f/manim/manim/manimlib/window.py", line 2, in <module>
    from moderngl_window.context.pyglet.window import Window as PygletWindow
  File "/home/sry/.local/lib/python3.6/site-packages/moderngl_window/context/pyglet/__init__.py", line 1, in <module>
    from .keys import Keys  # noqa
  File "/home/sry/.local/lib/python3.6/site-packages/moderngl_window/context/pyglet/keys.py", line 12, in <module>
    from pyglet.window import key
  File "/home/sry/.local/lib/python3.6/site-packages/pyglet/window/__init__.py", line 1918, in <module>
    gl._create_shadow_window()
  File "/home/sry/.local/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 206, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home/sry/.local/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 171, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/sry/.local/lib/python3.6/site-packages/pyglet/window/__init__.py", line 590, in __init__
    display = pyglet.canvas.get_display()
  File "/home/sry/.local/lib/python3.6/site-packages/pyglet/canvas/__init__.py", line 94, in get_display
    return Display()
  File "/home/sry/.local/lib/python3.6/site-packages/pyglet/canvas/xlib.py", line 123, in __init__
    raise NoSuchDisplayException('Cannot connect to "%s"' % name)
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"
```

When I execute `python3 -m manim example_scenes.py SquareToCircle -pl`, I got the exception above.

I'm using WSL on Windows 10

**Comment by TonyCrane** [comment]
Seems that you are using the community version of manim, so you'd better ask this question on their discord channel or open an issue in ManimCommunity/manim instead of here.
