### ISSUE TITLE
Unable to install?

### ISSUE THREAD

**Issue by mieotoha** [3b1b/manim#1635]
Before that, I have tried to install manim with `pip` or `pip3`

System: Ubuntu 20.04
Python: 3.8

using `pip`

```bash
pip install -e .
Obtaining file:///home/mieotoha/Application/manim
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting matplotlib
  Using cached matplotlib-3.4.3-cp38-cp38-manylinux1_x86_64.whl (10.3 MB)
Collecting moderngl-window
  Using cached moderngl_window-2.4.0-py3-none-any.whl (362 kB)
Collecting colour
  Using cached colour-0.1.5-py2.py3-none-any.whl (23 kB)
Collecting manimpango<0.4.0,>=0.2.0
  Using cached ManimPango-0.3.0.tar.gz (4.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmptlju1v5x get_requires_for_build_wheel /tmp/tmpcl9k6ksa
       cwd: /tmp/pip-install-n7acquqm/manimpango
  Complete output (33 lines):
  Package pangocairo was not found in the pkg-config search path.
  Perhaps you should add the directory containing `pangocairo.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'pangocairo' found
  Traceback (most recent call last):
    File "setup.py", line 130, in check_min_version
      check_call(command, stdout=subprocess.DEVNULL)
    File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['pkg-config', '--print-errors', '--atleast-version', '1.30.0', 'pangocairo']' returned non-zero exit status 1.
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/tmptlju1v5x", line 280, in <module>
      main()
    File "/tmp/tmptlju1v5x", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmptlju1v5x", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-aqd4pv4c/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-aqd4pv4c/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-aqd4pv4c/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 258, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-aqd4pv4c/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 197, in <module>
      _pkg_config_pangocairo.check_min_version(MINIMUM_PANGO_VERSION)
    File "setup.py", line 133, in check_min_version
      raise RequiredDependencyException(f"{self.name} >= {version} is required")
  __main__.RequiredDependencyException: pangocairo >= 1.30.0 is required
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmptlju1v5x get_requires_for_build_wheel /tmp/tmpcl9k6ksa Check the logs for full command output.
```

using `pip3`

```bash
pip3 install -e .
Obtaining file:///home/mieotoha/Application/manim
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting tqdm
  Using cached tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
Collecting sympy
  Using cached sympy-1.8-py3-none-any.whl (6.1 MB)
Collecting moderngl
  Using cached moderngl-5.6.4-cp38-cp38-manylinux1_x86_64.whl (680 kB)
Collecting argparse
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting matplotlib
  Using cached matplotlib-3.4.3-cp38-cp38-manylinux1_x86_64.whl (10.3 MB)
Collecting pydub
  Using cached pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from manimgl==1.1.1) (5.3.1)
Collecting mapbox-earcut
  Using cached mapbox_earcut-0.12.10-cp38-cp38-manylinux2010_x86_64.whl (79 kB)
Collecting validators
  Using cached validators-0.18.2-py3-none-any.whl (19 kB)
Requirement already satisfied: ipython in /usr/local/lib/python3.8/dist-packages (from manimgl==1.1.1) (7.27.0)
Collecting screeninfo
  Using cached screeninfo-0.7.tar.gz (10 kB)
Collecting colour
  Using cached colour-0.1.5-py2.py3-none-any.whl (23 kB)
Collecting manimpango<0.4.0,>=0.2.0
  Using cached ManimPango-0.3.0.tar.gz (4.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpg20v3ccv get_requires_for_build_wheel /tmp/tmpvc3b433k
       cwd: /tmp/pip-install-4dc2mhi7/manimpango
  Complete output (33 lines):
  Package pangocairo was not found in the pkg-config search path.
  Perhaps you should add the directory containing `pangocairo.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'pangocairo' found
  Traceback (most recent call last):
    File "setup.py", line 130, in check_min_version
      check_call(command, stdout=subprocess.DEVNULL)
    File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['pkg-config', '--print-errors', '--atleast-version', '1.30.0', 'pangocairo']' returned non-zero exit status 1.
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/tmpg20v3ccv", line 280, in <module>
      main()
    File "/tmp/tmpg20v3ccv", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmpg20v3ccv", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-kz1mxmef/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-kz1mxmef/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-kz1mxmef/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 258, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-kz1mxmef/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 197, in <module>
      _pkg_config_pangocairo.check_min_version(MINIMUM_PANGO_VERSION)
    File "setup.py", line 133, in check_min_version
      raise RequiredDependencyException(f"{self.name} >= {version} is required")
  __main__.RequiredDependencyException: pangocairo >= 1.30.0 is required
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpg20v3ccv get_requires_for_build_wheel /tmp/tmpvc3b433k Check the logs for full command output.
```

**Comment by shallow-beach** [comment]
had a similar error come up with pangocairo.pc on MacOS Sonoma w/ ARM. i am using brew as well as pyenv, and my error message implicated both, but all i needed to do was:
`brew install pango`
which and the pip install went right through after :)

**Comment by hyperbolic-c** [comment]
## without root to use apt install
If without root to install pango, it could be solved by installing pango from source code.
First, get pango file [pango-1.51.0](https://download.gnome.org/sources/pango/1.51/pango-1.51.0.tar.xz).
Unzip and get in the folder, use `meson` tool
```
meson setup $builddir --prefix=${path to install}
ninja -C $builddir
ninja -C $builddir install
```
and then add the path to `bashrc`, 
```
# pkg-config path
export PKG_CONFIG_PATH="/path/to/pango-1.51.2/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH"
```
after `source ~/.bashrc` everything is ok.

**Comment by MeMeBallJM** [comment]
@shallow-beach Thank you very much!! :D
