### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'find'

### ISSUE THREAD

**Issue by MukunthAG** [3b1b/manim#1646]
### Error while running ControlsExample Scene
I am trying to run the ControlsExample scene in example_scenes.py. I am getting an numpy.ndarray attribute error from it. I followed all the instructions correctly and didn't change any of the root manim files. This issue is only with this scene, other examples run well with no such errors. 

### Here is the code followed by the entire error
**Code**:
```
class ControlsExample(Scene):
    def setup(self):
        self.textbox = Textbox()
        self.checkbox = Checkbox()
        self.color_picker = ColorSliders()
        self.panel = ControlPanel(
            Text("Text", font_size=24), self.textbox, Line(),
            Text("Show/Hide Text", font_size=24), self.checkbox, Line(),
            Text("Color of Text", font_size=24), self.color_picker
        )
        self.add(self.panel)

    def construct(self):
        text = Text("text", font_size=96)

        def text_updater(old_text):
            assert(isinstance(old_text, Text))
            new_text = Text(self.textbox.get_value(), size=old_text.size)
            # new_text.align_data_and_family(old_text)
            new_text.move_to(old_text)
            if self.checkbox.get_value():
                new_text.set_fill(
                    color=self.color_picker.get_picked_color(),
                    opacity=self.color_picker.get_picked_opacity()
                )
            else:
                new_text.set_opacity(0)
            old_text.become(new_text)

        text.add_updater(text_updater)

        self.add(MotionMobject(text))

        self.textbox.set_value("Manim")
        # self.wait(60)
        # self.embed()
```

**Error**:

> Traceback (most recent call last):
  File "C:\Users\mukun\Desktop\Projects\MathAnime\manimPY39\Scripts\manimgl-script.py", line 33, in <module>
    sys.exit(load_entry_point('manimgl', 'console_scripts', 'manimgl')())
  File "c:\users\mukun\desktop\projects\mathanime\manim\manimlib\__main__.py", line 17, in main
    scene.run()
  File "c:\users\mukun\desktop\projects\mathanime\manim\manimlib\scene\scene.py", line 75, in run
    self.construct()
  File "example_scenes.py", line 665, in construct
    text.add_updater(text_updater)
  File "c:\users\mukun\desktop\projects\mathanime\manim\manimlib\mobject\mobject.py", line 507, in add_updater
    self.update(dt=0)
  File "c:\users\mukun\desktop\projects\mathanime\manim\manimlib\mobject\mobject.py", line 476, in update
    updater(self)
  File "example_scenes.py", line 653, in text_updater
    new_text = Text(self.textbox.get_value(), size=old_text.size)
  File "c:\users\mukun\desktop\projects\mathanime\manim\manimlib\mobject\svg\text_mobject.py", line 69, in __init__
    if text.find('\t') != -1:
AttributeError: 'numpy.ndarray' object has no attribute 'find'

### Environment
**OS System**:  Windows 10
**manim version**: Latest
**python version**: 3.9.7
**numpy version**: 1.21.2

**Comment by MukunthAG** [comment]
After searching for a while I found at that the error starts to appear only after this commit 6d7289338234acc6658b9377c0f0084aa1fa7119 , It was working fine until the previous commit 40290ada8343f10901fa9151cbdf84689667786d
