### ISSUE TITLE
"name 'Scene' is not defined" error when trying to run the manim tests scenes.

### ISSUE THREAD

**Issue by Arildo299** [3b1b/manim#1665]
when typing

"manim teste.py TestScene -pl"

it gives me this error

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\Scripts\manim-script.py", line 33, in <module>
    sys.exit(load_entry_point('manimlib==0.2.0', 'console_scripts', 'manim')())
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\manimlib\__init__.py", line 9, in main
    config = manimlib.config.get_configuration(args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\manimlib\config.py", line 155, in get_configuration
    module = get_module(args.file)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\manimlib\config.py", line 150, in get_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\user\Desktop\teste.py", line 1, in <module>
    class TestScene(Scene):
NameError: name 'Scene' is not defined

it is my second day of attempts, I'm on windows 10, everything else is installed correctly

**Comment by TonyCrane** [comment]
Please update your manim source code.
If you are using cairo-backend version, it is not recommended to use `manim` command, use `python manim.py` instead.
If you are using community version, please uninstall manimlib, which has the same command `manim`.

**Comment by Arildo299** [comment]
How do I update the manim source code? I have to download it from pip?

**Comment by Acpear** [comment]
It is recommend to download the source code by clicking the button "Code" ->"Download ZIP". After downloading it to your local disk, you are suggested to (OS: Windows)enter the directory where the ZIP downloaded and decompress it. Go into that decompressed folder, press key "Shift" and right click your mouse in empty area, then you can release "Shift". It should show a new button where you have access to command line. By clicking it, you opened the CMD (or, PowerShell), type the script "pip install -e .". Wish you success!
