### ISSUE TITLE
get_directories()["pi_creature_images"], KeyError: 'pi_creature_images'

### ISSUE THREAD

**Issue by Alimjoo** [3b1b/manim#1671]
### Describe the error
When I tring to render the codes in github/3b1b/vides, it git me a error called `get_directories()["pi_creature_images"], KeyError: 'pi_creature_images'`, what does this mean? Is that means I should create a directory called `pi_creature_images` and put it some where? Where I should put it ?

### Code and Error
**Code**:
```
Traceback (most recent call last):
  File "/Users/pi/Desktop/videos/custom/characters/pi_creature.py", line 58, in __init__
    get_directories()["pi_creature_images"],
KeyError: 'pi_creature_images'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/manimgl", line 33, in <module>
    sys.exit(load_entry_point('manimgl', 'console_scripts', 'manimgl')())
  File "/Users/pi/Desktop/manim/manimlib/__main__.py", line 25, in main
    scene.run()
  File "/Users/pi/Desktop/manim/manimlib/scene/scene.py", line 74, in run
    self.setup()
  File "/Users/pi/Desktop/videos/custom/characters/pi_creature_scene.py", line 42, in setup
    self.pi_creatures = VGroup(*self.create_pi_creatures())
  File "/Users/pi/Desktop/videos/custom/characters/pi_creature_scene.py", line 51, in create_pi_creatures
    return VGroup(self.create_pi_creature())
  File "/Users/pi/Desktop/videos/custom/characters/pi_creature_scene.py", line 54, in create_pi_creature
    pi_creature = PiCreature(**self.default_pi_creature_kwargs)
  File "/Users/pi/Desktop/videos/custom/characters/pi_creature.py", line 67, in __init__
    get_directories()["pi_creature_images"],
KeyError: 'pi_creature_images'
```

**Error**:
  get_directories()["pi_creature_images"],
KeyError: 'pi_creature_images'

### Environment
**OS System**:  macOS
**manim version**: I am using the latest manim
**python version**: 3.9

**Comment by voidguy** [comment]
how did you solve this?
