### ISSUE TITLE
I have been trying to install and run Manim on my Mac and the test scene hasn't been running if anyone could help I would really appreciate it

### ISSUE THREAD

**Issue by MariamElkholey** [3b1b/manim#1681]
Last login: Sun Nov 14 23:09:38 on ttys000
[3] 16948
(base) mariamelkholey@macbook-pro ~ % manimgl example_scenes.py OpeningManimExample

Traceback (most recent call last):
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/darwin.py", line 35, in GL
    return ctypesloader.loadLibrary(
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/ctypesloader.py", line 36, in loadLibrary
    return _loadLibraryWindows(dllType, name, mode)
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/ctypesloader.py", line 89, in _loadLibraryWindows
    return dllType( name, mode )
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/ctypes/__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ("dlopen(OpenGL, 0x000A): tried: '/Users/mariamelkholey/opt/anaconda3/lib/OpenGL' (no such file), '/Users/mariamelkholey/opt/anaconda3/lib/OpenGL' (no such file), '/Users/mariamelkholey/opt/anaconda3/lib/python3.8/lib-dynload/../../OpenGL' (no such file), '/Users/mariamelkholey/opt/anaconda3/lib/OpenGL' (no such file), '/Users/mariamelkholey/opt/anaconda3/bin/../lib/OpenGL' (no such file), 'OpenGL' (no such file), '/usr/local/lib/OpenGL' (no such file), '/usr/lib/OpenGL' (no such file), '/Users/mariamelkholey/OpenGL' (no such file), '/usr/local/lib/OpenGL' (no such file), '/usr/lib/OpenGL' (no such file)", 'OpenGL', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mariamelkholey/opt/anaconda3/bin/manimgl", line 5, in <module>
    from manimlib.__main__ import main
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/manimlib/__init__.py", line 21, in <module>
    from manimlib.camera.camera import *
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/manimlib/camera/camera.py", line 3, in <module>
    import OpenGL.GL as gl
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/__init__.py", line 36, in <module>
    _load()
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/__init__.py", line 33, in _load
    plugin.install(globals())
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 97, in install
    namespace[ name ] = getattr(self,name,None)
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/darwin.py", line 62, in GetCurrentContext
    return self.CGL.CGLGetCurrentContext 
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/darwin.py", line 45, in CGL
    def CGL(self): return self.GL
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/darwin.py", line 41, in GL
    raise ImportError("Unable to load OpenGL library", *err.args)
ImportError: ('Unable to load OpenGL library', "dlopen(OpenGL, 0x000A): tried: '/Users/mariamelkholey/opt/anaconda3/lib/OpenGL' (no such file), '/Users/mariamelkholey/opt/anaconda3/lib/OpenGL' (no such file), '/Users/mariamelkholey/opt/anaconda3/lib/python3.8/lib-dynload/../../OpenGL' (no such file), '/Users/mariamelkholey/opt/anaconda3/lib/OpenGL' (no such file), '/Users/mariamelkholey/opt/anaconda3/bin/../lib/OpenGL' (no such file), 'OpenGL' (no such file), '/usr/local/lib/OpenGL' (no such file), '/usr/lib/OpenGL' (no such file), '/Users/mariamelkholey/OpenGL' (no such file), '/usr/local/lib/OpenGL' (no such file), '/usr/lib/OpenGL' (no such file)", 'OpenGL', None)
(base) mariamelkholey@macbook-pro ~ % pip3 install colour
Requirement already satisfied: colour in ./opt/anaconda3/lib/python3.8/site-packages (0.1.5)
(base) mariamelkholey@macbook-pro ~ % python3 -m manim example_scenes.py SquareToCircle -pl
Manim Community v0.12.0

/Users/mariamelkholey/opt/anaconda3/lib/python3.8/runpy.py:127: RuntimeWarning: 'manim.__main__' found in sys.modules after import of package 'manim', but prior to execution of 'manim.__main__'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Manim Community v0.12.0

Usage: __main__.py render [OPTIONS] FILE [SCENE_NAMES]...
Try '__main__.py render --help' for help.

Error: no such option: -l
(base) mariamelkholey@macbook-pro ~ % python3 -m manim example_scenes.py SquareToCircle -pqm
Manim Community v0.12.0

/Users/mariamelkholey/opt/anaconda3/lib/python3.8/runpy.py:127: RuntimeWarning: 'manim.__main__' found in sys.modules after import of package 'manim', but prior to execution of 'manim.__main__'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Manim Community v0.12.0

Traceback (most recent call last):
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/manim/__main__.py", line 51, in <module>
    main()
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/manim/cli/render/commands.py", line 136, in render
    for SceneClass in scene_classes_from_file(file):
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/manim/utils/module_ops.py", line 125, in scene_classes_from_file
    module = get_module(file_path)
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/manim/utils/module_ops.py", line 53, in get_module
    raise FileNotFoundError(f"{file_name} not found")
FileNotFoundError: /Users/mariamelkholey/example_scenes.py not found
(base) mariamelkholey@macbook-pro ~ % cd manim
(base) mariamelkholey@macbook-pro manim % manimgl example_scenes.py OpeningManimExample
Traceback (most recent call last):
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/darwin.py", line 35, in GL
    return ctypesloader.loadLibrary(
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/ctypesloader.py", line 36, in loadLibrary
    return _loadLibraryWindows(dllType, name, mode)
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/ctypesloader.py", line 89, in _loadLibraryWindows
    return dllType( name, mode )
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/ctypes/__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ("dlopen(OpenGL, 0x000A): tried: '/Users/mariamelkholey/opt/anaconda3/lib/OpenGL' (no such file), '/Users/mariamelkholey/opt/anaconda3/lib/OpenGL' (no such file), '/Users/mariamelkholey/opt/anaconda3/lib/python3.8/lib-dynload/../../OpenGL' (no such file), '/Users/mariamelkholey/opt/anaconda3/lib/OpenGL' (no such file), '/Users/mariamelkholey/opt/anaconda3/bin/../lib/OpenGL' (no such file), 'OpenGL' (no such file), '/usr/local/lib/OpenGL' (no such file), '/usr/lib/OpenGL' (no such file), '/Users/mariamelkholey/manim/OpenGL' (no such file), '/usr/local/lib/OpenGL' (no such file), '/usr/lib/OpenGL' (no such file)", 'OpenGL', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mariamelkholey/opt/anaconda3/bin/manimgl", line 5, in <module>
    from manimlib.__main__ import main
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/manimlib/__init__.py", line 21, in <module>
    from manimlib.camera.camera import *
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/manimlib/camera/camera.py", line 3, in <module>
    import OpenGL.GL as gl
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/__init__.py", line 36, in <module>
    _load()
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/__init__.py", line 33, in _load
    plugin.install(globals())
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 97, in install
    namespace[ name ] = getattr(self,name,None)
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/darwin.py", line 62, in GetCurrentContext
    return self.CGL.CGLGetCurrentContext 
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/darwin.py", line 45, in CGL
    def CGL(self): return self.GL
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/darwin.py", line 41, in GL
    raise ImportError("Unable to load OpenGL library", *err.args)
ImportError: ('Unable to load OpenGL library', "dlopen(OpenGL, 0x000A): tried: '/Users/mariamelkholey/opt/anaconda3/lib/OpenGL' (no such file), '/Users/mariamelkholey/opt/anaconda3/lib/OpenGL' (no such file), '/Users/mariamelkholey/opt/anaconda3/lib/python3.8/lib-dynload/../../OpenGL' (no such file), '/Users/mariamelkholey/opt/anaconda3/lib/OpenGL' (no such file), '/Users/mariamelkholey/opt/anaconda3/bin/../lib/OpenGL' (no such file), 'OpenGL' (no such file), '/usr/local/lib/OpenGL' (no such file), '/usr/lib/OpenGL' (no such file), '/Users/mariamelkholey/manim/OpenGL' (no such file), '/usr/local/lib/OpenGL' (no such file), '/usr/lib/OpenGL' (no such file)", 'OpenGL', None)
(base) mariamelkholey@macbook-pro manim % manimgl example_scenes.py OpeningManimExample -p
Traceback (most recent call last):
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/darwin.py", line 35, in GL
    return ctypesloader.loadLibrary(
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/ctypesloader.py", line 36, in loadLibrary
    return _loadLibraryWindows(dllType, name, mode)
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/ctypesloader.py", line 89, in _loadLibraryWindows
    return dllType( name, mode )
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/ctypes/__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ("dlopen(OpenGL, 0x000A): tried: '/Users/mariamelkholey/opt/anaconda3/lib/OpenGL' (no such file), '/Users/mariamelkholey/opt/anaconda3/lib/OpenGL' (no such file), '/Users/mariamelkholey/opt/anaconda3/lib/python3.8/lib-dynload/../../OpenGL' (no such file), '/Users/mariamelkholey/opt/anaconda3/lib/OpenGL' (no such file), '/Users/mariamelkholey/opt/anaconda3/bin/../lib/OpenGL' (no such file), 'OpenGL' (no such file), '/usr/local/lib/OpenGL' (no such file), '/usr/lib/OpenGL' (no such file), '/Users/mariamelkholey/manim/OpenGL' (no such file), '/usr/local/lib/OpenGL' (no such file), '/usr/lib/OpenGL' (no such file)", 'OpenGL', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mariamelkholey/opt/anaconda3/bin/manimgl", line 5, in <module>
    from manimlib.__main__ import main
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/manimlib/__init__.py", line 21, in <module>
    from manimlib.camera.camera import *
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/manimlib/camera/camera.py", line 3, in <module>
    import OpenGL.GL as gl
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/__init__.py", line 36, in <module>
    _load()
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/__init__.py", line 33, in _load
    plugin.install(globals())
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 97, in install
    namespace[ name ] = getattr(self,name,None)
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/darwin.py", line 62, in GetCurrentContext
    return self.CGL.CGLGetCurrentContext 
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/darwin.py", line 45, in CGL
    def CGL(self): return self.GL
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Users/mariamelkholey/opt/anaconda3/lib/python3.8/site-packages/OpenGL/platform/darwin.py", line 41, in GL
    raise ImportError("Unable to load OpenGL library", *err.args)
ImportError: ('Unable to load OpenGL library', "dlopen(OpenGL, 0x000A): tried: '/Users/mariamelkholey/opt/anaconda3/lib/OpenGL' (no such file), '/Users/mariamelkholey/opt/anaconda3/lib/OpenGL' (no such file), '/Users/mariamelkholey/opt/anaconda3/lib/python3.8/lib-dynload/../../OpenGL' (no such file), '/Users/mariamelkholey/opt/anaconda3/lib/OpenGL' (no such file), '/Users/mariamelkholey/opt/anaconda3/bin/../lib/OpenGL' (no such file), 'OpenGL' (no such file), '/usr/local/lib/OpenGL' (no such file), '/usr/lib/OpenGL' (no such file), '/Users/mariamelkholey/manim/OpenGL' (no such file), '/usr/local/lib/OpenGL' (no such file), '/usr/lib/OpenGL' (no such file)", 'OpenGL', None)

that's all the code 
*note I am a beginner to coding so I might have some issues 
*note I was trying to run the test scene with anaconda and it did run but since then nothing happened any help would be appreciated

**Comment by TonyCrane** [comment]
See https://github.com/3b1b/manim/pull/1366#issuecomment-777313160.
