### ISSUE TITLE
ValueError: invalid literal for int() with base 16: ''

### ISSUE THREAD

**Issue by longlongvip** [3b1b/manim#1692]
### Describe the error
run manimgl example_scenes.py OpeningManimExample
get ValueError: invalid literal for int() with base 16: ''

### Code and Error
**Code**:
manimgl example_scenes.py OpeningManimExample

**Error**:
E:\ManimProject\manim>manimgl example_scenes.py OpeningManimExample
Traceback (most recent call last):
  File "D:\Python39\Scripts\manimgl-script.py", line 33, in <module>
    sys.exit(load_entry_point('manimgl', 'console_scripts', 'manimgl')())
  File "e:\manimproject\manim\manimlib\__main__.py", line 17, in main
    scene.run()
  File "e:\manimproject\manim\manimlib\scene\scene.py", line 75, in run
    self.construct()
  File "example_scenes.py", line 29, in construct
    IntegerMatrix(matrix, include_background_rectangle=True),
  File "e:\manimproject\manim\manimlib\mobject\matrix.py", line 88, in __init__
    self.add_background_rectangle()
  File "e:\manimproject\manim\manimlib\mobject\mobject.py", line 970, in add_background_rectangle
    self.background_rectangle = BackgroundRectangle(
  File "e:\manimproject\manim\manimlib\mobject\shape_matchers.py", line 36, in __init__
    SurroundingRectangle.__init__(self, mobject, color=color, **kwargs)
  File "e:\manimproject\manim\manimlib\mobject\shape_matchers.py", line 21, in __init__
    Rectangle.__init__(self, **kwargs)
  File "e:\manimproject\manim\manimlib\mobject\geometry.py", line 833, in __init__
    Polygon.__init__(self, UR, UL, DL, DR, **kwargs)
  File "e:\manimproject\manim\manimlib\mobject\geometry.py", line 716, in __init__
    super().__init__(**kwargs)
  File "e:\manimproject\manim\manimlib\mobject\types\vectorized_mobject.py", line 77, in __init__
    super().__init__(**kwargs)
  File "e:\manimproject\manim\manimlib\mobject\mobject.py", line 76, in __init__
    self.init_colors()
  File "e:\manimproject\manim\manimlib\mobject\types\vectorized_mobject.py", line 95, in init_colors
    self.set_fill(
  File "e:\manimproject\manim\manimlib\mobject\types\vectorized_mobject.py", line 120, in set_fill
    self.set_rgba_array_by_color(color, opacity, 'fill_rgba', recurse)
  File "e:\manimproject\manim\manimlib\mobject\mobject.py", line 879, in set_rgba_array_by_color
    rgbs = np.array([color_to_rgb(c) for c in listify(color)])
  File "e:\manimproject\manim\manimlib\mobject\mobject.py", line 879, in <listcomp>
    rgbs = np.array([color_to_rgb(c) for c in listify(color)])
  File "e:\manimproject\manim\manimlib\utils\color.py", line 16, in color_to_rgb
    return hex_to_rgb(color)
  File "e:\manimproject\manim\manimlib\utils\color.py", line 50, in hex_to_rgb
    return np.array([
  File "e:\manimproject\manim\manimlib\utils\color.py", line 51, in <listcomp>
    int(hex_part[i:i + 2], 16) / 255
ValueError: invalid literal for int() with base 16: ''

### Environment
**OS System**: Windows 10
**manim version**: master maybe before, I used it in 2021.08.
**python version**:3.9.6

**Comment by TonyCrane** [comment]
Have you ever set background color in the config files? If so, please show me that.
> Or maybe try updating your manimgl is a good choice?

**Comment by longlongvip** [comment]
I solve it by re-install manimgl
