### ISSUE TITLE
i have install all required packages for mainm and its sucessfully installed but is shows me allways that file not found what should i do ?

### ISSUE THREAD

**Issue by Pekkahu** [3b1b/manim#1699]
C:\Users\Owner>manim -pql scene.py CreateCircle
Manim Community v0.13.1

Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\tools\Manim\Scripts\manim.exe\__main__.py", line 7, in <module>
  File "C:\tools\Manim\Lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\tools\Manim\Lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\tools\Manim\Lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\tools\Manim\Lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\tools\Manim\Lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\tools\Manim\Lib\site-packages\manim\cli\render\commands.py", line 136, in render
    for SceneClass in scene_classes_from_file(file):
  File "C:\tools\Manim\Lib\site-packages\manim\utils\module_ops.py", line 125, in scene_classes_from_file
    module = get_module(file_path)
  File "C:\tools\Manim\Lib\site-packages\manim\utils\module_ops.py", line 53, in get_module
    raise FileNotFoundError(f"{file_name} not found")
FileNotFoundError: C:\Users\Owner\scene.py not found

**Comment by TonyCrane** [comment]
You are using the community version of manim, so you'd better ask this question on their discord channel or open an issue in ManimCommunity/manim.
