### ISSUE TITLE
UserWarning: g0-72 not recognized + Index out of range 

### ISSUE THREAD

**Issue by jyrg02** [3b1b/manim#1743]
### Describe the error
 I am trying to get a preview using the TestScene command.

### Code and Error
**Code**:

from manimlib.imports import*

class TestScene(Scene):
  def construct(self):
    t = TextMobject("Hello manim!")
    t.scale(2)

    self.play(Write(t))
    `self.wait()`

**Error**:

C:\Users\username\Downloads>manim test.py TestScene -p
Media will be written to C:\Users\username\Downloads\media\. You can change this behavior with the --media_dir flag.
Writing "\centering Hello manim!" to C:\Users\username\Downloads\media\Tex\5d48734699112c17.tex
C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-72 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-101 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-108 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-111 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-109 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-97 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-110 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-105 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-33 not recognized
  warnings.warn("%s not recognized" % ref)
Writing "Hello manim!" to C:\Users\username\Downloads\media\Tex\6b3bd74ad7213701.tex

Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\manimlib\scene\scene.py", line 75, in __init__
    self.construct()
  File "C:\Users\username\Downloads\test.py", line 5, in construct
    t = TextMobject("Hello manim!")
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\manimlib\mobject\svg\tex_mobject.py", line 150, in __init__
    self.break_up_by_substrings()
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\manimlib\mobject\svg\tex_mobject.py", line 190, in break_up_by_substrings
    sub_tex_mob.move_to(self.submobjects[last_submob_index], RIGHT)
IndexError: list index out of range

### Environment
**OS System**: 
**manim version**: master 
**python version**:

**Comment by TonyCrane** [comment]
`manim version: master` ? I don't think so.
I noticed that you use `from manimlib.imports import *` to import and used `TextMobject`, so I guess you are using the cairo-backend branch version of manim.
But this issue may cause by your LaTeX, maybe try reinstall it?
