### ISSUE TITLE
StreamLines Broadcast Input Error When Using ColorMap

### ISSUE THREAD

**Issue by seyisulu** [3b1b/manim#1786]
### Describe the bug

There is an error when I try to render streamlines using a magnitude dependent color map with `manimgl`.

However, it renders the streamlines with a single color if I set `color_by_magnitude=False`.

**Code**:

```

from manimlib import *

class Streaming(Scene): 
    def construct(self):
        fun = lambda x, y: np.sin(x/2) * UR + np.cos(y/2) * LEFT
        sls = StreamLines(
            fun, 
            NumberPlane(),
            step_multiple=0.5,
            stroke_width=4,
            stroke_color=LIGHT_PINK,
            color_by_magnitude=True,
            magnitude_range=(0,2.0),
        )
        asl = AnimatedStreamLines(
            sls,
            line_anim_class=ShowPassingFlash,
        )
        self.add(asl)
        self.wait(4)
```

 **Error**

```

ValueError: could not broadcast input array from shape (30,3,30,3) into shape (30,3)

```

**Wrong display or Error traceback**:

```

Traceback (most recent call last):
  File "C:\Python310\Scripts\manimgl-script.py", line 33, in <module>
    sys.exit(load_entry_point('manimgl', 'console_scripts', 'manimgl')())
  File "c:\users\paperspace\documents\code\manimgl\manimlib\__main__.py", line 25, in main
    scene.run()
  File "c:\users\paperspace\documents\code\manimgl\manimlib\scene\scene.py", line 91, in run
    self.construct()
  File "C:\Users\paperspace\Documents\Code\manimgl\Streaming.py", line 6, in construct
    sls = StreamLines(
  File "c:\users\paperspace\documents\code\manimgl\manimlib\mobject\vector_field.py", line 207, in __init__
    self.init_style()
  File "c:\users\paperspace\documents\code\manimgl\manimlib\mobject\vector_field.py", line 268, in init_style
    rgbas[:, :3] = rgbs
ValueError: could not broadcast input array from shape (30,3,30,3) into shape (30,3)

```

**Comment by seyisulu** [comment]
I'm open to creating a fix if anyone can point me in the right direction...

**Comment by TonyCrane** [comment]
Oh, that's a bug caused by https://github.com/3b1b/manim/commit/bf2d9edfe67c7e63ac0107d1d713df7ae7c3fb8f

That commit in #1764 changed the behavior of `interpolate` for `alpha` in ndarray form.

So there is a temporary fix to your problem:
```diff
--- a/manimlib/mobject/vector_field.py
+++ b/manimlib/mobject/vector_field.py
@@ -47,7 +47,7 @@ def get_vectorized_rgb_gradient_function(
         next_indices = np.clip(indices + 1, 0, len(rgbs) - 1)
         inter_alphas = scaled_alphas % 1
         inter_alphas = inter_alphas.repeat(3).reshape((len(indices), 3))
-        result = interpolate(rgbs[indices], rgbs[next_indices], inter_alphas)
+        result = (1 - inter_alphas) * rgbs[indices] + inter_alphas * rgbs[next_indices]
         return result
     return func
```

But I wonder whether we need another new function to use the old behavior of `interpolate` and check which `interpolate` in manim needs to use the old behavior (such as this). @3b1b

**Comment by 3b1b** [comment]
This does highlight how that commit was a bit hasty.

I think rather than going back to the old behavior, or having two distinct functions, interpolate can be fixed to just have better default behavior and options. I'll look into it.
