### ISSUE TITLE
Type Error when using in cmd

### ISSUE THREAD

**Issue by qixiao1224** [3b1b/manim#1803]
### Describe the error
after installation this type error happens

### Code and Error
**Code**:
when I use manimgl in cmd, it happens

**Error**:

Traceback (most recent call last):
  File "D:\anaconda\envs\manim\Scripts\manimgl-script.py", line 33, in <module>
    sys.exit(load_entry_point('manimgl', 'console_scripts', 'manimgl')())
  File "D:\anaconda\envs\manim\Scripts\manimgl-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "D:\anaconda\envs\manim\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "D:\anaconda\envs\manim\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\zqx98\manim\manimlib\__init__.py", line 55, in <module>
    from manimlib.scene.interactive_scene import *
  File "c:\users\zqx98\manim\manimlib\scene\interactive_scene.py", line 41, in <module>
    class InteractiveScene(Scene):
  File "c:\users\zqx98\manim\manimlib\scene\interactive_scene.py", line 153, in InteractiveScene
    def get_selection_search_set(self) -> list[Mobject]:
TypeError: 'type' object is not subscriptable
### Environment
**OS System**: 
**manim version**: master 
**python version**:

**Comment by Freshman101** [comment]
Hello, can u hear me? I want to know how did you solve this problem! Please help me.

**Comment by TonyCrane** [comment]
#1804 fixed this. Sorry, we just lost a `from __future__ import annotations`.

**Comment by Freshman101** [comment]
HHHHA,OK,thanks for your reply.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月13日(星期五) 上午8:15
收件人: "3b1b/manim";
抄送: "Comment";
主题: Re: [3b1b/manim] Type Error when using in cmd (Issue #1803)





 
#1804 fixed this. Sorry, we just lost a from __future__ import annotations.
 
&mdash;
