### ISSUE TITLE
Could anyone tell me what's wrong?

### ISSUE THREAD

**Issue by Dovuq** [3b1b/manim#1806]
```
~\manim>manimgl example_scenes.py OpeningManimExample
Traceback (most recent call last):
  File "O:\Program Files\Python\Scripts\manimgl-script.py", line 33, in <module>
    sys.exit(load_entry_point('manimgl', 'console_scripts', 'manimgl')())
  File "O:\Program Files\Python\Scripts\manimgl-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "o:\program files\python\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "o:\program files\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'manimlib.__main__'
```

**Comment by TonyCrane** [comment]
please check out whether you have installed `manimlib` through pip. If you have installed it, please `pip uninstall manimlib`.

**Comment by Dovuq** [comment]
Problem solved. Thanks
