### ISSUE TITLE
How to solve "TypeError: 'type' object is not subscriptable"?

### ISSUE THREAD

**Issue by Freshman101** [3b1b/manim#1810]
### Describe the error
Emm, to be honest, I just wanted to run the example code, but failed.

### Code and Error
Here is my input:  "**manimgl example_scenes.py SquareToCircle -pl**"

**Error**:
(manim) 
Traceback (most recent call last):
  File "D:\anaconda3\envs\manim\Scripts\manimgl-script.py", line 33, in <module>
    sys.exit(load_entry_point('manimgl', 'console_scripts', 'manimgl')())
  File "D:\anaconda3\envs\manim\Scripts\manimgl-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "D:\anaconda3\envs\manim\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "D:\anaconda3\envs\manim\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "f:\manim-master\manimlib\__init__.py", line 55, in <module>
    from manimlib.scene.interactive_scene import *
  File "f:\manim-master\manimlib\scene\interactive_scene.py", line 41, in <module>
    class InteractiveScene(Scene):
  File "f:\manim-master\manimlib\scene\interactive_scene.py", line 153, in InteractiveScene
    def get_selection_search_set(self) -> list[Mobject]:
TypeError: 'type' object is not subscriptable

### Environment
**OS System**: Windows10+Anaconda3
**manim version**: The latest version
**python version**:3.8.13

**Comment by Freshman101** [comment]
OK, this problem has been solved accidentally. But I find another problem  --  my computer counldn't draw the "x and y" axis, I will try to fix it.
