### ISSUE TITLE
Error on WSL 2

### ISSUE THREAD

**Issue by SheryConcepts** [3b1b/manim#1812]
### Describe the error

its my first time with manim. I use WSL and after setting it up and running with this command
manimgl start.py SquareToCirlce
directory fo start.py is manimlib
i suspect its Xserver issue, I am using GWSL
 gives below error
### Code and Error
**Code**:
from manimlib import *

class SquareToCircle(Scene):
     def construct(self):
           circle = Circle()
           circle.set_fill(BLUE, opacity=0.5)
            circle.set_stroke(BLUE_E, width=4)

            self.add(circle)

**Error**:

Traceback (most recent call last):
  File "/home/shery/.local/bin/manimgl", line 5, in <module>
    from manimlib.__main__ import main
  File "/home/shery/.local/lib/python3.8/site-packages/manimlib/__init__.py", line 23, in <module>
    from manimlib.window import *
  File "/home/shery/.local/lib/python3.8/site-packages/manimlib/window.py", line 5, in <module>
    from moderngl_window.context.pyglet.window import Window as PygletWindow
  File "/home/shery/.local/lib/python3.8/site-packages/moderngl_window/context/pyglet/__init__.py", line 1, in <module>
    from .keys import Keys  # noqa
  File "/home/shery/.local/lib/python3.8/site-packages/moderngl_window/context/pyglet/keys.py", line 12, in <module>
    from pyglet.window import key
  File "/home/shery/.local/lib/python3.8/site-packages/pyglet/window/__init__.py", line 1918, in <module>
    gl._create_shadow_window()
  File "/home/shery/.local/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 206, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home/shery/.local/lib/python3.8/site-packages/pyglet/window/xlib/__init__.py", line 171, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/shery/.local/lib/python3.8/site-packages/pyglet/window/__init__.py", line 590, in __init__
    display = pyglet.canvas.get_display()
  File "/home/shery/.local/lib/python3.8/site-packages/pyglet/canvas/__init__.py", line 94, in get_display
    return Display()
  File "/home/shery/.local/lib/python3.8/site-packages/pyglet/canvas/xlib.py", line 123, in __init__
    raise NoSuchDisplayException('Cannot connect to "%s"' % name)
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"
### Environment
**OS System**:  Windows Subsystem For linux version 2
**manim version**: master 
**python version**: 2.7.18

**Comment by Yupjun** [comment]
Does this problem also occur in python3?

**Comment by SheryConcepts** [comment]
> Does this problem also occur in python3?

yes, with python 3.8

**Comment by BirajAd** [comment]
Any update on this one yet? I am having the same issue
