### ISSUE TITLE
LaTeX rendering error

### ISSUE THREAD

**Issue by MrHeavythree** [3b1b/manim#1817]
# LaTeX rendering error

#### Description error

I admit that this is my third issue on this issue, but the old method has failed and there is nothing I can do about it.
I tried to modify it according to the method on https://github.com/3b1b/manim/issues/1606.I modified default_config.yml, even reinstalled latex and manim, but it didn't seem to work.

#### Code
```py
from manimlib import *

class ExampleScene(Scene):
    def construct(self):
        text_1 = Tex("a^{2} + b^{2} = c^{2}")
        text_2 = Text("This is the Pythagorean theorem.").next_to(text_1,DOWN)
        vg_1 = VGroup(text_1,text_2)
        text_1 = Tex(r"\int_{a}^{b} f(x)\mathrm{d}x = F(b)-F(a)")
        text_2 = Text("And this is Newton-Leibniz formula.").next_to(text_1,DOWN)
        vg_2 = VGroup(text_1,text_2)
        
        self.add(vg_1)
        self.play(Transform(vg_1,vg_2))
        self.wait()
```
#### Error

```powershell
[21:33:51] ERROR    LaTeX Error!  Not a worry, it happens to the best of us.                             tex_file_writing.py:90Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 196, in _run_module_as_main      
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310-32\Scripts\manimgl.exe\__main__.py", line 7, in <module>  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310-32\lib\site-packages\manimlib\__main__.py", line 25, in 
main
    scene.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310-32\lib\site-packages\manimlib\scene\scene.py", line 91, 
in run
    self.construct()
  File "C:\manim-master\vscode\Example.py", line 5, in construct
    text_1 = Tex("a^{2} + b^{2} = c^{2}")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310-32\lib\site-packages\manimlib\mobject\svg\tex_mobject.py", line 188, in __init__
    super().__init__(full_string, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310-32\lib\site-packages\manimlib\mobject\svg\tex_mobject.py", line 45, in __init__
    super().__init__(**kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310-32\lib\site-packages\manimlib\mobject\svg\svg_mobject.py", line 65, in __init__
    self.init_svg_mobject()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310-32\lib\site-packages\manimlib\mobject\svg\svg_mobject.py", line 76, in init_svg_mobject
    self.generate_mobject()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310-32\lib\site-packages\manimlib\mobject\svg\svg_mobject.py", line 91, in generate_mobject
    file_path = self.get_file_path()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310-32\lib\site-packages\manimlib\mobject\svg\tex_mobject.py", line 66, in get_file_path
    file_path = tex_to_svg_file(full_tex)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310-32\lib\site-packages\manimlib\utils\tex_file_writing.py", line 52, in tex_to_svg_file
    tex_to_svg(tex_file_content, svg_file)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310-32\lib\site-packages\manimlib\utils\tex_file_writing.py", line 60, in tex_to_svg
    svg_file = dvi_to_svg(tex_to_dvi(tex_file))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310-32\lib\site-packages\manimlib\utils\tex_file_writing.py", line 91, in tex_to_dvi
    with open(log_file, "r", encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\Tex\\3479a416a94bb416.log'
```

**System: Windows**
**Manim version: ManimGL v.1.6.1**
**Python version: python 3.10**

**Comment by TonyCrane** [comment]
Please specify `temporary_storage` in the .yml file.
