### ISSUE TITLE
Error when I ran the simple script to self-write Hello Manim.

### ISSUE THREAD

**Issue by RandyPlayzMC** [3b1b/manim#1830]
### Describe the error
I am trying to make Manim self-write Hello Manim!
When I tried running it, it gave me an error saying Latex error converting to dvi. I am using Python 3.7.9 and am also using MikTex. Could someone please help me with this? I looked all over the issues page but I don't get what they're trying to do.
Thank you in advance
### Code and Error
**Code**:
manim random.py TestScene -pl

This is the code for the document random.py:
-----------------------------------------------------
from manimlib.imports import *

class TestScene(Scene):
  def construct(self):
    t = TextMobject("Hello manim!")
    t.scale(2)

    self.play(Write(t))
    self.wait()
-------------------------------------------------------
Everything that's inbetween the lines, not just the code box.
The code in .............tex:
-------------------------------------------------------
\documentclass[preview]{standalone}

\usepackage[english]{babel}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{dsfont}
\usepackage{setspace}
\usepackage{tipa}
\usepackage{relsize}
\usepackage{textcomp}
\usepackage{mathrsfs}
\usepackage{calligra}
\usepackage{wasysym}
\usepackage{ragged2e}
\usepackage{physics}
\usepackage{xcolor}
\usepackage{microtype}
\DisableLigatures{encoding = *, family = * }
%\usepackage[UTF8]{ctex}
\linespread{1}

\begin{document}

\centering Hello manim!

\end{document}
----------------------------------
**Error**:
Media will be written to C:\Users\maste\OneDrive\Desktop\media\. You can change this behavior with the --media_dir flag.
'latex' is not recognized as an internal or external command,
operable program or batch file.

Traceback (most recent call last):
  File "C:\Users\maste\AppData\Local\Programs\Python\Python37\lib\site-packages\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\Users\maste\AppData\Local\Programs\Python\Python37\lib\site-packages\manimlib\scene\scene.py", line 75, in __init__
    self.construct()
  File "random.py", line 5, in construct
    t = TextMobject("Hello manim!")
  File "C:\Users\maste\AppData\Local\Programs\Python\Python37\lib\site-packages\manimlib\mobject\svg\tex_mobject.py", line 148, in __init__
    self, self.arg_separator.join(tex_strings), **kwargs
  File "C:\Users\maste\AppData\Local\Programs\Python\Python37\lib\site-packages\manimlib\mobject\svg\tex_mobject.py", line 44, in __init__
    self.template_tex_file_body
  File "C:\Users\maste\AppData\Local\Programs\Python\Python37\lib\site-packages\manimlib\utils\tex_file_writing.py", line 21, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
  File "C:\Users\maste\AppData\Local\Programs\Python\Python37\lib\site-packages\manimlib\utils\tex_file_writing.py", line 72, in tex_to_dvi
    "See log output above or the log file: %s" % log_file)
Exception: Latex error converting to dvi. See log output above or the log file: C:/Users/maste/OneDrive/Desktop/media/Tex/5d48734699112c17.log

### Environment
**Windows 11**
**manim version**: manimlib 
**3.7.9**:

**Comment by yuhan2680** [comment]
You can change the
t = TextMobject("Hello manim!")
to:
t = Text("Hello manim!")

**Comment by RandyPlayzMC** [comment]
Thank you yuhan2680, I just started coding, so I don't really know how to fix anything, but thank you anyways!
