### ISSUE TITLE
LaTeX Error

### ISSUE THREAD

**Issue by bienaole417** [3b1b/manim#1839]
### Describe the error

I tried to compile a piece of code but it can't compile normally.

### Code and Error
**Code**:

from manimlib.imports import *
class MaThe(Scene):
    def construct(self):
        f = TextMobject("(a+b)^2")
        f.scale(2.5)
        s = TextMobject("aa+ab+ba+bb")
        s.scale(2.5)
        d = TextMobject("a^2+2ab+b^2")
        d.scale(2.5)
        self.play(Write(f))
        self.wait(1)
        self.play(Transform(f, s))
        self.wait(1)
        self.play(Transform(s, d))
        self.wait(3)

**Error**:

Traceback (most recent call last):
  File "D:\manim-cairo-backend\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "D:\manim-cairo-backend\manimlib\scene\scene.py", line 75, in __init__
    self.construct()
  File ".\1.py", line 4, in construct
    f = TextMobject("(a+b)^2")
  File "D:\manim-cairo-backend\manimlib\mobject\svg\tex_mobject.py", line 147, in __init__
    SingleStringTexMobject.__init__(
  File "D:\manim-cairo-backend\manimlib\mobject\svg\tex_mobject.py", line 42, in __init__
    file_name = tex_to_svg_file(
  File "D:\manim-cairo-backend\manimlib\utils\tex_file_writing.py", line 21, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
  File "D:\manim-cairo-backend\manimlib\utils\tex_file_writing.py", line 69, in tex_to_dvi
    raise Exception(
Exception: Xelatex error converting to xdv. See log output above or the log file: D:/manim-cairo-backend/media/Tex/8e86b33858e652cb.log

### Environment
**OS System**: Windows 11
**manim version**: manim-cairo-backend 
**python version**: 3.10.5

**Comment by CaftBotti** [comment]
See also #1876, #570, #623

**Comment by CaftBotti** [comment]
Hi bienaole417. If you are using Win + R and enter "cmd", please stop doing that and use Win and search cmd. Then it will write correctly.
