### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Junital** [3b1b/manim#1846]
**Hello! I get one problem.**

When I run `manimgl start.py SquareToCircle -o` , the git bash return the error below.

```
Traceback (most recent call last):
  File "D:\D\Anaconda\envs\math\Scripts\manimgl-script.py", line 33, in <module>
    sys.exit(load_entry_point('manimgl', 'console_scripts', 'manimgl')())
  File "d:\d\github\manim\manimlib\__main__.py", line 25, in main
    scene.run()
  File "d:\d\github\manim\manimlib\scene\scene.py", line 116, in run
    self.file_writer.begin()
  File "d:\d\github\manim\manimlib\scene\scene_file_writer.py", line 207, in begin
    self.open_movie_pipe(self.get_movie_file_path())
  File "d:\d\github\manim\manimlib\scene\scene_file_writer.py", line 266, in open_movie_pipe
    self.writing_process = sp.Popen(command, stdin=sp.PIPE)
  File "D:\D\Anaconda\envs\math\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\D\Anaconda\envs\math\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
```

Can I get some help, please?

**Comment by yusancky** [comment]
Hello. This may be because you did not install [FFmpeg](https://ffmpeg.org/), or you did not add it to PATH. 

https://www.wikihow.com/Install-FFmpeg-on-Windows

**Comment by boring180** [comment]
I'm a mac user, and I tried to install ffmpeg, and I checked it's version 6.1.1. But now it is still having the same error message.

**Comment by boring180** [comment]
I tried to modify the configuration file with output: "/Users/boring180/Downloads"(boring180 is my user name, and this should be on line 7). At the end of the day, the bug message changed to "Encoder not found" I guess this will be a tentative solution for this problem.
