### ISSUE TITLE
[BUG]Error when using NumberPlane

### ISSUE THREAD

**Issue by CaftBotti** [3b1b/manim#1854]
Hi everyone. I'm new of manim, now i have a problem.I tried to add a numberplane in the code, but it caused error.
(My python file name: a.py)
Code here:

```
class NumberPlaneExample(Scene):
    CONFIG = {
        "axis_config": {
            "stroke_color": WHITE,
            "stroke_width": 2,
            "include_ticks": False,
            "include_tip": False,
            "line_to_number_buff": SMALL_BUFF,
            "label_direction": DR,
            "number_scale_val": 0.5,
        },
        "y_axis_config": {
            "label_direction": DR,
        },
        "background_line_style": {
            "stroke_color": BLUE_D,
            "stroke_width": 2,
            "stroke_opacity": 1,
        },
        # Defaults to a faded version of line_config
        "faded_line_style": None,
        "x_line_frequency": 1,
        "y_line_frequency": 1,
        "faded_line_ratio": 1,
        "make_smooth_after_applying_functions": True,
    }
    def construct(self):
        number_plane = NumberPlane()
        self.add(number_plane)
```

It caused error like this:
```
Traceback (most recent call last):
  File "c:\beibi\a\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "c:\beibi\a\manimlib\scene\scene.py", line 75, in __init__
    self.construct()
  File "c:\beibi\a\a.py", line 1180, in construct
    ax = Axes().add_coordinates()
  File "c:\beibi\a\manimlib\mobject\coordinate_systems.py", line 201, in add_coordinates
    self.add(self.get_coordinate_labels(x_vals, y_vals, **kwargs))
  File "c:\beibi\a\manimlib\mobject\coordinate_systems.py", line 194, in get_coordinate_labels
    x_mobs = self.get_x_axis().get_number_mobjects(*x_vals, **kwargs)
  File "c:\beibi\a\manimlib\mobject\coordinate_systems.py", line 52, in get_x_axis
    return self.get_axis(0)
TypeError: **Axes.get_axis() missing 2 required positional arguments: 'max_val' and 'axis_config'**
```

Manim Community 0.16.0 post 0
python 3.10

I tried many solutions, but nothing worked. No one on the internet seems to have made the mistake.

If you can help me, thanks a lot!

**Comment by TonyCrane** [comment]
You are using the community version of manim, so please ask this question in their discord channel, or open an issue in ManimCommunity/manim, instead of here.
