### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by cxy81223** [3b1b/manim#1897]
Hello, I got a problem in using manim through Python 3.10 (windows11) .
When I run `manimgl example_scenes.py GraphExample -o`, it returns the error below.

```
Traceback (most recent call last):
  File "D:\apps\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\apps\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\apps\Python\Python310\Scripts\manimgl.exe\__main__.py", line 7, in <module>
  File "D:\apps\Python\Python310\lib\site-packages\manimlib\__main__.py", line 22, in main
    scenes = manimlib.extract_scene.main(config)
  File "D:\apps\Python\Python310\lib\site-packages\manimlib\extract_scene.py", line 140, in main
    scenes = get_scenes_to_render(all_scene_classes, scene_config, config)
  File "D:\apps\Python\Python310\lib\site-packages\manimlib\extract_scene.py", line 103, in get_scenes_to_render
    fw_config["total_frames"] = compute_total_frames(scene_class, scene_config)
  File "D:\apps\Python\Python310\lib\site-packages\manimlib\extract_scene.py", line 87, in compute_total_frames
    pre_scene.run()
  File "D:\apps\Python\Python310\lib\site-packages\manimlib\scene\scene.py", line 91, in run
    self.construct()
  File "D:\manim-master\example_scenes.py", line 446, in construct
    sin_label = axes.get_graph_label(sin_graph, "\\sin(x)")
  File "D:\apps\Python\Python310\lib\site-packages\manimlib\mobject\coordinate_systems.py", line 239, in get_graph_label
    label = Tex(label)
  File "D:\apps\Python\Python310\lib\site-packages\manimlib\mobject\svg\tex_mobject.py", line 188, in __init__
    super().__init__(full_string, **kwargs)
  File "D:\apps\Python\Python310\lib\site-packages\manimlib\mobject\svg\tex_mobject.py", line 45, in __init__
    super().__init__(**kwargs)
  File "D:\apps\Python\Python310\lib\site-packages\manimlib\mobject\svg\svg_mobject.py", line 65, in __init__
    self.init_svg_mobject()
  File "D:\apps\Python\Python310\lib\site-packages\manimlib\mobject\svg\svg_mobject.py", line 76, in init_svg_mobject
    self.generate_mobject()
  File "D:\apps\Python\Python310\lib\site-packages\manimlib\mobject\svg\svg_mobject.py", line 92, in generate_mobject
    element_tree = ET.parse(file_path)
  File "D:\apps\Python\Python310\lib\xml\etree\ElementTree.py", line 1224, in parse
    tree.parse(source, parser)
  File "D:\apps\Python\Python310\lib\xml\etree\ElementTree.py", line 569, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\TexTemp\\Tex\\42c962cc458aefe6.svg'
```

Is there anything wrong?

**Comment by cxy81223** [comment]
It also warned me `WARNING  Unsupported element type: <class 'svgelements.svgelements.Use'> svg_mobject.py:174` while running.

**Comment by maleonhard** [comment]
same problem

**Comment by TonyCrane** [comment]
> It also warned me `WARNING Unsupported element type: <class 'svgelements.svgelements.Use'> svg_mobject.py:174` while running.

See https://github.com/3b1b/manim/issues/1904#issuecomment-1364468069

**Comment by wqw547243068** [comment]
Same too, Mac
> FileNotFoundError: [Errno 2] No such file or directory: '.../animation/tmp/Tex/15c8bcfa14f11dd2.svg'

Tried #1904 , didn't work
