### ISSUE TITLE
Invalid color type Exception occured running ControlsExample in example_scenes.py

### ISSUE THREAD

**Issue by YalienY** [3b1b/manim#1920]
I ran the ControlsExample in example_scenes.py
```
manimgl .\example_scenes.py ControlsExample
```
and this Exception occured:
```
Traceback (most recent call last):
  File "E:\Anaconda\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Anaconda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Anaconda\Scripts\manimgl.exe\__main__.py", line 7, in <module>
  File "D:\programFiles\manim\manim\manimlib\__main__.py", line 25, in main
    scene.run()
  File "D:\programFiles\manim\manim\manimlib\scene\scene.py", line 118, in run
    self.setup()
  File ".\example_scenes.py", line 636, in setup
    self.color_picker = ColorSliders()
  File "D:\programFiles\manim\manim\manimlib\mobject\interactive.py", line 298, in __init__
    self.a_slider.slider.set_color_by_gradient([BLACK, WHITE])
  File "D:\programFiles\manim\manim\manimlib\mobject\mobject.py", line 1294, in set_color_by_gradient
    self.set_color(colors)
  File "D:\programFiles\manim\manim\manimlib\mobject\types\vectorized_mobject.py", line 271, in set_co
    self.set_fill(color, opacity=opacity, recurse=recurse)
  File "D:\programFiles\manim\manim\manimlib\mobject\types\vectorized_mobject.py", line 150, in set_fi
    self.set_rgba_array_by_color(color, opacity, 'fill_rgba', recurse)
  File "D:\programFiles\manim\manim\manimlib\mobject\mobject.py", line 1245, in set_rgba_array_by_colo
    rgbs = np.array([color_to_rgb(c) for c in listify(color)])
  File "D:\programFiles\manim\manim\manimlib\mobject\mobject.py", line 1245, in <listcomp>
    rgbs = np.array([color_to_rgb(c) for c in listify(color)])
  File "D:\programFiles\manim\manim\manimlib\utils\color.py", line 27, in color_to_rgb
    raise Exception("Invalid color type")
Exception: Invalid color type
```
it seems like `self.a_slider.slider.set_color_by_gradient([BLACK, WHITE])` didn't work right.

I debug the program and found that it sent paraments `colors` with value `(['#000000', '#FFFFFF'],)` to `self.set_color` ,  which caused the Expection. 

I believe it's a bug that need to be fixed.

**Comment by 3b1b** [comment]
Thanks, I believe this is fixed [here](https://github.com/3b1b/manim/pull/1979).
