### ISSUE TITLE
Running the example code works briefly and then generates a stack trace and exits

### ISSUE THREAD

**Issue by ocheret** [3b1b/manim#1936]
### Describe the error
Running the example code works briefly and then generates a stack trace and exits

### Code and Error
```
$ manimgl example_scenes.py OpeningManimExample
```

**Error**:
```
sh: latex: command not found{c}\quad \\\quad \\\end{array}\right]"
[09:38:08] ERROR    LaTeX Error!  Not a worry, it        tex_file_writing.py:112
                    happens to the best of us.                                  
Traceback (most recent call last):                                
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/manimgl", line 8, in <module>
    sys.exit(main())
  File "/Users/chuck/git/manim/manimlib/__main__.py", line 25, in main
    scene.run()
  File "/Users/chuck/git/manim/manimlib/scene/scene.py", line 131, in run
    self.construct()
  File "/Users/chuck/git/manim/example_scenes.py", line 29, in construct
    IntegerMatrix(matrix, include_background_rectangle=True),
  File "/Users/chuck/git/manim/manimlib/mobject/matrix.py", line 205, in __init__
    super().__init__(matrix, element_alignment_corner=element_alignment_corner, **kwargs)
  File "/Users/chuck/git/manim/manimlib/mobject/matrix.py", line 100, in __init__
    self.add_brackets(bracket_v_buff, bracket_h_buff)
  File "/Users/chuck/git/manim/manimlib/mobject/matrix.py", line 145, in add_brackets
    brackets = Tex("".join((
  File "/Users/chuck/git/manim/manimlib/mobject/svg/tex_mobject.py", line 208, in __init__
    super().__init__(full_string, **kwargs)
  File "/Users/chuck/git/manim/manimlib/mobject/svg/tex_mobject.py", line 58, in __init__
    super().__init__(
  File "/Users/chuck/git/manim/manimlib/mobject/svg/svg_mobject.py", line 72, in __init__
    self.init_svg_mobject()
  File "/Users/chuck/git/manim/manimlib/mobject/svg/svg_mobject.py", line 99, in init_svg_mobject
    self.generate_mobject()
  File "/Users/chuck/git/manim/manimlib/mobject/svg/svg_mobject.py", line 114, in generate_mobject
    file_path = self.get_file_path()
  File "/Users/chuck/git/manim/manimlib/mobject/svg/tex_mobject.py", line 87, in get_file_path
    file_path = tex_content_to_svg_file(
  File "/Users/chuck/git/manim/manimlib/utils/tex_file_writing.py", line 81, in tex_content_to_svg_file
    create_tex_svg(full_tex, svg_file, compiler)
  File "/Users/chuck/git/manim/manimlib/utils/tex_file_writing.py", line 115, in create_tex_svg
    with open(root + ".log", "r", encoding="utf-8") as log_file:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/3j/kxrrqr310jzd37rtx2cdf1zm0000gn/T/Tex/c3372cf5b2620435.log'
[Chucks-MBP:manim (master)]527$ ls -l /var/folders/3j/kxrrqr310jzd37rtx2cdf1zm0000gn/T/Tex/
total 8
-rw-r--r--  1 chuck  staff  625 Dec 19 09:38 c3372cf5b2620435.tex
```

### Environment
**MacOS Ventura 13.0**: 
**ManimGL v1.6.1**: master 
**Python 3.10.7**:

**Comment by ocheret** [comment]
The instructions for MacOS simple say to use 'brew install ffmpeg mactex'. This does not seem to make LaTeX available anywhere, which may be the issue. Perhaps this is just a documentation problem?

**Comment by ocheret** [comment]
I resolved this by augmenting my PATH. Apparently, brew doesn't put the TeX stuff in the usual brew place and doesn't seem to let you know. I believe the docs here should suggesting adding:

`PATH=$PATH:/Library/TeX/texbin
`
to startup files.

**Comment by mills-nick** [comment]
On my macOs Sonoma, running `source ~/.zshrc` fixed this issue. Seems that sometimes, simply doing a brew or pip install doesn't update the PATH.
