### ISSUE TITLE
The program cannot find the tex log file

### ISSUE THREAD

**Issue by PlagueDoctors** [3b1b/manim#1960]
### Describe the bug
This problem was encountered when running the GraphExample code in the official document（ https://3b1b.github.io/manim/getting_started/example_scenes.html ）。 The bin folder path of Letex has been added to the system environment variable, and Miktex has completed all updates and installation of all packages.

**Code**:
        sin_label = axes.get_graph_label(sin_graph, "\\sin(x)")
        relu_label = axes.get_graph_label(relu_graph, Text("ReLU"))
        step_label = axes.get_graph_label(step_graph, Text("Step"), x=4)

**Wrong display or Error traceback**:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Pla\AppData\Local\Programs\Python\Python311\Scripts\manimgl.exe\__main__.py", line 7, in <module>
  File "C:\Users\Pla\AppData\Local\Programs\Python\Python311\Lib\site-packages\manimlib\__main__.py", line 25, in main
    scene.run()
  File "C:\Users\Pla\AppData\Local\Programs\Python\Python311\Lib\site-packages\manimlib\scene\scene.py", line 91, in run
    self.construct()
  File "C:\Users\Pla\Desktop\python_test_file\Manim\Manimgl\axes.py", line 36, in construct
    sin_label = axes.get_graph_label(sin_graph, "\\sin(x)")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pla\AppData\Local\Programs\Python\Python311\Lib\site-packages\manimlib\mobject\coordinate_systems.py", line 239, in get_graph_label
    label = Tex(label)
            ^^^^^^^^^^
  File "C:\Users\Pla\AppData\Local\Programs\Python\Python311\Lib\site-packages\manimlib\mobject\svg\tex_mobject.py", line 188, in __init__
    super().__init__(full_string, **kwargs)
  File "C:\Users\Pla\AppData\Local\Programs\Python\Python311\Lib\site-packages\manimlib\mobject\svg\tex_mobject.py", line 45, in __init__
    super().__init__(**kwargs)
  File "C:\Users\Pla\AppData\Local\Programs\Python\Python311\Lib\site-packages\manimlib\mobject\svg\svg_mobject.py", line 65, in __init__
    self.init_svg_mobject()
  File "C:\Users\Pla\AppData\Local\Programs\Python\Python311\Lib\site-packages\manimlib\mobject\svg\svg_mobject.py", line 76, in init_svg_mobject
    self.generate_mobject()
  File "C:\Users\Pla\AppData\Local\Programs\Python\Python311\Lib\site-packages\manimlib\mobject\svg\svg_mobject.py", line 91, in generate_mobject
    file_path = self.get_file_path()
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pla\AppData\Local\Programs\Python\Python311\Lib\site-packages\manimlib\mobject\svg\tex_mobject.py", line 66, in get_file_path
    file_path = tex_to_svg_file(full_tex)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pla\AppData\Local\Programs\Python\Python311\Lib\site-packages\manimlib\utils\tex_file_writing.py", line 52, in tex_to_svg_file
    tex_to_svg(tex_file_content, svg_file)
  File "C:\Users\Pla\AppData\Local\Programs\Python\Python311\Lib\site-packages\manimlib\utils\tex_file_writing.py", line 60, in tex_to_svg
    svg_file = dvi_to_svg(tex_to_dvi(tex_file))
                          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pla\AppData\Local\Programs\Python\Python311\Lib\site-packages\manimlib\utils\tex_file_writing.py", line 91, in tex_to_dvi
    with open(log_file, "r", encoding="utf-8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\PLA\\AppData\\Local\\Temp\\Tex\\42c962cc458aefe6.log'

**Comment by ForeverPx** [comment]
I met the same problem

**Comment by hyperbolic-c** [comment]
in the **default_config.yml**:
```
# Manim often generates tex_files or other kinds of serialized data
  # to keep from having to generate the same thing too many times.  By
  # default, these will be stored at tempfile.gettempdir(), e.g. this might
  # return whatever is at to the TMPDIR environment variable.  If you want to
  # specify them elsewhere,
  temporary_storage: "E:\\projects\\manim\\media"
```
You could solve the error by input your **temporary_storage**.
