### ISSUE TITLE
TypeError when running "manimgl example_scenes.py OpeningManimExample"

### ISSUE THREAD

**Issue by bsubercaseaux** [3b1b/manim#1976]
### Describe the error
After a fresh install (macOS Ventura 13.1), the starting example does not work for me.

### Code and Error
**Code**:
```
manimgl example_scenes.py OpeningManimExample
```

**Error**:

```
ManimGL v1.6.1
[18:49:08] INFO     Using the default configuration file, which you can modify in                         config.py:348
                    `/Users/bsuberca/Research/manim/manimlib/default_config.yml`                                       
           INFO     If you want to create a local configuration file, you can create a file named         config.py:349
                    `custom_config.yml`, or run `manimgl --config`                                                     
2023-01-28 18:49:09.002 Python[75224:37743336] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/vx/lhs1msj56h715m0q_sjnbnmm0000gr/T/org.python.python.savedState
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/manimgl", line 8, in <module>
    sys.exit(main())
  File "/Users/bsuberca/Research/manim/manimlib/__main__.py", line 25, in main
    scene.run()
  File "/Users/bsuberca/Research/manim/manimlib/scene/scene.py", line 148, in run
    self.construct()
  File "/Users/bsuberca/Research/manim/example_scenes.py", line 21, in construct
    self.play(Write(intro_words))
  File "/Users/bsuberca/Research/manim/manimlib/scene/scene.py", line 617, in play
    self.progress_through_animations(animations)
  File "/Users/bsuberca/Research/manim/manimlib/scene/scene.py", line 590, in progress_through_animations
    self.update_frame(dt)
  File "/Users/bsuberca/Research/manim/manimlib/scene/scene.py", line 313, in update_frame
    self.camera.capture(*self.mobjects)
  File "/Users/bsuberca/Research/manim/manimlib/camera/camera.py", line 225, in capture
    mobject.render(self.ctx, self.uniforms)
  File "/Users/bsuberca/Research/manim/manimlib/mobject/mobject.py", line 1941, in render
    self.shader_wrappers = self.get_shader_wrapper_list(ctx)
  File "/Users/bsuberca/Research/manim/manimlib/mobject/types/vectorized_mobject.py", line 1306, in get_shader_wrapper_list
    self.back_stroke_shader_wrapper.read_in(
  File "/Users/bsuberca/Research/manim/manimlib/shader_wrapper.py", line 193, in read_in
    np.concatenate(data_list, out=self.vert_data)
  File "<__array_function__ internals>", line 5, in concatenate
TypeError: Cannot cast array data from dtype({'names':['point','fill_rgba','fill_border_width','joint_product'], 'formats':[('<f4', (3,)),('<f4', (4,)),('<f4', (1,)),('<f4', (4,))], 'offsets':[0,48,88,32], 'itemsize':92}) to dtype([('point', '<f4', (3,)), ('stroke_rgba', '<f4', (4,)), ('stroke_width', '<f4', (1,)), ('joint_product', '<f4', (4,))]) according to the rule 'same_kind'
```

### Environment
**OS System**:  MacOS Ventura 13.1
**manim version**: master v1.6.1-997-gf296dd8d
**python version**: 3.10.

**Comment by 3b1b** [comment]
I'm not seeing the same issue, but it's possible [this](https://github.com/3b1b/manim/pull/1978) might fix it. Do you mind checking?

If not, can you share what version of numpy you have?

**Comment by bsubercaseaux** [comment]
That did work for me! Thanks a lot!
