### ISSUE TITLE
Errors occured during testing installed manimgl

### ISSUE THREAD

**Issue by Rookieleorere** [3b1b/manim#1983]
### Describe the error
<When attempting to test the function of installed manimgl, an error 'COM MTA not set' occured and with multiple trace back, but no image or picture were shown. Wonder if it is the pyglet glitch or something else.>

### Code and Error
**Code**:
<Manimgl start.py SquareToCircle>

**Error**:
<(base) C:\Users\ACCOUNT>manimgl --version
C:\Users\ACCOUNT\anaconda3\lib\site-packages\pyglet\libs\win32\__init__.py:326: UserWarning: Could not set COM MTA mode. Unexpected behavior may occur.
  warnings.warn("Could not set COM MTA mode. Unexpected behavior may occur.")
ManimGL v1.6.1

(base) C:\Users\ACCOUNT>manimgl start.py SquareToCircle
C:\Users\ACCOUNT\anaconda3\lib\site-packages\pyglet\libs\win32\__init__.py:326: UserWarning: Could not set COM MTA mode. Unexpected behavior may occur.
  warnings.warn("Could not set COM MTA mode. Unexpected behavior may occur.")
ManimGL v1.6.1
[14:57:00] INFO     Using the default configuration file, which you can modify in                         config.py:265
                    `c:\users\account\anaconda3\lib\site-packages\manimlib\default_config.yml`
           INFO     If you want to create a local configuration file, you can create a file named         config.py:266
                    `custom_config.yml`, or run `manimgl --config`
Traceback (most recent call last):
  File "C:\Users\ACCOUNT\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ACCOUNT\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ACCOUNT\anaconda3\Scripts\manimgl.exe\__main__.py", line 7, in <module>
  File "C:\Users\ACCOUNT\anaconda3\lib\site-packages\manimlib\__main__.py", line 21, in main
    config = manimlib.config.get_configuration(args)
  File "C:\Users\ACCOUNT\anaconda3\lib\site-packages\manimlib\config.py", line 271, in get_configuration
    custom_config = get_custom_config()
  File "C:\Users\ACCOUNT\anaconda3\lib\site-packages\manimlib\config.py", line 213, in get_custom_config
    config = yaml.safe_load(file)
  File "C:\Users\ACCOUNT\anaconda3\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\ACCOUNT\anaconda3\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\ACCOUNT\anaconda3\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\ACCOUNT\anaconda3\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\ACCOUNT\anaconda3\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\ACCOUNT\anaconda3\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\ACCOUNT\anaconda3\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\ACCOUNT\anaconda3\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\ACCOUNT\anaconda3\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\ACCOUNT\anaconda3\lib\site-packages\yaml\composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "C:\Users\ACCOUNT\anaconda3\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\ACCOUNT\anaconda3\lib\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "C:\Users\ACCOUNT\anaconda3\lib\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "C:\Users\ACCOUNT\anaconda3\lib\site-packages\yaml\scanner.py", line 251, in fetch_more_tokens
    return self.fetch_double()
  File "C:\Users\ACCOUNT\anaconda3\lib\site-packages\yaml\scanner.py", line 655, in fetch_double
    self.fetch_flow_scalar(style='"')
  File "C:\Users\ACCOUNT\anaconda3\lib\site-packages\yaml\scanner.py", line 666, in fetch_flow_scalar
    self.tokens.append(self.scan_flow_scalar(style))
  File "C:\Users\ACCOUNT\anaconda3\lib\site-packages\yaml\scanner.py", line 1149, in scan_flow_scalar
    chunks.extend(self.scan_flow_scalar_non_spaces(double, start_mark))
  File "C:\Users\ACCOUNT\anaconda3\lib\site-packages\yaml\scanner.py", line 1213, in scan_flow_scalar_non_spaces
    raise ScannerError("while scanning a double-quoted scalar", start_mark,
yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "c:\users\account\anaconda3\lib\site-packages\manimlib\default_config.yml", line 18, column 22
expected escape sequence of 8 hexadecimal numbers, but found 's'
  in "c:\users\account\anaconda3\lib\site-packages\manimlib\default_config.yml", line 18, column 27>

### Environment
**OS System**: Windows 10
**python version **:3.9

**Comment by TonyCrane** [comment]
> an error 'COM MTA not set' occured

That is JUST a warning.

The critical error is that there are erros in the `default_config.yml` file. Take a look at the end of the traceback:
```text
in "c:\users\account\anaconda3\lib\site-packages\manimlib\default_config.yml", line 18, column 22
expected escape sequence of 8 hexadecimal numbers, but found 's'
```
