### ISSUE TITLE
Manim OSError: [WinError 6]

### ISSUE THREAD

**Issue by ZYashore** [3b1b/manim#2005]
### Describe the error
用pycharm运行manimgl无法调用latex，一直报错OSError: [WinError 6]，请问如何解决？

### Code and Error
**Code**:
from manimlib import *

class demo(Scene):
    def construct(self):
        c = TexText("I am a speedmeter")
        s = Speedometer()
        self.play(FadeIn(c))
        self.wait()
        self.play(ReplacementTransform(c, s))
        self.wait(2)

if __name__ == "__main__":
    from os import system
    system("manimgl {} demo".format(__file__))

**Error**:
Traceback (most recent call last):
  File "f:\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "f:\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\python\Scripts\manimgl.exe\__main__.py", line 7, in <module>
  File "f:\python\lib\site-packages\manimlib\__main__.py", line 25, in main
    scene.run()
  File "f:\python\lib\site-packages\manimlib\scene\scene.py", line 91, in run
    self.construct()
  File "G:\manim_project\project\new\Demo.py", line 5, in construct
    c = TexText("I am a speedmeter")
  File "f:\python\lib\site-packages\manimlib\mobject\svg\tex_mobject.py", line 188, in __init__
    super().__init__(full_string, **kwargs)
  File "f:\python\lib\site-packages\manimlib\mobject\svg\tex_mobject.py", line 45, in __init__
    super().__init__(**kwargs)
  File "f:\python\lib\site-packages\manimlib\mobject\svg\svg_mobject.py", line 65, in __init__
    self.init_svg_mobject()
  File "f:\python\lib\site-packages\manimlib\mobject\svg\svg_mobject.py", line 76, in init_svg_mobject
    self.generate_mobject()
  File "f:\python\lib\site-packages\manimlib\mobject\svg\svg_mobject.py", line 91, in generate_mobject
    file_path = self.get_file_path()
  File "f:\python\lib\site-packages\manimlib\mobject\svg\tex_mobject.py", line 65, in get_file_path
    with display_during_execution(f"Writing \"{self.tex_string}\""):
  File "f:\python\lib\contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "f:\python\lib\site-packages\manimlib\utils\tex_file_writing.py", line 129, in display_during_execution
    max_characters = os.get_terminal_size().columns - 1
OSError: [WinError 6] 句柄无效。

### Environment
**OS System**: windows
**manim version**: ManimGL
**python version**:3.9.0

**Comment by longlongvip** [comment]
Plase see [this](https://www.bilibili.com/read/cv18012785?from=search)

**Comment by ZYashore** [comment]
> Plase see [this](https://www.bilibili.com/read/cv18012785?from=search)

Thank you for the answer, I have solved the problem
