### ISSUE TITLE
Raising OSError: [WinError 6] the handle is invalid.

### ISSUE THREAD

**Issue by newbei** [3b1b/manim#2052]
### Describe the error

It  runs well on Circle, Arc, Arrow demos and others.
When run a demo for SingleStringTex, Raising "OSError: [WinError 6] the handle is invalid."

How to fix it？

Texlive 2023 have been installed.

**tex**:
```
tex -v
TeX 3.141592653 (TeX Live 2023)
kpathsea version 6.3.5
Copyright 2023 D.E. Knuth.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the TeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the TeX source.
Primary author of TeX: D.E. Knuth.

```

**latex**:
```

latex -v
pdfTeX 3.141592653-2.6-1.40.25 (TeX Live 2023)
kpathsea version 6.3.5
Copyright 2023 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.39; using libpng 1.6.39
Compiled with zlib 1.2.13; using zlib 1.2.13
Compiled with xpdf version 4.04
```

### Code and Error
**Code**:
```
from manimlib import *

class text(Scene):
    def construct(self):
        tex = SingleStringTex(r"\begin{pmatrix}1&1\\1&1\end{pmatrix}")
        self.add(tex)

if __name__ == "__main__":
    from os import system
    system("manimgl {} text -c black".format(__file__))
```

**customer_config.yml**:
There's the same error both xelatex and latex for executable.
```
tex:
  executable: "xelatex -no-pdf"
  template_file: "ctex_template.tex"
  intermediate_filetype: "xdv"
#  executable: "latex"
#  template_file: "tex_template.tex"
#  intermediate_filetype: "dvi"
  text_to_replace: "[tex_expression]"
  # For ctex, use the following configuration
```

**Error**:
```
D:\programs\py390_64_venv\manim_test\Scripts\python.exe D:/workspace/python/manimtestl/src/com/t4/start.py
ManimGL v1.6.1
Traceback (most recent call last):
  File "D:\programs\python390_64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\programs\python390_64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\programs\py390_64_venv\manim_test\Scripts\manimgl.exe\__main__.py", line 7, in <module>
  File "d:\programs\py390_64_venv\manim_test\lib\site-packages\manimlib\__main__.py", line 25, in main
    scene.run()
  File "d:\programs\py390_64_venv\manim_test\lib\site-packages\manimlib\scene\scene.py", line 91, in run
    self.construct()
  File "D:\workspace\python\manimtestl\src\com\t4\start.py", line 5, in construct
    tex = SingleStringTex(r"test")
  File "d:\programs\py390_64_venv\manim_test\lib\site-packages\manimlib\mobject\svg\tex_mobject.py", line 45, in __init__
    super().__init__(**kwargs)
  File "d:\programs\py390_64_venv\manim_test\lib\site-packages\manimlib\mobject\svg\svg_mobject.py", line 65, in __init__
    self.init_svg_mobject()
  File "d:\programs\py390_64_venv\manim_test\lib\site-packages\manimlib\mobject\svg\svg_mobject.py", line 76, in init_svg_mobject
    self.generate_mobject()
  File "d:\programs\py390_64_venv\manim_test\lib\site-packages\manimlib\mobject\svg\svg_mobject.py", line 91, in generate_mobject
    file_path = self.get_file_path()
  File "d:\programs\py390_64_venv\manim_test\lib\site-packages\manimlib\mobject\svg\tex_mobject.py", line 65, in get_file_path
    with display_during_execution(f"Writing \"{self.tex_string}\""):
  File "D:\programs\python390_64\lib\contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "d:\programs\py390_64_venv\manim_test\lib\site-packages\manimlib\utils\tex_file_writing.py", line 129, in display_during_execution
    max_characters = os.get_terminal_size().columns - 1
OSError: [WinError 6] the handle is invalid.
```

### Environment
**OS System**: Windows 10
**manim version**: ManimGL v1.6.1
**python version**: Python 390_64

**Comment by newbei** [comment]
I found that worked well in cmd, but Rasing error above when run in PyCharm Terminal.

**Comment by bhattacharjeeajay12** [comment]
> worked well in cmd, but Rasing error above when run in PyCharm Terminal.

HI @newbei how did you solve this issue. I am also facing it in PyCharm.
