### ISSUE TITLE
I want to install manim

### ISSUE THREAD

**Issue by kermag** [3b1b/manim#2075]
I typed manimgl in cmd

error
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jm\AppData\Local\Programs\Python\Python312\Scripts\manimgl.exe\__main__.py", line 4, in <module>
  File "C:\Users\jm\AppData\Local\Programs\Python\Python312\Lib\site-packages\manimlib\__init__.py", line 1, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

**Comment by HauenderPhilip** [comment]
I solved this by running
`pip install setuptools`

**Comment by shallow-beach** [comment]
are you following the steps of the [docs](https://docs.manim.community/en/stable/installation)? there are a few more helpful instructions than the README from the github.
