### ISSUE TITLE
Getting ValueError when trying to run a simple example python file(Ubuntu)

### ISSUE THREAD

**Issue by asifmkutty** [3b1b/manim#2114]
I tried running manimgl with and without root priviliges and i got these errors repeatedly 
sudo -E manimgl example_scenes.py 
[sudo] password for dot: 
ManimGL v1.6.1
[20:01:11] INFO     Using the default configuration file, which you can modify in `/home/dot/.local/lib/python3.10/site-packages/manimlib/default_config.yml`      config.py:265
           INFO     If you want to create a local configuration file, you can create a file named `custom_config.yml`, or run `manimgl --config`                   config.py:266
01: AnimatingMethods
02: ControlsExample
03: CoordinateSystemExample
04: GraphExample
05: InteractiveDevelopment
06: OpeningManimExample
07: SurfaceExample
08: TexAndNumbersExample
09: TexIndexing
10: TexTransformExample
11: TextExample
12: UpdatersExample

That module has multiple scenes, which ones would you like to render?
Scene Name or Number: 4
Traceback (most recent call last):
  File "/usr/local/bin/manimgl", line 33, in <module>
    sys.exit(load_entry_point('manimgl', 'console_scripts', 'manimgl')())
  File "/home/dot/.local/lib/python3.10/site-packages/manimlib/__main__.py", line 25, in main
    scene.run()
  File "/home/dot/.local/lib/python3.10/site-packages/manimlib/scene/scene.py", line 91, in run
    self.construct()
  File "/home/dot/manim/example_scenes.py", line 422, in construct
    axes = Axes((-3, 10), (-1, 8), height=6)
  File "/home/dot/.local/lib/python3.10/site-packages/manimlib/mobject/coordinate_systems.py", line 383, in __init__
    self.x_axis = self.create_axis(
  File "/home/dot/.local/lib/python3.10/site-packages/manimlib/mobject/coordinate_systems.py", line 405, in create_axis
    axis = NumberLine(range_terms, **new_config)
  File "/home/dot/.local/lib/python3.10/site-packages/manimlib/mobject/number_line.py", line 60, in __init__
    super().__init__(self.x_min * RIGHT, self.x_max * RIGHT, **kwargs)
  File "/home/dot/.local/lib/python3.10/site-packages/manimlib/mobject/geometry.py", line 450, in __init__
    super().__init__(**kwargs)
  File "/home/dot/.local/lib/python3.10/site-packages/manimlib/mobject/types/vectorized_mobject.py", line 85, in __init__
    super().__init__(**kwargs)
  File "/home/dot/.local/lib/python3.10/site-packages/manimlib/mobject/mobject.py", line 89, in __init__
    self.init_points()
  File "/home/dot/.local/lib/python3.10/site-packages/manimlib/mobject/geometry.py", line 453, in init_points
    self.set_points_by_ends(self.start, self.end, self.buff, self.path_arc)
  File "/home/dot/.local/lib/python3.10/site-packages/manimlib/mobject/geometry.py", line 487, in set_points_by_ends
    self.set_points_as_corners([start, end])
  File "/home/dot/.local/lib/python3.10/site-packages/manimlib/mobject/types/vectorized_mobject.py", line 496, in set_points_as_corners
    self.set_anchors_and_handles(*[
  File "/home/dot/.local/lib/python3.10/site-packages/manimlib/mobject/types/vectorized_mobject.py", line 365, in set_anchors_and_handles
    self.set_points(new_points)
  File "/home/dot/.local/lib/python3.10/site-packages/manimlib/mobject/types/vectorized_mobject.py", line 968, in wrapper
    if not np.all(self.get_points() == old_points):
ValueError: operands could not be broadcast together with shapes (3,3) (0,3)

### I have disabled my conda env too and installed latex, but still the issue persists

**Comment by hyperbolic-c** [comment]
Maybe you would solve it by switching to numpy 1.24 using `pip install numpy==1.24`
