### ISSUE TITLE
Crash on provided example; Matrix unexpected keyword 'include_background_rectangle'

### ISSUE THREAD

**Issue by proteusGIT** [3b1b/manim#2116]
### Describe the bug
Crash on provided example.

**Code**:
`$ python -m manimlib example_scenes.py OpeningManimExample`

**Wrong display or Error traceback**:
```
$ python -m manimlib example_scenes.py OpeningManimExample
C:\Users\user\AppData\Roaming\Python\Python312\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
ManimGL v1.6.1
[13:21:56] INFO     Using the default configuration file, which you can modify in `c:\users\user\documents\manim\manimlib\default_config.yml`                                                                                                   config.py:362
           INFO     If you want to create a local configuration file, you can create a file named `custom_config.yml`, or run `manimgl --config`                                                                                                                  config.py:363
           WARNING  You may be using Windows platform and have not specified the path of `temporary_storage`, which may cause OSError. So it is recommended to specify the `temporary_storage` in the config file (.yml)                                          config.py:327
           WARNING  You may be using Windows platform and have not specified the path of `temporary_storage`, which may cause OSError. So it is recommended to specify the `temporary_storage` in the config file (.yml)                                          config.py:327
           INFO     Using the default configuration file, which you can modify in `c:\users\user\documents\manim\manimlib\default_config.yml`                                                                                                   config.py:362
           INFO     If you want to create a local configuration file, you can create a file named `custom_config.yml`, or run `manimgl --config`                                                                                                                  config.py:363
           WARNING  You may be using Windows platform and have not specified the path of `temporary_storage`, which may cause OSError. So it is recommended to specify the `temporary_storage` in the config file (.yml)                                          config.py:327
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\Documents\TCSbase\manim\manimlib\__main__.py", line 29, in <module>
    main()
  File "C:\Users\user\Documents\TCSbase\manim\manimlib\__main__.py", line 25, in main
    scene.run()
  File "C:\Users\user\Documents\TCSbase\manim\manimlib\scene\scene.py", line 163, in run
    self.construct()
  File "C:\Users\user\Documents\TCSbase\manim\example_scenes.py", line 29, in construct
    IntegerMatrix(matrix, include_background_rectangle=True),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Documents\TCSbase\manim\manimlib\mobject\matrix.py", line 246, in __init__
    super().__init__(matrix, num_decimal_places, decimal_config, **config)
  File "C:\Users\user\Documents\TCSbase\manim\manimlib\mobject\matrix.py", line 225, in __init__
    super().__init__(
TypeError: Matrix.__init__() got an unexpected keyword argument 'include_background_rectangle'
```

### Additional context
I just installed on windows.
Also I just installed python and had to add it to the path and also had to "pip setuptools" to make it work.
I guess the installation instructions are not really great for windows.
Also, as you can see I am not just calling `$ manim example_scenes.py OpeningManimExample`  but had to change that to make it at least run.
I am using the just cloned git repo though.

**Comment by hyperbolic-c** [comment]
got the same error

**Comment by hyperbolic-c** [comment]
just remove it, by[this pull](https://github.com/3b1b/manim/pull/2108)
