### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/xx/xxxxx/T/Tex/xxxxxxxxxx.log'

### ISSUE THREAD

**Issue by AJNOURI** [3b1b/manim#2137]
### Describe the bug
Just after cloning the repo and installing the packages, I am trying to test the instructions in the README.md :

> Using manim
> Try running the following:
> 
> manimgl example_scenes.py OpeningManimExample

**Code**:
`manimgl example_scenes.py OpeningManimExample -os`

**Wrong display or Error traceback**:

> ManimGL v1.6.1
> [19:38:15] INFO     Using the default configuration file, which you can modify in `<path_to_your_project>/manimlib/default_config.yml`                                                                                                    config.py:362
>            INFO     If you want to create a local configuration file, you can create a file named `custom_config.yml`, or run `manimgl --config`                                                                                                                      config.py:363
> sh: latex: command not foundc}\quad \\\quad \\\end{array}\right]
>            ERROR    LaTeX Error!  Not a worry, it happens to the best of us.                                                                                                                                                                                tex_file_writing.py:114
> Traceback (most recent call last):                              
>   File "<path_to_your_project>/.venv/bin/manimgl", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "<path_to_your_project>/manimlib/__main__.py", line 25, in main
>     scene.run()
>   File "<path_to_your_project>/manimlib/scene/scene.py", line 163, in run
>     self.construct()
>   File "<path_to_your_project>/example_scenes.py", line 29, in construct
>     IntegerMatrix(matrix),
>     ^^^^^^^^^^^^^^^^^^^^^
>   File "<path_to_your_project>/manimlib/mobject/matrix.py", line 246, in __init__
>     super().__init__(matrix, num_decimal_places, decimal_config, **config)
>   File "<path_to_your_project>/manimlib/mobject/matrix.py", line 225, in __init__
>     super().__init__(
>   File "<path_to_your_project>/manimlib/mobject/matrix.py", line 61, in __init__
>     self.brackets = self.create_brackets(self.rows, bracket_v_buff, bracket_h_buff)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<path_to_your_project>/manimlib/mobject/matrix.py", line 122, in create_brackets
>     brackets = Tex("".join((
>                ^^^^^^^^^^^^^
>   File "<path_to_your_project>/manimlib/mobject/svg/tex_mobject.py", line 57, in __init__
>     super().__init__(
>   File "<path_to_your_project>/manimlib/mobject/svg/string_mobject.py", line 69, in __init__
>     super().__init__(**kwargs)
>   File "<path_to_your_project>/manimlib/mobject/svg/svg_mobject.py", line 76, in __init__
>     self.init_svg_mobject()
>   File "<path_to_your_project>/manimlib/mobject/svg/svg_mobject.py", line 105, in init_svg_mobject
>     submobs = self.mobjects_from_file(self.get_file_path())
>                                       ^^^^^^^^^^^^^^^^^^^^
>   File "<path_to_your_project>/manimlib/mobject/svg/string_mobject.py", line 77, in get_file_path
>     return self.get_file_path_by_content(self.get_content(is_labelled))
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<path_to_your_project>/manimlib/mobject/svg/tex_mobject.py", line 85, in get_file_path_by_content
>     return tex_content_to_svg_file(
>            ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<path_to_your_project>/manimlib/utils/tex_file_writing.py", line 83, in tex_content_to_svg_file
>     create_tex_svg(full_tex, svg_file, compiler)
>   File "<path_to_your_project>/manimlib/utils/tex_file_writing.py", line 118, in create_tex_svg
>     with open(root + ".log", "r", encoding="utf-8") as log_file:
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/xx/xxxxx/T/Tex/xxxxxxxxxx.log'

### Additional context

>     ### macOS System Information ###
>     System Version:
>     ProductName:        macOS
>     ProductVersion:     14.4.1
>     BuildVersion:       23E224
> 
>     Hardware Information:
>     Hardware:
> 
>     Hardware Overview:
> 
>       Model Name: MacBook Pro
>       Model Identifier: Mac14,9
>       Model Number: Z17G00251FN/A
>       Chip: Apple M2 Pro
>       Total Number of Cores: 10 (6 performance and 4 efficiency)
>       Memory: 32 GB

**Comment by obiscr** [comment]
As a temporary solution, create the log file manually: 
```
touch /var/folders/xx/xxxxx/T/Tex/xxxxxxxxxx.log
```
