### ISSUE TITLE
Cannot use `Difference` boolean operation in latest cloned ManimGL

### ISSUE THREAD

**Issue by MathItYT** [3b1b/manim#2174]
### Describe the bug
I ran the piece of code shown below, and I came across with a `ValueError` related to NumPy broadcasting.

**Code**:
```py
from manimlib import *


FG_COLOR: str = "#EBEBEB"


class Introduction(InteractiveScene):
    def construct(self) -> None:
        olympiad_background = Difference(FullScreenRectangle(), TexText("Olimpiadas", font_size=96))
        olympiad_background.set_stroke(width=0)
        olympiad_background.set_fill(color=FG_COLOR, opacity=1)
        self.add(olympiad_background)
```

**Wrong display or Error traceback**:
```
ManimGL v1.6.1
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\manimgl\.venv\Scripts\manimgl.exe\__main__.py", line 7, in <module>
  File "D:\manimgl\.venv\Lib\site-packages\manimlib\__main__.py", line 25, in main
    scene.run()
  File "D:\manimgl\.venv\Lib\site-packages\manimlib\scene\scene.py", line 163, in run
    self.construct()
  File "D:\manimgl\main.py", line 48, in construct
    olympiad_background = Difference(FullScreenRectangle(), TexText("Olimpiadas", font_size=96))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\manimgl\.venv\Lib\site-packages\manimlib\mobject\boolean_ops.py", line 72, in __init__
    [_convert_vmobject_to_skia_path(clip)],
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\manimgl\.venv\Lib\site-packages\manimlib\mobject\boolean_ops.py", line 14, in _convert_vmobject_to_skia_path
    subpaths = vmobject.get_subpaths_from_points(vmobject.get_all_points())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\manimgl\.venv\Lib\site-packages\manimlib\mobject\types\vectorized_mobject.py", line 750, in get_subpaths_from_points
    end_indices = self.get_subpath_end_indices_from_points(points)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\manimgl\.venv\Lib\site-packages\manimlib\mobject\types\vectorized_mobject.py", line 738, in get_subpath_end_indices_from_points
    is_end = (a0 == h).all(1) & (abs(h - a1) > atol).any(1)
                                     ~~^~~~
ValueError: operands could not be broadcast together with shapes (575,3) (574,3)
```

### Additional context
I think the problem is just that `get_subpath_end_indices_from_points` method from `VMobject`, where broadcasting issues aren't considered, because you can't subtract two NumPy arrays together without ensuring they're the same size. Its source code is below:

```py
def get_subpath_end_indices_from_points(self, points: Vect3Array) -> np.ndarray:
        atol = 1e-4  # TODO, this is too unsystematic
        a0, h, a1 = points[0:-1:2], points[1::2], points[2::2]
        # An anchor point is considered the end of a path
        # if its following handle is sitting on top of it.
        # To disambiguate this from cases with many null
        # curves in a row, we also check that the following
        # anchor is genuinely distinct.
        is_end = (a0 == h).all(1) & (abs(h - a1) > atol).any(1)
        end_indices = (2 * n for n, end in enumerate(is_end) if end)
        return np.array([*end_indices, len(points) - 1])
```

It's obvious that `a0` and `h` are the same size, but we can't say the same for `a1`.

**Comment by 3b1b** [comment]
Thanks, it looks like _convert_vmobject_to_skia_path was not implemented properly.
