### ISSUE TITLE
ImportError: cannot import name LaggedStart

### ISSUE THREAD

**Issue by dbw5718** [3b1b/manim#228]
```
tachyon@Lenovo-G480:~/manim$ python extract_scene.py old_projects/256.py get_google_logo
Traceback (most recent call last):
  File "extract_scene.py", line 263, in <module>
    main()
  File "extract_scene.py", line 220, in main
    module = get_module(config["file"])
  File "extract_scene.py", line 215, in get_module
    return get_module_posix(file_name)
  File "extract_scene.py", line 209, in get_module_posix
    last_module = imp.load_module(part, *load_args)
  File "/home/tachyon/manim/./old_projects/256.py", line 24, in <module>
    from topics.common_scenes import *
  File "/home/tachyon/manim/topics/common_scenes.py", line 6, in <module>
    from animation.simple_animations import Write, DrawBorderThenFill, LaggedStart
ImportError: cannot import name LaggedStart
```
I want to use  older_projects/256.py to generate a demonstration animation, but this error has occurred. How do I solve it?

**Comment by rajdakin** [comment]
It seems 3b1b completely refactored the imports. You should remove every `from `[...]` import `[...] and replace them by `from big_ol_pile_of_manim_imports import *`

**Comment by eulertour** [comment]
Closing, as this issue is inactive.
