### ISSUE TITLE
Not able to run manimgl

### ISSUE THREAD

**Issue by Gsparsh22** [3b1b/manim#2282]
### Describe the error
manimgl not runnig

**Error**:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\spars\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts\manimgl.exe\__main__.py", line 4, in <module>
  File "C:\Windows\System32\manim\manimlib\__init__.py", line 1, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

### Environment
**Windows 11**: 
**python 3.12.0**:

**Comment by sundebug** [comment]
please install setuptools package

pip install setuptools

**Comment by Gsparsh22** [comment]
Thanks
