### ISSUE TITLE
'module' object has no attribute 'meta_animations'

### ISSUE THREAD

**Issue by MitchAllain** [3b1b/manim#23]
Looks like the `init.py` file in `animation` declares a module `meta_animations` which does not exist. Here is my traceback:

```
Traceback (most recent call last):
  File "extract_scene.py", line 188, in <module>
    main()
  File "extract_scene.py", line 166, in main
    module = get_module(config["file"])
  File "extract_scene.py", line 161, in get_module
    last_module = imp.load_module(part, *load_args)
  File "/Users/mitchallain/Development/Python/3b1b/manim/./music_and_measure.py", line 9, in <module>
    from animation import *
AttributeError: 'module' object has no attribute 'meta_animations'
```

Should be a simple fix, but I wanted to make sure there wasn't any functionality missing here.

**Comment by eulertour** [comment]
Closing, as this issue is old and inactive.
