### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 39-97: ordinal not in range(128)

### ISSUE THREAD

**Issue by ishandutta2007** [3b1b/manim#263]
(env27) ishandutta2007@MacBook-Pro:~/Documents/Projects/manim$ `python extract_scene.py example_scenes.py SquareToCircle -pl `

> Writing to MEDIA_DIR/animations/example_scenes/480p15/SquareToCircleTemp.mp4
>   0%|                                                                                                                                                       | 0/15 [00:00<?, ?it/s]
> 
> 
> Traceback (most recent call last):
>   File "extract_scene.py", line 273, in main
>     handle_scene(SceneClass(**scene_kwargs), **config)
>   File "/Users/ishandutta2007/Documents/Projects/manim/scene/scene.py", line 71, in __init__
>     self.construct(*self.construct_args)
>   File "/Users/ishandutta2007/Documents/Projects/manim/./example_scenes.py", line 22, in construct
>     self.play(ShowCreation(square))
>   File "/Users/ishandutta2007/Documents/Projects/manim/scene/scene.py", line 454, in play
>     for t in self.get_animation_time_progression(animations):
>   File "/Users/ishandutta2007/Documents/Projects/manim/env27/lib/python2.7/site-packages/tqdm/_tqdm.py", line 622, in __iter__
>     1 / avg_time if avg_time else None, bar_format))
>   File "/Users/ishandutta2007/Documents/Projects/manim/env27/lib/python2.7/site-packages/tqdm/_tqdm.py", line 98, in print_status
>     fp_write('\r' + s + (' ' * max(last_printed_len[0] - len_s, 0)))
>   File "/Users/ishandutta2007/Documents/Projects/manim/env27/lib/python2.7/site-packages/tqdm/_tqdm.py", line 92, in fp_write
>     fp.write(_unicode(s))
> UnicodeEncodeError: 'ascii' codec can't encode characters in position 39-97: ordinal not in range(128)
> 
> 
> 
>

**Comment by ishandutta2007** [comment]
Trying to see if anything non ascii is being sent to scene>play() I see no issues,

example_scenes.py > SquareToCircle > construct 
```
        sc = ShowCreation(square)
        print(sc)
        print(type(sc))
        self.play(ShowCreation(square))        
```

> ShowCreationSquare
> <class 'animation.creation.ShowCreation'>
>
