### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by VirajBShah** [3b1b/manim#265]
While trying the example in the README.md, I get the error:

`D:\manim-master>python extract_scene.py example_scenes.py SquareToCircle -pl
Traceback (most recent call last):
  File "extract_scene.py", line 283, in <module>
    main()
  File "extract_scene.py", line 243, in main
    module = get_module(config["file"])
  File "extract_scene.py", line 237, in get_module
    return get_module_windows(file_name)
  File "extract_scene.py", line 222, in get_module_windows
    last_module = imp.load_module(part, *load_args)
  File ".\example_scenes.py", line 4, in <module>
    from .big_ol_pile_of_manim_imports import *
ValueError: Attempted relative import in non-package`

What do I do?

**Comment by zimmermant** [comment]
In the file `example_scenes.py` remove the period from the beginning of the line `.big_ol_pile_of_manim_imports import *`.  That should fix the relative import error.

**Comment by VirajBShah** [comment]
I tried it.
I just get two empty folders:
designs and animations

**Comment by eulertour** [comment]
Are you still seeing this issue? If so, have you verified that you're using python 3.7?

**Comment by vignesh99** [comment]
Hello @zimmermant @eulertour ,
I am also facing an error when running manim class_name which is defined in file that uses relative import. Is this common to happen? Is there no way I can have a relative import and run the manim command in the terminal? Please let me know.
