### ISSUE TITLE
ImportError: No module named animation

### ISSUE THREAD

**Issue by nisealyj** [3b1b/manim#274]
I've installed manim on Win10.  After run "python  extract_scene.py -s example_scenes.py",

the next error is shown in the python interactive interpretor:

> Traceback (most recent call last):
  File "extract_scene.py", line 15, in <module>
    from scene.scene import Scene
  File "G:\python\manim\scene\scene.py", line 16, in <module>
    from animation.transform import MoveToTarget
  File "G:\python\manim\animation\transform.py", line 8, in <module>
    from animation.animation import Animation
ImportError: No module named animation

What I can do? I'm looking forward to get help to solve this problem.

**Comment by elaitha** [comment]
I was having the same problem but I fixed it this way:

Because transform.py is in the same module as animation.py the line:
`from animation.animation import Animation`
is somehow messing things up.

Instead of that I just used the line:
`from animation import Animation`
and it worked.
