### ISSUE TITLE
TypeError while running a triangle.py scene

### ISSUE THREAD

**Issue by rajdakin** [3b1b/manim#30]
I got an error when I try to run some of the [old_projects/triangle_of_power/triangle.py](https://github.com/3b1b/manim/blob/master/old_projects/triangle_of_power/triangle.py) scene.
My command is:
```
python extract_scene.py -p old_projects/triangle_of_power/triangle.py DrawInsideTriangle
```

But after that I get:
```
Traceback (most recent call last):
  File "extract_scene.py", line 187, in main
    handle_scene(SceneClass(**scene_kwargs), **config)
  File "/home/loic/Sources/Git/manim/scene/scene.py", line 47, in __init__
    self.construct(*self.construct_args)
  File "/home/loic/Sources/Git/manim/./old_projects/triangle_of_power/triangle.py", line 527, in construct
    top = TOP()
  File "/home/loic/Sources/Git/manim/./old_projects/triangle_of_power/triangle.py", line 91, in __init__
    VMobject.__init__(self, **kwargs)
  File "/home/loic/Sources/Git/manim/mobject/mobject.py", line 33, in __init__
    self.generate_points()
  File "/home/loic/Sources/Git/manim/./old_projects/triangle_of_power/triangle.py", line 104, in generate_points
    self.set_values(self.x, self.y, self.z)
  File "/home/loic/Sources/Git/manim/./old_projects/triangle_of_power/triangle.py", line 108, in set_values
    self.set_value(i, mob)
  File "/home/loic/Sources/Git/manim/./old_projects/triangle_of_power/triangle.py", line 111, in set_value
    self.values[index] = self.put_on_vertex(index, value)
  File "/home/loic/Sources/Git/manim/./old_projects/triangle_of_power/triangle.py", line 125, in put_on_vertex
    value.center()
  File "/home/loic/Sources/Git/manim/mobject/mobject.py", line 230, in center
    self.shift(-self.get_center())
  File "/home/loic/Sources/Git/manim/mobject/mobject.py", line 124, in shift
    mob.points += total_vector
TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
```
And then the fail sound.

Is there something wrong in what am I doing?

**Comment by shahar603** [comment]
Replace the function _shift_ at _manim/mobject/mobject.py_ with the following code:

```
def shift(self, *vectors):
    total_vector = reduce(op.add, vectors)
    for mob in self.family_members_with_points():
        mob.points = mob.points.astype('float')  # Added this line that casts mob.points to a float array
        mob.points += total_vector
    return self

```
I haven't tested this on Linux or Mac but because this issue is a NumPy issue I belive it would work on other platforms as well.

For some reason the '+', 'x' and '•' symbols are much bigger (on my Windows machine) compared to those in the video. The other animations that use this function (Which also crash for the same reason before the modification) seems to be ok.

**Comment by rajdakin** [comment]
It worked, thanks!
Will create a pull request (I'm on Linux, and it worked on windows too) -- but the symbols are way too large... Will create a new issue.
