### ISSUE TITLE
File "<frozen importlib._bootstrap>", line 1006, in _gcd_import

### ISSUE THREAD

**Issue by sgbr1993** [3b1b/manim#307]
I'm new at using manim. I just finished installing and I am trying to follow the tutorial, but: 

$ python extract_scene.py manim_tutorial_1.py Shapes -pl
Traceback (most recent call last):
  File "extract_scene.py", line 287, in <module>
    main()
  File "extract_scene.py", line 247, in main
    module = get_module(config["file"])
  File "extract_scene.py", line 242, in get_module
    return importlib.import_module(module_name)
  File "/home/rodrigo/manim37/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/rodrigo/manim37/manim-master/manim_tutorial_1.py", line 22
    self.play(ShowCreation(line))
                                ^
TabError: inconsistent use of tabs and spaces in indentation

How can I solve it?

**Comment by icreiuheciijc** [comment]
[This](https://stackoverflow.com/questions/5685406/inconsistent-use-of-tabs-and-spaces-in-indentation) will help you.
