### ISSUE TITLE
SyntaxError: invalid syntax in return np.array([*color_to_rgb(color), alpha])

### ISSUE THREAD

**Issue by CRLannister** [3b1b/manim#308]
while running python extract_scene.py example_scenes.py SquareToCircle -pl in a vitualenv with python 2.7.15
The error output is: 
Traceback (most recent call last):
  File "extract_scene.py", line 15, in <module>
    from scene.scene import Scene
  File "/home/ashish/Documents/Codes/python/3b1b-manim/manim/scene/scene.py", line 15, in <module>
    from animation.animation import Animation
  File "/home/ashish/Documents/Codes/python/3b1b-manim/manim/animation/animation.py", line 5, in <module>
    from mobject.mobject import Mobject
  File "/home/ashish/Documents/Codes/python/3b1b-manim/manim/mobject/mobject.py", line 14, in <module>
    from utils.color import color_gradient
  File "/home/ashish/Documents/Codes/python/3b1b-manim/manim/utils/color.py", line 23
    return np.array([*color_to_rgb(color), alpha])
                     ^
SyntaxError: invalid syntax

**Comment by cclauss** [comment]
[flake8](http://flake8.pycqa.org) testing of https://github.com/3b1b/manim on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./old_projects/bell.py:222:38: E999 SyntaxError: invalid syntax
            for here, x in (here1, 0), (here2, 4)
                                     ^
./old_projects/borsuk.py:217:11: E999 SyntaxError: invalid syntax
         y=lambda m: m1.get
          ^
./old_projects/eoc/chapter6.py:399:35: E999 SyntaxError: invalid syntax
                for i, j in (1, 0), (0, 1)
                                  ^
./old_projects/nn/network.py:258:16: F821 undefined name 'get_norm'
        norm = get_norm(gradient)
               ^
./old_projects/nn/network.py:264:15: F821 undefined name 'get_norm'
        print(get_norm(old_pre_sig_guess - pre_sig_guess))
              ^
3     E999 SyntaxError: invalid syntax
2     F821 undefined name 'get_norm'
5
```

**Comment by Elteoremadebeethoven** [comment]
manim-master works in Python 3, not in Python 2, install pip3 and requieriments with pip3

**Comment by cclauss** [comment]
I believe that this issue can be closed.

**Comment by Matemasters** [comment]
Greetings!
I'm already in Python 3.6.6 and when I type 

> (manim36) C:\Users\PaKo>python extract_scene.py example_scenes.py SquareToCircle -pl
 
I get the following: 

> Traceback (most recent call last):
  File "C:\Users\PaKo\Desktop\Python\3blue_1brown\manim-master\extract_scene.py", line 299, in <module>
    main()
  File "C:\Users\PaKo\Desktop\Python\3blue_1brown\manim-master\extract_scene.py", line 259, in main
    module = get_module(config["file"])
  File "C:\Users\PaKo\Desktop\Python\3blue_1brown\manim-master\extract_scene.py", line 254, in get_module
    return importlib.import_module(module_name)
  File "C:\Users\PaKo\Anaconda2\envs\manim36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "< frozen importlib._bootstrap  >", line 994, in _gcd_import
  File "< frozen importlib._bootstrap  >", line 971, in _find_and_load
  File "< frozen importlib._bootstrap  >", line 941, in _find_and_load_unlocked
  File "< frozen importlib._bootstrap  >", line 219, in _call_with_frames_removed
  File "< frozen importlib._bootstrap  >", line 994, in _gcd_import
  File "< frozen importlib._bootstrap  >", line 971, in _find_and_load
  File "< frozen importlib._bootstrap  >", line 941, in _find_and_load_unlocked
  File "< frozen importlib._bootstrap  >", line 219, in _call_with_frames_removed
  File "< frozen importlib._bootstrap  >", line 994, in _gcd_import
  File "< frozen importlib._bootstrap  >", line 971, in _find_and_load
  File "< frozen importlib._bootstrap  >", line 941, in _find_and_load_unlocked
  File "< frozen importlib._bootstrap  >", line 219, in _call_with_frames_removed
  File "< frozen importlib._bootstrap  >", line 994, in _gcd_import
  File "< frozen importlib._bootstrap  >", line 971, in _find_and_load
  File "< frozen importlib._bootstrap >", line 941, in _find_and_load_unlocked
  File "< frozen importlib._bootstrap >", line 219, in _call_with_frames_removed
  File "< frozen importlib._bootstrap >", line 994, in _gcd_import
  File "< frozen importlib._bootstrap >", line 971, in _find_and_load
  File "< frozen importlib._bootstrap >", line 941, in _find_and_load_unlocked
  File "< frozen importlib._bootstrap >", line 219, in _call_with_frames_removed
  File "< frozen importlib._bootstrap >", line 994, in _gcd_import
  File "< frozen importlib._bootstrap >", line 971, in _find_and_load
  File "< frozen importlib._bootstrap >", line 941, in _find_and_load_unlocked
  File "< frozen importlib._bootstrap >", line 219, in _call_with_frames_removed
  File "< frozen importlib._bootstrap >", line 994, in _gcd_import
  File "< frozen importlib._bootstrap >", line 971, in _find_and_load
  File "< frozen importlib._bootstrap >", line 941, in _find_and_load_unlocked
  File "< frozen importlib._bootstrap >", line 219, in _call_with_frames_removed
  File "< frozen importlib._bootstrap >", line 994, in _gcd_import
  File "< frozen importlib._bootstrap >", line 971, in _find_and_load
  File "< frozen importlib._bootstrap >", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'C:'

Did it install right all the requirements or am I missing something?
Thank you in advanced,

**Comment by Elteoremadebeethoven** [comment]
The correct form is:

```sh
python3 extract_scene.py example_scenes.py SquareToCircle -pl
```
