### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified    Access is denied.

### ISSUE THREAD

**Issue by razvangheorghe** [3b1b/manim#316]
I'm trying to get manim to work and I can't run the example. Here's the error I got.

```(manim37) C:\Users\Razvan\Documents\GitHub\manim>python extract_scene.py example_scenes.py SquareToCircle -pl
Writing to C:\Users\Razvan\Documents\GitHub\manim\export\animations\example_scenes\480p15\SquareToCircleTemp.mp4



Traceback (most recent call last):
  File "extract_scene.py", line 277, in main
    handle_scene(SceneClass(**scene_kwargs), **config)
  File "C:\Users\Razvan\Documents\GitHub\manim\scene\scene.py", line 69, in __init__
    self.open_movie_pipe()
  File "C:\Users\Razvan\Documents\GitHub\manim\scene\scene.py", line 627, in open_movie_pipe
    self.writing_process = sp.Popen(command, stdin=sp.PIPE)
  File "C:\Users\Razvan\Anaconda3\envs\manim37\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Razvan\Anaconda3\envs\manim37\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified



Access is denied.```

**Comment by kicus** [comment]
Did you solve the this problem ?

**Comment by razvangheorghe** [comment]
@kicus nope, didn't have much time to spend on this.

**Comment by Elteoremadebeethoven** [comment]
Trie run CMD as administratorr

**Comment by razvangheorghe** [comment]
@Elteoremadebeethoven This worked! Thanks!
