### ISSUE TITLE
3blue1brown | manim | 1 problem related in getting manim to run (SquareToCircle example)

### ISSUE THREAD

**Issue by Matemasters** [3b1b/manim#317]
Greetings!
I'm following the instructions of the tutorial (https://talkingphysics.wordpress.com/2018/06/11/learning-how-to-animate-videos-using-manim-series-a-journey/) but, when I type 

> (manim36) C:\Users\PaKo>python C:\Users\PaKo\Desktop\Python\3blue_1brown\manim-master\extract_scene.py C:\Users\PaKo\Desktop\Python\3blue_1brown\manim-master\example_scenes.py
SquareToCircle -pl
 
I get the following: (I'm working in python 3.6.6)

> Traceback (most recent call last):
  File "C:\Users\PaKo\Desktop\Python\3blue_1brown\manim-master\extract_scene.py", line 299, in <module>
    main()
  File "C:\Users\PaKo\Desktop\Python\3blue_1brown\manim-master\extract_scene.py", line 259, in main
    module = get_module(config["file"])
  File "C:\Users\PaKo\Desktop\Python\3blue_1brown\manim-master\extract_scene.py", line 254, in get_module
    return importlib.import_module(module_name)
  File "C:\Users\PaKo\Anaconda2\envs\manim36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "< frozen importlib._bootstrap  >", line 994, in _gcd_import
  File "< frozen importlib._bootstrap  >", line 971, in _find_and_load
  File "< frozen importlib._bootstrap  >", line 941, in _find_and_load_unlocked
  File "< frozen importlib._bootstrap  >", line 219, in _call_with_frames_removed
  File "< frozen importlib._bootstrap  >", line 994, in _gcd_import
  File "< frozen importlib._bootstrap  >", line 971, in _find_and_load
  File "< frozen importlib._bootstrap  >", line 941, in _find_and_load_unlocked
  File "< frozen importlib._bootstrap  >", line 219, in _call_with_frames_removed
  File "< frozen importlib._bootstrap  >", line 994, in _gcd_import
  File "< frozen importlib._bootstrap  >", line 971, in _find_and_load
  File "< frozen importlib._bootstrap  >", line 941, in _find_and_load_unlocked
  File "< frozen importlib._bootstrap  >", line 219, in _call_with_frames_removed
  File "< frozen importlib._bootstrap  >", line 994, in _gcd_import
  File "< frozen importlib._bootstrap  >", line 971, in _find_and_load
  File "< frozen importlib._bootstrap >", line 941, in _find_and_load_unlocked
  File "< frozen importlib._bootstrap >", line 219, in _call_with_frames_removed
  File "< frozen importlib._bootstrap >", line 994, in _gcd_import
  File "< frozen importlib._bootstrap >", line 971, in _find_and_load
  File "< frozen importlib._bootstrap >", line 941, in _find_and_load_unlocked
  File "< frozen importlib._bootstrap >", line 219, in _call_with_frames_removed
  File "< frozen importlib._bootstrap >", line 994, in _gcd_import
  File "< frozen importlib._bootstrap >", line 971, in _find_and_load
  File "< frozen importlib._bootstrap >", line 941, in _find_and_load_unlocked
  File "< frozen importlib._bootstrap >", line 219, in _call_with_frames_removed
  File "< frozen importlib._bootstrap >", line 994, in _gcd_import
  File "< frozen importlib._bootstrap >", line 971, in _find_and_load
  File "< frozen importlib._bootstrap >", line 941, in _find_and_load_unlocked
  File "< frozen importlib._bootstrap >", line 219, in _call_with_frames_removed
  File "< frozen importlib._bootstrap >", line 994, in _gcd_import
  File "< frozen importlib._bootstrap >", line 971, in _find_and_load
  File "< frozen importlib._bootstrap >", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'C:'

Can you help me to solve this issue so I can visualize the video? 
Thank you in advanced,

**Comment by Matemasters** [comment]
Thank you very much for your response. 
I haven´t installed python3 ,can you share the "official" download link?
And, how can you manage in writing the .py documents without the path (i.e. without C:\Users\... etc  etc) , do I need to add the path in PATH (the enviroment variable)?
Thanks again !

**Comment by Elteoremadebeethoven** [comment]
It depends on your version of Windows. I recommend version [3.5.6](https://www.python.org/downloads/). You must also install pip3 and install the requirements with pip3. If you have many problems, I recommend that you better install a light distribution of GNU / Linux (such as Lubuntu) in a virtual machine.

**Comment by Matemasters** [comment]
Ok, thank you again. Regards,

**Comment by Elteoremadebeethoven** [comment]
Yes, sorry, I change the variable of "python" for "python3", because you are in Windows. Then, you can use python extrac_,,,

**Comment by Elteoremadebeethoven** [comment]
Check this [video]/(https://www.youtube.com/watch?v=MzV4N4XUvYc) to install whl files and download the pycairo version of

https://www.lfd.uci.edu/~gohlke/pythonlibs/

![captura de pantalla de 2018-10-09 03-08-31](https://user-images.githubusercontent.com/43224662/46655317-e1cec400-cb70-11e8-90a4-3cbab5e272e3.png)

Try of the more recent to older and install again the requieriments.txt with pip3

**Comment by Matemasters** [comment]
Hi and thank you for your kind responses,

 I think I did install well pycairo, because when I type `(manim37) C:\Users\PaKo>pip3 install C:\Users\PaKo\Desktop\Python\pycairo-1.17.1-cp37-cp37m-win_amd64.whl` 
I get
 `Requirement already satisfied: pycairo==1.17.1 from file:///C:/Users/PaKo/Desktop/Python/pycairo-1.17.1-cp37-cp37m-win_amd64.whl in c:\users\pako\anaconda2\envs\manim37\lib\site-packages (1.17.1) `
I also think that I did install well requirements.txt because when I type `(manim37) C:\Users\PaKo>pip3 install -r C:\Users\PaKo\Desktop\Python\3blue_1brown\manim-master\requirements.txt` 
I get 
`Requirement already satisfied: argparse==1.4.0 in c:\users\pako\anaconda2\envs\manim37\lib\site-packages (from -r C:\Users\PaKo\Desktop\Python\3blue_1brown\manim-master\requirements.txt (line 1)) (1.4.0)
Requirement already satisfied: colour==0.1.5 in c:\users\pako\anaconda2\envs\manim37\lib\site-packages (from -r C:\Users\PaKo\Desktop\Python\3blue_1brown\manim-master\requirements.txt (line 2)) (0.1.5)
Requirement already satisfied: numpy==1.15.0 in c:\users\pako\anaconda2\envs\manim37\lib\site-packages (from -r C:\Users\PaKo\Desktop\Python\3blue_1brown\manim-master\requirements.txt (line 3)) (1.15.0)
Requirement already satisfied: Pillow==5.2.0 in c:\users\pako\anaconda2\envs\manim37\lib\site-packages (from -r C:\Users\PaKo\Desktop\Python\3blue_1brown\manim-master\requirements.txt (line 4)) (5.2.0)
Requirement already satisfied: progressbar==2.5 in c:\users\pako\anaconda2\envs\manim37\lib\site-packages (from -r C:\Users\PaKo\Desktop\Python\3blue_1brown\manim-master\requirements.txt (line 5)) (2.5)
Requirement already satisfied: scipy==1.1.0 in c:\users\pako\anaconda2\envs\manim37\lib\site-packages (from -r C:\Users\PaKo\Desktop\Python\3blue_1brown\manim-master\requirements.txt (line 6)) (1.1.0)
Requirement already satisfied: tqdm==4.24.0 in c:\users\pako\anaconda2\envs\manim37\lib\site-packages (from -r C:\Users\PaKo\Desktop\Python\3blue_1brown\manim-master\requirements.txt (line 7)) (4.24.0)
Requirement already satisfied: opencv-python==3.4.2.17 in c:\users\pako\anaconda2\envs\manim37\lib\site-packages (from -r C:\Users\PaKo\Desktop\Python\3blue_1brown\manim-master\requirements.txt (line 8)) (3.4.2.17)
Requirement already satisfied: pycairo==1.17.1 in c:\users\pako\anaconda2\envs\manim37\lib\site-packages (from -r C:\Users\PaKo\Desktop\Python\3blue_1brown\manim-master\requirements.txt (line 9)) (1.17.1)`
Coming back with the error message, python tells me that the error comes from line 127 of `__init__.py` which says the following:

```
def import_module(name, package=None):
    """ Import a module.

    The 'package' argument is required when performing a relative import. It
    specifies the package to use as the anchor point from which to resolve the
    relative import to an absolute import.

   """
    level = 0
    if name.startswith('.'):
        if not package:
            msg = ("the 'package' argument is required to perform a relative "
                   "import for {!r}")
            raise TypeError(msg.format(name))
        for character in name:
            if character != '.':
                break
            level += 1
    return _bootstrap._gcd_import(name[level:], package, level)
```
Do you think I'm missing installing something? Thank you again,

**Comment by Matemasters** [comment]
Well, I kinda fix something... I wrote `(manim37) C:\Users\PaKo>python C:\Users\PaKo\Desktop\Python\3blue_1brown\manim-master\extract_scene.py example_scenes.py SquareToCircle -pl` instead of `(manim37) C:\Users\PaKo>python C:\Users\PaKo\Desktop\Python\3blue_1brown\manim-master\extract_scene.py C:\Users\PaKo\Desktop\Python\3blue_1brown\manim-master\example_scenes.py
SquareToCircle -pl` that is I got rid of 

> C:\Users\PaKo\Desktop\Python\3blue_1brown\manim-master\ 

in example_scenes.py. But now I get a new error (but I think it's better than the last error I got :p)

`Writing to C:\Users\PaKo\Desktop\Python\3blue_1brown\manim-master\example_scenes\480p15\SquareToCircleTemp.mp4



Traceback (most recent call last):
  File "C:\Users\PaKo\Desktop\Python\3blue_1brown\manim-master\extract_scene.py", line 289, in main
    handle_scene(SceneClass(**scene_kwargs), **config)
  File "C:\Users\PaKo\Desktop\Python\3blue_1brown\manim-master\scene\scene.py", line 69, in __init__
    self.open_movie_pipe()
  File "C:\Users\PaKo\Desktop\Python\3blue_1brown\manim-master\scene\scene.py", line 627, in open_movie_pipe
    self.writing_process = sp.Popen(command, stdin=sp.PIPE)
  File "C:\Users\PaKo\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Users\PaKo\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado



El sistema no puede encontrar la ruta especificada.`

Still don't know how to proceed, any ideas? :)

**Comment by Matemasters** [comment]
Finally I got it!  I needed to install ffmpeg through a zip file  (https://www.wikihow.com/Install-FFmpeg-on-Windows) instead by using "pip3 install ffmpeg". Also I made the adjustments shown in https://github.com/3b1b/manim/issues/173 .Thanks for your help!
