### ISSUE TITLE
Can't open videos

### ISSUE THREAD

**Issue by arguiot** [3b1b/manim#32]
Hello, when I'm trying to render a scene, it renders the video, but I can't open it. I'm not getting any errors (except when I try to preview a video), and the file is saved. But, I can't open it, I think it's empty.
I don't think it comes from ffmpeg. I'm running everything with python 2.7, on OS X El Capitan.

This might help:
```terminal
python2.7 extract_scene.py -w example_scenes.py
1: CountingScene
2: PiCreatureScene
3: SquareToCircle
4: TeacherStudentsScene
5: WarpSquare
6: WriteStuff

Choose number corresponding to desired scene/arguments.
(Use comma separated list for multiple entries)

Choice(s): 3
Writing to ~/DEV/others/manim/files/movies/example_scenes/SquareToCircle.mp4
  0%|                                                              | 0/60 [00:00<?, ?it/s]
```

**Comment by rajdakin** [comment]
It's working for me (`###` is my hidden path to manim's folder):
```
python2.7 extract_scene.py -w example_scenes.py
1: CountingScene
2: PiCreatureScene
3: SquareToCircle
4: TeacherStudentsScene
5: WarpSquare
6: WriteStuff

Choose number corresponding to desired scene/arguments.
(Use comma separated list for multiple entries)

Choice(s): 3
Writing to ###/manim/files/movies/example_scenes/SquareToCircle.mp4
Animation 1: ShowCreationSquare: 100%|████████████████████████████████████████████████████████████████████████████████████████| 60/60 [00:11<00:00,  5.34it/s]
Animation 2: TransformSquareToCircle:  75%|██████████████████████████████████████████████████████████████▎                    | 45/60 [00:08<00:02,  5.24it/s]^C



Traceback (most recent call last):
  File "extract_scene.py", line 187, in main
    handle_scene(SceneClass(**scene_kwargs), **config)
  File "###/manim/scene/scene.py", line 48, in __init__
    self.construct(*self.construct_args)
  File "###/manim/./example_scenes.py", line 35, in construct
    self.play(Transform(square, circle))
  File "###/manim/scene/scene.py", line 323, in play
    self.update_frame(moving_mobjects, static_image)
  File "###/manim/scene/scene.py", line 113, in update_frame
    self.capture_mobjects_in_camera(mobjects, **kwargs)
  File "###/manim/scene/scene.py", line 102, in capture_mobjects_in_camera
    self.camera.capture_mobjects(mobjects, **kwargs)
  File "###/manim/camera.py", line 90, in capture_mobjects
    self.display_multiple_vectorized_mobjects(vmobjects)
  File "###/manim/camera.py", line 100, in display_multiple_vectorized_mobjects
    canvas.flush()
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 741, in frombytes
    s = d.decode(data)
KeyboardInterrupt
```

Using a Linux Mint 18.1 system.

PS: the `00:00<?, ?it/s` shown in your terminal's copy affected me somewhere else (I don't remember where), and my `ChoicesInNecklaceCutting.mp4` file seems to be even empty (`262` on the size column when doing `ls -l` on it).

**Comment by eulertour** [comment]
Closing, as this issue is old and inactive.
