### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by 1001root** [3b1b/manim#334]
ashish@CRLannister:~/Documents/Codes/python/3b1b-manim/manim$ python3 extract_scene.py example_scenes.py SquareToCircle -pl
Writing to /home/ashish/Documents/Codes/python/3b1b-manim/manim/output/animations/example_scenes/480p15/SquareToCircleTemp.mp4

Traceback (most recent call last):
  File "extract_scene.py", line 289, in main
    handle_scene(SceneClass(**scene_kwargs), **config)
  File "/home/ashish/Documents/Codes/python/3b1b-manim/manim/scene/scene.py", line 71, in __init__
    self.construct(*self.construct_args)
  File "/home/ashish/Documents/Codes/python/3b1b-manim/manim/example_scenes.py", line 20, in construct
    circle.set_fill(PINK, opacity=0.5)
  File "/home/ashish/Documents/Codes/python/3b1b-manim/manim/mobject/types/vectorized_mobject.py", line 132, in set_fill
    self.update_rgbas_array("fill_rgbas", color, opacity)
  File "/home/ashish/Documents/Codes/python/3b1b-manim/manim/mobject/types/vectorized_mobject.py", line 125, in update_rgbas_array
    curr_rgbas[:, 3] = rgbas[:, 3]
IndexError: index 3 is out of bounds for axis 1 with size 2

**Comment by eulertour** [comment]
Are you still running into this problem? If so, can you describe your installation setup?
