### ISSUE TITLE
AttributeError when running curves.py

### ISSUE THREAD

**Issue by rkuoyemnbeek** [3b1b/manim#37]
Hi,

I am trying to run the code `run extract_scene.py -p curves.py`. 
When choosing one of the scenes, I get attributeErrors. 
These are a few of the errors I get.  
1. scene: BrachistochroneWordSliding
`Traceback (most recent call last):
  File "C:\Users\Koen\manim\extract_scene.py", line 200, in main
    handle_scene(SceneClass(**scene_kwargs), **config)
  File "C:\Users\Koen\manim\scene\scene.py", line 48, in __init__
    self.construct(*self.construct_args)
  File ".\curves.py", line 128, in construct
  File ".\curves.py", line 78, in __init__
  File "C:\Users\Koen\manim\animation\animation.py", line 35, in __init__
    self.update(0)
  File "C:\Users\Koen\manim\animation\animation.py", line 54, in update
    self.update_mobject(self.rate_func(alpha))
  File ".\curves.py", line 95, in update_mobject
AttributeError: 'TexMobject' object has no attribute 'rgbs'`

2. scene BumpyDefineCurveWithKnob
`Traceback (most recent call last):
  File "C:\Users\Koen\manim\extract_scene.py", line 200, in main
    handle_scene(SceneClass(**scene_kwargs), **config)
  File "C:\Users\Koen\manim\scene\scene.py", line 48, in __init__
    self.construct(*self.construct_args)
  File ".\curves.py", line 643, in construct
AttributeError: 'Circle' object has no attribute 'add_line'`

And there are many more. Is this a known phenomenon and how can I deal with this?

kind regards,

**Comment by eulertour** [comment]
Closing, as this issue is old and inactive.
