### ISSUE TITLE
WindowsError: [Error 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by ELAD1010** [3b1b/manim#388]
I am running Python 2.7 in windows 10.
When I'm trying to run a program with scapy command in PyCharm, I get this error:

Traceback (most recent call last):
  File "C:/PycharmProjects/Cyber/sdsd.py", line 4, in <module>
    from scapy.all import*
  File "C:\gvahim\python27\lib\site-packages\scapy\all.py", line 18, in <module>
    from scapy.arch import *
  File "C:\gvahim\python27\lib\site-packages\scapy\arch\__init__.py", line 67, in <module>
    from scapy.arch.windows import *  # noqa F403
  File "C:\gvahim\python27\lib\site-packages\scapy\arch\windows\__init__.py", line 36, in <module>
    from scapy.supersocket import SuperSocket
  File "C:\gvahim\python27\lib\site-packages\scapy\supersocket.py", line 24, in <module>
    import scapy.packet
  File "C:\gvahim\python27\lib\site-packages\scapy\packet.py", line 28, in <module>
    from scapy.extlib import PYX
  File "C:\gvahim\python27\lib\site-packages\scapy\extlib.py", line 54, in <module>
    if _test_pyx():
  File "C:\gvahim\python27\lib\site-packages\scapy\extlib.py", line 45, in _test_pyx
    stdout=devnull, stderr=subprocess.STDOUT)
  File "C:\gvahim\python27\lib\subprocess.py", line 181, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\gvahim\python27\lib\subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\gvahim\python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\gvahim\python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

How Can I fix it?

**Comment by eulertour** [comment]
This problem isn't related to manim, it looks like scapy isn't installed correctly. That said, manim is written for python 3.7 and won't work in python 2.

**Comment by ELAD1010** [comment]
Thank you. 
But,do you know what is the solution to fix my problem?

**Comment by eulertour** [comment]
You have to verify your installation of scapy. I'm going to close this as again, it isn't related to manim.
