### ISSUE TITLE
import readline is failing

### ISSUE THREAD

**Issue by samern92** [3b1b/manim#394]
I am trying to run examples_scenes.py and it threw a ModuleNotFoundError when it tried to import readline. This should be easy to resolve - just pip install readline right? Nope. readline apparently doesn't work on Windows, and I got this strange follow-up error below. I don't know what to do at this point. Help?

c:\Tensorexperiments\manim>python -m manim example_scenes.py SquareToCircle -pl
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Tensorexperiments\manim\manim.py", line 4, in <module>
    import manimlib.stream_starter
  File "c:\Tensorexperiments\manim\manimlib\stream_starter.py", line 4, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'

c:\Tensorexperiments\manim>pip install readline
Collecting readline
  Downloading https://files.pythonhosted.org/packages/f4/01/2cf081af8d880b44939a5f1b446551a7f8d59eae414277fd0c303757ff1b/readline-6.2.4.1.tar.gz (2.3MB)
    100% |████████████████████████████████| 2.3MB 8.5MB/s
    Complete output from command python setup.py egg_info:
    error: this module is not meant to work on Windows
Command "python setup.py egg_info" failed with error code 1 in C:\Users\SAMERN~1\AppData\Local\Temp\pip-install-z8maklzo\readline\

**Comment by samern92** [comment]
Found a fix! Apparently the correct thing to do on Windows is 

pip install pyreadline

**Comment by VaultDeveloper** [comment]
This requirements should be added in the readme.md and requirements.txt
