### ISSUE TITLE
Can't install using anaconda on OSX 10.11.6

### ISSUE THREAD

**Issue by diego898** [3b1b/manim#4]
I can't seem to get it to install on OSX 10.11.6 using the anaconda python distribution. Following your instructions:

```
(python2) ➜  src git clone https://github.com/scottopell/aggdraw-64bits
Cloning into 'aggdraw-64bits'...
remote: Counting objects: 216, done.
remote: Total 216 (delta 0), reused 0 (delta 0), pack-reused 216
Receiving objects: 100% (216/216), 308.91 KiB | 367.00 KiB/s, done.
Resolving deltas: 100% (105/105), done.
Checking connectivity... done.
(python2) ➜  src cd aggdraw-64bits
(python2) ➜  aggdraw-64bits git:(master) python setup.py build_ext -i
=== freetype support disabled
running build_ext
building 'aggdraw' extension
creating build
creating build/temp.macosx-10.5-x86_64-2.7
creating build/temp.macosx-10.5-x86_64-2.7/agg2
creating build/temp.macosx-10.5-x86_64-2.7/agg2/src
gcc -fno-strict-aliasing -I/Users/diego/anaconda/envs/python2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iagg2/include -I/Users/diego/anaconda/envs/python2/include/python2.7 -c aggdraw.cxx -o build/temp.macosx-10.5-x86_64-2.7/aggdraw.o
aggdraw.cxx:504:55: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
        PyObject* buffer = PyObject_CallMethod(image, "tobytes", NULL);
                                                      ^
aggdraw.cxx:530:64: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
        self->draw = new draw_adaptor<agg::pixfmt_gray8>(self, "L");
                                                               ^
aggdraw.cxx:533:64: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
        self->draw = new draw_adaptor<agg::pixfmt_rgb24>(self, "RGB");
                                                               ^
aggdraw.cxx:536:64: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
        self->draw = new draw_adaptor<agg::pixfmt_bgr24>(self, "BGR");
                                                               ^
aggdraw.cxx:539:65: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
        self->draw = new draw_adaptor<agg::pixfmt_rgba32>(self, "RGBA");
                                                                ^
aggdraw.cxx:639:62: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
        result = PyObject_CallFunction(aggdraw_getcolor_obj, "O", color);
                                                             ^
aggdraw.cxx:1059:47: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
    result = PyObject_CallMethod(self->image, "frombytes", "N", buffer);
                                              ^
aggdraw.cxx:1059:60: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
    result = PyObject_CallMethod(self->image, "frombytes", "N", buffer);
                                                           ^
aggdraw.cxx:1114:5: warning: delete called on 'draw_adaptor_base' that is
      abstract but has non-virtual destructor [-Wdelete-non-virtual-dtor]
    delete self->draw;
    ^
aggdraw.cxx:1133:31: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
    static char* kwlist[] = { "color", "width", "opacity", NULL };
                              ^
aggdraw.cxx:1133:40: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
    static char* kwlist[] = { "color", "width", "opacity", NULL };
                                       ^
aggdraw.cxx:1133:49: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
    static char* kwlist[] = { "color", "width", "opacity", NULL };
                                                ^
aggdraw.cxx:1164:31: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
    static char* kwlist[] = { "color", "opacity", NULL };
                              ^
aggdraw.cxx:1164:40: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
    static char* kwlist[] = { "color", "opacity", NULL };
                                       ^
aggdraw.cxx:1195:31: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
    static char* kwlist[] = { "color", "file", "size", "opacity", NULL };
                              ^
aggdraw.cxx:1195:40: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
    static char* kwlist[] = { "color", "file", "size", "opacity", NULL };
                                       ^
aggdraw.cxx:1195:48: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
    static char* kwlist[] = { "color", "file", "size", "opacity", NULL };
                                               ^
aggdraw.cxx:1195:56: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
    static char* kwlist[] = { "color", "file", "size", "opacity", NULL };
                                                       ^
aggdraw.cxx:169:21: warning: unused variable 'FontType' [-Wunused-variable]
static PyTypeObject FontType = {
                    ^
19 warnings generated.
gcc -fno-strict-aliasing -I/Users/diego/anaconda/envs/python2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iagg2/include -I/Users/diego/anaconda/envs/python2/include/python2.7 -c agg2/src/agg_arc.cpp -o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_arc.o
gcc -fno-strict-aliasing -I/Users/diego/anaconda/envs/python2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iagg2/include -I/Users/diego/anaconda/envs/python2/include/python2.7 -c agg2/src/agg_bezier_arc.cpp -o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_bezier_arc.o
gcc -fno-strict-aliasing -I/Users/diego/anaconda/envs/python2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iagg2/include -I/Users/diego/anaconda/envs/python2/include/python2.7 -c agg2/src/agg_curves.cpp -o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_curves.o
gcc -fno-strict-aliasing -I/Users/diego/anaconda/envs/python2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iagg2/include -I/Users/diego/anaconda/envs/python2/include/python2.7 -c agg2/src/agg_path_storage.cpp -o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_path_storage.o
gcc -fno-strict-aliasing -I/Users/diego/anaconda/envs/python2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iagg2/include -I/Users/diego/anaconda/envs/python2/include/python2.7 -c agg2/src/agg_rasterizer_scanline_aa.cpp -o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_rasterizer_scanline_aa.o
gcc -fno-strict-aliasing -I/Users/diego/anaconda/envs/python2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iagg2/include -I/Users/diego/anaconda/envs/python2/include/python2.7 -c agg2/src/agg_trans_affine.cpp -o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_trans_affine.o
gcc -fno-strict-aliasing -I/Users/diego/anaconda/envs/python2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iagg2/include -I/Users/diego/anaconda/envs/python2/include/python2.7 -c agg2/src/agg_vcgen_contour.cpp -o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_vcgen_contour.o
gcc -fno-strict-aliasing -I/Users/diego/anaconda/envs/python2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iagg2/include -I/Users/diego/anaconda/envs/python2/include/python2.7 -c agg2/src/agg_vcgen_stroke.cpp -o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_vcgen_stroke.o
g++ -bundle -undefined dynamic_lookup -L/Users/diego/anaconda/envs/python2/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.5-x86_64-2.7/aggdraw.o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_arc.o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_bezier_arc.o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_curves.o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_path_storage.o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_rasterizer_scanline_aa.o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_trans_affine.o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_vcgen_contour.o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_vcgen_stroke.o -L/Users/diego/anaconda/envs/python2/lib -o /Users/diego/src/aggdraw-64bits/aggdraw.so
(python2) ➜  aggdraw-64bits git:(master) python setup.py install
=== freetype support disabled
running install
running build
running build_ext
building 'aggdraw' extension
gcc -fno-strict-aliasing -I/Users/diego/anaconda/envs/python2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iagg2/include -I/Users/diego/anaconda/envs/python2/include/python2.7 -c aggdraw.cxx -o build/temp.macosx-10.5-x86_64-2.7/aggdraw.o
aggdraw.cxx:504:55: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
        PyObject* buffer = PyObject_CallMethod(image, "tobytes", NULL);
                                                      ^
aggdraw.cxx:530:64: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
        self->draw = new draw_adaptor<agg::pixfmt_gray8>(self, "L");
                                                               ^
aggdraw.cxx:533:64: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
        self->draw = new draw_adaptor<agg::pixfmt_rgb24>(self, "RGB");
                                                               ^
aggdraw.cxx:536:64: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
        self->draw = new draw_adaptor<agg::pixfmt_bgr24>(self, "BGR");
                                                               ^
aggdraw.cxx:539:65: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
        self->draw = new draw_adaptor<agg::pixfmt_rgba32>(self, "RGBA");
                                                                ^
aggdraw.cxx:639:62: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
        result = PyObject_CallFunction(aggdraw_getcolor_obj, "O", color);
                                                             ^
aggdraw.cxx:1059:47: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
    result = PyObject_CallMethod(self->image, "frombytes", "N", buffer);
                                              ^
aggdraw.cxx:1059:60: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
    result = PyObject_CallMethod(self->image, "frombytes", "N", buffer);
                                                           ^
aggdraw.cxx:1114:5: warning: delete called on 'draw_adaptor_base' that is
      abstract but has non-virtual destructor [-Wdelete-non-virtual-dtor]
    delete self->draw;
    ^
aggdraw.cxx:1133:31: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
    static char* kwlist[] = { "color", "width", "opacity", NULL };
                              ^
aggdraw.cxx:1133:40: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
    static char* kwlist[] = { "color", "width", "opacity", NULL };
                                       ^
aggdraw.cxx:1133:49: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
    static char* kwlist[] = { "color", "width", "opacity", NULL };
                                                ^
aggdraw.cxx:1164:31: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
    static char* kwlist[] = { "color", "opacity", NULL };
                              ^
aggdraw.cxx:1164:40: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
    static char* kwlist[] = { "color", "opacity", NULL };
                                       ^
aggdraw.cxx:1195:31: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
    static char* kwlist[] = { "color", "file", "size", "opacity", NULL };
                              ^
aggdraw.cxx:1195:40: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
    static char* kwlist[] = { "color", "file", "size", "opacity", NULL };
                                       ^
aggdraw.cxx:1195:48: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
    static char* kwlist[] = { "color", "file", "size", "opacity", NULL };
                                               ^
aggdraw.cxx:1195:56: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
    static char* kwlist[] = { "color", "file", "size", "opacity", NULL };
                                                       ^
aggdraw.cxx:169:21: warning: unused variable 'FontType' [-Wunused-variable]
static PyTypeObject FontType = {
                    ^
19 warnings generated.
gcc -fno-strict-aliasing -I/Users/diego/anaconda/envs/python2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iagg2/include -I/Users/diego/anaconda/envs/python2/include/python2.7 -c agg2/src/agg_arc.cpp -o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_arc.o
gcc -fno-strict-aliasing -I/Users/diego/anaconda/envs/python2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iagg2/include -I/Users/diego/anaconda/envs/python2/include/python2.7 -c agg2/src/agg_bezier_arc.cpp -o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_bezier_arc.o
gcc -fno-strict-aliasing -I/Users/diego/anaconda/envs/python2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iagg2/include -I/Users/diego/anaconda/envs/python2/include/python2.7 -c agg2/src/agg_curves.cpp -o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_curves.o
gcc -fno-strict-aliasing -I/Users/diego/anaconda/envs/python2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iagg2/include -I/Users/diego/anaconda/envs/python2/include/python2.7 -c agg2/src/agg_path_storage.cpp -o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_path_storage.o
gcc -fno-strict-aliasing -I/Users/diego/anaconda/envs/python2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iagg2/include -I/Users/diego/anaconda/envs/python2/include/python2.7 -c agg2/src/agg_rasterizer_scanline_aa.cpp -o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_rasterizer_scanline_aa.o
gcc -fno-strict-aliasing -I/Users/diego/anaconda/envs/python2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iagg2/include -I/Users/diego/anaconda/envs/python2/include/python2.7 -c agg2/src/agg_trans_affine.cpp -o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_trans_affine.o
gcc -fno-strict-aliasing -I/Users/diego/anaconda/envs/python2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iagg2/include -I/Users/diego/anaconda/envs/python2/include/python2.7 -c agg2/src/agg_vcgen_contour.cpp -o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_vcgen_contour.o
gcc -fno-strict-aliasing -I/Users/diego/anaconda/envs/python2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iagg2/include -I/Users/diego/anaconda/envs/python2/include/python2.7 -c agg2/src/agg_vcgen_stroke.cpp -o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_vcgen_stroke.o
creating build/lib.macosx-10.5-x86_64-2.7
g++ -bundle -undefined dynamic_lookup -L/Users/diego/anaconda/envs/python2/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.5-x86_64-2.7/aggdraw.o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_arc.o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_bezier_arc.o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_curves.o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_path_storage.o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_rasterizer_scanline_aa.o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_trans_affine.o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_vcgen_contour.o build/temp.macosx-10.5-x86_64-2.7/agg2/src/agg_vcgen_stroke.o -L/Users/diego/anaconda/envs/python2/lib -o build/lib.macosx-10.5-x86_64-2.7/aggdraw.so
running install_lib
copying build/lib.macosx-10.5-x86_64-2.7/aggdraw.so -> /Users/diego/anaconda/envs/python2/lib/python2.7/site-packages
running install_egg_info
Removing /Users/diego/anaconda/envs/python2/lib/python2.7/site-packages/aggdraw-1.1_64bits-py2.7.egg-info
Writing /Users/diego/anaconda/envs/python2/lib/python2.7/site-packages/aggdraw-1.1_64bits-py2.7.egg-info
```

I then issue a self test, as described on the [aggdraw repo](https://github.com/scottopell/aggdraw-64bits) and I get:

```
(python2) ➜  aggdraw-64bits git:(master) python selftest.py
Traceback (most recent call last):
  File "selftest.py", line 5, in <module>
    import Image
ImportError: No module named Image
```

But then I fire up ipython to try and import aggdraw and I get:

```
(python2) ➜  aggdraw-64bits git:(master) ipython
Python 2.7.11 |Anaconda 4.0.0 (x86_64)| (default, Dec  6 2015, 18:57:58)
Type "copyright", "credits" or "license" for more information.

IPython 4.1.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from aggdraw import *

In [2]:
```

But when I then try to install the missing requirements I get:

```
(python2) ➜  manim git:(master) pip install -r requirements.txt
Collecting aggdraw===2.0 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement aggdraw===2.0 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for aggdraw===2.0 (from -r requirements.txt (line 1))
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(python2) ➜  manim git:(master)
```

I searched the `ImportError: No module named Image` error during the self test, and I came across the mention of PIL vs [Pillow](https://pillow.readthedocs.io/en/latest/installation.html)

**Comment by jbaldus** [comment]
I deleted the `aggdraw===2.0` line from requirements.txt, since it can't be installed by pip, then re-try `pip install -r requirements.txt` to install Pillow.  Then try the selftest.py in aggdraw.

**Comment by diego898** [comment]
hm I tried that but then got this:

```
➜  manim git:(master) subl requirements.txt
➜  manim git:(master) pip install -r requirements.txt
Collecting colour==0.1.2 (from -r requirements.txt (line 1))
  Downloading colour-0.1.2.tar.gz
Collecting numpy==1.11.0 (from -r requirements.txt (line 2))
  Downloading numpy-1.11.0-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.8MB)
    100% |████████████████████████████████| 3.8MB 171kB/s
Collecting Pillow==1.7.8 (from -r requirements.txt (line 3))
  Downloading Pillow-1.7.8.zip (410kB)
    100% |████████████████████████████████| 419kB 1.1MB/s
Collecting progressbar==2.3 (from -r requirements.txt (line 4))
  Downloading progressbar-2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/mh/f311201s7p1dvk5sp293lmh40000gn/T/pip-build-a1_yrp4i/progressbar/setup.py", line 5, in <module>
        import progressbar
      File "/private/var/folders/mh/f311201s7p1dvk5sp293lmh40000gn/T/pip-build-a1_yrp4i/progressbar/progressbar/__init__.py", line 59, in <module>
        from progressbar.widgets import *
      File "/private/var/folders/mh/f311201s7p1dvk5sp293lmh40000gn/T/pip-build-a1_yrp4i/progressbar/progressbar/widgets.py", line 121, in <module>
        class FileTransferSpeed(Widget):
      File "/Users/diego/anaconda/lib/python3.5/abc.py", line 133, in __new__
        cls = super().__new__(mcls, name, bases, namespace)
    ValueError: 'format' in __slots__ conflicts with class variable

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/mh/f311201s7p1dvk5sp293lmh40000gn/T/pip-build-a1_yrp4i/progressbar/
➜  manim git:(master) ✗
```

That seems unrelated so ill look into that and report back. Thanks!

**Comment by vladimir-mezentsev** [comment]
the last error occurs with python3. I reckon, this rep is meant to be built with python 2.

**Comment by scottopell** [comment]
the aggdraw self test doesn't work on my end either, and everything works fine for me. So that's just a red herring.

(note I just forked the aggdraw repo onto github, I'm not a dev on it)

**Comment by diego898** [comment]
closing old issue
