### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Janphr** [3b1b/manim#403]
Any idea? using debian subsystem on windows 10

Successfully installed Pillow-5.2.0 argparse-1.4.0 colour-0.1.5 numpy-1.15.0 opencv-python-3.4.2.17 progressbar-2.5 pycairo-1.17.1 scipy-1.1.0 tqdm-4.24.0

janphr@PC:/manim$ python3 -m manim example_scenes.py SquareToCircle -pl
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/janphr/manim/manim.py", line 2, in <module>
    import manimlib.config
  File "/home/janphr/manim/manimlib/config.py", line 88
    print(f"Failed to render scene: {str(e)}")
                                            ^
SyntaxError: invalid syntax

janphr@PC:/manim$ python3 --version
Python 3.5.3

**Comment by icreiuheciijc** [comment]
The `f"{}"` string format syntax is not supported in Python 3.5. Only Python 3.6 or above does.

**Comment by Janphr** [comment]
tanks!
