### ISSUE TITLE
name 'self' is not defined

### ISSUE THREAD

**Issue by financialphysician** [3b1b/manim#414]
I'm trying to run the following scene from a tutorial that a physics professor at University of Wisconsin put together. In the last handful of examples, I kept getting 

```
NameError: name 'self' is not defined
```

The following code is what I'm running. Any ideas?

```
class ExampleThreeD(ThreeDScene):
	CONFIG = {
	"plane_kwargs" : {
	"color" : RED_B
	},
	"point_charge_loc" : 0.5*RIGHT-1.5*UP,
	}
	def construct(self):
		#self.set_camera_position(0, -np.pi/2) #Old code
		plane = NumberPlane(**self.plane_kwargs)
		plane.main_lines.fade(.9)
		plane.add(plane.get_axis_labels())
		self.add(plane)
		
		field2D = VGroup(*[self.calc_field2D(x*RIGHT+y*UP)
		for x in np.arange(-9,9,1)
		for y in np.arange(-5,5,1)
		])
		
		self.set_camera_orientation(phi=PI/3,gamma=PI/5)
		self.play(ShowCreation(field2D))
		self.wait()
		self.move_camera(gamma=0)
		self.move_camera(phi=3/4*PI, theta=-PI/2)
		self.begin_ambient_camera_rotation(rate=0.1)
		self.wait(6)
	
	def calc_field2D(self,point):
		x,y = point[:2]
		Rx,Ry = self.point_charge_loc[:2]
		r = math.sqrt((x-Rx)**2 + (y-Ry)**2)
		efield = (point - self.point_charge_loc)/r**3
		return Vector(efield).shift(point)
```

**Comment by fukanchik** [comment]
Worked ok for me. Produced 10 seconds of animation.
What is the exact error you see?

**Comment by financialphysician** [comment]
Here's what the terminal is saying. I'll attach the file as well. (better to have too much info than too little)

'''
python3 -m manim manim_tutorial_1.py ExampleThreeD -pl
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/guest/code/manim/manim.py", line 9, in <module>
    config = manimlib.config.get_configuration(args)
  File "/Users/guest/code/manim/manimlib/config.py", line 111, in get_configuration
    "module": get_module(args.file),
  File "/Users/guest/code/manim/manimlib/config.py", line 92, in get_module
    return importlib.import_module(module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/guest/code/manim/manim_tutorial_1.py", line 331, in <module>
    class MovingCharges(Scene):
  File "/Users/guest/code/manim/manim_tutorial_1.py", line 372, in MovingCharges
    self.play(FadeIn(particles))
NameError: name 'self' is not defined
'''

**Comment by eulertour** [comment]
It looks like lines 372-376 of your script should be indented. The problem isn't related to the snippet you included, or to the rest of the library code.

**Comment by financialphysician** [comment]
> It looks like lines 372-376 of your script should be indented. The problem isn't related to the snippet you included, or to the rest of the library code.

You're totally right. It's so obvious after looking at the error again. Thank you for figuring that out.
