### ISSUE TITLE
Problems with 3D Scene

### ISSUE THREAD

**Issue by Elteoremadebeethoven** [3b1b/manim#428]
Hi every one. In the most recent version of manim (4/Feb/19) when I try run:
```sh
python3 -m manim old_projects/sphere_area.py SphereCylinderScene -pl
```

I have:
```sh
Traceback (most recent call last):
  File "/Users/alexlvazquez/Downloads/manim-master/manimlib/extract_scene.py", line 153, in main
    scene = SceneClass(**scene_kwargs)
  File "/Users/alexlvazquez/Downloads/manim-master/manimlib/scene/three_d_scene.py", line 149, in __init__
    if self.camera.get_pixel_width() == PRODUCTION_QUALITY_CAMERA_CONFIG["pixel_width"]:
AttributeError: 'SphereCylinderScene' object has no attribute 'camera'
```

And if I add in manimlib/scene/three_d_scene, in the line 149:
```python3
 self.camera = self.camera_class(**self.camera_config)
```
Then I have:
```sh
/Users/alexvazquez/Downloads/manim-master 2/media/videos/old_projects/sphere_area/480p15/partial_movie_files/SphereCylinderScene/partial_movie_file_list.txt: Invalid data found when processing input

File ready at /Users/alexvazquez/Downloads/manim-master 2/media/videos/old_projects/sphere_area/480p15/SphereCylinderScene.mp4
```

But the directory is empy.

Thanks for you help, I don't know what to do.

**Comment by Elteoremadebeethoven** [comment]
I understand perfectly what you want to tell me. You don't care that your old videos run in all versions of manim because that is very tedious. The reason of my cuestion is because I'm not  expert to understand why. And do not worry, I can perfectly compile the videos in old versions, I just wanted to learn more. 

Thanks for answering.
