### ISSUE TITLE
AttributeError: 'FadeOutAndShiftDown' object has no attribute 'starting_mobject'

### ISSUE THREAD

**Issue by xy-23** [3b1b/manim#436]
When I run this: py -m manim example_scenes.py OpeningManimExample -pl
It rendered some videos but then thrown an error:
Traceback (most recent call last):
  File "C:\Users\xy\Desktop\manim\manimlib\extract_scene.py", line 153, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\Users\xy\Desktop\manim\manimlib\scene\scene.py", line 54, in __init__
    self.construct()
  File "example_scenes.py", line 34, in construct
    OldLaggedStart(FadeOutAndShiftDown, basel),
  File "C:\Users\xy\Desktop\manim\manimlib\scene\scene.py", line 455, in wrapper
    func(self, *args, **kwargs)
  File "C:\Users\xy\Desktop\manim\manimlib\scene\scene.py", line 512, in play
    self.finish_animations(animations)
  File "C:\Users\xy\Desktop\manim\manimlib\scene\scene.py", line 493, in finish_animations
    animation.clean_up_from_scene(self)
  File "C:\Users\xy\Desktop\manim\manimlib\animation\composition.py", line 186, in clean_up_from_scene
    anim.clean_up_from_scene(*args, **kwargs)
  File "C:\Users\xy\Desktop\manim\manimlib\animation\fading.py", line 23, in clean_up_from_scene
    self.interpolate(0)
  File "C:\Users\xy\Desktop\manim\manimlib\animation\animation.py", line 111, in interpolate
    self.interpolate_mobject(self.rate_func(alpha))
  File "C:\Users\xy\Desktop\manim\manimlib\animation\animation.py", line 121, in interpolate_mobject
    families = list(self.get_all_families_zipped())
  File "C:\Users\xy\Desktop\manim\manimlib\animation\transform.py", line 99, in get_all_families_zipped
    self.starting_mobject,
AttributeError: 'FadeOutAndShiftDown' object has no attribute 'starting_mobject'
Is this a bug?

**Comment by xy-23** [comment]
btw, what is Udaters mean?

**Comment by 3b1b** [comment]
Ah, my fault, I recently changed how LaggedStart worked and didn't replace it properly in this examples file.  I just updated it, and things should work now.

**Comment by xy-23** [comment]
Now it works, thanks.
