### ISSUE TITLE
Some shape constructors not working

### ISSUE THREAD

**Issue by jeanimal** [3b1b/manim#446]
I have been getting errors in shape constructors when trying to run the tutorial at https://github.com/zimmermant/manim_tutorial/blob/master/manim_tutorial_P37.py.

I run it like this:
python3 -m manim manim_tutorial_P37.py MoreShapes -pl

First I got an error in the Ellipse constructor: "name 'width' is not defined"-- the full stack is below.  I think I fixed it with
https://github.com/3b1b/manim/compare/master...jeanimal:patch-1

Then I got an error in the CurvedArrow constructor: 'CurvedArrow' object has no attribute 'get_length'
I do not have a proposed fix (which would require implementing get_length()).

Stack trace for Ellipse constructor problem...
Traceback (most recent call last):
  File "/Users/me/Code/python3/manim/manimlib/extract_scene.py", line 153, in main
    scene = SceneClass(**scene_kwargs)
  File "/Users/me/Code/python3/manim/manimlib/scene/scene.py", line 52, in __init__
    self.construct()
  File "manim_tutorial_P37.py", line 33, in construct
    ellipse=Ellipse(width=3, height=1, color=RED)
  File "/Users/me/Code/python3/manim/manimlib/mobject/geometry.py", line 319, in __init__
    self.set_width(width, stretch=True)
NameError: name 'width' is not defined

Stack trace for CurvedArrow constructor problem...
Traceback (most recent call last):
File "/Users/me/Code/python3/manim/manimlib/extract_scene.py", line 153, in main
scene = SceneClass(**scene_kwargs)
File "/Users/me/Code/python3/manim/manimlib/scene/scene.py", line 52, in **init**
self.construct()
File "manim_tutorial_P37.py", line 35, in construct
pointer = CurvedArrow(2_RIGHT,5_RIGHT,color=MAROON_C)
File "/Users/me/Code/python3/manim/manimlib/mobject/geometry.py", line 250, in **init**
self.add_tip()
File "/Users/me/Code/python3/manim/manimlib/mobject/geometry.py", line 45, in add_tip
self.reset_endpoints_based_on_tip(tip, at_start)
File "/Users/me/Code/python3/manim/manimlib/mobject/geometry.py", line 84, in reset_endpoints_based_on_tip
if self.get_length() == 0:
AttributeError: 'CurvedArrow' object has no attribute 'get_length'

**Comment by jeanimal** [comment]
I have a pull request to fix CurvedArrow.  (It just reverts the commit that resulted in the bug.)

https://github.com/3b1b/manim/pull/454
