### ISSUE TITLE
zeta.py AttributeError: 'ShowZetaOnHalfPlane' object has no attribute 'y_min'

### ISSUE THREAD

**Issue by lc3t35** [3b1b/manim#52]
When I run 
````
python extract_scene.py -p old_projects/zeta.py ShowZetaOnHalfPlane
````
I have the following error 
````
Writing "\zeta( s )= \frac{1}{1^s} +  \frac{1}{2^s} +  \frac{1}{3^s} +  \frac{1}{4^s} +  \cdots" to /Users/laurent/Work/xxxx/manim/files/Tex/-5201468256000681301.tex
Writing "\zeta(" to /Users/laurent/Work/xxxx/manim/files/Tex/3529308138940232413.tex
Writing ")=" to /Users/laurent/Work/xxxx/manim/files/Tex/8430908102380925009.tex
Writing "\frac{1}{1^s} +" to /Users/laurent/Work/xxxx/manim/files/Tex/1583025563881409802.tex
Writing "\frac{1}{2^s} +" to /Users/laurent/Work/xxxx/manim/files/Tex/6484072650047720569.tex
Writing "\frac{1}{3^s} +" to /Users/laurent/Work/xxxx/manim/files/Tex/1463901432775095568.tex
Writing "\frac{1}{4^s} +" to /Users/laurent/Work/xxxxs/manim/files/Tex/5428990312259487727.tex
Writing "\cdots" to /Users/laurent/Work/xxxx/manim/files/Tex/5511331107690932742.tex

Traceback (most recent call last):
  File "extract_scene.py", line 206, in main
    handle_scene(SceneClass(**scene_kwargs), **config)
  File "/Users/laurent/Work/xxxx/manim/scene/scene.py", line 52, in __init__
    self.construct(*self.construct_args)
  File "/Users/laurent/Work/xxxx/manim/./old_projects/zeta.py", line 1760, in construct
    self.initial_transformation()
  File "/Users/laurent/Work/xxxx/manim/./old_projects/zeta.py", line 1788, in initial_transformation
    self.add_extra_plane_lines_for_zeta(animate = True)
  File "/Users/laurent/Work/xxxx/manim/./old_projects/zeta.py", line 84, in add_extra_plane_lines_for_zeta
    dense_grid = self.get_dense_grid(**kwargs)
  File "/Users/laurent/Work/xxxx/manim/./old_projects/zeta.py", line 98, in get_dense_grid
    max(self.y_min, self.extra_lines_y_min),
AttributeError: 'ShowZetaOnHalfPlane' object has no attribute 'y_min'

sh: play: command not found
````

**Comment by lc3t35** [comment]
Solved by adding in CONFIG : 
````
"y_min" : 1,
"y_max" : int(SPACE_WIDTH+2),
````

**Comment by lc3t35** [comment]
Noticed also missing image Riemann : 
````
photo = ImageMobject("Riemann", invert = False)
````

**Comment by eulertour** [comment]
Closing, since this issue seems to be resolved.
