### ISSUE TITLE
Attribute Error: 'NoneType' object has no attribute 'loader'

### ISSUE THREAD

**Issue by elmiba** [3b1b/manim#534]
Hi folks,
I have a slight problem and no idea how to solve it. 
due to the fact that I am doeing this for school, I have quite some time pressure so I'm hoping you could help me. ://

Here is my error message:

`Manim> Py -m manim "test folder manim"\test_folder_manim.py Shapes -pl
Media will be stored in ./media\. You can change this behavior by writing a different directory to media_dir.txt.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\Manim\manim.py", line 5, in <module>
    manimlib.main()
  File "C:\Users\user\Manim\manimlib\__init__.py", line 10, in main
    config = manimlib.config.get_configuration(args)
  File "C:\Users\user\Manim\manimlib\config.py", line 158, in get_configuration
    module = get_module(args.file)
  File "C:\Users\user\Manim\manimlib\config.py", line 152, in get_module
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 580, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'`

I was trying to run the test file from this tutorial: [https://talkingphysics.wordpress.com/2019/01/08/getting-started-animating-with-manim-and-python-3-7/]

I'm running a WIN10 machine, using Py 3.7 and I've installed all the necessary packages the day before yesterday.

Cheers 
elmiba

 P.S.: By the way, doese anyone know what the big_ol_pile_of_manim_imports is, because I can't find that anywhere to import it...

**Comment by Elteoremadebeethoven** [comment]
"big_ol_pile_of_manim_imports" does not exist anymore, now is "manimlib/imports":
````python3
from manimlib.imports import *
````
That line imports all packages of manim: Animations, Classes, Methods, etc.

Then, the complete code are:
````python3
from manimlib.imports import *

class Shapes(Scene):
    def construct(self):
        circle = Circle()
        square = Square()
        line=Line(np.array([3,0,0]),np.array([5,0,0]))
        triangle=Polygon(np.array([0,0,0]),np.array([1,1,0]),np.array([1,-1,0]))

        self.add(line)
        self.play(ShowCreation(circle))
        self.play(FadeOut(circle))
        self.play(GrowFromCenter(square))
        self.play(Transform(square,triangle))
````

**Comment by elmiba** [comment]
Thanks a lot!! 
I will try it in the evening when I’m back home. 

Elmiba

**Comment by elmiba** [comment]
Thank you for your awnser and it solved my problem but like murphys law says I have a new problemt to solve...
 @Elteoremadebeethoven

**Comment by elmiba** [comment]
I thought I got this problem solved, but it seems like I couldn't solve it. 

I tried using conda the las few days, but then I get no output, as described in Issue #538 .

Switching back to the normal install I get the same error again also with the code above...

Here is the output:

```cmd
C:\Users\USER\manim>Py -m manim QuadratZuKreis -pl
Media will be stored in ./media\. You can change this behavior by writing a different directory to media_dir.txt.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\manim\manim.py", line 5, in <module>
    manimlib.main()
  File "C:\Users\USER\manim\manimlib\__init__.py", line 10, in main
    config = manimlib.config.get_configuration(args)
  File "C:\Users\USER\manim\manimlib\config.py", line 158, in get_configuration
    module = get_module(args.file)
  File "C:\Users\USER\manim\manimlib\config.py", line 152, in get_module
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 580, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'
```

I hope somebody could help me!

Maybe it is because of Visual Studio being installed.

Thanks elmiba

**Comment by sososea** [comment]
Have you solved the problem, because I met the same problem with u
