### ISSUE TITLE
TypeError: remove_list_redundancies() missing 1 required positional argument: 'l'

### ISSUE THREAD

**Issue by elmiba** [3b1b/manim#539]
Hi there,
here I go again, with another error:

I tried to run the first Scene in the example file:
```python
from manimlib.imports import *

# To watch one of these scenes, run the following:
# python -m manim example_scenes.py SquareToCircle -pl
#
# Use the flat -l for a faster rendering at a lower
# quality.
# Use -s to skip to the end and just save the final frame
# Use the -p to have the animation (or image, if -s was
# used) pop up once done.
# Use -n <number> to skip ahead to the n'th animation of a scene.


class OpeningManimExample(Scene):
    def construct(self):
        title = TextMobject("This is some \\LaTeX")
        basel = TexMobject(
            "\\sum_{n=1}^\\infty "
            "\\frac{1}{n^2} = \\frac{\\pi^2}{6}"
        )
        VGroup(title, basel).arrange(DOWN)
        self.play(
            Write(title),
            FadeInFrom(basel, UP),
        )
        self.wait()

        transform_title = TextMobject("That was a transform")
        transform_title.to_corner(UP + LEFT)
        self.play(
            Transform(title, transform_title),
            LaggedStart(*map(FadeOutAndShiftDown, basel)),
        )
        self.wait()

        grid = NumberPlane()
        grid_title = TextMobject("This is a grid")
        grid_title.scale(1.5)
        grid_title.move_to(transform_title)

        self.add(grid, grid_title)  # Make sure title is on top of grid
        self.play(
            FadeOut(title),
            FadeInFromDown(grid_title),
            ShowCreation(grid, run_time=3, lag_ratio=0.1),
        )
        self.wait()

        grid_transform_title = TextMobject(
            "That was a non-linear function \\\\"
            "applied to the grid"
        )
        grid_transform_title.move_to(grid_title, UL)
        grid.prepare_for_nonlinear_transform()
        self.play(
            grid.apply_function,
            lambda p: p + np.array([
                np.sin(p[1]),
                np.sin(p[0]),
                0,
            ]),
            run_time=3,
        )
        self.wait()
        self.play(
            Transform(grid_title, grid_transform_title)
        )
        self.wait()

``` 
And got this error message:
```cmd
C:\Users\USER\manim>Py -m manim example_scenes.py OpeningManimExample -pl
Media will be stored in ./media\. You can change this behavior by writing a different directory to media_dir.txt.



Traceback (most recent call last):
  File "C:\Users\USER\manim\manimlib\extract_scene.py", line 150, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\Users\USER\manim\manimlib\scene\scene.py", line 52, in __init__
    self.construct()
  File "example_scenes.py", line 34, in construct
    LaggedStart(*map(FadeOutAndShiftDown, basel)),
  File "C:\Users\USER\manim\manimlib\animation\composition.py", line 33, in __init__
    self.group = Group(*remove_list_redundancies(
TypeError: remove_list_redundancies() missing 1 required positional argument: 'l'
```

I tried filling in the 'missing' "l" and got this error message:
```cmd
C:\Users\USER\manim>Py -m manim example_scenes.py OpeningManimExample -pl
Media will be stored in ./media\. You can change this behavior by writing a different directory to media_dir.txt.



Traceback (most recent call last):
  File "C:\Users\USER\manim\manimlib\extract_scene.py", line 150, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\Users\USER\manim\manimlib\scene\scene.py", line 52, in __init__
    self.construct()
  File "example_scenes.py", line 34, in construct
    LaggedStart(*map(FadeOutAndShiftDown, basel)),
  File "C:\Users\USER\manim\manimlib\animation\composition.py", line 33, in __init__
    self.group = Group(*remove_list_redundancies(l
NameError: name 'l' is not defined
```

I hope somebody could help me out ;)

Thanks!

**Comment by elmiba** [comment]
Edit: This only happens in some codes and I still didn‘t figure out what causes that.

**Comment by Kolloom** [comment]
Can't replicate using ubuntu 19.04 venv installation. Any windows users care to check?

**Comment by Kolloom** [comment]
The line should have been like this: https://github.com/3b1b/manim/blob/master/manimlib/animation/composition.py#L33
