### ISSUE TITLE
No module named manimlib.__main__

### ISSUE THREAD

**Issue by ConorONeill2** [3b1b/manim#575]
I've installed manim, but can't get it to run the example scenes. I input this command into the command line:

```python -m manimlib example_scenes.py SquareToCircle -pl```

And I get the following back:

```Media will be stored in ./media\. You can change this behavior by writing a different directory to media_dir.txt.
[File Path]\Python37-32\lib\site-packages\pydub\utils.py:165: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
[File Path]\Python37-32\python.exe: No module named manimlib.__main__; 'manimlib' is a package and cannot be directly executed```

So there's two problems there - first, I have ffmpeg installed in the same folder as all my other libraries, and it works fine, so I don't know why it's not being found here. Second, and far more importantly, I don't know why it's trying to read manimlib.__main__, and if that file is meant to exist but somehow didn't get installed, or if something wonky is going on that it's trying to read a file it's not meant to.

I'm running Python 3.7 on a Windows 10 OS.

**Comment by Kolloom** [comment]
try ``python -m manim example_scenes.py SquareToCircle -pl``

**Comment by NewWorldVulture** [comment]
I'm having the same issue as OP.
When I run the snip you recommended, I get the following:
```
python -m manim example_scenes.py SquareToCircle -pl
C:\Users\~\AppData\Local\Programs\Python\Python37-32\python.exe: No module named manim
```
Environment variables are set up fine, confirmed that `manimlib` is installed.

**Comment by Kolloom** [comment]
@NewWorldVulture 

Did you install it with pip3 from pypi?
Run it with ``python3``
On some system python defaults to 2.7

**Comment by NewWorldVulture** [comment]
There's no Python 2 on this computer. Just to confirm, I ran it with python3:
`python3 -m manim example_scenes.py SquareToCircle -pl
'python3' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by Kolloom** [comment]
are you running from within the manim repo ?

**Comment by NewWorldVulture** [comment]
Ah. My brain just now turned on.
No, I downloaded manimlib through pip, so of course I won't have the example_scenes.py.
I'm able to `import manimlib` in a Python shell, so I don't think this is an actual issue. If OP followed the same Windows Installation instructions I did, I suspect they're in the same boat. We won't be able to run the commands "as is".
Thank you for helping, @Kolloom !

**Comment by bwanaaa** [comment]
I created a conda environment and installed all the necessary packages including manimlib.
Then I can get this line to run

`python3 -m manim example_scenes.py SquareToCircle -pl
`
if I start a terminal from inside the manim directory after I 'git clone' this project.
The correct animations are written in the correct directories.

But what does the -pl switch do?

Also, how do I use manim from the python interpreter?
This seems to fail:
```
$ python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import manimlib
Media will be stored in ./media/. You can change this behavior by writing a different directory to media_dir.txt.
>>> from example_scenes import *
>>> SquareToCircle
<class 'example_scenes.SquareToCircle'>
>>> SquareToCircle()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stefan/miniconda3/envs/manim/lib/python3.7/site-packages/manimlib/scene/scene.py", line 37, in __init__
    self, **self.file_writer_config,
  File "/home/stefan/miniconda3/envs/manim/lib/python3.7/site-packages/manimlib/scene/scene_file_writer.py", line 44, in __init__
    self.init_output_directories()
  File "/home/stefan/miniconda3/envs/manim/lib/python3.7/site-packages/manimlib/scene/scene_file_writer.py", line 49, in init_output_directories
    output_directory = self.output_directory or self.get_default_output_directory()
  File "/home/stefan/miniconda3/envs/manim/lib/python3.7/site-packages/manimlib/scene/scene_file_writer.py", line 80, in get_default_output_directory
    filename = os.path.basename(self.input_file_path)
AttributeError: 'SceneFileWriter' object has no attribute 'input_file_path'
>>> SquareToCircle('/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() takes 1 positional argument but 2 were given
>>> SquareToCircle('./')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() takes 1 positional argument but 2 were given
```

How can I execute my script from within the python interpreter?

**Comment by yoshiask** [comment]
@ConorONeill2 Are you still having issues?

**Comment by stevenschn** [comment]
> Ah. My brain just now turned on.
> No, I downloaded manimlib through pip, so of course I won't have the example_scenes.py.
> I'm able to `import manimlib` in a Python shell, so I don't think this is an actual issue. If OP followed the same Windows Installation instructions I did, I suspect they're in the same boat. We won't be able to run the commands "as is".
> Thank you for helping, @Kolloom !

Any comments on how you fixed this or what commands you did use!? I am in the same boat but have no clue...
