### ISSUE TITLE
Latex error converting to dvi

### ISSUE THREAD

**Issue by HariprasadBS** [3b1b/manim#601]
Traceback (most recent call last):
  File "C:\Manim\manim\manimlib\extract_scene.py", line 150, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\Manim\manim\manimlib\scene\scene.py", line 52, in __init__
    self.construct()
  File "example_scenes.py", line 20, in construct
    title = TextMobject("This is some \\LaTeX")
  File "C:\Manim\manim\manimlib\mobject\svg\tex_mobject.py", line 144, in __init__
    self, self.arg_separator.join(tex_strings), **kwargs
  File "C:\Manim\manim\manimlib\mobject\svg\tex_mobject.py", line 44, in __init__
    self.template_tex_file_body
  File "C:\Manim\manim\manimlib\utils\tex_file_writing.py", line 19, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
  File "C:\Manim\manim\manimlib\utils\tex_file_writing.py", line 67, in tex_to_dvi
    "See log output above or the log file: %s" % log_file)
Exception: Latex error converting to dvi. See log output above or the log file: ./media\Tex\081b5f87a6472151.log

please help me resolve this. thx.

**Comment by Kolloom** [comment]
Please paste the log file

**Comment by HariprasadBS** [comment]
the problem is resolved. thx. :)
