### ISSUE TITLE
MikTex error?

### ISSUE THREAD

**Issue by Bergjensen33** [3b1b/manim#676]
Hello, I'm using Windows 10 64 bits.
```
Traceback (most recent call last):
  File "c:\users\3301\appdata\local\programs\python\python37\lib\site-packages\manimlib\extract_scene.py", line 150, in main
    scene = SceneClass(**scene_kwargs)
  File "c:\users\3301\appdata\local\programs\python\python37\lib\site-packages\manimlib\scene\scene.py", line 52, in __init__
    self.construct()
  File "example_scenes.py", line 20, in construct
    title = TextMobject("This is some \\LaTeX")
  File "c:\users\3301\appdata\local\programs\python\python37\lib\site-packages\manimlib\mobject\svg\tex_mobject.py", line 144, in __init__
    self, self.arg_separator.join(tex_strings), **kwargs
  File "c:\users\3301\appdata\local\programs\python\python37\lib\site-packages\manimlib\mobject\svg\tex_mobject.py", line 44, in __init__
    self.template_tex_file_body
  File "c:\users\3301\appdata\local\programs\python\python37\lib\site-packages\manimlib\utils\tex_file_writing.py", line 19, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
  File "c:\users\3301\appdata\local\programs\python\python37\lib\site-packages\manimlib\utils\tex_file_writing.py", line 67, in tex_to_dvi
    "See log output above or the log file: %s" % log_file)
Exception: Latex error converting to dvi. See log output above or the log file: Tex\081b5f87a6472151.log
```

The log:
```
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (MiKTeX 2.9.7140 64-bit) (preloaded format=latex 2019.8.9)  9 AUG 2019 17:11
entering extended mode
**./Tex/081b5f87a6472151.tex
(Tex/081b5f87a6472151.tex
LaTeX2e <2018-12-01>

("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/standalone\standalo
ne.cls"
Document Class: standalone 2018/03/26 v1.3a Class to compile TeX sub-files stan
dalone
("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/tools\shellesc.sty"
Package: shellesc 2016/06/07 v0.02a unified shell escape interface for LaTeX
Package shellesc Info: Restricted shell escape enabled on input line 69.
)
("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/generic/oberdiek\ifluatex
.sty"
Package: ifluatex 2016/05/16 v1.4 Provides the ifluatex switch (HO)
Package ifluatex Info: LuaTeX not detected.
)
("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/generic/oberdiek\ifpdf.st
y"
Package: ifpdf 2018/09/07 v3.3 Provides the ifpdf switch
)
("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/generic/ifxetex\ifxetex.s
ty"
Package: ifxetex 2010/09/12 v0.6 Provides ifxetex conditional
) ("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/xkeyval\xkeyval.s
ty"
Package: xkeyval 2014/12/03 v2.7a package option processing (HA)

("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/generic/xkeyval\xkeyval.t
ex"
("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/generic/xkeyval\xkvutils.
tex"
\XKV@toks=\toks14
\XKV@tempa@toks=\toks15

("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/generic/xkeyval\keyval.te
x"))
\XKV@depth=\count80
File: xkeyval.tex 2014/12/03 v2.7a key=value parser (HA)
))
\sa@internal=\count81
\c@sapage=\count82

("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/standalone\standalo
ne.cfg"
File: standalone.cfg 2018/03/26 v1.3a Default configuration file for 'standalon
e' class
) ("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/base\article.cls"
Document Class: article 2018/09/03 v1.4i Standard LaTeX document class
("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/base\size10.clo"
File: size10.clo 2018/09/03 v1.4i Standard LaTeX file (size option)
)
\c@part=\count83
\c@section=\count84
\c@subsection=\count85
\c@subsubsection=\count86
\c@paragraph=\count87
\c@subparagraph=\count88
\c@figure=\count89
\c@table=\count90
\abovecaptionskip=\skip41
\belowcaptionskip=\skip42
\bibindent=\dimen102
) ("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/preview\preview.s
ty"
Package: preview 2017/04/24 11.91 (AUCTeX/preview-latex)

("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/generic/luatex85\luatex85
.sty"
Package: luatex85 2016/06/15 v1.4 pdftex aliases for luatex
)
("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/preview\prtightpage
.def"
\PreviewBorder=\dimen103
)
\pr@snippet=\count91
\pr@box=\box27
\pr@output=\toks16
)) ("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/generic/babel\babel.st
y"
Package: babel 2019/07/19 3.33 The Babel package
("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/generic/babel\switch.def"
File: switch.def 2019/07/19 3.33 Babel switching mechanism
)
*************************************
* Local config file bblopts.cfg used
*
("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/arabi\bblopts.cfg"
File: bblopts.cfg 2005/09/08 v0.1 add Arabic and Farsi to "declared" options of
 babel
)
("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/babel-english\engli
sh.ldf"
Language: english 2017/06/06 v3.3r English support from the babel system
("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/generic/babel\babel.def"
File: babel.def 2019/07/19 3.33 Babel common definitions
\babel@savecnt=\count92
\U@D=\dimen104

("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/generic/babel\txtbabel.de
f")
\bbl@dirlevel=\count93
)
\l@canadian = a dialect from \language\l@american 
\l@australian = a dialect from \language\l@british 
\l@newzealand = a dialect from \language\l@british 
)) ("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/amsmath\amsmath.
sty"
Package: amsmath 2018/12/01 v2.17b AMS math features
\@mathmargin=\skip43
For additional information on amsmath, use the `?' option.
("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/amsmath\amstext.sty
"
Package: amstext 2000/06/29 v2.01 AMS text
("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/amsmath\amsgen.sty"
File: amsgen.sty 1999/11/30 v2.0 generic functions
\@emptytoks=\toks17
\ex@=\dimen105
)) ("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/amsmath\amsbsy.s
ty"
Package: amsbsy 1999/11/29 v1.2d Bold Symbols
\pmbraise@=\dimen106
) ("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/amsmath\amsopn.st
y"
Package: amsopn 2016/03/08 v2.02 operator names
)
\inf@bad=\count94
LaTeX Info: Redefining \frac on input line 223.
\uproot@=\count95
\leftroot@=\count96
LaTeX Info: Redefining \overline on input line 385.
\classnum@=\count97
\DOTSCASE@=\count98
LaTeX Info: Redefining \ldots on input line 482.
LaTeX Info: Redefining \dots on input line 485.
LaTeX Info: Redefining \cdots on input line 606.
\Mathstrutbox@=\box28
\strutbox@=\box29
\big@size=\dimen107
LaTeX Font Info:    Redeclaring font encoding OML on input line 729.
LaTeX Font Info:    Redeclaring font encoding OMS on input line 730.
\macc@depth=\count99
\c@MaxMatrixCols=\count100
\dotsspace@=\muskip10
\c@parentequation=\count101
\dspbrk@lvl=\count102
\tag@help=\toks18
\row@=\count103
\column@=\count104
\maxfields@=\count105
\andhelp@=\toks19
\eqnshift@=\dimen108
\alignsep@=\dimen109
\tagshift@=\dimen110
\tagwidth@=\dimen111
\totwidth@=\dimen112
\lineht@=\dimen113
\@envbody=\toks20
\multlinegap=\skip44
\multlinetaggap=\skip45
\mathdisplay@stack=\toks21
LaTeX Info: Redefining \[ on input line 2844.
LaTeX Info: Redefining \] on input line 2845.
)
("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/amsfonts\amssymb.st
y"
Package: amssymb 2013/01/14 v3.01 AMS font symbols

("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/amsfonts\amsfonts.s
ty"
Package: amsfonts 2013/01/14 v3.01 Basic AMSFonts support
\symAMSa=\mathgroup4
\symAMSb=\mathgroup5
LaTeX Font Info:    Overwriting math alphabet `\mathfrak' in version `bold'
(Font)                  U/euf/m/n --> U/euf/b/n on input line 106.
))
("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/doublestroke\dsfont
.sty"
Package: dsfont 1995/08/01 v0.1 Double stroke roman fonts
)
("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/setspace\setspace.s
ty"
Package: setspace 2011/12/19 v6.7a set line spacing
) ("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/tipa\tipa.sty"
Package: tipa 2002/08/08 TIPA version 1.1
("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/base\fontenc.sty"
Package: fontenc 2018/08/11 v2.0j Standard LaTeX package
("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/tipa\t3enc.def"
File: t3enc.def 2001/12/31 T3 encoding
Now handling font encoding T3 ...
... no UTF-8 mapping file for font encoding T3
) ("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/base\ot1enc.def"
File: ot1enc.def 2018/08/11 v2.0j Standard LaTeX file
LaTeX Font Info:    Redeclaring font encoding OT1 on input line 48.
))) ("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/relsize\relsize
.sty"
Package: relsize 2013/03/29 ver 4.1
) ("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/base\textcomp.sty
"
Package: textcomp 2018/08/11 v2.0j Standard LaTeX package
Package textcomp Info: Sub-encoding information:
(textcomp)               5 = only ISO-Adobe without \textcurrency
(textcomp)               4 = 5 + \texteuro
(textcomp)               3 = 4 + \textohm
(textcomp)               2 = 3 + \textestimated + \textcurrency
(textcomp)               1 = TS1 - \textcircled - \t
(textcomp)               0 = TS1 (full)
(textcomp)             Font families with sub-encoding setting implement
(textcomp)             only a restricted character set as indicated.
(textcomp)             Family '?' is the default used for unknown fonts.
(textcomp)             See the documentation for details.
Package textcomp Info: Setting ? sub-encoding to TS1/1 on input line 79.
("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/base\ts1enc.def"
File: ts1enc.def 2001/06/05 v3.0e (jk/car/fm) Standard LaTeX file
Now handling font encoding TS1 ...
... processing UTF-8 mapping file for font encoding TS1
("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/base\ts1enc.dfu"
File: ts1enc.dfu 2018/10/05 v1.2f UTF-8 support for inputenc
   defining Unicode char U+00A2 (decimal 162)
   defining Unicode char U+00A3 (decimal 163)
   defining Unicode char U+00A4 (decimal 164)
   defining Unicode char U+00A5 (decimal 165)
   defining Unicode char U+00A6 (decimal 166)
   defining Unicode char U+00A7 (decimal 167)
   defining Unicode char U+00A8 (decimal 168)
   defining Unicode char U+00A9 (decimal 169)
   defining Unicode char U+00AA (decimal 170)
   defining Unicode char U+00AC (decimal 172)
   defining Unicode char U+00AE (decimal 174)
   defining Unicode char U+00AF (decimal 175)
   defining Unicode char U+00B0 (decimal 176)
   defining Unicode char U+00B1 (decimal 177)
   defining Unicode char U+00B2 (decimal 178)
   defining Unicode char U+00B3 (decimal 179)
   defining Unicode char U+00B4 (decimal 180)
   defining Unicode char U+00B5 (decimal 181)
   defining Unicode char U+00B6 (decimal 182)
   defining Unicode char U+00B7 (decimal 183)
   defining Unicode char U+00B9 (decimal 185)
   defining Unicode char U+00BA (decimal 186)
   defining Unicode char U+00BC (decimal 188)
   defining Unicode char U+00BD (decimal 189)
   defining Unicode char U+00BE (decimal 190)
   defining Unicode char U+00D7 (decimal 215)
   defining Unicode char U+00F7 (decimal 247)
   defining Unicode char U+0192 (decimal 402)
   defining Unicode char U+02C7 (decimal 711)
   defining Unicode char U+02D8 (decimal 728)
   defining Unicode char U+02DD (decimal 733)
   defining Unicode char U+0E3F (decimal 3647)
   defining Unicode char U+2016 (decimal 8214)
   defining Unicode char U+2020 (decimal 8224)
   defining Unicode char U+2021 (decimal 8225)
   defining Unicode char U+2022 (decimal 8226)
   defining Unicode char U+2030 (decimal 8240)
   defining Unicode char U+2031 (decimal 8241)
   defining Unicode char U+203B (decimal 8251)
   defining Unicode char U+203D (decimal 8253)
   defining Unicode char U+2044 (decimal 8260)
   defining Unicode char U+204E (decimal 8270)
   defining Unicode char U+2052 (decimal 8274)
   defining Unicode char U+20A1 (decimal 8353)
   defining Unicode char U+20A4 (decimal 8356)
   defining Unicode char U+20A6 (decimal 8358)
   defining Unicode char U+20A9 (decimal 8361)
   defining Unicode char U+20AB (decimal 8363)
   defining Unicode char U+20AC (decimal 8364)
   defining Unicode char U+20B1 (decimal 8369)
   defining Unicode char U+2103 (decimal 8451)
   defining Unicode char U+2116 (decimal 8470)
   defining Unicode char U+2117 (decimal 8471)
   defining Unicode char U+211E (decimal 8478)
   defining Unicode char U+2120 (decimal 8480)
   defining Unicode char U+2122 (decimal 8482)
   defining Unicode char U+2126 (decimal 8486)
   defining Unicode char U+2127 (decimal 8487)
   defining Unicode char U+212E (decimal 8494)
   defining Unicode char U+2190 (decimal 8592)
   defining Unicode char U+2191 (decimal 8593)
   defining Unicode char U+2192 (decimal 8594)
   defining Unicode char U+2193 (decimal 8595)
   defining Unicode char U+2329 (decimal 9001)
   defining Unicode char U+232A (decimal 9002)
   defining Unicode char U+2422 (decimal 9250)
   defining Unicode char U+25E6 (decimal 9702)
   defining Unicode char U+25EF (decimal 9711)
   defining Unicode char U+266A (decimal 9834)
   defining Unicode char U+FEFF (decimal 65279)
))
LaTeX Info: Redefining \oldstylenums on input line 334.
Package textcomp Info: Setting cmr sub-encoding to TS1/0 on input line 349.
Package textcomp Info: Setting cmss sub-encoding to TS1/0 on input line 350.
Package textcomp Info: Setting cmtt sub-encoding to TS1/0 on input line 351.
Package textcomp Info: Setting cmvtt sub-encoding to TS1/0 on input line 352.
Package textcomp Info: Setting cmbr sub-encoding to TS1/0 on input line 353.
Package textcomp Info: Setting cmtl sub-encoding to TS1/0 on input line 354.
Package textcomp Info: Setting ccr sub-encoding to TS1/0 on input line 355.
Package textcomp Info: Setting ptm sub-encoding to TS1/4 on input line 356.
Package textcomp Info: Setting pcr sub-encoding to TS1/4 on input line 357.
Package textcomp Info: Setting phv sub-encoding to TS1/4 on input line 358.
Package textcomp Info: Setting ppl sub-encoding to TS1/3 on input line 359.
Package textcomp Info: Setting pag sub-encoding to TS1/4 on input line 360.
Package textcomp Info: Setting pbk sub-encoding to TS1/4 on input line 361.
Package textcomp Info: Setting pnc sub-encoding to TS1/4 on input line 362.
Package textcomp Info: Setting pzc sub-encoding to TS1/4 on input line 363.
Package textcomp Info: Setting bch sub-encoding to TS1/4 on input line 364.
Package textcomp Info: Setting put sub-encoding to TS1/5 on input line 365.
Package textcomp Info: Setting uag sub-encoding to TS1/5 on input line 366.
Package textcomp Info: Setting ugq sub-encoding to TS1/5 on input line 367.
Package textcomp Info: Setting ul8 sub-encoding to TS1/4 on input line 368.
Package textcomp Info: Setting ul9 sub-encoding to TS1/4 on input line 369.
Package textcomp Info: Setting augie sub-encoding to TS1/5 on input line 370.
Package textcomp Info: Setting dayrom sub-encoding to TS1/3 on input line 371.
Package textcomp Info: Setting dayroms sub-encoding to TS1/3 on input line 372.

Package textcomp Info: Setting pxr sub-encoding to TS1/0 on input line 373.
Package textcomp Info: Setting pxss sub-encoding to TS1/0 on input line 374.
Package textcomp Info: Setting pxtt sub-encoding to TS1/0 on input line 375.
Package textcomp Info: Setting txr sub-encoding to TS1/0 on input line 376.
Package textcomp Info: Setting txss sub-encoding to TS1/0 on input line 377.
Package textcomp Info: Setting txtt sub-encoding to TS1/0 on input line 378.
Package textcomp Info: Setting lmr sub-encoding to TS1/0 on input line 379.
Package textcomp Info: Setting lmdh sub-encoding to TS1/0 on input line 380.
Package textcomp Info: Setting lmss sub-encoding to TS1/0 on input line 381.
Package textcomp Info: Setting lmssq sub-encoding to TS1/0 on input line 382.
Package textcomp Info: Setting lmvtt sub-encoding to TS1/0 on input line 383.
Package textcomp Info: Setting lmtt sub-encoding to TS1/0 on input line 384.
Package textcomp Info: Setting qhv sub-encoding to TS1/0 on input line 385.
Package textcomp Info: Setting qag sub-encoding to TS1/0 on input line 386.
Package textcomp Info: Setting qbk sub-encoding to TS1/0 on input line 387.
Package textcomp Info: Setting qcr sub-encoding to TS1/0 on input line 388.
Package textcomp Info: Setting qcs sub-encoding to TS1/0 on input line 389.
Package textcomp Info: Setting qpl sub-encoding to TS1/0 on input line 390.
Package textcomp Info: Setting qtm sub-encoding to TS1/0 on input line 391.
Package textcomp Info: Setting qzc sub-encoding to TS1/0 on input line 392.
Package textcomp Info: Setting qhvc sub-encoding to TS1/0 on input line 393.
Package textcomp Info: Setting futs sub-encoding to TS1/4 on input line 394.
Package textcomp Info: Setting futx sub-encoding to TS1/4 on input line 395.
Package textcomp Info: Setting futj sub-encoding to TS1/4 on input line 396.
Package textcomp Info: Setting hlh sub-encoding to TS1/3 on input line 397.
Package textcomp Info: Setting hls sub-encoding to TS1/3 on input line 398.
Package textcomp Info: Setting hlst sub-encoding to TS1/3 on input line 399.
Package textcomp Info: Setting hlct sub-encoding to TS1/5 on input line 400.
Package textcomp Info: Setting hlx sub-encoding to TS1/5 on input line 401.
Package textcomp Info: Setting hlce sub-encoding to TS1/5 on input line 402.
Package textcomp Info: Setting hlcn sub-encoding to TS1/5 on input line 403.
Package textcomp Info: Setting hlcw sub-encoding to TS1/5 on input line 404.
Package textcomp Info: Setting hlcf sub-encoding to TS1/5 on input line 405.
Package textcomp Info: Setting pplx sub-encoding to TS1/3 on input line 406.
Package textcomp Info: Setting pplj sub-encoding to TS1/3 on input line 407.
Package textcomp Info: Setting ptmx sub-encoding to TS1/4 on input line 408.
Package textcomp Info: Setting ptmj sub-encoding to TS1/4 on input line 409.
)
("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/jknappen\mathrsfs.s
ty"
Package: mathrsfs 1996/01/01 Math RSFS package v1.0 (jk)
\symrsfs=\mathgroup6
)
("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/fundus-calligra\cal
ligra.sty"
Package: calligra 2012/04/10 v1.9 LaTeX package calligra
) ("C:\Users\3301\AppData\Local\Programs\MiKTeX 2.9\tex/latex/wasysym\wasysym.s
ty"
Package: wasysym 2003/10/30 v2.0 Wasy-2 symbol support package
\symwasy=\mathgroup7
LaTeX Font Info:    Overwriting symbol font `wasy' in version `bold'
(Font)                  U/wasy/m/n --> U/wasy/b/n on input line 90.
)

! LaTeX Error: File `ragged2e.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.15 \usepackage
                {physics}
 
Here is how much of TeX's memory you used:
 4015 strings out of 492896
 53108 string characters out of 3124229
 114201 words of memory out of 3000000
 7886 multiletter control sequences out of 15000+200000
 4952 words of font info for 18 fonts, out of 3000000 for 9000
 1141 hyphenation exceptions out of 8191
 34i,0n,56p,238b,56s stack positions out of 5000i,500n,10000p,200000b,50000s

No pages of output.

```

**Comment by girishgargcool** [comment]
Have you installed the full version of miktex? Its about 4gb in size

**Comment by chaoxiaosu** [comment]
I faced the same problem on my Win 10 and found a workaround. I changed the L29 of _manimlib/constants.py_ to ` MEDIA_DIR = os.path.join(os.getcwd(), "media")`, then got passed. 

You can see [here](https://github.com/3b1b/manim/pull/689#issuecomment-522333581) for details.

**Comment by wizardor** [comment]
You should install "ragged2e"  packages in MikTex's Packages management UI windows,
1, to search "ragged2e" in the search bar,
2, select "ragged2e" and right click, to install package

If you have some troubles, maybe you need to change the settings and to select another server source.
