### ISSUE TITLE
 UnicodeDecodeError: 'gbk' codec can't decode byte 0x9c in position 1903: illegal multibyte sequence

### ISSUE THREAD

**Issue by ouening** [3b1b/manim#684]
When I install manimlib in win 10(python3.7.2), errors happened:
`  ERROR: Command errored out with exit status 1:
     command: 'c:\applications\wpy64-3720\python-3.7.2.amd64\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-rz_rty69\\manimlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-rz_rty69\\manimlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\admin\AppData\Local\Temp\pip-install-rz_rty69\manimlib\
    Complete output (22 lines):
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "c:\applications\wpy64-3720\python-3.7.2.amd64\lib\site-packages\pbr\core.py", line 96, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "c:\applications\wpy64-3720\python-3.7.2.amd64\lib\site-packages\pbr\util.py", line 256, in cfg_to_args            File "c:\applications\wpy64-3720\python-3.7.2.amd64\lib\site-packages\pbr\hooks\__init__.py", line 25, in setup_hook                                                                                                                              metadata_config.run()                                                                                                 File "c:\applications\wpy64-3720\python-3.7.2.amd64\lib\site-packages\pbr\hooks\base.py", line 27, in run                 self.hook()                                                                                                           File "c:\applications\wpy64-3720\python-3.7.2.amd64\lib\site-packages\pbr\hooks\metadata.py", line 26, in hook            self.config['name'], self.config.get('version', None))                                                                File "c:\applications\wpy64-3720\python-3.7.2.amd64\lib\site-packages\pbr\packaging.py", line 831, in get_version         version = _get_version_from_pkg_metadata(package_name)                                                                File "c:\applications\wpy64-3720\python-3.7.2.amd64\lib\site-packages\pbr\packaging.py", line 799, in _get_version_from_pkg_metadata                                                                                                              pkg_metadata = email.message_from_file(pkg_metadata_file)                                                             File "c:\applications\wpy64-3720\python-3.7.2.amd64\lib\email\__init__.py", line 54, in message_from_file                 return Parser(*args, **kws).parse(fp)                                                                                 File "c:\applications\wpy64-3720\python-3.7.2.amd64\lib\email\parser.py", line 54, in parse                               data = fp.read(8192)                                                                                                UnicodeDecodeError: 'gbk' codec can't decode byte 0x9c in position 1903: illegal multibyte sequence                     error in setup command: Error parsing C:\Users\admin\AppData\Local\Temp\pip-install-rz_rty69\manimlib\setup.cfg: UnicodeDecodeError: 'gbk' codec can't decode byte 0x9c in position 1903: illegal multibyte sequence                            ----------------------------------------                                                                            ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.    `

Anyone can fix it? I have installed the prerequest solftware.

**Comment by xy-23** [comment]
You can try https://jingyan.baidu.com/article/25648fc1471e6a9191fd002e.html
