### ISSUE TITLE
Error while typing 'python -m manim example_scenes.py SquareToCircle -pl'

### ISSUE THREAD

**Issue by Ashish45351** [3b1b/manim#693]
why do i get this error. I am using Windows 10. please help me i am tired of getting errors.

C:\Manim\manim_3_feb>python -m manim example_scenes.py SquareToCircle -pl

Traceback (most recent call last):
  File "C:\python37\lib\site-packages\manimlib\extract_scene.py", line 150, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\python37\lib\site-packages\manimlib\scene\scene.py", line 37, in __init__
    self, **self.file_writer_config,
  File "C:\python37\lib\site-packages\manimlib\scene\scene_file_writer.py", line 44, in __init__
    self.init_output_directories()
  File "C:\python37\lib\site-packages\manimlib\scene\scene_file_writer.py", line 75, in init_output_directories
    movie_dir = guarantee_existence(consts.VIDEO_OUTPUT_DIR)
  File "C:\python37\lib\site-packages\manimlib\utils\file_ops.py", line 15, in guarantee_existence
    os.makedirs(path)
  File "C:\python37\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''

**Comment by Ashish45351** [comment]
i was using old version of  manimlib so i get that error now it is solved
