### ISSUE TITLE
OSError: No file matching Suv.svg in image directory

### ISSUE THREAD

**Issue by Hulenkius** [3b1b/manim#700]
I've tried putting the .SVG image into */media/designs/svg_images. But when I want to quote it in the .py file it still reports errors:

```
Traceback (most recent call last):
  File "/home/jason/Documents/manim/manimlib/extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "/home/jason/Documents/manim/manimlib/scene/scene.py", line 53, in __init__
    self.construct()
  File "SVGTEST.py", line 44, in construct
    height=height_size
  File "/home/jason/Documents/manim/manimlib/mobject/svg/svg_mobject.py", line 45, in __init__
    self.ensure_valid_file()
  File "/home/jason/Documents/manim/manimlib/mobject/svg/svg_mobject.py", line 63, in ensure_valid_file
    self.file_name)
OSError: No file matching MYSVG.svg in image directory

```
(Manjaro Linux, Texlive)

**Comment by Elteoremadebeethoven** [comment]
That is the older format, the new one is `assets/svg_images/files.svg`.
