### ISSUE TITLE
安装好所有模块 ，如下提示

### ISSUE THREAD

**Issue by Campanulata** [3b1b/manim#701]
TYLORGAN-MB0:manim omen$ python3 -m manim example_scenes.py WriteStuff -pl
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/omen/ManimInstall/manim/manim.py", line 2, in <module>
    import manimlib
  File "/Users/omen/ManimInstall/manim/manimlib/__init__.py", line 4, in <module>
    import manimlib.extract_scene
  File "/Users/omen/ManimInstall/manim/manimlib/extract_scene.py", line 9, in <module>
    from manimlib.scene.scene import Scene
  File "/Users/omen/ManimInstall/manim/manimlib/scene/scene.py", line 12, in <module>
    from manimlib.camera.camera import Camera
  File "/Users/omen/ManimInstall/manim/manimlib/camera/camera.py", line 9, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'
TYLORGAN-MB0:manim omen$

**Comment by SolarLiner** [comment]
Your installation of Python doesn't include `pycairo` which is the module that draws the shapes into images.

**Comment by Campanulata** [comment]
3q.and i akready solved this problem.but i have a new question that i can't use Chinese by textmobject

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Nathan Graule <notifications@github.com>
发送时间: Wednesday, August 21, 2019 7:46:15 PM
收件人: 3b1b/manim <manim@noreply.github.com>
抄送: Campanulata <ts1989512@outlook.com>; Author <author@noreply.github.com>
主题: Re: [3b1b/manim] 安装好所有模块 ，如下提示 (#701)


Your installation of Python doesn't include pycairo which is the module that draws the shapes into images.

―

**Comment by zombie110year** [comment]
```sh
pip install -U pycario
```

could help you. macOS is a Unix-like system, you won't get trouble in C compiling, in most cases...
