### ISSUE TITLE
不能使用中文

### ISSUE THREAD

**Issue by Campanulata** [3b1b/manim#702]
TYLORGAN-MB0:manim omen$ python3 -m manim 1.py WriteStuff -pl
Media will be written to ./media/. You can change this behavior with the --media_dir flag.

Traceback (most recent call last):
  File "/Users/omen/OneDrive/manim/manimlib/extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "/Users/omen/OneDrive/manim/manimlib/scene/scene.py", line 53, in __init__
    self.construct()
  File "1.py", line 101, in construct
    w0=TextMobject("I 的",color=RED)
  File "/Users/omen/OneDrive/manim/manimlib/mobject/svg/tex_mobject.py", line 144, in __init__
    self, self.arg_separator.join(tex_strings), **kwargs
  File "/Users/omen/OneDrive/manim/manimlib/mobject/svg/tex_mobject.py", line 44, in __init__
    self.template_tex_file_body
  File "/Users/omen/OneDrive/manim/manimlib/utils/tex_file_writing.py", line 19, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
  File "/Users/omen/OneDrive/manim/manimlib/utils/tex_file_writing.py", line 67, in tex_to_dvi
    "See log output above or the log file: %s" % log_file)
Exception: Latex error converting to dvi. See log output above or the log file: ./media/Tex/c2ebd396bb368ef6.log

TYLORGAN-MB0:manim omen$

**Comment by xy-23** [comment]
Change TEX_USE_CTEX in constants.py to True.

**Comment by Cenderme** [comment]
I set it to True but the problem is consisting.

**Comment by asustnt3** [comment]
Changed TEX_USE_CTEX in constants.py to True. but still cannot write chinese in TextMobject("你好")

Traceback (most recent call last):
  File "L:\Software\manimlib-0.1.10\manimlib\extract_scene.py", line 150, in main
    scene = SceneClass(**scene_kwargs)
  File "L:\Software\manimlib-0.1.10\manimlib\scene\scene.py", line 52, in __init__
    self.construct()
  File "example_scenes.py", line 101, in construct
    "你好",
  File "L:\Software\manimlib-0.1.10\manimlib\mobject\svg\tex_mobject.py", line 144, in __init__
    self, self.arg_separator.join(tex_strings), **kwargs
  File "L:\Software\manimlib-0.1.10\manimlib\mobject\svg\tex_mobject.py", line 44, in __init__
    self.template_tex_file_body
  File "L:\Software\manimlib-0.1.10\manimlib\utils\tex_file_writing.py", line 19, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
  File "L:\Software\manimlib-0.1.10\manimlib\utils\tex_file_writing.py", line 67, in tex_to_dvi
    "See log output above or the log file: %s" % log_file)
Exception: Latex error converting to dvi. See log output above or the log file: Tex\1c2ddcefad627309.log

**Comment by asustnt3** [comment]
after installing the  packages in miktex,  it works

**Comment by HumbleHumbert** [comment]
> after installing the packages in miktex, it works

Can you tell me more details? I'm kinda stuck here too. Thanks.
