### ISSUE TITLE
Issues running manim after installing everything

### ISSUE THREAD

**Issue by alecab94** [3b1b/manim#706]
After doing everything in this video, I am getting this when running:
 python -m manim example_scenes.py SquareToCircle -pl

Microsoft Windows [Version 10.0.18362.295]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Manim\Manim_1>python -m manim example_scenes.py SquareTocircle -pl
Traceback (most recent call last):
  File "C:\Users\aleca\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\aleca\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Manim\Manim_1\manim.py", line 3, in <module>
    import manimlib.extract_scene
  File "C:\Manim\Manim_1\manimlib\extract_scene.py", line 9, in <module>
    from manimlib.scene.scene import Scene
  File "C:\Manim\Manim_1\manimlib\scene\scene.py", line 11, in <module>
    from manimlib.camera.camera import Camera
  File "C:\Manim\Manim_1\manimlib\camera\camera.py", line 8, in <module>
    from scipy.spatial.distance import pdist
  File "C:\Users\aleca\AppData\Local\Programs\Python\Python37-32\lib\site-packages\scipy\spatial\__init__.py", line 94, in <module>
    from .kdtree import *
  File "C:\Users\aleca\AppData\Local\Programs\Python\Python37-32\lib\site-packages\scipy\spatial\kdtree.py", line 8, in <module>
    import scipy.sparse
  File "C:\Users\aleca\AppData\Local\Programs\Python\Python37-32\lib\site-packages\scipy\sparse\__init__.py", line 229, in <module>
    from .csr import *
  File "C:\Users\aleca\AppData\Local\Programs\Python\Python37-32\lib\site-packages\scipy\sparse\csr.py", line 15, in <module>
    from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
ImportError: DLL load failed: %1 is not a valid Win32 application.

C:\Manim\Manim_1>

Not sure what I did wrong.

**Comment by xy-23** [comment]
You can try to see this https://github.com/scipy/scipy/issues/9230
