### ISSUE TITLE
No module named 'mobject.mobject'

### ISSUE THREAD

**Issue by FFloresM** [3b1b/manim#722]
As I run the command `python3 -m manim old_projects/three_dimensions.py` the error message said
`Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/francisco/manim/manim.py", line 5, in <module>
    manimlib.main()
  File "/home/francisco/manim/manimlib/__init__.py", line 11, in main
    config = manimlib.config.get_configuration(args)
  File "/home/francisco/manim/manimlib/config.py", line 185, in get_configuration
    module = get_module(args.file)
  File "/home/francisco/manim/manimlib/config.py", line 180, in get_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "old_projects/three_dimensions.py", line 4, in <module>
    from mobject.mobject import Mobject, Mobject1D, Mobject2D, Mobject
ModuleNotFoundError: No module named 'mobject.mobject'; 'mobject' is not a package`

I don't find the `mobject` module.
SO Manjaro. manim version 0.1.10

**Comment by TravorLZH** [comment]
As you can see, you are trying to produce videos from [`old_projects/`][1], which is already not working for the new version of `manim`. I suggest that you can try making videos from [`active_projects/`][2] instead.

[1]: https://github.com/3b1b/manim/tree/master/old_projects
[2]: https://github.com/3b1b/manim/tree/master/active_projects
