### ISSUE TITLE
Error when running Manim 'SquareToCircle' Demo (ModuleNotFoundError: No module named 'cairo')

### ISSUE THREAD

**Issue by Bart-Weil** [3b1b/manim#740]
**(Relevant info: Using fish shell on Mac 10.12.6, using python 3.7.4 (pyenv).

When installing Manim on Mac OSX following the guide in the repository, The installation went smoothly, until I tried running the 'square to circle' test to check if everything worked. That produced the following error:**

⋊> ~/M/manim on master ⨯ python3 -m manim example_scenes.py WriteStuff -pl                                                                                                                          14:10:12
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/bartweil/Manim/manim/manim.py", line 2, in <module>
    import manimlib
  File "/Users/bartweil/Manim/manim/manimlib/__init__.py", line 4, in <module>
    import manimlib.extract_scene
  File "/Users/bartweil/Manim/manim/manimlib/extract_scene.py", line 9, in <module>
    from manimlib.scene.scene import Scene
  File "/Users/bartweil/Manim/manim/manimlib/scene/scene.py", line 12, in <module>
    from manimlib.camera.camera import Camera
  File "/Users/bartweil/Manim/manim/manimlib/camera/camera.py", line 9, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'

As far as I can tell, cairo and pycairo are both install (running installation commands prompt a 'Requirement already satisfied: pycairo in /usr/local/lib/python3.7/site-packages (1.18.1)' response.

I have already done a significant amount of digging, but any help is still very much appreciated

**Comment by bromzh** [comment]
I have similar troubles.

Try to reinstall pycairo. Activate your virtual env, then:
```
brew install cairo # if you don't
brew reinstall libffi
```
After this, you need to export PKG_CONFIG_PATH var with path to pkgconfig for libffi:
```
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
pip install pycairo # now it work
```

**Comment by Bart-Weil** [comment]
That works now! Thank you so much man, I was just about ready to give up and try installing on a different OS.
