### ISSUE TITLE
Hello... When I try to run the code the following error appears...    Traceback (most recent call last):   File "C:\Users\Rafhael\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 193, in _run_module_as_main     "__main__", mod_spec)   File "C:\Users\Rafhael\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code     exec(code, run_globals)   File "C:\Manim\manim.py", line 9, in <module>     config = manimlib.config.get_configuration(args)   File "C:\Users\Rafhael\AppData\Local\Programs\Python\Python37-32\lib\site-packages\manimlib\config.py", line 185, in get_configuration     module = get_module(args.file)   File "C:\Users\Rafhael\AppData\Local\Programs\Python\Python37-32\lib\site-packages\manimlib\config.py", line 179, in get_module     module = importlib.util.module_from_spec(spec)   File "<frozen importlib._bootstrap>", line 580, in module_from_spec AttributeError: 'NoneType' object has no attribute 'loader'

### ISSUE THREAD

**Issue by raphateixeira** [3b1b/manim#749]
### If this is a support request:

**Please attempt to solve the problem on your own before opening an issue.**
Between old issues, StackOverflow, and Google, you should be able to find
solutions to most of the common problems.

Include at least:
1. Steps to reproduce the issue (e.g. the command you ran)
2. The unexpected behavior that occurred (e.g. error messages or screenshots)
3. The environment (e.g. operating system and version of manim)

### If this is a feature request:
Include the motivation for making this change.

**Comment by Elteoremadebeethoven** [comment]
Please change your title and post the error in the body section.

**Comment by PhilippImhof** [comment]
Also, please include the code you are trying to run...
