### ISSUE TITLE
`--live-stream` not supported in the docker image

### ISSUE THREAD

**Issue by Synthetica9** [3b1b/manim#753]
When I pass the `--live-stream` flag to the docker container, I get the following message:

```
$ env INPUT_PATH=. OUTPUT_PATH=./output docker-compose run manim --livestream
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/manimlib/stream_starter.py", line 38, in __new__
    return Scene(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/manimlib/scene/scene.py", line 37, in __init__
    self, **self.file_writer_config,
  File "/usr/local/lib/python3.7/site-packages/manimlib/scene/scene_file_writer.py", line 44, in __init
    self.init_output_directories()
  File "/usr/local/lib/python3.7/site-packages/manimlib/scene/scene_file_writer.py", line 49, in init_o
    module_directory = self.output_directory or self.get_default_module_directory()
  File "/usr/local/lib/python3.7/site-packages/manimlib/scene/scene_file_writer.py", line 95, in get_de
    filename = os.path.basename(self.input_file_path)
AttributeError: 'SceneFileWriter' object has no attribute 'input_file_path'

Manim is now running in streaming mode. Stream animations by passing
them to manim.play(), e.g.
>>> c = Circle()
>>> manim.play(ShowCreation(c))

>>> c = Circle()
>>> manim.play(ShowCreation(c))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'manim' is not defined
>>> 
```

I would have expected that I would be able to find the stream in ./output

## Environment:

Docker on NixOS. Versions:

```
$ docker --version
Docker version 19.03.2, build 6a30dfca03664a0b6bf0646a7d389ee7d0318e6e
$ docker-compose --version
docker-compose version 1.24.1, build 4667896
$ uname -a
Linux AquaRing 5.3.5 #1-NixOS SMP Mon Oct 7 17:01:58 UTC 2019 x86_64 GNU/Linux
```

**Comment by sas5580** [comment]
Livestreaming seems to have been broken in general since `scene_file_writer.py` was added, and also due to some changes to how directory constants were set. I am currently looking into fixing this, will have a PR up soon.
