### ISSUE TITLE
Manim won't run.

### ISSUE THREAD

**Issue by LittleGreenMan36** [3b1b/manim#767]
**I followed [this](https://www.youtube.com/watch?v=ZltiKHFWmv8) tutorial to download and install Manim on Windows 10. I believe I followed every step. However when ever i run** `python3 -m manim example_scenes.py WriteStuff -pl` **or** `python3 -m manim example_scenes.py SquareToCircle -pl`**, for the first time, I get this thrown at my face :** 

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Manim\manim-master\manim.py", line 2, in <module>
    import manimlib
  File "C:\Manim\manim-master\manimlib\__init__.py", line 4, in <module>
    import manimlib.extract_scene
  File "C:\Manim\manim-master\manimlib\extract_scene.py", line 9, in <module>
    from manimlib.scene.scene import Scene
  File "C:\Manim\manim-master\manimlib\scene\scene.py", line 9, in <module>
    from manimlib.animation.animation import Animation
  File "C:\Manim\manim-master\manimlib\animation\animation.py", line 5, in <module>
    from manimlib.mobject.mobject import Mobject
  File "C:\Manim\manim-master\manimlib\mobject\mobject.py", line 15, in <module>
    from manimlib.utils.color import color_gradient
  File "C:\Manim\manim-master\manimlib\utils\color.py", line 8, in <module>
    from manimlib.utils.bezier import interpolate
  File "C:\Manim\manim-master\manimlib\utils\bezier.py", line 1, in <module>
    from scipy import linalg
  File "C:\Users\Riddhiman\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\linalg\__init__.py", line 195, in <module>
    from .misc import *
  File "C:\Users\Riddhiman\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\linalg\misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "C:\Users\Riddhiman\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\linalg\blas.py", line 214, in <module>
    from scipy.linalg import _fblas
ImportError: DLL load failed: The specified module could not be found.

**What could be the problem and how can I fix and/or avoid it?
Thanks**

**Comment by PhilippImhof** [comment]
I do not use Windows, but this link might be helpful:

https://stackoverflow.com/questions/25406492/importing-scipy-or-scikit-image-from-scipy-linalg-import-fblas-import-error
