### ISSUE TITLE
manimlib installation error on windows

### ISSUE THREAD

**Issue by heiye007** [3b1b/manim#787]
when I use **pip install manimlib**

Collecting manimlib
  Using cached https://files.pythonhosted.org/packages/d1/57/1ed0a44a8b97ffa0cf3d9fa8d4bdf3742d9984fd39ff6b3291af597045ee/manimlib-0.1.10.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\11239\appdata\local\programs\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\11239\\AppData\\Local\\Temp\\pip-install-h9vrzjxe\\manimlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\11239\\AppData\\Local\\Temp\\pip-install-h9vrzjxe\\manimlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\11239\AppData\Local\Temp\pip-install-h9vrzjxe\manimlib\pip-egg-info'
         cwd: C:\Users\11239\AppData\Local\Temp\pip-install-h9vrzjxe\manimlib\
    Complete output (22 lines):
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "c:\users\11239\appdata\local\temp\pip-install-h9vrzjxe\manimlib\.eggs\pbr-5.4.3-py3.8.egg\pbr\core.py", line 96, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "c:\users\11239\appdata\local\temp\pip-install-h9vrzjxe\manimlib\.eggs\pbr-5.4.3-py3.8.egg\pbr\util.py", line 270, in cfg_to_args
        pbr.hooks.setup_hook(config)
      File "c:\users\11239\appdata\local\temp\pip-install-h9vrzjxe\manimlib\.eggs\pbr-5.4.3-py3.8.egg\pbr\hooks\__init__.py", line 25, in setup_hook
        metadata_config.run()
      File "c:\users\11239\appdata\local\temp\pip-install-h9vrzjxe\manimlib\.eggs\pbr-5.4.3-py3.8.egg\pbr\hooks\base.py", line 27, in run
        self.hook()
      File "c:\users\11239\appdata\local\temp\pip-install-h9vrzjxe\manimlib\.eggs\pbr-5.4.3-py3.8.egg\pbr\hooks\metadata.py", line 25, in hook
        self.config['version'] = packaging.get_version(
      File "c:\users\11239\appdata\local\temp\pip-install-h9vrzjxe\manimlib\.eggs\pbr-5.4.3-py3.8.egg\pbr\packaging.py", line 856, in get_version
        version = _get_version_from_pkg_metadata(package_name)
      File "c:\users\11239\appdata\local\temp\pip-install-h9vrzjxe\manimlib\.eggs\pbr-5.4.3-py3.8.egg\pbr\packaging.py", line 824, in _get_version_from_pkg_metadata
        pkg_metadata = email.message_from_file(pkg_metadata_file)
      File "c:\users\11239\appdata\local\programs\python\python38-32\lib\email\__init__.py", line 54, in message_from_file
        return Parser(*args, **kws).parse(fp)
      File "c:\users\11239\appdata\local\programs\python\python38-32\lib\email\parser.py", line 53, in parse
        data = fp.read(8192)
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x9c in position 1903: illegal multibyte sequence
    error in setup command: Error parsing C:\Users\11239\AppData\Local\Temp\pip-install-h9vrzjxe\manimlib\setup.cfg: UnicodeDecodeError: 'gbk' codec can't decode byte 0x9c in position 1903: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Elteoremadebeethoven** [comment]
Here https://github.com/Elteoremadebeethoven/AnimationsWithManim/blob/master/English/6a_plots_2D/scenes.md

**Comment by 625248808** [comment]
When I click the download green button, there is no drop-down box and no download path for me. What should I do? My computer is win10 system. What's the problem? Hope for a quick answer.

**Comment by funfwo** [comment]
same problem. perhaps manim can make an installer for windows. Separated packages make huge errors when separatedly installed

**Comment by heiye007** [comment]
> same problem. perhaps manim can make an installer for windows. Separated packages make huge errors when separatedly installed

https://jingyan.baidu.com/article/25648fc1471e6a9191fd002e.html

**Comment by AswanthT** [comment]
You are probably missing git added to your path variables. You can add <gitHubLocation>\GitHubDesktop\app-2.6.3\resources\app\git\cmd
