### ISSUE TITLE
ModuleNotFoundError: No module named 'mobject'

### ISSUE THREAD

**Issue by dtbulmerJRs** [3b1b/manim#808]
I am using manim from the cloned repo. meaning I run for example:

python3 ./manim.py '/home/dtb2/manim/active_projects/eop/chapter1/various_intro_visuals.py' TwoDiceTableScene -pl

but I get an import error from mobject which is in the manimlib directory.
Traceback (most recent call last):
  File "./manim.py", line 5, in <module>
    manimlib.main()
  File "/home/dtb2/manim/manimlib/__init__.py", line 11, in main
    config = manimlib.config.get_configuration(args)
  File "/home/dtb2/manim/manimlib/config.py", line 185, in get_configuration
    module = get_module(args.file)
  File "/home/dtb2/manim/manimlib/config.py", line 180, in get_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dtb2/manim/active_projects/eop/chapter1/various_intro_visuals.py", line 2, in <module>
    from active_projects.eop.reusable_imports import *
  File "/home/dtb2/manim/active_projects/eop/reusable_imports.py", line 1, in <module>
    from active_projects.eop.reusables.binary_option import *
  File "/home/dtb2/manim/active_projects/eop/reusables/binary_option.py", line 1, in <module>
    from mobject.types.vectorized_mobject import *
ModuleNotFoundError: No module named 'mobject'

I dont want to go through each file to fix imports, so what am I doing wrong?

**Comment by stefanpatrichi** [comment]
Try writing _-m manim_ instead of _./manim.py_.
Manim is a **module**. (-m comes from module)
