### ISSUE TITLE
"can't open file 'extract_scene.py': [Errno 2] No such file or directory" error on a macbook pro

### ISSUE THREAD

**Issue by jgcolman** [3b1b/manim#809]
I am working through Brian Howell's very clear tutorial on how to get started. I get stuck at the Step 9 with the command:

> python3 extract_scene.py example_scenes.py SquareToCircle -pl

Which evokes the following response:

>/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'extract_scene.py': [Errno 2] No such file or directory

 It is clear that it is looking in the wrong place for the file but I have no idea how to tell it where it should be looking. 

I am on a mid-2014 MacBook Pro running Catalina 10.15.1.
I am very experienced with R but have not used Python or Terminal.

**Comment by Elteoremadebeethoven** [comment]
```
python3 -m manim example_scenes.py SquareToCircle -pl
```

**Comment by jgcolman** [comment]
Many thanks Elteoremadebeethoven,
Something happened, but I still have problems.

> (venv) Jeremy1@Jeremys-MacBook-Pro manim % python3 -m manim example_scenes.py SquareToCircle -pl
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/Jeremy1/animations/manim/manim.py", line 2, in <module>
    import manimlib
  File "/Users/Jeremy1/animations/manim/manimlib/__init__.py", line 2, in <module>
    import manimlib.config
  File "/Users/Jeremy1/animations/manim/manimlib/config.py", line 2, in <module>
    import colour
ModuleNotFoundError: No module named 'colour'
(venv) Jeremy1@Jeremys-MacBook-Pro manim %

**Comment by Elteoremadebeethoven** [comment]
```
python3 -m pip install -r requieriments.txt
```
the requieriments.txt file is in the manim-master folder.

**Comment by scuasmq** [comment]
I met the same question. The extract_scene.py is in manimlib,  `python3 manimlib/extract_scene.py example_scenes.py SquareToCircle -pl ` , but it errors :ModuleNotFoundError: No module named 'manimlib'. And I met the ModuleNotFoundError: No module named 'colour' error too.
If you solved the errors, can you tell me how to do?

**Comment by PgBiel** [comment]
@scuasmq `python3 -m pip install -r requirements.txt`

**Comment by piyush2003m** [comment]
@jgcolman Did you find a solution to this problem? I am running into the exact same issue.

**Comment by scuasmq** [comment]
> @jgcolman Did you find a solution to this problem? I am running into the exact same issue.

you should install the manimlib link to global path or keep it under your directory
