### ISSUE TITLE
IOError and  OSError: No file matching file in image directory

### ISSUE THREAD

**Issue by vasanthkashyap** [3b1b/manim#822]
I am using Windows 10 and I am facing this error when I try to run 
`python -m manim example_scenes.py WriteStuff -pm`
It shows me an error which reads 

`dvisvgm: warning: running with administrator privileges`
`ERROR: can't open file 'C:/Program.dvi' for reading`

`Traceback (most recent call last):`
 ` File "C:\Program Files (x86)\Python libraries\manim\manimlib\extract_scene.py", line 153, in main
    scene = SceneClass(**scene_kwargs)`
  `File "C:\Program Files (x86)\Python libraries\manim\manimlib\scene\scene.py", line 54, in __init__`
   ` self.construct()`
  `File "example_scenes.py", line 98, in construct`
   ` example_text = TextMobject(`
  `File "C:\Program Files (x86)\Python libraries\manim\manimlib\mobject\svg\tex_mobject.py", line 143, in __init__`
   ` SingleStringTexMobject.__init__(`
`  File "C:\Program Files (x86)\Python libraries\manim\manimlib\mobject\svg\tex_mobject.py", line 47, in __init__`
    `SVGMobject.__init__(self, file_name=file_name, **kwargs)`
  `File "C:\Program Files (x86)\Python libraries\manim\manimlib\mobject\svg\svg_mobject.py", line 47, in __init__`
   ` self.ensure_valid_file()`
 ` File "C:\Program Files (x86)\Python libraries\manim\manimlib\mobject\svg\svg_mobject.py", line 64, in ensure_valid_file`
  `  raise IOError("No file matching %s in image directory" %`
`OSError: No file matching C:/Program Files (x86)/Python libraries/manim/manimlib/files/Tex/47f78a457bde38f5.svg in image directory`

This seems to be similar to [https://github.com/3b1b/manim/issues/372](url) but not completely the same. Hence I have chosen to open a new issue.
 Previously I had faced an error saying `Latex not recognized as an internal or external command` but the solution given by @godaygo in  [https://github.com/3b1b/manim/issues/623](url) worked for me and I also had to change my path variable from `C:\Program Files (x86)\Python libraries\MiTeX 2.9\miktex\bin\x64\` to `C:\Program Files (x86)\Python libraries\MiTeX 2.9\miktex\bin\x64`

Any help to resolve this issue is appreciated.
Thankyou.

**Comment by Micoael** [comment]
maybe you should run dvisvgm in administrator mode

**Comment by Tony031218** [comment]
If you still have this problem, try to update dvisvgm.

**Comment by yjf10086** [comment]
I am using Windows 10 and I am facing this error when I try to run
It shows me an error which reads python -m manim example_scenes.py WriteStuff -pm


(base) c:\manim>python -m manim example_scenes.py WriteStuff -pl
Media will be written to c:\manim\media\. You can change this behavior with the --media_dir flag.



Traceback (most recent call last):
  File "c:\manim\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "c:\manim\manimlib\scene\scene.py", line 75, in __init__
    self.construct()
  File "example_scenes.py", line 100, in construct
    example_text = TextMobject(
  File "c:\manim\manimlib\mobject\svg\tex_mobject.py", line 147, in __init__
    SingleStringTexMobject.__init__(
  File "c:\manim\manimlib\mobject\svg\tex_mobject.py", line 46, in __init__
    SVGMobject.__init__(self, file_name=file_name, **kwargs)
  File "c:\manim\manimlib\mobject\svg\svg_mobject.py", line 45, in __init__
    self.ensure_valid_file()
  File "c:\manim\manimlib\mobject\svg\svg_mobject.py", line 62, in ensure_valid_file
    raise IOError("No file matching %s in image directory" %
OSError: No file matching c:/manim/media/Tex/c0bd21d57323a926.svg in image directory

Any help to resolve this issue is appreciated.
Thankyou.
