### ISSUE TITLE
Error when using the command python3 -m pip install -r requirements.txt

### ISSUE THREAD

**Issue by christantinople** [3b1b/manim#890]
Running setup.py install for Pillow ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/k_/lhglds3j0k52fgg96l4r62lm0000gn/T/pip-install-gtdo_7kf/Pillow/setup.py'"'"'; __file__='"'"'/private/var/folders/k_/lhglds3j0k52fgg96l4r62lm0000gn/T/pip-install-gtdo_7kf/Pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/k_/lhglds3j0k52fgg96l4r62lm0000gn/T/pip-record-kif646zv/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/k_/lhglds3j0k52fgg96l4r62lm0000gn/T/pip-install-gtdo_7kf/Pillow/
    Complete output (175 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.8
    creating build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/MpoImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/ImageMode.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/PngImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/XbmImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/PcxImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/SunImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/ImageFile.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/SpiderImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/TarIO.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/FitsStubImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/MpegImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/BdfFontFile.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/GribStubImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/ImageStat.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/PixarImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/GimpPaletteFile.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/ImageColor.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/ContainerIO.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/MspImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/MicImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/_version.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/ImtImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/GifImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/PalmImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/ImageQt.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/ImageMath.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/PaletteFile.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/FontFile.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/PdfParser.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/ExifTags.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/ImageCms.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/FpxImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/ImageChops.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/BufrStubImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/PSDraw.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/PcdImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/ImageFilter.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/ImageDraw2.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/ImagePath.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/DcxImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/JpegPresets.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/features.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/ImageDraw.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/GimpGradientFile.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/ImageWin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/IcoImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/_tkinter_finder.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/EpsImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/TgaImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/ImageMorph.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/WalImageFile.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/PcfFontFile.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/BlpImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/ImageTk.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/GbrImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/ImageOps.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/PdfImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/ImageShow.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/ImageEnhance.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/WmfImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/ImageGrab.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/WebPImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/FliImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/TiffTags.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/CurImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/_util.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/GdImageFile.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/TiffImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/IptcImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/ImagePalette.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/BmpImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/ImageTransform.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/IcnsImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/McIdasImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/XpmImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/OleFileIO.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/DdsImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/ImageSequence.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/PyAccess.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/_binary.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/Image.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/XVThumbImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/SgiImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/ImImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/PsdImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/JpegImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/ImageFont.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/PpmImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    copying src/PIL/FtexImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.8/PIL
    running egg_info
    writing src/Pillow.egg-info/PKG-INFO
    writing dependency_links to src/Pillow.egg-info/dependency_links.txt
    writing top-level names to src/Pillow.egg-info/top_level.txt
    reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching '.travis'
    warning: no previously-included files found matching '.travis/*'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
    running build_ext
    
    
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    Traceback (most recent call last):
      File "/private/var/folders/k_/lhglds3j0k52fgg96l4r62lm0000gn/T/pip-install-gtdo_7kf/Pillow/setup.py", line 760, in <module>
        setup(name=NAME,
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/private/var/folders/k_/lhglds3j0k52fgg96l4r62lm0000gn/T/pip-install-gtdo_7kf/Pillow/setup.py", line 582, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: zlib
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/k_/lhglds3j0k52fgg96l4r62lm0000gn/T/pip-install-gtdo_7kf/Pillow/setup.py", line 807, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/k_/lhglds3j0k52fgg96l4r62lm0000gn/T/pip-install-gtdo_7kf/Pillow/setup.py'"'"'; __file__='"'"'/private/var/folders/k_/lhglds3j0k52fgg96l4r62lm0000gn/T/pip-install-gtdo_7kf/Pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/k_/lhglds3j0k52fgg96l4r62lm0000gn/T/pip-record-kif646zv/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

From the requirements.txt file, I removed the equals sign and the numbers on the line "opencv-python==3.4.2.17" as I had an error that's similar to what's detailed here: [](https://github.com/3b1b/manim/issues/773)

This fixed that particular error, but then I got two more errors. One is in regards to the large error message detailed above, and the other one was "opencv-python 4.2.0.32 has requirement numpy>=1.17.3, but you'll have numpy 1.15.0 which is incompatible." I updated my version of numpy and that didn't work, so I changed the line in requirements.txt to be "numpy==1.18.1" (updated version). So that error is now gone but the error above persists.

Any help on how to resolve this error would be greatly appreciated.

**Comment by Elteoremadebeethoven** [comment]
Most likely, you are using an old MacOS version, if so you will have to install the Python version 3.7 to download the required opencv version. You can install pyenv and select version 3.7 so that this does not happen, use this version of [requirements.txt](https://github.com/3b1b/manim/blob/3b088b12843b7a4459fe71eba96b70edafb7aa78/requirements.txt) so you can use it using PIP.

**Comment by 314har-code** [comment]
i have similar issue, but this did not work for me

**Comment by uda3** [comment]
I have  the same problem I
 use python 3.8 any help
