### ISSUE TITLE
Can't install on Windows/Anaconda/Python 3

### ISSUE THREAD

**Issue by nesteruk** [3b1b/manim#9]
Collecting progressbar==2.3 (from -r requirements.txt (line 4))
  Downloading progressbar-2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Dmitri\AppData\Local\Temp\pip-build-saceb6m0\progressbar\setup.py", line 5, in <module>
        import progressbar
      File "c:\users\dmitri\appdata\local\temp\pip-build-saceb6m0\progressbar\progressbar__init__.py", line 59, in <module>
        from progressbar.widgets import *
      File "c:\users\dmitri\appdata\local\temp\pip-build-saceb6m0\progressbar\progressbar\widgets.py", line 121, in <module>
        class FileTransferSpeed(Widget):
      File "C:\Anaconda3\lib\abc.py", line 133, in **new**
        cls = super().**new**(mcls, name, bases, namespace)
    ValueError: 'format' in **slots** conflicts with class variable

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in C:\Users\Dmitri\AppData\Local\Temp\pip-build-saceb6m0\progressbar\

**Comment by nesteruk** [comment]
That was an attempt with Python 3. With python 2, I managed to install all the libs, but now getting

```
C:\Dropbox\Projects\Open-Source\manim>python extract_scene.py -p example_scenes.py SquareToCircle
Traceback (most recent call last):
  File "extract_scene.py", line 183, in <module>
    main()
  File "extract_scene.py", line 162, in main
    module = get_module(config["file"])
  File "extract_scene.py", line 154, in get_module
    last_module = imp.load_module(".", *imp.find_module("."))
ImportError: No module named .
```

**Comment by mrkgnao** [comment]
I'm getting the same `__slots__` problems on a new Gentoo system.

**Comment by ExtremeWarrior** [comment]
I'm suffering from the same issue, let's just hope he does a video, because this seems to be ever-customized, only him can understand this engine.

**Comment by pankajb64** [comment]
This fails on WinPython 3.4 too. Same error. `ValueError: 'format' in __slots__ conflicts with class variable` (Not sure if I need to log it as a separate issue?)

**Comment by eulertour** [comment]
Closing, as this issue is very old and inactive.
