### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by Coldrain1232008** [3b1b/manim#901]
I have done all the setup. But when I test the example with CODE:
`python3 -m manim example_scenes.py SquareToCircle -pl`
I got the error as below:
`Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\manim\manim.py", line 2, in <module>
    import manimlib
  File "E:\manim\manimlib\__init__.py", line 4, in <module>
    import manimlib.extract_scene
  File "E:\manim\manimlib\extract_scene.py", line 9, in <module>
    from manimlib.scene.scene import Scene
  File "E:\manim\manimlib\scene\scene.py", line 9, in <module>
    from manimlib.animation.animation import Animation
  File "E:\manim\manimlib\animation\animation.py", line 5, in <module>
    from manimlib.mobject.mobject import Mobject
  File "E:\manim\manimlib\mobject\mobject.py", line 15, in <module>
    from manimlib.utils.color import color_gradient
  File "E:\manim\manimlib\utils\color.py", line 8, in <module>
    from manimlib.utils.bezier import interpolate
  File "E:\manim\manimlib\utils\bezier.py", line 1, in <module>
    from scipy import linalg
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\linalg\__init__.py", line 190, in <module>
    from .misc import *
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\linalg\misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\linalg\blas.py", line 214, in <module>
    from scipy.linalg import _fblas
ImportError: DLL load failed: 找不到指定的模块。`

**Comment by Tours1994** [comment]
same

**Comment by hanwenzhu** [comment]
Same as #767. Try to install NumPy-MKL from https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy instead of NumPy.
