### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'loader'

### ISSUE THREAD

**Issue by zoladon** [3b1b/manim#919]
I have downloaded manimlib, (with pip3) as well as cairo, ffmpeg, and sox. (with brew)

I tried to run this program, entering```manim Manim Demo.py Shapes -pl``` into my command line, which worked [here](https://github.com/3b1b/manim/issues/534) for someone with a seemingly the same problem:

```
from manimlib.imports import *

class Shapes(Scene):
    def construct(self):
        circle = Circle()
        square = Square()
        line=Line(np.array([3,0,0]),np.array([5,0,0]))
        triangle=Polygon(np.array([0,0,0]),np.array([1,1,0]),np.array([1,-1,0]))

        self.add(line)
        self.play(ShowCreation(circle))
        self.play(FadeOut(circle))
        self.play(GrowFromCenter(square))
        self.play(Transform(square,triangle))
```

This gave the following error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/manim", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/manimlib/__init__.py", line 11, in main
    config = manimlib.config.get_configuration(args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/manimlib/config.py", line 185, in get_configuration
    module = get_module(args.file)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/manimlib/config.py", line 179, in get_module
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 580, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'
```

I just recently downloaded macOS Catalina, (10.15.4), and am using Python 3.7.

**Comment by Elteoremadebeethoven** [comment]
It is `manim Demo.py Shapes -pl`

**Comment by zoladon** [comment]
My file is actually named "Manim Demo.py", which seems to have been a poor choice... Renaming it, I am getting a new error. 

I made copy of the code with the name "Try2.py". When I run ```manim Try2 Shapes -pl```, I get:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/manim", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/manimlib/__init__.py", line 11, in main
    config = manimlib.config.get_configuration(args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/manimlib/config.py", line 185, in get_configuration
    module = get_module(args.file)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/manimlib/config.py", line 180, in get_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 859, in get_code
  File "<frozen importlib._bootstrap_external>", line 916, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'Try2.py'
```

**Comment by zoladon** [comment]
Nevermind I fixed it!

**Comment by andreplima** [comment]
@zoladon, I am experiencing the same problem. Could you please share your solution with me?

**Comment by DutchEllie** [comment]
@zoladon Hey, please share your solution, others are running into the same problem and we'd like to know how you fixed it.

**Comment by tinfungster** [comment]
Check whether your file name is right in the terminal.

**Comment by Ericlpl** [comment]
Could you please share your solution? I'm in the same problem. @zoladon
