### ISSUE TITLE
Trouble rendering an SVG Image correctly 

### ISSUE THREAD

**Issue by luketimmerman314** [3b1b/manim#926]
So, I have my own little creature that I made (it is an SVG file) using InkScape. However, it was not rendering correctly when I ran my python code. For reference, I have attached the error message that I am receiving when I try and run my code:

Media will be written to ./media/. You can change this behavior with the --media_dir flag.
conversation.py:39: UserWarning: No PsiCreatures design with mode happy
  (self.file_name_prefix, mode))

Traceback (most recent call last):
  File "conversation.py", line 36, in __init__
    SVGMobject.__init__(self, file_name=svg_file, **kwargs)
  File "/Users/luketimmerman/Animation/manim/manimlib/mobject/svg/svg_mobject.py", line 46, in __init__
    VMobject.__init__(self, **kwargs)
  File "/Users/luketimmerman/Animation/manim/manimlib/mobject/mobject.py", line 48, in __init__
    self.generate_points()
  File "/Users/luketimmerman/Animation/manim/manimlib/mobject/svg/svg_mobject.py", line 69, in generate_points
    mobjects = self.get_mobjects_from(svg)
  File "/Users/luketimmerman/Animation/manim/manimlib/mobject/svg/svg_mobject.py", line 87, in get_mobjects_from
    for child in element.childNodes
  File "/Users/luketimmerman/Animation/manim/manimlib/mobject/svg/svg_mobject.py", line 87, in <listcomp>
    for child in element.childNodes
  File "/Users/luketimmerman/Animation/manim/manimlib/mobject/svg/svg_mobject.py", line 87, in get_mobjects_from
    for child in element.childNodes
  File "/Users/luketimmerman/Animation/manim/manimlib/mobject/svg/svg_mobject.py", line 87, in <listcomp>
    for child in element.childNodes
  File "/Users/luketimmerman/Animation/manim/manimlib/mobject/svg/svg_mobject.py", line 91, in get_mobjects_from
    element.getAttribute('d')
  File "/Users/luketimmerman/Animation/manim/manimlib/mobject/svg/svg_mobject.py", line 119, in path_string_to_mobject
    return VMobjectFromSVGPathstring(path_string)
  File "/Users/luketimmerman/Animation/manim/manimlib/mobject/svg/svg_mobject.py", line 322, in __init__
    VMobject.__init__(self, **kwargs)
  File "/Users/luketimmerman/Animation/manim/manimlib/mobject/mobject.py", line 48, in __init__
    self.generate_points()
  File "/Users/luketimmerman/Animation/manim/manimlib/mobject/svg/svg_mobject.py", line 349, in generate_points
    self.handle_command(command, coord_string)
  File "/Users/luketimmerman/Animation/manim/manimlib/mobject/svg/svg_mobject.py", line 359, in handle_command
    new_points = self.string_to_points(coord_string)
  File "/Users/luketimmerman/Animation/manim/manimlib/mobject/svg/svg_mobject.py", line 422, in string_to_points
    numbers = string_to_numbers(coord_string)
  File "/Users/luketimmerman/Animation/manim/manimlib/mobject/svg/svg_mobject.py", line 24, in string_to_numbers
    for s in re.split("[ ,]", num_string)
  File "/Users/luketimmerman/Animation/manim/manimlib/mobject/svg/svg_mobject.py", line 25, in <listcomp>
    if s != ""
ValueError: could not convert string to float: '6.39.22'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/luketimmerman/Animation/manim/manimlib/extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "/Users/luketimmerman/Animation/manim/manimlib/scene/scene.py", line 53, in __init__
    self.construct()
  File "conversation.py", line 70, in construct
    psi_creature = PsiCreature()
  File "conversation.py", line 44, in __init__
    SVGMobject.__init__(self, mode="happy", file_name=svg_file, **kwargs)
  File "/Users/luketimmerman/Animation/manim/manimlib/mobject/svg/svg_mobject.py", line 45, in __init__
    self.ensure_valid_file()
  File "/Users/luketimmerman/Animation/manim/manimlib/mobject/svg/svg_mobject.py", line 63, in ensure_valid_file
    self.file_name)
OSError: No file matching assets/PsiCreatures_happy.svg in image directory

Thanks for any help y'all can give!

**Comment by luketimmerman314** [comment]
Hello?

**Comment by luketimmerman314** [comment]
Do y'all need more information?

**Comment by luketimmerman314** [comment]
So, I've been experimenting today, and I was able to get some of the simple .svg files I created in InkScape to render correctly when I ran my code. But, as the images got more complex, the images rendered completely terribly. I don't understand why this would be. I'm using the same application, and I was even able to get Grant's PiCreatures_plain.svg to run through InkScape. Any suggestions?

**Comment by raghavg123** [comment]
The default directory for manim to look for svg images is `assets/svg_images` (outside the manimlib folder) so try putting your file `PsiCreatures_happy.svg` in that folder (if it doesn't exist, create it), so that should solve your second problem.

**Comment by chiraagChakravarthy** [comment]
Hey. I'm having a similar issue, where my ellipses and rectangles render fine, but the lines just don't show up. Do you have any insight into why that may happen?

**Comment by cosmin-ionita** [comment]
Got the same issue too. Many SVG images that I download from the web have issues, they throw `ValueError: could not convert string to float` when trying to use them. Any advice on how to fix those SVG files, or what is the problem? Thanks

**Comment by yoshiask** [comment]
These are known issues in Manim. The parser in SVGMobject is really only designed to work well with the LaTeX output. It ignores a lot of things, including colors and `<line>` objects. The [Manim Community](https://github.com/ManimCommunity/manim) fork will have fixes for most of this soon. In the meantime, if you share your SVG file I can add it to my list of SVGs to test fixes with.

**Comment by shailvaidya** [comment]
I am facing a similar issue. I am using the `circuitikz` library in Tex to draw some circuits. The SVG file created is correct and shows all the components correctly. But in manim, some components are missing a line or two.
