### ISSUE TITLE
Unable to run example_scenes.py

### ISSUE THREAD

**Issue by She92ock** [3b1b/manim#931]
Hello guys, I installed all necessary packages and programs in order to run manimlib. In addition, my python version is **3.7.3**. Unfortunately when I try to run example_scenes.py it keeps showing this error.
Traceback (most recent call last):
  File "D:/Orgil/Installs/manim-master/example_scenes.py", line 3, in <module>
    from manimlib.imports import *
  File "D:\Orgil\Installs\manim-master\manimlib\__init__.py", line 4, in <module>
    import manimlib.extract_scene
  File "D:\Orgil\Installs\manim-master\manimlib\extract_scene.py", line 9, in <module>
    from manimlib.scene.scene import Scene
  File "D:\Orgil\Installs\manim-master\manimlib\scene\scene.py", line 12, in <module>
    from manimlib.camera.camera import Camera
  File "D:\Orgil\Installs\manim-master\manimlib\camera\camera.py", line 9, in <module>
    import cairo
  File "D:\Orgil\Python\lib\site-packages\cairo\__init__.py", line 1, in <module>
    from ._cairo import *  # noqa: F401,F403
ImportError: DLL load failed: The specified module could not be found.

**Comment by raghavg123** [comment]
You may need to install pycairo separately using a wheel.

**Comment by She92ock** [comment]
Thanks for responding. I fixed my problem by updating my pycairo which is 1.19.1.
