### ISSUE TITLE
Error installing manim via pip

### ISSUE THREAD

**Issue by Thxios** [3b1b/manim#945]
As I use pip to install manim, I got following error message:

```
 ERROR: Command errored out with exit status 1:
     command: 'c:\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\LEE\\AppData\\Local\\Temp\\pip-install-k39hbwf4\\manimlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\LEE\\AppData\\Local\\Temp\\pip-install-k39hbwf4\\manimlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\LEE\AppData\Local\Temp\pip-install-k39hbwf4\manimlib\
    Complete output (22 lines):
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "c:\users\lee\appdata\local\temp\pip-install-k39hbwf4\manimlib\.eggs\pbr-5.4.4-py3.7.egg\pbr\core.py", line 96, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "c:\users\lee\appdata\local\temp\pip-install-k39hbwf4\manimlib\.eggs\pbr-5.4.4-py3.7.egg\pbr\util.py", line 271, in cfg_to_args
        pbr.hooks.setup_hook(config)
      File "c:\users\lee\appdata\local\temp\pip-install-k39hbwf4\manimlib\.eggs\pbr-5.4.4-py3.7.egg\pbr\hooks\__init__.py", line 25, in setup_hook
        metadata_config.run()
      File "c:\users\lee\appdata\local\temp\pip-install-k39hbwf4\manimlib\.eggs\pbr-5.4.4-py3.7.egg\pbr\hooks\base.py", line 27, in run
        self.hook()
      File "c:\users\lee\appdata\local\temp\pip-install-k39hbwf4\manimlib\.eggs\pbr-5.4.4-py3.7.egg\pbr\hooks\metadata.py", line 26, in hook
        self.config['name'], self.config.get('version', None))
      File "c:\users\lee\appdata\local\temp\pip-install-k39hbwf4\manimlib\.eggs\pbr-5.4.4-py3.7.egg\pbr\packaging.py", line 858, in get_version
        version = _get_version_from_pkg_metadata(package_name)
      File "c:\users\lee\appdata\local\temp\pip-install-k39hbwf4\manimlib\.eggs\pbr-5.4.4-py3.7.egg\pbr\packaging.py", line 826, in _get_version_from_pkg_metadata
        pkg_metadata = email.message_from_file(pkg_metadata_file)
      File "c:\python37\lib\email\__init__.py", line 54, in message_from_file
        return Parser(*args, **kws).parse(fp)
      File "c:\python37\lib\email\parser.py", line 53, in parse
        data = fp.read(8192)
    UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 1887: illegal multibyte sequence
    error in setup command: Error parsing C:\Users\LEE\AppData\Local\Temp\pip-install-k39hbwf4\manimlib\setup.cfg: UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 1887: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I tried `chcp 65001` command on command prompt to change the default encoding from cp949 to utf-8, but it didn't work.
How can I handle this problem? I'm running python 3.7.5 on windows10.

**Comment by PommesPeter** [comment]
you can try to update your pip package manager. I hope it will work on your computer.

**Comment by Thxios** [comment]
> you can try to update your pip package manager. I hope it will work on your computer.

I'm using pip 20.0.2, which I thought to be the newest version of pip. Is there a newer version of pip??

**Comment by xy-23** [comment]
Not recommended to install manim via pip
