### ISSUE TITLE
Why can't i render old 3b1b files 

### ISSUE THREAD

**Issue by yutharsan** [3b1b/manim#963]
### If this is a support request:

**Please attempt to solve the problem on your own before opening an issue.**
Between old issues, StackOverflow, and Google, you should be able to find
solutions to most of the common problems.

Include at least:
1. Steps to reproduce the issue (e.g. the command you ran)
2. The unexpected behavior that occurred (e.g. error messages or screenshots)
3. The environment (e.g. operating system and version of manim)

### If this is a feature request:
Include the motivation for making this change.

**Comment by yutharsan** [comment]
C:\Manim>python -m manim from_3b1b\old\basel\basel.py LightIndicator -pm
Traceback (most recent call last):
  File "C:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Manim\manim.py", line 5, in <module>
    manimlib.main()
  File "C:\Manim\manimlib\__init__.py", line 11, in main
    config = manimlib.config.get_configuration(args)
  File "C:\Manim\manimlib\config.py", line 185, in get_configuration
    module = get_module(args.file)
  File "C:\Manim\manimlib\config.py", line 180, in get_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "from_3b1b\old\basel\basel.py", line 6, in <module>
    from once_useful_constructs.light import *
ModuleNotFoundError: No module named 'once_useful_constructs'

**Comment by Aathish04** [comment]
Manim is a rapidly changing Library. Those files were written for an older version of Manim.

If you want to run those animations, your best option is to use an older version of Manim.

Alternatively, if you like a challenge, you could rewrite the animation to make it work with the current version of Manim.

Also, it is considered bad practice to comment on your own issue unless responding to another persons question. 

Please properly format your code/errors with \`\`\` before and after the code/error message, to make it easier to read.
