### ISSUE TITLE
How to fix:"ImportError: DLL load failed while importing _fblas: The specified module could not be found"

### ISSUE THREAD

**Issue by ashish453** [3b1b/manim#964]
i did this and get this :

C:\Manim\manim-master>python -m manim example_scenes.py SquareToCircle -pl
Traceback (most recent call last):
  File "C:\Python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Manim\manim-master\manim.py", line 2, in <module>
    import manimlib
  File "C:\Manim\manim-master\manimlib\__init__.py", line 4, in <module>
    import manimlib.extract_scene
  File "C:\Manim\manim-master\manimlib\extract_scene.py", line 9, in <module>
    from manimlib.scene.scene import Scene
  File "C:\Manim\manim-master\manimlib\scene\scene.py", line 9, in <module>
    from manimlib.animation.animation import Animation
  File "C:\Manim\manim-master\manimlib\animation\animation.py", line 5, in <module>
    from manimlib.mobject.mobject import Mobject
  File "C:\Manim\manim-master\manimlib\mobject\mobject.py", line 15, in <module>
    from manimlib.utils.color import color_gradient
  File "C:\Manim\manim-master\manimlib\utils\color.py", line 8, in <module>
    from manimlib.utils.bezier import interpolate
  File "C:\Manim\manim-master\manimlib\utils\bezier.py", line 1, in <module>
    from scipy import linalg
  File "C:\Python38-32\lib\site-packages\scipy\linalg\__init__.py", line 195, in <module>
    from .misc import *
  File "C:\Python38-32\lib\site-packages\scipy\linalg\misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "C:\Python38-32\lib\site-packages\scipy\linalg\blas.py", line 215, in <module>
    from scipy.linalg import _fblas
ImportError: DLL load failed while importing _fblas: The specified module could not be found.

**Comment by Joocheol** [comment]
Try
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by ashish453** [comment]
i don't get it. what has visualstudio hs to do with manim?

**Comment by Joocheol** [comment]
That was my guess for resolving "ImportError: DLL load failed while importing _fblas: The specified module could not be found.".

Some programs or modules seem to need Visual C++ redistributable packages to be processed correctly. At least I have resolved a similar DLL problem when I installed manim.

**Comment by scottdoy** [comment]
I had the same issue just now; here's how I fixed it. For reference I'm on 64-bit Windows 10 Pro 1903.

I use conda, and in a new environment, I got the error above when trying to install with `pip install -r requirements.txt`. I removed the environment and tried again using the instructions for conda, `conda env create -f environment.yml`. This time, I got the following error:

```
Traceback (most recent call last):
  File "manim.py", line 5, in <module>
    manimlib.main()
  File "F:\work\github\manim\manimlib\__init__.py", line 9, in main
    config = manimlib.config.get_configuration(args)
  File "F:\work\github\manim\manimlib\config.py", line 155, in get_configuration
    module = get_module(args.file)
  File "F:\work\github\manim\manimlib\config.py", line 150, in get_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "example_scenes.py", line 3, in <module>
    from manimlib.imports import *
  File "F:\work\github\manim\manimlib\imports.py", line 53, in <module>
    from manimlib.mobject.svg.code_mobject import *
  File "F:\work\github\manim\manimlib\mobject\svg\code_mobject.py", line 10, in <module>
    from pygments import highlight
ModuleNotFoundError: No module named 'pygments'
```

A quick `conda install pygments` later, and the examples ran without an issue.

**Comment by 08ming** [comment]
> Try
> https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

Don't fucking your answer
