### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by sanjalchetu8055** [3b1b/manim#990]
I tried **direct approach for windows** and i did setup the project as shown in the steps and then ran the command 
**python manim.py example_scenes.py SquareToCircle -pl** which is giving me below error.

Traceback (most recent call last):
  **File "C:\Users\HP\manimnew\manim\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\Users\HP\manimnew\manim\manimlib\scene\scene.py", line 53, in __init__
    self.construct()
  File "example_scenes.py", line 83, in construct
    self.play(ShowCreation(square))**
  File "C:\Users\HP\manimnew\manim\manimlib\scene\scene.py", line 405, in wrapper
    self.file_writer.begin_animation(allow_write)
  File "C:\Users\HP\manimnew\manim\manimlib\scene\scene_file_writer.py", line 170, in begin_animation
    self.open_movie_pipe()
  File "C:\Users\HP\manimnew\manim\manimlib\scene\scene_file_writer.py", line 243, in open_movie_pipe
    self.writing_process = subprocess.Popen(command, stdin=subprocess.PIPE)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)

**FileNotFoundError: [WinError 2] The system cannot find the file specified**

**Comment by Priyangakalyan** [comment]
Hi,

I am also facing the same issue. Can you please help me with this ?

Regards,
Priyanga

**Comment by sanjalchetu8055** [comment]
Hey even I did not get the solution yet.

**Comment by yoshiask** [comment]
Are you sure that you have installed ffmpeg correctly?

**Comment by sanjalchetu8055** [comment]
yup did that

**Comment by Priyangakalyan** [comment]
Yes I have installed ffmpeg following this link ,
https://www.wikihow.com/Install-FFmpeg-on-Windows 
and confirmed the package version in cmd.

**Comment by sanjalchetu8055** [comment]
Yeah is it working for you now?

**Comment by sanjalchetu8055** [comment]
I have been trying for a week😭😢 no luck.

**Comment by Priyangakalyan** [comment]
No I installed pycairo and ffmpeg but still its not working

**Comment by sanjalchetu8055** [comment]
https://youtu.be/ZltiKHFWmv8
 I tried this YouTube video but that approach is also not working if you
can try and you get please let me know.

**Comment by sanjalchetu8055** [comment]
Hey did you try any luck?

**Comment by Priyangakalyan** [comment]
Hi, I have fixed the issue now the example_scenes.py is working fine. Initially I have setted the ffmpeg path as user variable by changing it to the system variable problem got resolved.

**Comment by sanjalchetu8055** [comment]
hey bro i am trying it from so many days can you please make an video that
would be really helpful.

**Comment by sanjalchetu8055** [comment]
hey i tried again using the video link which i sent you but still didn't
work and used the manim github link to install but still did not work so
can you please send me your complete video of installation so that I can
follow it.

Kind Regards

Sanjal C C

**Comment by suhailsherif** [comment]
Look at the file manimlib\constants.py

There is a constant FFMPEG_BIN, which is set to "ffmpeg". Change this to "C:\\\\ffmpeg\\bin\\ffmpeg.exe" (or wherever you have placed ffmpeg.exe after unzipping the installer).

(Double slashes are so that \b and \f etc don't become special characters.)

Do let us know if this works.

**Comment by PromethiumL** [comment]
I changed the "ffmpeg" to the actual path and it works.

**Comment by c3mcavus** [comment]
I tried to change ```ffmpeg``` path but it didn't work. When I change path , I encountered another error. Error is: 
<img width="696" alt="d" src="https://user-images.githubusercontent.com/45109328/104730865-d86b3380-574b-11eb-9c2f-00abef70af42.png">

When I created a new folder, then put the file into it and run it, it worked. But I don't know why :) 
You can try. 
REFERENCE: https://docs.manim.community/en/v0.2.0/tutorials/quickstart.html


@suhailsherif @sanjalchetu8055 @Priyangakalyan
