### ISSUE TITLE
Cannot import manimlib

### ISSUE THREAD

**Issue by swainsubrat** [3b1b/manim#991]
### If this is a support request:

**Please attempt to solve the problem on your own before opening an issue.**
Between old issues, StackOverflow, and Google, you should be able to find
solutions to most of the common problems.

Include at least:
1. Steps to reproduce the issue (e.g. the command you ran)
2. The unexpected behavior that occurred (e.g. error messages or screenshots)
3. The environment (e.g. operating system and version of manim)

### If this is a feature request:
Include the motivation for making this change.

**Comment by swainsubrat** [comment]
>>> import manimlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/thunderclap/anaconda3/lib/python3.7/site-packages/manimlib/__init__.py", line 4, in <module>
    import manimlib.extract_scene
  File "/home/thunderclap/anaconda3/lib/python3.7/site-packages/manimlib/extract_scene.py", line 9, in <module>
    from manimlib.scene.scene import Scene
  File "/home/thunderclap/anaconda3/lib/python3.7/site-packages/manimlib/scene/scene.py", line 11, in <module>
    from manimlib.camera.camera import Camera
  File "/home/thunderclap/anaconda3/lib/python3.7/site-packages/manimlib/camera/camera.py", line 9, in <module>
    import cairo
  File "/home/thunderclap/anaconda3/lib/python3.7/site-packages/cairo/__init__.py", line 1, in <module>
    from ._cairo import *  # noqa: F401,F403
ImportError: /home/thunderclap/anaconda3/lib/python3.7/site-packages/cairo/_cairo.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cairo_tee_surface_index

**Comment by stevenschn** [comment]
Try:

`import manimlib.imports import * `

**Comment by tshrpl** [comment]
if the problen is solved, please close this issue

**Comment by swainsubrat** [comment]
>>> import manimlib.imports import *
  File "<stdin>", line 1
    import manimlib.imports import *
                                 ^
SyntaxError: invalid syntax
>>> from manimlib.imports import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/thunderclap/anaconda3/envs/math/lib/python3.7/site-packages/manimlib/__init__.py", line 4, in <module>
    import manimlib.extract_scene
  File "/home/thunderclap/anaconda3/envs/math/lib/python3.7/site-packages/manimlib/extract_scene.py", line 9, in <module>
    from manimlib.scene.scene import Scene
  File "/home/thunderclap/anaconda3/envs/math/lib/python3.7/site-packages/manimlib/scene/scene.py", line 11, in <module>
    from manimlib.camera.camera import Camera
  File "/home/thunderclap/anaconda3/envs/math/lib/python3.7/site-packages/manimlib/camera/camera.py", line 9, in <module>
    import cairo
  File "/home/thunderclap/anaconda3/envs/math/lib/python3.7/site-packages/cairo/__init__.py", line 1, in <module>
    from ._cairo import *  # noqa: F401,F403
ImportError: /home/thunderclap/anaconda3/envs/math/lib/python3.7/site-packages/cairo/_cairo.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cairo_tee_surface_index
>>> 

Same thing

**Comment by Tony031218** [comment]
> >>> import manimlib.imports import *
> 
>   File "<stdin>", line 1
> 
>     import manimlib.imports import *
> 
>                                  ^
> 
> SyntaxError: invalid syntax
> 
> >>> from manimlib.imports import *
> 
> Traceback (most recent call last):
> 
>   File "<stdin>", line 1, in <module>
> 
>   File "/home/thunderclap/anaconda3/envs/math/lib/python3.7/site-packages/manimlib/__init__.py", line 4, in <module>
> 
>     import manimlib.extract_scene
> 
>   File "/home/thunderclap/anaconda3/envs/math/lib/python3.7/site-packages/manimlib/extract_scene.py", line 9, in <module>
> 
>     from manimlib.scene.scene import Scene
> 
>   File "/home/thunderclap/anaconda3/envs/math/lib/python3.7/site-packages/manimlib/scene/scene.py", line 11, in <module>
> 
>     from manimlib.camera.camera import Camera
> 
>   File "/home/thunderclap/anaconda3/envs/math/lib/python3.7/site-packages/manimlib/camera/camera.py", line 9, in <module>
> 
>     import cairo
> 
>   File "/home/thunderclap/anaconda3/envs/math/lib/python3.7/site-packages/cairo/__init__.py", line 1, in <module>
> 
>     from ._cairo import *  # noqa: F401,F403
> 
> ImportError: /home/thunderclap/anaconda3/envs/math/lib/python3.7/site-packages/cairo/_cairo.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cairo_tee_surface_index
> 
> >>> 
> 
> 
> 
> Same thing

`from manimlib.imports import *`
I think you’d better study Python before using manim.

Problem is solved,please close this issue.

**Comment by swainsubrat** [comment]
@Tony031218 I'm sorry. But @stevenschn above written that import manimlib.imports import * and I just took that and copy-pasted it. I thought this might be something else. But then I tried the actual one from manimlib.imports import *(You can see the below lines). While copy-pasting from the terminal, I copied it all. That's why it is showing like this. And I do know Python.

**Comment by swainsubrat** [comment]
I'm closing this issue for now because I don't see any solution coming from you guys. Good wishes. Stay safe.
